Armadillo Technical: Base< elem_type, derived > Struct Template Reference
Base< elem_type, derived > Struct Template Reference
[Base]
Class for static polymorphism, modelled after the "Curiously Recurring Template Pattern" (CRTP). Used for type-safe downcasting in functions that restrict their input(s) to be classes that are derived from Base (e.g. Mat, Op, Glue, diagview, subview). A Base object can be converted to a Mat object by the unwrap class.
#include <Base.hpp>
Public Member Functions
arma_inline const derived & get_ref () const
Detailed Description
template<typename elem_type, typename derived>
struct Base< elem_type, derived >
Class for static polymorphism, modelled after the "Curiously Recurring Template Pattern" (CRTP). Used for type-safe downcasting in functions that restrict their input(s) to be classes that are derived from Base (e.g. Mat, Op, Glue, diagview, subview). A Base object can be converted to a Mat object by the unwrap class.
Definition at line 27 of file Base.hpp.
Member Function Documentation
template<typename elem_type, typename derived> arma_inline const derived& Base< elem_type, derived >::get_ref () const [inline]
Definition at line 32 of file Base.hpp.
Referenced by abs(), accu(), acos(), acosh(), op_norm_dot::apply(), op_dot::apply(), asin(), asinh(), atan(), atanh(), chol(), cor(), cos(), cosh(), cov(), det(), diagmat(), eig_gen(), eig_sym(), eps(), exp(), conv_to< out_eT >::from(), inv(), kron(), log(), log10(), lu(), max(), mean(), median(), min(), norm(), operator!=(), operator%(), subview< eT >::operator%=(), subview_cube< eT >::operator%=(), operator*(), operator+(), subview< eT >::operator+=(), subview_cube< eT >::operator+=(), operator-(), subview< eT >::operator-=(), subview_cube< eT >::operator-=(), operator/(), subview< eT >::operator/=(), subview_cube< eT >::operator/=(), operator<(), operator<=(), subview< eT >::operator=(), subview_cube< eT >::operator=(), diagview< eT >::operator=(), operator==(), operator>(), operator>=(), pinv(), pow(), prod(), qr(), rank(), repmat(), reshape(), shuffle(), sin(), sinh(), solve(), sort(), sqrt(), square(), stddev(), sum(), svd(), tan(), tanh(), trace(), trans(), trunc_exp(), trunc_log(), and var().
    {
    return static_cast<const derived&>(*this);
    }