Armadillo Technical: access Class Reference
access Class Reference
[Access]
#include <access.hpp>
Static Public Member Functions
template<typename T1 >
static arma_inline T1 & rw (const T1 &x)
internal function to allow modification of data declared as read-only
template<typename eT >
static arma_inline const eT & tmp_real (const eT &X)
internal function to obtain the real part of either a plain number or a complex number
template<typename T >
static arma_inline const T tmp_real (const std::complex< T > &X)
Detailed Description
Definition at line 21 of file access.hpp.
Member Function Documentation
template<typename T1 > static arma_inline T1& access::rw (const T1 & x) [inline, static]
internal function to allow modification of data declared as read-only
Definition at line 26 of file access.hpp.
Referenced by op_reshape::apply(), subview< eT >::at(), subview_cube< eT >::at(), Mat< eT >::at(), Cube< eT >::at(), Row< eT >::col(), Col< eT >::Col(), subview< eT >::colptr(), Mat< eT >::colptr(), Cube< eT >::create_mat(), Cube< eT >::Cube(), Cube< eT >::delete_mat(), podarray< eT >::fill(), Mat< eT >::fill(), Cube< eT >::fill(), podarray< eT >::init(), Mat< eT >::init(), field< oT >::init(), Cube< eT >::init(), Mat< eT >::Mat(), subview< eT >::operator()(), subview_cube< eT >::operator()(), podarray< eT >::operator()(), Mat< eT >::operator()(), Cube< eT >::operator()(), Mat< eT >::operator*=(), Cube< eT >::operator*=(), Mat< eT >::operator+=(), Cube< eT >::operator+=(), Mat< eT >::operator-=(), Cube< eT >::operator-=(), Mat< eT >::operator/=(), Cube< eT >::operator/=(), podarray< eT >::operator=(), Mat< eT >::operator=(), Cube< eT >::operator=(), Col< eT >::operator=(), subview< eT >::operator[](), subview_cube< eT >::operator[](), podarray< eT >::operator[](), Mat< eT >::operator[](), Cube< eT >::operator[](), podarray< eT >::podarray(), Row< eT >::Row(), Col< eT >::row(), subview_cube< eT >::slice_colptr(), Mat< eT >::swap_rows(), Cube< eT >::~Cube(), field< oT >::~field(), Mat< eT >::~Mat(), and podarray< eT >::~podarray().
{ return const_cast<T1&>(x); }
template<typename eT > static arma_inline const eT& access::tmp_real (const eT & X) [inline, static]
internal function to obtain the real part of either a plain number or a complex number
Definition at line 29 of file access.hpp.
Referenced by log_det(), auxlib::log_det(), and diskio::save_ppm_binary().
{ return X;        }
template<typename T > static arma_inline const T access::tmp_real (const std::complex< T > & X) [inline, static]
Definition at line 30 of file access.hpp.
{ return X.real(); }