Armadillo Technical: BaseCube< elem_type, derived > Struct Template Reference
BaseCube< elem_type, derived > Struct Template Reference
[BaseCube]
Analog of the Base class, intended for cubes.
#include <BaseCube.hpp>
Public Member Functions
arma_inline const derived & get_ref () const
Detailed Description
template<typename elem_type, typename derived>
struct BaseCube< elem_type, derived >
Analog of the Base class, intended for cubes.
Definition at line 24 of file BaseCube.hpp.
Member Function Documentation
template<typename elem_type, typename derived> arma_inline const derived& BaseCube< elem_type, derived >::get_ref () const [inline]
Definition at line 29 of file BaseCube.hpp.
Referenced by abs(), accu(), acos(), acosh(), as_scalar(), asin(), asinh(), atan(), atanh(), conj(), cos(), cosh(), exp(), fabs(), conv_to< out_eT >::from(), imag(), log(), log10(), operator!=(), operator%(), subview_cube< eT >::operator%=(), operator*(), operator+(), subview_cube< eT >::operator+=(), operator-(), subview_cube< eT >::operator-=(), operator/(), subview_cube< eT >::operator/=(), operator<(), operator<=(), subview_cube< eT >::operator=(), operator==(), operator>(), operator>=(), pow(), real(), reshape(), sin(), sinh(), sqrt(), square(), tan(), tanh(), trunc_exp(), and trunc_log().
    {
    return static_cast<const derived&>(*this);
    }