Armadillo Technical: Base< elem_type, derived > Struct Template Reference
Base< elem_type, derived > Struct Template Reference
[Base]
Class for static polymorphism, modelled after the "Curiously Recurring Template Pattern" (CRTP). Used for type-safe downcasting in functions that restrict their input(s) to be classes that are derived from Base (e.g. Mat, Op, Glue, diagview, subview). A Base object can be converted to a Mat object by the unwrap class.
#include <Base.hpp>
Public Member Functions
arma_inline const derived & get_ref () const
Detailed Description
template<typename elem_type, typename derived>
struct Base< elem_type, derived >
Class for static polymorphism, modelled after the "Curiously Recurring Template Pattern" (CRTP). Used for type-safe downcasting in functions that restrict their input(s) to be classes that are derived from Base (e.g. Mat, Op, Glue, diagview, subview). A Base object can be converted to a Mat object by the unwrap class.
Definition at line 28 of file Base.hpp.
Member Function Documentation
template<typename elem_type, typename derived> arma_inline const derived& Base< elem_type, derived >::get_ref () const [inline]
Definition at line 33 of file Base.hpp.
Referenced by abs(), accu_proxy(), accu_unwrap(), acos(), acosh(), op_inv::apply_diag(), op_norm_dot::apply_proxy(), op_dot::apply_proxy(), op_norm_dot::apply_unwrap(), op_dot::apply_unwrap(), as_scalar(), as_scalar_diag(), asin(), asinh(), atan(), atanh(), chol(), conj(), conv(), cor(), cos(), cosh(), cov(), cross(), det(), diagmat(), diagvec(), eig_gen(), eig_sym(), eps(), exp(), fabs(), find(), fliplr(), flipud(), conv_to< out_eT >::from(), op_find::helper(), htrans(), imag(), inv(), join_cols(), join_rows(), kron(), log(), log10(), log_det(), lu(), max(), mean(), median(), min(), norm_proxy(), norm_unwrap(), operator!=(), operator%(), subview< eT >::operator%=(), subview_cube< eT >::operator%=(), operator*(), operator+(), subview< eT >::operator+=(), subview_cube< eT >::operator+=(), operator-(), subview< eT >::operator-=(), subview_cube< eT >::operator-=(), operator/(), subview< eT >::operator/=(), subview_cube< eT >::operator/=(), operator<(), operator<=(), subview_cube< eT >::operator=(), diagview< eT >::operator=(), operator==(), operator>(), operator>=(), subview< eT >::operator_equ_mat(), subview< eT >::operator_equ_proxy(), pinv(), pow(), princomp(), princomp_cov(), prod(), qr(), rank(), real(), repmat(), reshape(), shuffle(), sin(), sinh(), solve(), sort(), sort_index(), sqrt(), square(), stddev(), sum(), svd(), tan(), tanh(), toeplitz(), trace(), trans(), trunc_exp(), trunc_log(), and var().
    {
    return static_cast<const derived&>(*this);
    }