Armadillo Technical: isnt_same_type< T1, T2 > Struct Template Reference
isnt_same_type< T1, T2 > Struct Template Reference
[Traits]
#include <traits.hpp>
Static Public Member Functions
static void check ()
Static Public Attributes
static const bool value = true
Detailed Description
template<typename T1, typename T2>
struct isnt_same_type< T1, T2 >
Definition at line 222 of file traits.hpp.
Member Function Documentation
template<typename T1, typename T2> static void isnt_same_type< T1, T2 >::check () [inline, static]
Definition at line 226 of file traits.hpp.
Referenced by accu(), norm(), and trace().
    {
    arma_static_assert<false> ERROR___TYPE_MISMATCH;
    ERROR___TYPE_MISMATCH = ERROR___TYPE_MISMATCH;
    }
Member Data Documentation
template<typename T1, typename T2> const bool isnt_same_type< T1, T2 >::value = true [static]
Definition at line 224 of file traits.hpp.