Armadillo Technical: unwrap_write< Mat< eT > > Class Template Reference
unwrap_write< Mat< eT > > Class Template Reference
[Unwrap]
#include <unwrap.hpp>
Public Member Functions
unwrap_write (Mat< eT > &out, const Mat< eT > &A)
unwrap_write (Row< eT > &out, const Mat< eT > &A)
unwrap_write (Col< eT > &out, const Mat< eT > &A)
~unwrap_write ()
Public Attributes
const Mat< eT > & M
Detailed Description
template<typename eT>
class unwrap_write< Mat< eT > >
Definition at line 738 of file unwrap.hpp.
Constructor & Destructor Documentation
template<typename eT > unwrap_write< Mat< eT > >::unwrap_write (Mat< eT > & out, const Mat< eT > & A) [inline]
Definition at line 743 of file unwrap.hpp.
References Mat< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Mat< eT > >::unwrap_write (Row< eT > & out, const Mat< eT > & A) [inline]
Definition at line 752 of file unwrap.hpp.
References Row< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Mat< eT > >::unwrap_write (Col< eT > & out, const Mat< eT > & A) [inline]
Definition at line 761 of file unwrap.hpp.
References Col< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Mat< eT > >::~unwrap_write () [inline]
Definition at line 770 of file unwrap.hpp.
    {
    arma_extra_debug_sigprint();
    }
Member Data Documentation
template<typename eT > const Mat<eT>& unwrap_write< Mat< eT > >::M
Definition at line 776 of file unwrap.hpp.