Armadillo Technical: unwrap_write< Col< eT > > Class Template Reference
unwrap_write< Col< eT > > Class Template Reference
[Unwrap]
#include <unwrap.hpp>
Public Member Functions
unwrap_write (Mat< eT > &out, const Col< eT > &A)
unwrap_write (Row< eT > &out, const Col< eT > &A)
unwrap_write (Col< eT > &out, const Col< eT > &A)
~unwrap_write ()
Public Attributes
const Col< eT > & M
Detailed Description
template<typename eT>
class unwrap_write< Col< eT > >
Definition at line 827 of file unwrap.hpp.
Constructor & Destructor Documentation
template<typename eT > unwrap_write< Col< eT > >::unwrap_write (Mat< eT > & out, const Col< eT > & A) [inline]
Definition at line 832 of file unwrap.hpp.
References Mat< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Col< eT > >::unwrap_write (Row< eT > & out, const Col< eT > & A) [inline]
Definition at line 841 of file unwrap.hpp.
References Row< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Col< eT > >::unwrap_write (Col< eT > & out, const Col< eT > & A) [inline]
Definition at line 850 of file unwrap.hpp.
References Col< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Col< eT > >::~unwrap_write () [inline]
Definition at line 859 of file unwrap.hpp.
    {
    }
Member Data Documentation
template<typename eT > const Col<eT>& unwrap_write< Col< eT > >::M
Definition at line 864 of file unwrap.hpp.