Armadillo Technical: syslib Class Reference
syslib Class Reference
[Syslib]
#include <syslib_proto.hpp>
Static Public Member Functions
template<typename eT >
static arma_inline void copy_elem (eT *dest, const eT *src, const u32 n_elem)
Detailed Description
Definition at line 20 of file syslib_proto.hpp.
Member Function Documentation
template<typename eT > static arma_inline void syslib::copy_elem (eT * dest, const eT * src, const u32 n_elem) [inline, static]
Definition at line 28 of file syslib_proto.hpp.
Referenced by op_reshape::apply(), op_trans::apply_noalias(), Cube< eT >::Cube(), conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< Col< out_eT > >::from(), conv_to< Row< out_eT > >::from(), Mat< eT >::init(), Cube< eT >::init(), Mat< eT >::Mat(), auxlib::solve_od(), and auxlib::solve_ud().
    {
    if( n_elem <= (128/sizeof(eT)) )
      {
      for(u32 i=0; i<n_elem; ++i)
        {
        dest[i] = src[i];
        }
      }
    else
      {
      std::memcpy(dest, src, n_elem*sizeof(eT));
      }
    }