Armadillo Technical: Phy< eT > Class Template Reference
Phy< eT > Class Template Reference
[Constants]
Physical constants taken from NIST and WolframAlpha on 2009-06-23 http://physics.nist.gov/cuu/Constants http://www.wolframalpha.com See also http://en.wikipedia.org/wiki/Physical_constant.
#include <constants.hpp>
Static Public Member Functions
static const eT m_u ()
atomic mass constant (in kg)
static const eT N_A ()
Avogadro constant.
static const eT k ()
Boltzmann constant (in joules per kelvin).
static const eT k_evk ()
Boltzmann constant (in eV/K).
static const eT a_0 ()
Bohr radius (in meters).
static const eT mu_B ()
Bohr magneton.
static const eT Z_0 ()
characteristic impedance of vacuum (in ohms)
static const eT G_0 ()
conductance quantum (in siemens)
static const eT k_e ()
Coulomb's constant (in meters per farad).
static const eT eps_0 ()
electric constant (in farads per meter)
static const eT m_e ()
electron mass (in kg)
static const eT eV ()
electron volt (in joules)
static const eT e ()
elementary charge (in coulombs)
static const eT F ()
Faraday constant (in coulombs).
static const eT alpha ()
fine-structure constant
static const eT alpha_inv ()
inverse fine-structure constant
static const eT K_J ()
Josephson constant.
static const eT mu_0 ()
magnetic constant (in henries per meter)
static const eT phi_0 ()
magnetic flux quantum (in webers)
static const eT R ()
molar gas constant (in joules per mole kelvin)
static const eT G ()
Newtonian constant of gravitation (in newton square meters per kilogram squared).
static const eT h ()
Planck constant (in joule seconds).
static const eT h_bar ()
Planck constant over 2 pi, aka reduced Planck constant (in joule seconds).
static const eT m_p ()
proton mass (in kg)
static const eT R_inf ()
Rydberg constant (in reciprocal meters).
static const eT c_0 ()
speed of light in vacuum (in meters per second)
static const eT sigma ()
Stefan-Boltzmann constant.
static const eT R_k ()
von Klitzing constant (in ohms)
static const eT b ()
Wien wavelength displacement law constant.
Detailed Description
template<typename eT>
class Phy< eT >
Physical constants taken from NIST and WolframAlpha on 2009-06-23 http://physics.nist.gov/cuu/Constants http://www.wolframalpha.com See also http://en.wikipedia.org/wiki/Physical_constant.
Definition at line 61 of file constants.hpp.
Member Function Documentation
template<typename eT > static const eT Phy< eT >::m_u () [inline, static]
atomic mass constant (in kg)
Definition at line 66 of file constants.hpp.
References Phy< eT >::e().
{  return eT(1.660538782e-27); }
template<typename eT > static const eT Phy< eT >::N_A () [inline, static]
Avogadro constant.
Definition at line 69 of file constants.hpp.
{  return eT(6.02214179e23); }
template<typename eT > static const eT Phy< eT >::k () [inline, static]
Boltzmann constant (in joules per kelvin).
Definition at line 72 of file constants.hpp.
References Phy< eT >::e().
{  return eT(1.3806504e-23); }
template<typename eT > static const eT Phy< eT >::k_evk () [inline, static]
Boltzmann constant (in eV/K).
Definition at line 75 of file constants.hpp.
References Phy< eT >::e().
{  return eT(8.617343e-5); }
template<typename eT > static const eT Phy< eT >::a_0 () [inline, static]
Bohr radius (in meters).
Definition at line 78 of file constants.hpp.
References Phy< eT >::e().
{ return eT(0.52917720859e-10); }
template<typename eT > static const eT Phy< eT >::mu_B () [inline, static]
Bohr magneton.
Definition at line 81 of file constants.hpp.
References Phy< eT >::e().
{ return(927.400915e-26); }
template<typename eT > static const eT Phy< eT >::Z_0 () [inline, static]
characteristic impedance of vacuum (in ohms)
Definition at line 84 of file constants.hpp.
References Phy< eT >::e().
{ return eT(3.76730313461771e-2); }
template<typename eT > static const eT Phy< eT >::G_0 () [inline, static]
conductance quantum (in siemens)
Definition at line 87 of file constants.hpp.
References Phy< eT >::e().
{ return eT(7.7480917004e-5); }
template<typename eT > static const eT Phy< eT >::k_e () [inline, static]
Coulomb's constant (in meters per farad).
Definition at line 90 of file constants.hpp.
{ return eT(8.9875517873681764e9); }
template<typename eT > static const eT Phy< eT >::eps_0 () [inline, static]
electric constant (in farads per meter)
Definition at line 93 of file constants.hpp.
References Phy< eT >::e().
{ return eT(8.85418781762039e-12); }
template<typename eT > static const eT Phy< eT >::m_e () [inline, static]
electron mass (in kg)
Definition at line 96 of file constants.hpp.
References Phy< eT >::e().
{ return eT(9.10938215e-31); }
template<typename eT > static const eT Phy< eT >::eV () [inline, static]
electron volt (in joules)
Definition at line 99 of file constants.hpp.
References Phy< eT >::e().
{ return eT(1.602176487e-19); }
template<typename eT > static const eT Phy< eT >::e () [inline, static]
elementary charge (in coulombs)
Definition at line 102 of file constants.hpp.
Referenced by Phy< eT >::a_0(), Phy< eT >::alpha(), Phy< eT >::b(), Phy< eT >::eps_0(), Phy< eT >::eV(), Phy< eT >::G(), Phy< eT >::G_0(), Phy< eT >::h(), Phy< eT >::h_bar(), Phy< eT >::k(), Phy< eT >::k_evk(), Phy< eT >::m_e(), Phy< eT >::m_p(), Phy< eT >::m_u(), Phy< eT >::mu_0(), Phy< eT >::mu_B(), Phy< eT >::phi_0(), Phy< eT >::sigma(), and Phy< eT >::Z_0().
{ return eT(1.602176487e-19); }
template<typename eT > static const eT Phy< eT >::F () [inline, static]
Faraday constant (in coulombs).
Definition at line 105 of file constants.hpp.
{ return eT(96485.3399); }
template<typename eT > static const eT Phy< eT >::alpha () [inline, static]
fine-structure constant
Definition at line 108 of file constants.hpp.
References Phy< eT >::e().
{ return eT(7.2973525376e-3); }
template<typename eT > static const eT Phy< eT >::alpha_inv () [inline, static]
inverse fine-structure constant
Definition at line 111 of file constants.hpp.
{ return eT(137.035999679); }
template<typename eT > static const eT Phy< eT >::K_J () [inline, static]
Josephson constant.
Definition at line 114 of file constants.hpp.
{ return eT(483597.891e9); }
template<typename eT > static const eT Phy< eT >::mu_0 () [inline, static]
magnetic constant (in henries per meter)
Definition at line 117 of file constants.hpp.
References Phy< eT >::e().
{ return eT(1.25663706143592e-06); }
template<typename eT > static const eT Phy< eT >::phi_0 () [inline, static]
magnetic flux quantum (in webers)
Definition at line 120 of file constants.hpp.
References Phy< eT >::e().
{ return eT(2.067833667e-15); }
template<typename eT > static const eT Phy< eT >::R () [inline, static]
molar gas constant (in joules per mole kelvin)
Definition at line 123 of file constants.hpp.
{ return eT(8.314472); }
template<typename eT > static const eT Phy< eT >::G () [inline, static]
Newtonian constant of gravitation (in newton square meters per kilogram squared).
Definition at line 126 of file constants.hpp.
References Phy< eT >::e().
{ return eT(6.67428e-11); }
template<typename eT > static const eT Phy< eT >::h () [inline, static]
Planck constant (in joule seconds).
Definition at line 129 of file constants.hpp.
References Phy< eT >::e().
{ return eT(6.62606896e-34); }
template<typename eT > static const eT Phy< eT >::h_bar () [inline, static]
Planck constant over 2 pi, aka reduced Planck constant (in joule seconds).
Definition at line 132 of file constants.hpp.
References Phy< eT >::e().
{ return eT(1.054571628e-34); }
template<typename eT > static const eT Phy< eT >::m_p () [inline, static]
proton mass (in kg)
Definition at line 135 of file constants.hpp.
References Phy< eT >::e().
{ return eT(1.672621637e-27); }
template<typename eT > static const eT Phy< eT >::R_inf () [inline, static]
Rydberg constant (in reciprocal meters).
Definition at line 138 of file constants.hpp.
{ return eT(10973731.568527); }
template<typename eT > static const eT Phy< eT >::c_0 () [inline, static]
speed of light in vacuum (in meters per second)
Definition at line 141 of file constants.hpp.
{ return eT(299792458.0); }
template<typename eT > static const eT Phy< eT >::sigma () [inline, static]
Stefan-Boltzmann constant.
Definition at line 144 of file constants.hpp.
References Phy< eT >::e().
{ return eT(5.670400e-8); }
template<typename eT > static const eT Phy< eT >::R_k () [inline, static]
von Klitzing constant (in ohms)
Definition at line 147 of file constants.hpp.
{ return eT(25812.807557); }
template<typename eT > static const eT Phy< eT >::b () [inline, static]
Wien wavelength displacement law constant.
Definition at line 150 of file constants.hpp.
References Phy< eT >::e().
{ return eT(2.8977685e-3); }