Armadillo Technical: unwrap_write< Row< eT > > Class Template Reference
unwrap_write< Row< eT > > Class Template Reference
[Unwrap]
#include <unwrap.hpp>
Public Member Functions
unwrap_write (Mat< eT > &out, const Row< eT > &A)
unwrap_write (Row< eT > &out, const Row< eT > &A)
unwrap_write (Col< eT > &out, const Row< eT > &A)
~unwrap_write ()
Public Attributes
const Row< eT > & M
Detailed Description
template<typename eT>
class unwrap_write< Row< eT > >
Definition at line 783 of file unwrap.hpp.
Constructor & Destructor Documentation
template<typename eT > unwrap_write< Row< eT > >::unwrap_write (Mat< eT > & out, const Row< eT > & A) [inline]
Definition at line 788 of file unwrap.hpp.
References Mat< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Row< eT > >::unwrap_write (Row< eT > & out, const Row< eT > & A) [inline]
Definition at line 797 of file unwrap.hpp.
References Row< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Row< eT > >::unwrap_write (Col< eT > & out, const Row< eT > & A) [inline]
Definition at line 805 of file unwrap.hpp.
References Col< eT >::copy_size().
    : M(A)
    {
    arma_extra_debug_sigprint();
    out.copy_size(A);
    }
template<typename eT > unwrap_write< Row< eT > >::~unwrap_write () [inline]
Definition at line 814 of file unwrap.hpp.
    {
    }
Member Data Documentation
template<typename eT > const Row<eT>& unwrap_write< Row< eT > >::M
Definition at line 819 of file unwrap.hpp.