Armadillo Technical: syslib Class Reference
syslib Class Reference
[Syslib]
#include <syslib_proto.hpp>
Static Public Member Functions
template<typename eT >
static arma_hot void copy_elem (eT *dest, const eT *src, const u32 n_elem)
Detailed Description
Definition at line 21 of file syslib_proto.hpp.
Member Function Documentation
template<typename eT > static arma_hot void syslib::copy_elem (eT * dest, const eT * src, const u32 n_elem) [inline, static]
Definition at line 30 of file syslib_proto.hpp.
Referenced by op_reshape::apply(), op_trans::apply_noalias(), Cube< eT >::Cube(), conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< Col< out_eT > >::from(), conv_to< Row< out_eT > >::from(), Mat< eT >::init(), Cube< eT >::init(), Mat< eT >::Mat(), podarray< eT >::operator=(), podarray< eT >::podarray(), auxlib::solve_od(), and auxlib::solve_ud().
    {
    if( n_elem <= (128/sizeof(eT)) )
      {
      u32 i,j;
      for(i=0, j=1; j<n_elem; i+=2, j+=2)
        {
        dest[i] = src[i];
        dest[j] = src[j];
        }
      if(i < n_elem)
        {
        dest[i] = src[i];
        }
      }
    else
      {
      std::memcpy(dest, src, n_elem*sizeof(eT));
      }
    }