Armadillo Technical: Cmath_wrap
Cmath_wrap
Functions
template<typename eT >
arma_inline bool arma_isfinite (eT val)
arma_inline bool arma_isfinite (float x)
arma_inline bool arma_isfinite (double x)
template<typename T >
arma_inline bool arma_isfinite (const std::complex< T > &x)
Function Documentation
template<typename eT > arma_inline bool arma_isfinite (eT val) [inline]
Definition at line 30 of file cmath_wrap.hpp.
Referenced by arma_isfinite(), and Mat< eT >::is_finite().
  {
  return true;
  }
arma_inline bool arma_isfinite (float x)
Definition at line 39 of file cmath_wrap.hpp.
  {
  #if defined(_GLIBCXX_USE_C99_MATH)
    {
    return (std::isfinite(x) != 0);
    }
  #else
    {
    const bool x_is_inf = ( (x == x) && ((x - x) != float(0)) );
    const bool x_is_nan = (x != x);
    return ( (x_is_inf == false) && (x_is_nan == false) );
    }
  #endif
  }
arma_inline bool arma_isfinite (double x)
Definition at line 59 of file cmath_wrap.hpp.
  {
  #if defined(_GLIBCXX_USE_C99_MATH)
    {
    return (std::isfinite(x) != 0);
    }
  #else
    {
    const bool x_is_inf = ( (x == x) && ((x - x) != double(0)) );
    const bool x_is_nan = (x != x);
    return ( (x_is_inf == false) && (x_is_nan == false) );
    }
  #endif
  }
template<typename T > arma_inline bool arma_isfinite (const std::complex< T > & x) [inline]
Definition at line 80 of file cmath_wrap.hpp.
References arma_isfinite().
  {
  if( (arma_isfinite(x.real()) == false) || (arma_isfinite(x.imag()) == false) )
    {
    return false;
    }
  else
    {
    return true;
    }
  }