Armadillo Technical: Glue_plus
Glue_plus
Classes
class glue_plus
Class which implements the immediate addition matrices, with the result stored in 'mat' (dense matrix).
class glue_plus_diag
Functions
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Mat< eT > &A, const Mat< eT > &B)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Mat< eT > &A, const Mat< eT > &B, const Mat< eT > &C)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Glue< Mat< eT >, Mat< eT >, glue_plus > &X)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Glue< Glue< Mat< eT >, Mat< eT >, glue_plus >, Mat< eT >, glue_plus > &X)
template<typename T1 , typename T2 >
static void glue_plus::apply (Mat< typename T1::elem_type > &out, const Glue< T1, T2, glue_plus > &X)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Glue< Mat< eT >, subview< eT >, glue_plus > &X)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Glue< subview< eT >, Mat< eT >, glue_plus > &X)
template<typename eT >
static void glue_plus::apply (Mat< eT > &out, const Glue< subview< eT >, subview< eT >, glue_plus > &X)
template<typename eT >
static void glue_plus::apply_inplace (Mat< eT > &out, const Mat< eT > &B)
template<typename T1 , typename op_type >
static void glue_plus::apply_inplace (Mat< typename T1::elem_type > &out, const Op< T1, op_type > &X)
template<typename T1 >
static void glue_plus::apply_inplace (Mat< typename T1::elem_type > &out, const Op< T1, op_square > &X)
template<typename T1 , typename T2 , typename glue_type >
static void glue_plus::apply_inplace (Mat< typename T1::elem_type > &out, const Glue< T1, T2, glue_type > &X)
template<typename T1 , typename T2 >
static void glue_plus::apply_inplace (Mat< typename T1::elem_type > &out, const Glue< T1, T2, glue_times > &X)
template<typename T1 , typename T2 >
static void glue_plus::apply (Mat< typename T1::elem_type > &out, const Glue< Glue< T1, Col< typename T1::elem_type >, glue_times_vec >, T2, glue_plus > &in)
template<typename T1 , typename T2 >
static void glue_plus::apply (Mat< typename T1::elem_type > &out, const Glue< Glue< Row< typename T1::elem_type >, T1, glue_times_vec >, T2, glue_plus > &in)
template<typename eT1 , typename eT2 >
static void glue_plus::apply_mixed (Mat< typename promote_type< eT1, eT2 >::result > &out, const Mat< eT1 > &X, const Mat< eT2 > &Y)
template<typename T1 , typename T2 >
static void glue_plus_diag::apply (Mat< typename T1::elem_type > &out, const T1 &A, const Op< T2, op_diagmat > &B)
template<typename T1 , typename T2 >
static void glue_plus_diag::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_diagmat > &A, const Op< T2, op_diagmat > &B)
template<typename T1 , typename T2 >
static void glue_plus_diag::apply (Mat< typename T1::elem_type > &out, const Glue< T1, Op< T2, op_diagmat >, glue_plus_diag > &X)
template<typename T1 , typename T2 >
static void glue_plus_diag::apply (Mat< typename T1::elem_type > &out, const Glue< Op< T1, op_diagmat >, T2, glue_plus_diag > &X)
template<typename T1 , typename T2 >
static void glue_plus_diag::apply (Mat< typename T1::elem_type > &out, const Glue< Op< T1, op_diagmat >, Op< T2, op_diagmat >, glue_plus_diag > &X)
Function Documentation
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Mat< eT > & A, const Mat< eT > & B) [inline, static, inherited]
Definition at line 24 of file glue_plus_meat.hpp.
References Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, Mat< eT >::n_elem, Mat< eT >::n_rows, and Mat< eT >::set_size().
Referenced by apply(), apply_inplace(), and apply_mixed().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "matrix addition");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] + B_mem[i];
    }
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Mat< eT > & A, const Mat< eT > & B, const Mat< eT > & C) [inline, static, inherited]
Definition at line 51 of file glue_plus_meat.hpp.
References Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, Mat< eT >::n_elem, Mat< eT >::n_rows, and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "matrix addition");
  arma_debug_assert_same_size(A, C, "matrix addition");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT* C_mem   = C.mem;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] + B_mem[i] + C_mem[i];
    }
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Glue< Mat< eT >, Mat< eT >, glue_plus > & X) [inline, static, inherited]
Definition at line 80 of file glue_plus_meat.hpp.
References apply().
  {
  glue_plus::apply(out, X.A, X.B);
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Glue< Glue< Mat< eT >, Mat< eT >, glue_plus >, Mat< eT >, glue_plus > & X) [inline, static, inherited]
Definition at line 90 of file glue_plus_meat.hpp.
References apply().
  {
  glue_plus::apply(out, X.A.A, X.A.B, X.B);
  }
template<typename T1 , typename T2 > void glue_plus::apply (Mat< typename T1::elem_type > & out, const Glue< T1, T2, glue_plus > & X) [inline, static, inherited]
Definition at line 100 of file glue_plus_meat.hpp.
References Glue< T1, T2, glue_type >::A, apply(), apply_inplace(), Glue< T1, T2, glue_type >::B, and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const u32 N_mat = 1 + depth_lhs< glue_plus, Glue<T1,T2,glue_plus> >::num;
  arma_extra_debug_print( arma_boost::format("N_mat = %d") % N_mat );
  if(N_mat == 2)
    {
    if(is_glue_times<T1>::value == true)
      {
      out = X.B;
      glue_plus::apply_inplace(out, X.A);
      }
    else
    if(is_glue_times<T2>::value == true)
      {
      out = X.A;
      glue_plus::apply_inplace(out, X.B);
      }
    else
      {
      const unwrap<T1> tmp1(X.A);
      const unwrap<T2> tmp2(X.B);
      glue_plus::apply(out, tmp1.M, tmp2.M);
      }
    }
  else
    {
    const Mat<eT>* ptrs[N_mat];
    bool            del[N_mat];
    mat_ptrs<glue_plus, Glue<T1,T2,glue_plus> >::get_ptrs(ptrs, del, X);
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format("ptrs[%d] = %x") % i % ptrs[i] );
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format(" del[%d] = %d") % i %  del[i] );
    const u32 n_rows = ptrs[0]->n_rows;
    const u32 n_cols = ptrs[0]->n_cols;
    const Mat<eT>& tmp_mat = *(ptrs[0]);
    for(u32 i=1; i<N_mat; ++i)
      {
      arma_debug_assert_same_size(tmp_mat, *(ptrs[i]), "matrix addition");
      }
    // no aliasing problem
    out.set_size(n_rows, n_cols);
    const u32 n_elem = ptrs[0]->n_elem;
    for(u32 j=0; j<n_elem; ++j)
      {
      eT acc = ptrs[0]->mem[j];
      for(u32 i=1; i < N_mat; ++i)
        {
        acc += ptrs[i]->mem[j];
        }
      out[j] = acc;
      }
    for(u32 i=0; i<N_mat; ++i)
      {
      if(del[i] == true)
        {
        arma_extra_debug_print( arma_boost::format("delete mat_ptr[%d]") % i );
        delete ptrs[i];
        }
      }
    }
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Glue< Mat< eT >, subview< eT >, glue_plus > & X) [inline, static, inherited]
Definition at line 196 of file glue_plus_meat.hpp.
References apply(), Mat< eT >::at(), Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  const Mat<eT>& orig_A = X.A;
  const Mat<eT>& orig_B = X.B.m;
  if( &out != &orig_B )
    {
    //const u32 sub_B_n_rows = X.B.n_rows;
    //const u32 sub_B_n_cols = X.B.n_cols;
    arma_debug_assert_same_size(X.A, X.B, "matrix addition");
    out.set_size(orig_A.n_rows, orig_A.n_cols);
    for(u32 col = 0; col<orig_A.n_cols; ++col)
      {
      const u32 B_col_mod = X.B.aux_col1 + col;
      for(u32 row = 0; row<orig_A.n_rows; ++row)
        {
        const u32 B_row_mod = X.B.aux_row1 + row;
        out.at(row,col) =  orig_A.at(row, col) + orig_B.at(B_row_mod, B_col_mod);
        }
      }
    }
  else
    {
    const Mat<eT> processed_B(X.B);  // create a matrix out of subview
    glue_plus::apply(out, orig_A, processed_B);
    }
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Glue< subview< eT >, Mat< eT >, glue_plus > & X) [inline, static, inherited]
Definition at line 244 of file glue_plus_meat.hpp.
References apply(), Mat< eT >::at(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  const Mat<eT>& orig_A = X.A.m;
  const unwrap_check< Mat<eT> > tmp(X.B, out);
  const Mat<eT>& orig_B = tmp.M;
  if( &out != &orig_A )
    {
    const u32 sub_A_n_rows = X.A.n_rows;
    const u32 sub_A_n_cols = X.A.n_cols;
    arma_debug_assert_same_size(X.A, X.B, "matrix addition");
    out.set_size(sub_A_n_rows, sub_A_n_cols);
    for(u32 col = 0; col<sub_A_n_cols; ++col)
      {
      const u32 A_col_mod = X.A.aux_col1 + col;
      for(u32 row = 0; row<sub_A_n_rows; ++row)
        {
        const u32 A_row_mod = X.A.aux_row1 + row;
        out.at(row,col) =  orig_A.at(A_row_mod, A_col_mod) + orig_B.at(row, col);
        }
      }
    }
  else
    {
    const Mat<eT> processed_A(X.A);
    glue_plus::apply(out, processed_A, orig_B);
    }
  }
template<typename eT > void glue_plus::apply (Mat< eT > & out, const Glue< subview< eT >, subview< eT >, glue_plus > & X) [inline, static, inherited]
Definition at line 293 of file glue_plus_meat.hpp.
References apply(), Mat< eT >::at(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  const Mat<eT>& orig_A = X.A.m;
  const Mat<eT>& orig_B = X.B.m;
  if( (&out != &orig_A) && (&out != &orig_B) )
    {
    const u32 sub_A_n_rows = X.A.n_rows;
    const u32 sub_A_n_cols = X.A.n_cols;
    const u32 sub_B_n_rows = X.B.n_rows;
    const u32 sub_B_n_cols = X.B.n_cols;
    arma_debug_assert_same_size(X.A, X.B, "matrix addition");
    out.set_size(sub_A_n_rows, sub_A_n_cols);
    for(u32 col = 0; col<sub_A_n_cols; ++col)
      {
      const u32 A_col_mod = X.A.aux_col1 + col;
      const u32 B_col_mod = X.B.aux_col1 + col;
      for(u32 row = 0; row<sub_A_n_rows; ++row)
        {
        const u32 A_row_mod = X.A.aux_row1 + row;
        const u32 B_row_mod = X.B.aux_row1 + row;
        out.at(row,col) =  orig_A.at(A_row_mod, A_col_mod) + orig_B.at(B_row_mod, B_col_mod);
        }
      }
    }
  else
    {
    const Mat<eT> processed_A(X.A);
    const Mat<eT> processed_B(X.B);
    glue_plus::apply(out, processed_A, processed_B);
    }
  }
template<typename eT > void glue_plus::apply_inplace (Mat< eT > & out, const Mat< eT > & B) [inline, static, inherited]
Definition at line 339 of file glue_plus_meat.hpp.
References Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by apply(), and Mat< eT >::operator+=().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(out, B, "matrix addition");
        eT* out_mem = out.memptr();
  const eT* B_mem   = B.mem;
  const u32 n_elem  = B.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] += B_mem[i];
    }
  }
template<typename T1 , typename op_type > void glue_plus::apply_inplace (Mat< typename T1::elem_type > & out, const Op< T1, op_type > & X) [inline, static, inherited]
Definition at line 363 of file glue_plus_meat.hpp.
References apply().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Mat<eT> tmp(X);
  glue_plus::apply(out, out, tmp);
  }
template<typename T1 > void glue_plus::apply_inplace (Mat< typename T1::elem_type > & out, const Op< T1, op_square > & X) [inline, static, inherited]
Definition at line 378 of file glue_plus_meat.hpp.
References Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(X.m);
  const Mat<eT>& B = tmp.M;
  arma_debug_assert_same_size(out, B, "matrix addition");
        eT* out_mem = out.memptr();
  const eT* B_mem   = B.mem;
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    const eT tmp = B_mem[i];
    out_mem[i] += tmp*tmp;
    }
  }
template<typename T1 , typename T2 , typename glue_type > void glue_plus::apply_inplace (Mat< typename T1::elem_type > & out, const Glue< T1, T2, glue_type > & X) [inline, static, inherited]
Definition at line 406 of file glue_plus_meat.hpp.
  {
  arma_extra_debug_sigprint();
  out = X + out;
  }
template<typename T1 , typename T2 > void glue_plus::apply_inplace (Mat< typename T1::elem_type > & out, const Glue< T1, T2, glue_times > & X) [inline, static, inherited]
Definition at line 418 of file glue_plus_meat.hpp.
References Glue< T1, T2, glue_type >::A, apply(), Glue< T1, T2, glue_type >::B, Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_check<T1> tmp1(X.A, out);
  const unwrap_check<T2> tmp2(X.B, out);
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_mul_size(A, B, "matrix multiplication");
  arma_debug_assert_same_size(out.n_rows, out.n_cols, A.n_rows, B.n_cols, "matrix addition");
  gemm<false,false,false,true>::apply(out, A, B, eT(1), eT(1));
  }
template<typename T1 , typename T2 > void glue_plus::apply (Mat< typename T1::elem_type > & out, const Glue< Glue< T1, Col< typename T1::elem_type >, glue_times_vec >, T2, glue_plus > & in) [inline, static, inherited]
Definition at line 448 of file glue_plus_meat.hpp.
References gemv< do_trans_A, use_alpha, use_beta >::apply(), Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.A.A);
  const unwrap<T2> tmp2(in.B);
  const Mat<eT>& A = tmp1.M;
  const Col<eT>& B = in.A.B;
  const Mat<eT>& C = tmp2.M;
  arma_debug_assert_mul_size(A, B, "matrix multiplication");
  arma_debug_assert_same_size(A.n_rows, B.n_cols, C.n_rows, C.n_cols, "matrix addition");
  if( (&out != &A) && (&out != &B) )
    {
    out = C;
    gemv<false,false,true>::apply(out.memptr(), A, B.mem, eT(1), eT(1));
    }
  else
    {
    const unwrap_check< Mat<eT>    > tmp1(A,out);
    const unwrap_check< Col<eT> > tmp2(B,out);
    const Mat<eT>& A_safe = tmp1.M;
    const Col<eT>& B_safe = tmp2.M;
    out = C;
    gemv<false,false,true>::apply(out.memptr(), A_safe, B_safe.mem, eT(1), eT(1));
    }
  }
template<typename T1 , typename T2 > void glue_plus::apply (Mat< typename T1::elem_type > & out, const Glue< Glue< Row< typename T1::elem_type >, T1, glue_times_vec >, T2, glue_plus > & in) [inline, static, inherited]
Definition at line 492 of file glue_plus_meat.hpp.
References gemv< do_trans_A, use_alpha, use_beta >::apply(), Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.A.B);
  const unwrap<T2> tmp2(in.B);
  const Row<eT>& A = in.A.A;
  const Mat<eT>& B = tmp1.M;
  const Mat<eT>& C = tmp2.M;
  arma_debug_assert_mul_size(A, B, "matrix multiplication");
  arma_debug_assert_same_size(A.n_rows, B.n_cols, C.n_rows, C.n_cols, "matrix addition");
  if( (&out != &A) && (&out != &B) )
    {
    out = C;
    gemv<true,false,true>::apply(out.memptr(), B, A.mem, eT(1), eT(1));
    }
  else
    {
    const unwrap_check< Mat<eT> > tmp1(A,out);
    const unwrap_check< Mat<eT> > tmp2(B,out);
    const Mat<eT>& A_safe = tmp1.M;
    const Mat<eT>& B_safe = tmp2.M;
    out = C;
    gemv<true,false,true>::apply(out.memptr(), B_safe, A_safe.mem, eT(1), eT(1));
    }
  }
template<typename eT1 , typename eT2 > void glue_plus::apply_mixed (Mat< typename promote_type< eT1, eT2 >::result > & out, const Mat< eT1 > & X, const Mat< eT2 > & Y) [inline, static, inherited]
Definition at line 538 of file glue_plus_meat.hpp.
References apply(), Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, Mat< eT >::n_elem, Mat< eT >::n_rows, and Mat< eT >::set_size().
Referenced by operator+().
  {
  arma_extra_debug_sigprint();
  typedef typename promote_type<eT1,eT2>::result out_eT;
  arma_debug_assert_same_size(X,Y, "matrix addition");
  out.set_size(X.n_rows, X.n_cols);
        out_eT* out_mem = out.memptr();
  const eT1*    X_mem   = X.mem;
  const eT2*    Y_mem   = Y.mem;
  const u32 n_elem = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = upgrade_val<eT1,eT2>::apply(X_mem[i]) + upgrade_val<eT1,eT2>::apply(Y_mem[i]);
    }
  }
template<typename T1 , typename T2 > void glue_plus_diag::apply (Mat< typename T1::elem_type > & out, const T1 & A, const Op< T2, op_diagmat > & B) [inline, static, inherited]
Definition at line 569 of file glue_plus_meat.hpp.
References Mat< eT >::at(), Mat< eT >::is_square(), Op< T1, op_type >::m, Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::set_size().
Referenced by glue_plus_diag::apply().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(A_orig);
  const unwrap<T2> tmp2(B_orig.m);
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_check( !B.is_square(), "glue_plus_diag::apply(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix addition");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
  for(u32 col=0; col<A.n_cols; ++col)
    {
    for(u32 row=0; row<A.n_rows; ++row)
      {
      if(col != row)
        {
        out.at(row,col) = A.at(row,col);
        }
      else
        {
        out.at(row,col) = A.at(row,col) + B.at(row,col);
        }
      }
    }
  }
template<typename T1 , typename T2 > void glue_plus_diag::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_diagmat > & A, const Op< T2, op_diagmat > & B) [inline, static, inherited]
Definition at line 612 of file glue_plus_meat.hpp.
References Mat< eT >::at(), Mat< eT >::is_square(), Op< T1, op_type >::m, Mat< eT >::n_cols, Mat< eT >::n_rows, Mat< eT >::set_size(), and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(A_orig.m);
  const unwrap<T2> tmp2(B_orig.m);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_check( !A.is_square(), "glue_plus_diag::apply(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix addition");
  if( (&out != &A) && (&out != &B) )
    {
    out.zeros(A.n_rows, A.n_cols);
    for(u32 i=0; i<A.n_rows; ++i)
      {
      out.at(i,i) = A.at(i,i) + B.at(i,i);
      }
    }
  else
    {
    out.set_size(A.n_rows, A.n_cols);
    for(u32 col=0; col<A.n_cols; ++col)
      {
      for(u32 row=0; row<A.n_rows; ++row)
        {
        if(col != row)
          {
          out.at(row,col) = 0.0;
          }
        else
          {
          out.at(row,col) = A.at(row,col) + B.at(row,col);
          }
        }
      }
    }
  }
template<typename T1 , typename T2 > void glue_plus_diag::apply (Mat< typename T1::elem_type > & out, const Glue< T1, Op< T2, op_diagmat >, glue_plus_diag > & X) [inline, static, inherited]
Definition at line 666 of file glue_plus_meat.hpp.
References glue_plus_diag::apply().
  {
  glue_plus_diag::apply(out, X.A, X.B);
  }
template<typename T1 , typename T2 > void glue_plus_diag::apply (Mat< typename T1::elem_type > & out, const Glue< Op< T1, op_diagmat >, T2, glue_plus_diag > & X) [inline, static, inherited]
Definition at line 676 of file glue_plus_meat.hpp.
References glue_plus_diag::apply().
  {
  glue_plus_diag::apply(out, X.B, X.A);  // NOTE: arguments are swapped
  }
template<typename T1 , typename T2 > void glue_plus_diag::apply (Mat< typename T1::elem_type > & out, const Glue< Op< T1, op_diagmat >, Op< T2, op_diagmat >, glue_plus_diag > & X) [inline, static, inherited]
Definition at line 686 of file glue_plus_meat.hpp.
References glue_plus_diag::apply().
  {
  glue_plus_diag::apply(out, X.A, X.B);
  }