Armadillo Technical: Cmath_wrap
Cmath_wrap
Functions
template<typename eT >
arma_inline bool arma_isfinite (eT val)
template<>
arma_inline bool arma_isfinite (float x)
template<>
arma_inline bool arma_isfinite (double x)
template<typename T >
arma_inline bool arma_isfinite (const std::complex< T > &x)
Function Documentation
template<typename eT > arma_inline bool arma_isfinite (eT val) [inline]
Definition at line 25 of file cmath_wrap.hpp.
Referenced by arma_isfinite(), Mat< eT >::is_finite(), Cube< eT >::is_finite(), log_add(), and running_stat< eT >::operator()().
  {
  return true;
  }
template<> arma_inline bool arma_isfinite (float x) [inline]
Definition at line 35 of file cmath_wrap.hpp.
  {
  #if defined(ARMA_HAVE_STD_ISFINITE)
    {
    return (std::isfinite(x) != 0);
    }
  #else
    {
    const bool x_is_inf = ( (x == x) && ((x - x) != float(0)) );
    const bool x_is_nan = (x != x);
    return ( (x_is_inf == false) && (x_is_nan == false) );
    }
  #endif
  }
template<> arma_inline bool arma_isfinite (double x) [inline]
Definition at line 56 of file cmath_wrap.hpp.
  {
  #if defined(ARMA_HAVE_STD_ISFINITE)
    {
    return (std::isfinite(x) != 0);
    }
  #else
    {
    const bool x_is_inf = ( (x == x) && ((x - x) != double(0)) );
    const bool x_is_nan = (x != x);
    return ( (x_is_inf == false) && (x_is_nan == false) );
    }
  #endif
  }
template<typename T > arma_inline bool arma_isfinite (const std::complex< T > & x) [inline]
Definition at line 77 of file cmath_wrap.hpp.
References arma_isfinite().
  {
  if( (arma_isfinite(x.real()) == false) || (arma_isfinite(x.imag()) == false) )
    {
    return false;
    }
  else
    {
    return true;
    }
  }