Armadillo Technical: Glue_div
Glue_div
Classes
class glue_div
Class which implements the immediate element-wise division of two or more matrices.
Functions
template<typename T1 , typename T2 >
static void glue_div::apply (Mat< typename T1::elem_type > &out, const Glue< T1, T2, glue_div > &X)
template<typename T1 >
static void glue_div::apply_inplace (Mat< typename T1::elem_type > &out, const T1 &X)
template<typename eT1 , typename eT2 >
static void glue_div::apply_mixed (Mat< typename promote_type< eT1, eT2 >::result > &out, const Mat< eT1 > &X, const Mat< eT2 > &Y)
element-wise division with different element types
template<typename eT >
static void glue_div::apply (Mat< eT > &out, const Mat< eT > &A, const Mat< eT > &B)
template<typename eT >
static void glue_div::apply (Mat< eT > &out, const Mat< eT > &A, const Mat< eT > &B, const Mat< eT > &C)
template<typename eT >
static void glue_div::apply (Mat< eT > &out, const Glue< Mat< eT >, Mat< eT >, glue_div > &X)
template<typename eT >
static void glue_div::apply (Mat< eT > &out, const Glue< Glue< Mat< eT >, Mat< eT >, glue_div >, Mat< eT >, glue_div > &X)
Function Documentation
template<typename T1 , typename T2 > void glue_div::apply (Mat< typename T1::elem_type > & out, const Glue< T1, T2, glue_div > & X) [inline, static, inherited]
Definition at line 24 of file glue_div_meat.hpp.
References Glue< T1, T2, glue_type >::A, apply_inplace(), Glue< T1, T2, glue_type >::B, and Mat< eT >::set_size().
Referenced by apply(), and apply_mixed().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const u32 N_mat = 1 + depth_lhs< glue_div, Glue<T1,T2,glue_div> >::num;
  arma_extra_debug_print( arma_boost::format("N_mat = %d") % N_mat );
  if(N_mat == 2)
    {
    if(is_Mat<T1>::value == false)
      {
      out = X.A;
      glue_div::apply_inplace(out, X.B);
      }
    else
      {
      const unwrap<T1> tmp1(X.A);
      const unwrap<T2> tmp2(X.B);
      glue_div::apply(out, tmp1.M, tmp2.M);
      }
    }
  else
    {
    const Mat<eT>* ptrs[N_mat];
    bool            del[N_mat];
    mat_ptrs<glue_div, Glue<T1,T2,glue_div> >::get_ptrs(ptrs, del, X);
    //mat_ptrs_outcheck<glue_div, Glue<T1,T2,glue_div> >::get_ptrs(ptrs, del, X, &out);
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format("ptrs[%d] = %x") % i % ptrs[i] );
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format(" del[%d] = %d") % i %  del[i] );
    const Mat<eT>& tmp_mat = *(ptrs[0]);
    for(u32 i=1; i<N_mat; ++i)
      {
      arma_debug_assert_same_size(tmp_mat, *(ptrs[i]), "element-wise matrix division");
      }
    const u32 n_rows = ptrs[0]->n_rows;
    const u32 n_cols = ptrs[0]->n_cols;
    // no aliasing problem
    out.set_size(n_rows,n_cols);
    const u32 n_elem = ptrs[0]->n_elem;
    for(u32 j=0; j<n_elem; ++j)
      {
      eT acc = ptrs[0]->mem[j];
      for(u32 i=1; i<N_mat; ++i)
        {
        acc /= ptrs[i]->mem[j];
        }
      out[j] = acc;
      }
    for(u32 i=0; i<N_mat; ++i)
      {
      if(del[i] == true)
        {
        arma_extra_debug_print( arma_boost::format("delete ptrs[%d]") % i );
        delete ptrs[i];
        }
      }
    }
  }
template<typename T1 > void glue_div::apply_inplace (Mat< typename T1::elem_type > & out, const T1 & X) [inline, static, inherited]
Definition at line 105 of file glue_div_meat.hpp.
References Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by apply(), and Mat< eT >::operator/=().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X);
  const Mat<eT>& B = tmp.M;
  arma_debug_assert_same_size(out, B, "element-wise matrix division");
  const u32 n_elem = out.n_elem;
        eT* out_mem = out.memptr();
  const eT* B_mem   = B.mem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] /= B_mem[i];
    }
  }
template<typename eT1 , typename eT2 > void glue_div::apply_mixed (Mat< typename promote_type< eT1, eT2 >::result > & out, const Mat< eT1 > & X, const Mat< eT2 > & Y) [inline, static, inherited]
element-wise division with different element types
Definition at line 134 of file glue_div_meat.hpp.
References apply(), and Mat< eT >::mem.
Referenced by operator/().
  {
  arma_extra_debug_sigprint();
  typedef typename promote_type<eT1,eT2>::result out_eT;
  arma_debug_assert_same_size(X,Y, "element-wise matrix division");
  //out.set_size(X.n_rows, X.n_cols);
  out.copy_size(X);
        out_eT* out_mem = out.memptr();
  const eT1*    X_mem   = X.mem;
  const eT2*    Y_mem   = Y.mem;
  const u32 n_elem = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = upgrade_val<eT1,eT2>::apply(X_mem[i]) / upgrade_val<eT1,eT2>::apply(Y_mem[i]);
    }
  }
template<typename eT > void glue_div::apply (Mat< eT > & out, const Mat< eT > & A, const Mat< eT > & B) [inline, static, inherited]
Definition at line 162 of file glue_div_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "element-wise matrix division");
  // no aliasing problem
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  const u32 n_elem = A.n_elem;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] / B_mem[i];
    }
  }
template<typename eT > void glue_div::apply (Mat< eT > & out, const Mat< eT > & A, const Mat< eT > & B, const Mat< eT > & C) [inline, static, inherited]
Definition at line 190 of file glue_div_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "element-wise matrix division");
  arma_debug_assert_same_size(B, C, "element-wise matrix division");
  // no aliasing problem
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  const u32 n_elem = A.n_elem;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT* C_mem   = C.mem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] / B_mem[i] / C_mem[i];
    }
  }
template<typename eT > void glue_div::apply (Mat< eT > & out, const Glue< Mat< eT >, Mat< eT >, glue_div > & X) [inline, static, inherited]
Definition at line 222 of file glue_div_meat.hpp.
References apply().
  {
  glue_div::apply(out, X.A, X.B);
  }
template<typename eT > void glue_div::apply (Mat< eT > & out, const Glue< Glue< Mat< eT >, Mat< eT >, glue_div >, Mat< eT >, glue_div > & X) [inline, static, inherited]
Definition at line 232 of file glue_div_meat.hpp.
References apply().
  {
  glue_div::apply(out, X.A.A, X.A.B, X.B);
  }