Armadillo Technical: Op_cor
Op_cor
Classes
class op_cor
Functions
template<typename eT >
static void op_cor::direct_cor (Mat< eT > &out, const Mat< eT > &X, const u32 norm_type)
template<typename T >
static void op_cor::direct_cor (Mat< std::complex< T > > &out, const Mat< std::complex< T > > &X, const u32 norm_type)
template<typename T1 >
static void op_cor::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_cor > &in)
Function Documentation
template<typename eT > void op_cor::direct_cor (Mat< eT > & out, const Mat< eT > & X, const u32 norm_type) [inline, static, inherited]
Definition at line 27 of file op_cor_meat.hpp.
References Mat< eT >::is_vec(), Mat< eT >::n_rows, Mat< eT >::set_size(), stddev(), sum(), and trans().
Referenced by apply().
  {
  arma_extra_debug_sigprint();
  if(A.is_vec())
    {
    out.set_size(1,1);
    out[0] = eT(1);
    }
  else
    {
    const u32 N = A.n_rows;
    const eT norm_val = (norm_type == 0) ? ( (N > 1) ? eT(N-1) : eT(1) ) : eT(N);
    const Row<eT> acc = sum(A);
    const Row<eT> sd  = stddev(A);
    out = (trans(A) * A);
    out -= (trans(acc) * acc)/eT(N);
    out /= norm_val;
    out /= trans(sd) * sd;
    }
  }
template<typename T > void op_cor::direct_cor (Mat< std::complex< T > > & out, const Mat< std::complex< T > > & X, const u32 norm_type) [inline, static, inherited]
Definition at line 56 of file op_cor_meat.hpp.
References conj(), stddev(), sum(), and trans().
  {
  arma_extra_debug_sigprint();
  typedef typename std::complex<T> eT;
  if(A.is_vec())
    {
    out.set_size(1,1);
    out[0] = eT(1);
    }
  else
    {
    const u32 N = A.n_rows;
    const eT norm_val = (norm_type == 0) ? ( (N > 1) ? eT(N-1) : eT(1) ) : eT(N);
    const Row<eT> acc = sum(A);
    const Row<T>  sd  = stddev(A);
    out = trans(conj(A)) * A;
    out -= (trans(conj(acc)) * acc)/eT(N);
    out /= norm_val;
    //out = out / (trans(sd) * sd);
    out /= conv_to< Mat<eT> >::from(trans(sd) * sd);
    }
  }
template<typename T1 > void op_cor::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_cor > & in) [inline, static, inherited]
Definition at line 89 of file op_cor_meat.hpp.
References Op< T1, op_type >::aux_u32_a, direct_cor(), and Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_check<T1> tmp(in.m, out);
  const Mat<eT>& A     = tmp.M;
  const u32 norm_type = in.aux_u32_a;
  op_cor::direct_cor(out, A, norm_type);
  }