Armadillo Technical: Fn_diagmat
Fn_diagmat
Functions
template<typename T1 >
const Op< T1, op_diagmat > diagmat (const Base< typename T1::elem_type, T1 > &X)
interpret a mat as a diagonal matrix (i.e. off-diagonal entries are zero)
template<typename eT >
const Op< Mat< eT >
, op_diagmat_vec > diagmat (const Col< eT > &X)
interpret a colvec as a diagonal matrix
template<typename eT >
const Op< Mat< eT >
, op_diagmat_vec > diagmat (const Row< eT > &X)
interpret a rowvec as a diagonal matrix
template<typename eT >
Mat< eT > diagmat (const subview_col< eT > &X)
create a diagonal matrix out of subview_col
template<typename eT >
Mat< eT > diagmat (const subview_row< eT > &X)
create a diagonal matrix out of subview_row
template<typename eT >
Mat< eT > diagmat (const diagview< eT > &X)
create a diagonal matrix out of diagview
template<typename T1 >
const Op< T1, op_diagmat > & diagmat (const Op< T1, op_diagmat > &X)
two consecutive diagmat operations are equivalent to one diagmat operation
Function Documentation
template<typename T1 > const Op<T1, op_diagmat> diagmat (const Base< typename T1::elem_type, T1 > & X) [inline]
interpret a mat as a diagonal matrix (i.e. off-diagonal entries are zero)
Definition at line 24 of file fn_diagmat.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_pinv::direct_pinv().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_diagmat>(X.get_ref());
  }
template<typename eT > const Op<Mat<eT>, op_diagmat_vec> diagmat (const Col< eT > & X) [inline]
interpret a colvec as a diagonal matrix
Definition at line 37 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  return Op<Mat<eT>, op_diagmat_vec>(X);
  }
template<typename eT > const Op<Mat<eT>, op_diagmat_vec> diagmat (const Row< eT > & X) [inline]
interpret a rowvec as a diagonal matrix
Definition at line 50 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  return Op<Mat<eT>, op_diagmat_vec>(X);
  }
template<typename eT > Mat<eT> diagmat (const subview_col< eT > & X) [inline]
create a diagonal matrix out of subview_col
Definition at line 63 of file fn_diagmat.hpp.
References Mat< eT >::at(), subview< eT >::n_elem, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename eT > Mat<eT> diagmat (const subview_row< eT > & X) [inline]
create a diagonal matrix out of subview_row
Definition at line 84 of file fn_diagmat.hpp.
References Mat< eT >::at(), subview< eT >::n_elem, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename eT > Mat<eT> diagmat (const diagview< eT > & X) [inline]
create a diagonal matrix out of diagview
Definition at line 105 of file fn_diagmat.hpp.
References Mat< eT >::at(), diagview< eT >::n_elem, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename T1 > const Op<T1, op_diagmat>& diagmat (const Op< T1, op_diagmat > & X) [inline]
two consecutive diagmat operations are equivalent to one diagmat operation
Definition at line 126 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("diagmat(): two consecutive diagmat() operations detected");
  return X;
  }