Armadillo Technical: Fn_rand
Fn_rand
Functions
const Op< mat, op_rand > rand (const u32 n_rows, const u32 n_cols)
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
const Op< colvec, op_rand > rand (const u32 n_elem)
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
const OpCube< cube, op_rand > rand (const u32 n_rows, const u32 n_cols, const u32 n_slices)
Generate a dense cube with all elements set to random values in the [0,1] interval (uniform distribution).
Function Documentation
const Op< mat_type, op_rand > rand (const u32 n_rows, const u32 n_cols) [inline]
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 38 of file fn_rand.hpp.
Referenced by op_shuffle::apply(), op_rand::direct_rand(), and op_randn::randn().
  {
  arma_extra_debug_sigprint();
  arma_type_check<is_Mat<mat_type>::value == false>::apply();
  return Op<mat_type,op_rand>(n_rows, n_cols, 'j');
  }
const Op< vec_type, op_rand > rand (const u32 n_elem) [inline]
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 64 of file fn_rand.hpp.
  {
  arma_extra_debug_sigprint();
  arma_type_check< (is_Col<vec_type>::value == false) && (is_Row<vec_type>::value == false) >::apply();
  if(is_Row<vec_type>::value == true)
    {
    return Op<vec_type,op_rand>(1, n_elem, 'j');
    }
  else
    {
    return Op<vec_type,op_rand>(n_elem, 1, 'j');
    }
  }
const OpCube< cube_type, op_rand > rand (const u32 n_rows, const u32 n_cols, const u32 n_slices) [inline]
Generate a dense cube with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 103 of file fn_rand.hpp.
  {
  arma_extra_debug_sigprint();
  arma_type_check<is_Cube<cube_type>::value == false>::apply();
  return OpCube<cube_type,op_rand>(n_rows, n_cols, n_slices);
  }