Armadillo Technical: Fn_trans
Fn_trans
Functions
template<typename T1 >
const Op< T1, op_trans > trans (const Base< typename T1::elem_type, T1 > &X)
template<typename eT >
const Op< Row< eT >, op_trans > trans (const Row< eT > &X)
template<typename eT >
const Op< Col< eT >, op_trans > trans (const Col< eT > &X)
template<typename T1 >
const T1 & trans (const Op< T1, op_trans > &X)
two consecutive transpose operations cancel each other
template<typename T1 >
const Op< T1, op_diagmat > trans (const Op< T1, op_diagmat > &X)
transpose of a diagonal matrix gives you the original matrix back
template<typename T1 >
const Op< T1, op_htrans > trans (const Op< T1, op_conj > &X)
the transpose of the conjugate of a complex matrix is equivalent to the hermitian transpose
Function Documentation
template<typename T1 > const Op<T1, op_trans> trans (const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 23 of file fn_trans.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), op_cor::direct_cor(), glue_cor::direct_cor(), op_cov::direct_cov(), glue_cov::direct_cov(), op_pinv::direct_pinv(), auxlib::solve_od(), auxlib::solve_ud(), and running_stat_vec_aux::update_stats().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_trans>(X.get_ref());
  }
template<typename eT > const Op<Row<eT>, op_trans> trans (const Row< eT > & X) [inline]
Definition at line 35 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  return Op<Row<eT>, op_trans>(X);
  }
template<typename eT > const Op<Col<eT>, op_trans> trans (const Col< eT > & X) [inline]
Definition at line 47 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  return Op<Col<eT>, op_trans>(X);
  }
template<typename T1 > const T1& trans (const Op< T1, op_trans > & X) [inline]
two consecutive transpose operations cancel each other
Definition at line 60 of file fn_trans.hpp.
References Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("trans(): removing op_trans");
  return X.m;
  }
template<typename T1 > const Op<T1, op_diagmat> trans (const Op< T1, op_diagmat > & X) [inline]
transpose of a diagonal matrix gives you the original matrix back
Definition at line 74 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("trans(): not applying op_trans to diagonal matrix");
  return X;
  }
template<typename T1 > const Op<T1, op_htrans> trans (const Op< T1, op_conj > & X) [inline]
the transpose of the conjugate of a complex matrix is equivalent to the hermitian transpose
Definition at line 88 of file fn_trans.hpp.
References Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_complex<typename T1::elem_type>::value == false >::apply();
  return Op<T1, op_htrans>(X.m);
  }