Armadillo Technical: Op_eps
Op_eps
Classes
class op_eps
Functions
template<typename eT >
static eT op_eps::direct_eps (const eT x)
template<typename T >
static T op_eps::direct_eps (const std::complex< T > &x)
template<typename eT >
static void op_eps::direct_eps (Mat< eT > &out, const Mat< eT > &A)
template<typename T >
static void op_eps::direct_eps (Mat< T > &out, const Mat< std::complex< T > > &A)
template<typename T1 >
static void op_eps::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_eps > &in)
Function Documentation
template<typename eT > eT op_eps::direct_eps (const eT x) [inline, static, inherited]
Definition at line 27 of file op_eps_meat.hpp.
References abs(), log10(), and pow().
Referenced by apply(), direct_eps(), op_pinv::direct_pinv(), eps(), and rank().
  {
  //arma_extra_debug_sigprint();
  // acording to IEEE Standard for Floating-Point Arithmetic (IEEE 754)
  // the mantissa length for double is 53 bits = std::numeric_limits<double>::digits
  // the mantissa length for float  is 24 bits = std::numeric_limits<float >::digits
  //return std::pow( std::numeric_limits<eT>::radix, (std::floor(std::log10(std::abs(x))/std::log10(std::numeric_limits<eT>::radix))-(std::numeric_limits<eT>::digits-1)) );
  const eT radix_eT     = eT(std::numeric_limits<eT>::radix);
  const eT digits_m1_eT = eT(std::numeric_limits<eT>::digits - 1);
  return std::pow( radix_eT, eT(std::floor(std::log10(std::abs(x))/std::log10(radix_eT)) - digits_m1_eT) );
  }
template<typename T > T op_eps::direct_eps (const std::complex< T > & x) [inline, static, inherited]
Definition at line 48 of file op_eps_meat.hpp.
References abs(), log10(), and pow().
  {
  //arma_extra_debug_sigprint();
  //return std::pow( std::numeric_limits<T>::radix, (std::floor(std::log10(std::abs(x))/std::log10(std::numeric_limits<T>::radix))-(std::numeric_limits<T>::digits-1)) );
  const T radix_T     = T(std::numeric_limits<T>::radix);
  const T digits_m1_T = T(std::numeric_limits<T>::digits - 1);
  return std::pow( radix_T, T(std::floor(std::log10(std::abs(x))/std::log10(radix_T)) - digits_m1_T) );
  }
template<typename eT > void op_eps::direct_eps (Mat< eT > & out, const Mat< eT > & A) [inline, static, inherited]
Definition at line 65 of file op_eps_meat.hpp.
References Mat< eT >::copy_size(), direct_eps(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = op_eps::direct_eps( A_mem[i] );
    }
  }
template<typename T > void op_eps::direct_eps (Mat< T > & out, const Mat< std::complex< T > > & A) [inline, static, inherited]
Definition at line 87 of file op_eps_meat.hpp.
References Mat< eT >::copy_size(), direct_eps(), and Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  typedef typename std::complex<T> eT;
  out.copy_size(A);
         T* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = op_eps::direct_eps( A_mem[i] );
    }
  }
template<typename T1 > void op_eps::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_eps > & in) [inline, static, inherited]
Definition at line 111 of file op_eps_meat.hpp.
References direct_eps(), and Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type  eT;
  // in this case it doesn't matter if there is aliasing
  // (i.e. &out = &in.m), hence we use unwrap rather than unwrap_check
  const unwrap<T1>   tmp(in.m);
  const Mat<eT>& A = tmp.M;
  op_eps::direct_eps(out, A);
  }