Armadillo Technical: Fn_misc
Fn_misc
Functions
template<typename eT >
Mat< eT > linspace (const eT start, const eT end, const u32 num, const u32 dim=0)
Generate a vector with 'num' elements. The values of the elements linearly increase from 'start' upto (and including) 'end'.
mat linspace (const double start, const double end, const u32 num, const u32 dim=0)
template<typename T , typename T1 >
Mat< T > real (const Base< std::complex< T >, T1 > &X)
template<typename T , typename T1 >
Cube< T > real (const BaseCube< std::complex< T >, T1 > &X)
template<typename T , typename T1 >
Mat< T > imag (const Base< std::complex< T >, T1 > &X)
template<typename T , typename T1 >
Cube< T > imag (const BaseCube< std::complex< T >, T1 > &X)
template<typename eT >
eT log_add (eT log_a, eT log_b)
template<typename eT >
eT trunc_log (const eT x)
template<typename eT >
eT trunc_exp (const eT x)
template<typename T1 >
const Op< T1, op_log > log (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_log > log (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_trunc_log > trunc_log (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_trunc_log > trunc_log (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_log10 > log10 (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_log10 > log10 (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_exp > exp (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_exp > exp (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_trunc_exp > trunc_exp (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_trunc_exp > trunc_exp (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
Mat< typename T1::pod_type > abs (const Base< typename T1::elem_type, T1 > &X)
template<typename T1 >
Cube< typename T1::pod_type > abs (const BaseCube< typename T1::elem_type, T1 > &X)
template<typename T1 >
Mat< typename T1::pod_type > fabs (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
Cube< typename T1::pod_type > fabs (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_square > square (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_square > square (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_sqrt > sqrt (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_sqrt > sqrt (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_pow > pow (const Base< typename T1::elem_type, T1 > &A, const typename T1::elem_type exponent)
template<typename T1 >
const OpCube< T1, op_pow > pow (const BaseCube< typename T1::elem_type, T1 > &A, const typename T1::elem_type exponent)
template<typename T1 >
const Op< T1, op_pow > pow (const Base< typename T1::elem_type, T1 > &A, const typename T1::elem_type::value_type exponent)
template<typename T1 >
const OpCube< T1, op_pow > pow (const BaseCube< typename T1::elem_type, T1 > &A, const typename T1::elem_type::value_type exponent)
template<typename T1 >
const Op< T1, op_pow_s32 > pow (const Base< typename T1::elem_type, T1 > &A, const s32 exponent)
template<typename T1 >
const OpCube< T1, op_pow_s32 > pow (const BaseCube< typename T1::elem_type, T1 > &A, const s32 exponent)
template<typename T , typename T1 >
const Op< T1, op_conj > conj (const Base< std::complex< T >, T1 > &A)
template<typename T , typename T1 >
const OpCube< T1, op_conj > conj (const BaseCube< std::complex< T >, T1 > &A)
template<typename T1 >
const T1 & conj (const Op< T1, op_conj > &A)
template<typename T1 >
const T1 & conj (const OpCube< T1, op_conj > &A)
template<typename T1 >
const Op< T1, op_htrans > conj (const Op< T1, op_trans > &A)
the conjugate of the transpose of a complex matrix is the same as the hermitian transpose
Function Documentation
template<typename eT > Mat<eT> linspace (const eT start, const eT end, const u32 num, const u32 dim = 0) [inline]
Generate a vector with 'num' elements. The values of the elements linearly increase from 'start' upto (and including) 'end'.
Definition at line 26 of file fn_misc.hpp.
References Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (num < 2), "linspace(): num must be >= 2");
  Mat<eT> x;
  if(dim == 0)
    {
    x.set_size(num,1);  // column vector
    }
  else
    {
    x.set_size(1,num);  // row vector
    }
  const eT delta = (end-start)/(num-1);
  x[0] = start;
  for(u32 i=1; i<num; ++i)
    {
    x[i] = x[i-1] + delta;
    }
  return x;
  }
mat linspace (const double start, const double end, const u32 num, const u32 dim = 0) [inline]
Definition at line 60 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return linspace<double>(start, end, num, dim);
  }
template<typename T , typename T1 > Mat<T> real (const Base< std::complex< T >, T1 > & X) [inline]
Definition at line 74 of file fn_misc.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by real(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<T> eT;
  const unwrap<T1> A_tmp(X.get_ref());
  const Mat<eT>& A = A_tmp.M;
  Mat<T> out(A.n_rows, A.n_cols);
  const eT* A_mem = A.mem;
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::real(A_mem[i]);
    }
  return out;
  }
template<typename T , typename T1 > Cube<T> real (const BaseCube< std::complex< T >, T1 > & X) [inline]
Definition at line 101 of file fn_misc.hpp.
References Cube< eT >::memptr(), Cube< eT >::n_elem, and real().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<T> eT;
  const unwrap_cube<T1> A_tmp(X.get_ref());
  const Cube<eT>& A   = A_tmp.M;
  Cube<T> out(A.n_rows, A.n_cols, A.n_slices);
  const eT* A_mem = A.mem;
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::real(A_mem[i]);
    }
  return out;
  }
template<typename T , typename T1 > Mat<T> imag (const Base< std::complex< T >, T1 > & X) [inline]
Definition at line 131 of file fn_misc.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by imag().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<T> eT;
  const unwrap<T1> A_tmp(X.get_ref());
  const Mat<eT>& A = A_tmp.M;
  Mat<T> out(A.n_rows, A.n_cols);
  const eT* A_mem = A.mem;
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::imag(A_mem[i]);
    }
  return out;
  }
template<typename T , typename T1 > Cube<T> imag (const BaseCube< std::complex< T >, T1 > & X) [inline]
Definition at line 158 of file fn_misc.hpp.
References imag(), Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<T> eT;
  const unwrap_cube<T1> A_tmp(X.get_ref());
  const Cube<eT>& A   = A_tmp.M;
  Cube<T> out(A.n_rows, A.n_cols, A.n_slices);
  const eT* A_mem = A.mem;
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::imag(A_mem[i]);
    }
  return out;
  }
template<typename eT > eT log_add (eT log_a, eT log_b) [inline]
Definition at line 188 of file fn_misc.hpp.
References arma_isfinite(), exp(), and log().
  {
  if(log_a < log_b)
    {
    std::swap(log_a, log_b);
    }
  const eT negdelta = log_b - log_a;
  if( (negdelta < Math<eT>::log_min()) || (arma_isfinite(negdelta) == false) )
    {
    return log_a;
    }
  else
    {
    #if defined(ARMA_HAVE_LOG1P)
      return (log_a + log1p(std::exp(negdelta)));
    #else
      return (log_a + std::log(1.0 + std::exp(negdelta)));
    #endif
    }
  }
template<typename eT > eT trunc_log (const eT x) [inline]
Definition at line 216 of file fn_misc.hpp.
References log(), Math< eT >::log_max(), and Math< eT >::log_min().
Referenced by op_trunc_log::apply().
  {
  if(std::numeric_limits<eT>::is_iec559)
    {
    if(x == std::numeric_limits<eT>::infinity())
      {
      return Math<eT>::log_max();
      }
    if(x <= 0)
      {
      return Math<eT>::log_min();
      }
    else
      {
      return std::log(x);
      }
    }
  else
    {
    return std::log(x);
    }
  }
template<typename eT > eT trunc_exp (const eT x) [inline]
Definition at line 244 of file fn_misc.hpp.
References exp(), and max().
Referenced by op_trunc_exp::apply().
  {
  if(std::numeric_limits<eT>::is_iec559 && (x >= Math<eT>::log_max() ))
    {
    return std::numeric_limits<eT>::max();
    }
  else
    {
    return std::exp(x);
    }
  }
template<typename T1 > const Op<T1, op_log> log (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 264 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_log::apply(), log_add(), Math< eT >::log_max(), Math< eT >::log_min(), and trunc_log().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_log>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_log> log (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 276 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_log>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_trunc_log> trunc_log (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 291 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_trunc_log>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_trunc_log> trunc_log (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 303 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_trunc_log>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_log10> log10 (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 318 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_log10::apply(), and op_eps::direct_eps().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_log10>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_log10> log10 (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 330 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_log10>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_exp> exp (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 345 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_exp::apply(), log_add(), and trunc_exp().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_exp>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_exp> exp (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 357 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_exp>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_trunc_exp> trunc_exp (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 372 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_trunc_exp>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_trunc_exp> trunc_exp (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 384 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_trunc_exp>(A.get_ref());
  }
template<typename T1 > Mat<typename T1::pod_type> abs (const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 399 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref(), Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, Mat< eT >::n_elem, and Mat< eT >::n_rows.
Referenced by abs(), op_min::apply(), op_median::apply(), op_max::apply(), arma_qsort_helper< std::complex< T > >::ascend_compare(), arma_qsort_helper< std::complex< T > >::descend_compare(), op_median::direct_cx_median_index(), op_eps::direct_eps(), op_max::direct_max(), op_min::direct_min(), fabs(), and norm().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> A_tmp(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  const Mat<in_eT>& A = A_tmp.M;
  Mat<out_eT> out(A.n_rows, A.n_cols);
  const in_eT* A_mem   = A.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::abs(A_mem[i]);
    }
  return out;
  }
template<typename T1 > Cube<typename T1::pod_type> abs (const BaseCube< typename T1::elem_type, T1 > & X) [inline]
Definition at line 432 of file fn_misc.hpp.
References abs(), BaseCube< elem_type, derived >::get_ref(), Cube< eT >::mem, Cube< eT >::memptr(), Cube< eT >::n_cols, Cube< eT >::n_elem, Cube< eT >::n_rows, and Cube< eT >::n_slices.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> A_tmp(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  const Cube<in_eT>& A = A_tmp.M;
  Cube<out_eT> out(A.n_rows, A.n_cols, A.n_slices);
  const in_eT* A_mem   = A.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::abs(A_mem[i]);
    }
  return out;
  }
template<typename T1 > Mat<typename T1::pod_type> fabs (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 468 of file fn_misc.hpp.
References abs().
  {
  arma_extra_debug_sigprint();
  return abs(A);
  }
template<typename T1 > Cube<typename T1::pod_type> fabs (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 480 of file fn_misc.hpp.
References abs().
  {
  arma_extra_debug_sigprint();
  return abs(A);
  }
template<typename T1 > const Op<T1, op_square> square (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 495 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_square>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_square> square (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 507 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_square>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_sqrt> sqrt (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 522 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by accu(), op_stddev::apply(), op_sqrt::apply(), op_norm_dot::apply(), norm(), running_stat_vec< eT >::stddev(), running_stat< eT >::stddev(), and stddev().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_sqrt>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_sqrt> sqrt (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 534 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_sqrt>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_pow> pow (const Base< typename T1::elem_type, T1 > & A, const typename T1::elem_type exponent) [inline]
Definition at line 548 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_pow::apply(), op_eps::direct_eps(), op_pow_s32::internal_pow(), op_pow::internal_pow(), and norm().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_pow>(A.get_ref(), exponent);
  }
template<typename T1 > const OpCube<T1, op_pow> pow (const BaseCube< typename T1::elem_type, T1 > & A, const typename T1::elem_type exponent) [inline]
Definition at line 560 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_pow>(A.get_ref(), exponent);
  }
template<typename T1 > const Op<T1, op_pow> pow (const Base< typename T1::elem_type, T1 > & A, const typename T1::elem_type::value_type exponent) [inline]
Definition at line 574 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_pow>(A.get_ref(), eT(exponent));
  }
template<typename T1 > const OpCube<T1, op_pow> pow (const BaseCube< typename T1::elem_type, T1 > & A, const typename T1::elem_type::value_type exponent) [inline]
Definition at line 586 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_pow>(A.get_ref(), eT(exponent));
  }
template<typename T1 > const Op<T1, op_pow_s32> pow (const Base< typename T1::elem_type, T1 > & A, const s32 exponent) [inline]
Definition at line 603 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  if(exponent >= 0)
    {
    return Op<T1, op_pow_s32>(A.get_ref(), exponent, 0);
    }
  else
    {
    return Op<T1, op_pow_s32>(A.get_ref(), -exponent, 1);
    }
  }
template<typename T1 > const OpCube<T1, op_pow_s32> pow (const BaseCube< typename T1::elem_type, T1 > & A, const s32 exponent) [inline]
Definition at line 622 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  if(exponent >= 0)
    {
    return OpCube<T1, op_pow_s32>(A.get_ref(), exponent, 0);
    }
  else
    {
    return OpCube<T1, op_pow_s32>(A.get_ref(), -exponent, 1);
    }
  }
template<typename T , typename T1 > const Op<T1, op_conj> conj (const Base< std::complex< T >, T1 > & A) [inline]
Definition at line 647 of file fn_misc.hpp.
Referenced by op_conj::apply(), op_htrans::apply(), op_htrans::apply_noalias(), op_cor::direct_cor(), glue_cor::direct_cor(), op_cov::direct_cov(), glue_cov::direct_cov(), eig_gen(), auxlib::svd(), and running_stat_vec_aux::update_stats().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_conj>(A.get_ref());
  }
template<typename T , typename T1 > const OpCube<T1, op_conj> conj (const BaseCube< std::complex< T >, T1 > & A) [inline]
Definition at line 659 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_conj>(A.get_ref());
  }
template<typename T1 > const T1& conj (const Op< T1, op_conj > & A) [inline]
Definition at line 671 of file fn_misc.hpp.
References Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return A.m;
  }
template<typename T1 > const T1& conj (const OpCube< T1, op_conj > & A) [inline]
Definition at line 683 of file fn_misc.hpp.
References OpCube< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return A.m;
  }
template<typename T1 > const Op<T1, op_htrans> conj (const Op< T1, op_trans > & A) [inline]
the conjugate of the transpose of a complex matrix is the same as the hermitian transpose
Definition at line 695 of file fn_misc.hpp.
References Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_complex<typename T1::elem_type>::value == false >::apply();
  return Op<T1, op_htrans>(A.m);
  }