Armadillo Technical: Op_misc
Op_misc
Classes
class op_log
class op_trunc_log
class op_log10
class op_exp
class op_trunc_exp
class op_sqrt
class op_square
class op_pow
class op_pow_s32
class op_conj
Functions
template<typename T1 >
static void op_log::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_log > &in)
template<typename T1 >
static void op_log::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_log > &in)
template<typename T1 >
static void op_trunc_log::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_trunc_log > &in)
template<typename T1 >
static void op_trunc_log::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_trunc_log > &in)
template<typename T1 >
static void op_log10::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_log10 > &in)
template<typename T1 >
static void op_log10::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_log10 > &in)
template<typename T1 >
static void op_exp::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_exp > &in)
template<typename T1 >
static void op_exp::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_exp > &in)
template<typename T1 >
static void op_trunc_exp::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_trunc_exp > &in)
template<typename T1 >
static void op_trunc_exp::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_trunc_exp > &in)
template<typename T1 >
static void op_sqrt::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_sqrt > &in)
template<typename T1 >
static void op_sqrt::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_sqrt > &in)
template<typename T1 >
static void op_square::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_square > &in)
template<typename T1 >
static void op_square::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_square > &in)
template<typename T1 , typename T2 >
static T1 op_pow::internal_pow (const T1 base, const T2 exponent)
template<typename T2 >
static char op_pow::internal_pow (const char base, const T2 exponent)
template<typename T2 >
static unsigned char op_pow::internal_pow (const unsigned char base, const T2 exponent)
template<typename T2 >
static int op_pow::internal_pow (const int base, const T2 exponent)
template<typename T2 >
static unsigned int op_pow::internal_pow (const unsigned int base, const T2 exponent)
template<typename T1 >
static void op_pow::apply (Mat< typename T1::pod_type > &out, const Op< T1, op_pow > &in)
template<typename T1 >
static void op_pow::apply (Cube< typename T1::pod_type > &out, const OpCube< T1, op_pow > &in)
template<typename T1 >
static void op_pow::apply (Mat< std::complex< typename T1::pod_type > > &out, const Op< T1, op_pow > &in)
template<typename T1 >
static void op_pow::apply (Cube< std::complex< typename T1::pod_type > > &out, const OpCube< T1, op_pow > &in)
template<typename T1 >
static T1 op_pow_s32::internal_pow (const T1 base, const int exponent)
static char op_pow_s32::internal_pow (const char base, const int exponent)
static unsigned char op_pow_s32::internal_pow (const unsigned char base, const int exponent)
static int op_pow_s32::internal_pow (const int base, const int exponent)
static unsigned int op_pow_s32::internal_pow (const unsigned int base, const int exponent)
template<typename T1 >
static void op_pow_s32::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_pow_s32 > &in)
template<typename T1 >
static void op_pow_s32::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_pow_s32 > &in)
template<typename T1 >
static void op_conj::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_conj > &in)
template<typename T1 >
static void op_conj::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_conj > &in)
Function Documentation
template<typename T1 > void op_log::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_log > & in) [inline, static, inherited]
Definition at line 24 of file op_misc_meat.hpp.
References log(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::log(A_mem[i]);
    }
  }
template<typename T1 > void op_log::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_log > & in) [inline, static, inherited]
Definition at line 48 of file op_misc_meat.hpp.
References log(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::log(A_mem[i]);
    }
  }
template<typename T1 > void op_trunc_log::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_trunc_log > & in) [inline, static, inherited]
Definition at line 72 of file op_misc_meat.hpp.
References Op< T1, op_type >::m, Mat< eT >::memptr(), Mat< eT >::n_elem, and trunc_log().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = trunc_log(A_mem[i]);
    }
  }
template<typename T1 > void op_trunc_log::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_trunc_log > & in) [inline, static, inherited]
Definition at line 96 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::m, Cube< eT >::memptr(), Cube< eT >::n_elem, and trunc_log().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = trunc_log(A_mem[i]);
    }
  }
template<typename T1 > void op_log10::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_log10 > & in) [inline, static, inherited]
Definition at line 120 of file op_misc_meat.hpp.
References log10(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::log10(A_mem[i]);
    }
  }
template<typename T1 > void op_log10::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_log10 > & in) [inline, static, inherited]
Definition at line 144 of file op_misc_meat.hpp.
References log10(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::log10(A_mem[i]);
    }
  }
template<typename T1 > void op_exp::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_exp > & in) [inline, static, inherited]
Definition at line 168 of file op_misc_meat.hpp.
References exp(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::exp(A_mem[i]);
    }
  }
template<typename T1 > void op_exp::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_exp > & in) [inline, static, inherited]
Definition at line 192 of file op_misc_meat.hpp.
References exp(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::exp(A_mem[i]);
    }
  }
template<typename T1 > void op_trunc_exp::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_trunc_exp > & in) [inline, static, inherited]
Definition at line 216 of file op_misc_meat.hpp.
References Op< T1, op_type >::m, Mat< eT >::memptr(), Mat< eT >::n_elem, and trunc_exp().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = trunc_exp(A_mem[i]);
    }
  }
template<typename T1 > void op_trunc_exp::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_trunc_exp > & in) [inline, static, inherited]
Definition at line 240 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::m, Cube< eT >::memptr(), Cube< eT >::n_elem, and trunc_exp().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = trunc_exp(A_mem[i]);
    }
  }
template<typename T1 > void op_sqrt::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_sqrt > & in) [inline, static, inherited]
Definition at line 264 of file op_misc_meat.hpp.
References Op< T1, op_type >::m, Mat< eT >::memptr(), Mat< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::sqrt(A_mem[i]);
    }
  }
template<typename T1 > void op_sqrt::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_sqrt > & in) [inline, static, inherited]
Definition at line 288 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::m, Cube< eT >::memptr(), Cube< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::sqrt(A_mem[i]);
    }
  }
template<typename T1 > void op_square::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_square > & in) [inline, static, inherited]
Definition at line 312 of file op_misc_meat.hpp.
References Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    const eT val = A_mem[i];
    out_mem[i] = val*val;
    }
  }
template<typename T1 > void op_square::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_square > & in) [inline, static, inherited]
Definition at line 337 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    const eT val = A_mem[i];
    out_mem[i] = val*val;
    }
  }
template<typename T1 , typename T2 > T1 op_pow::internal_pow (const T1 base, const T2 exponent) [inline, static, inherited]
Definition at line 362 of file op_misc_meat.hpp.
References pow().
Referenced by op_pow::apply().
  {
  return std::pow(base, exponent);
  }
template<typename T2 > char op_pow::internal_pow (const char base, const T2 exponent) [inline, static, inherited]
Definition at line 372 of file op_misc_meat.hpp.
References pow().
  {
  typedef char out_type;
  return out_type( std::pow(double(base), exponent) );
  }
template<typename T2 > unsigned char op_pow::internal_pow (const unsigned char base, const T2 exponent) [inline, static, inherited]
Definition at line 383 of file op_misc_meat.hpp.
References pow().
  {
  typedef unsigned char out_type;
  return out_type( std::pow(double(base), exponent) );
  }
template<typename T2 > int op_pow::internal_pow (const int base, const T2 exponent) [inline, static, inherited]
Definition at line 394 of file op_misc_meat.hpp.
References pow().
  {
  typedef int out_type;
  return out_type( std::pow(double(base), exponent) );
  }
template<typename T2 > unsigned int op_pow::internal_pow (const unsigned int base, const T2 exponent) [inline, static, inherited]
Definition at line 405 of file op_misc_meat.hpp.
References pow().
  {
  typedef unsigned int out_type;
  return out_type( std::pow(double(base), exponent) );
  }
template<typename T1 > void op_pow::apply (Mat< typename T1::pod_type > & out, const Op< T1, op_pow > & in) [inline, static, inherited]
Definition at line 416 of file op_misc_meat.hpp.
References Op< T1, op_type >::aux, op_pow::internal_pow(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    //out_mem[i] = std::pow(A_mem[i], in.aux);
    out_mem[i] = op_pow::internal_pow(A_mem[i], in.aux);
    }
  }
template<typename T1 > void op_pow::apply (Cube< typename T1::pod_type > & out, const OpCube< T1, op_pow > & in) [inline, static, inherited]
Definition at line 442 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::aux, op_pow::internal_pow(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    //out_mem[i] = std::pow(A_mem[i], in.aux);
    out_mem[i] = op_pow::internal_pow(A_mem[i], in.aux);
    }
  }
template<typename T1 > void op_pow::apply (Mat< std::complex< typename T1::pod_type > > & out, const Op< T1, op_pow > & in) [inline, static, inherited]
Definition at line 468 of file op_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::n_elem, and pow().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type  T;
  typedef std::complex<T>       eT;
  isnt_same_type<eT, typename T1::elem_type>::check();
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  if(in.aux.imag() == T(0))
    {
    const T in_aux_real = in.aux.real();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = std::pow(A.mem[i], in_aux_real);
      }
    }
  else
    {
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = std::pow(A.mem[i], in.aux);
      }
    }
  }
template<typename T1 > void op_pow::apply (Cube< std::complex< typename T1::pod_type > > & out, const OpCube< T1, op_pow > & in) [inline, static, inherited]
Definition at line 511 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::n_elem, and pow().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type  T;
  typedef std::complex<T>       eT;
  isnt_same_type<eT, typename T1::elem_type>::check();
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  if(in.aux.imag() == T(0))
    {
    const T in_aux_real = in.aux.real();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = std::pow(A.mem[i], in_aux_real);
      }
    }
  else
    {
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = std::pow(A.mem[i], in.aux);
      }
    }
  }
template<typename T1 > T1 op_pow_s32::internal_pow (const T1 base, const int exponent) [inline, static, inherited]
Definition at line 554 of file op_misc_meat.hpp.
References pow().
Referenced by op_pow_s32::apply().
  {
  return std::pow(base, exponent);
  }
char op_pow_s32::internal_pow (const char base, const int exponent) [inline, static, inherited]
Definition at line 563 of file op_misc_meat.hpp.
References pow().
  {
  typedef char out_type;
  return out_type( std::pow(double(base), exponent) );
  }
unsigned char op_pow_s32::internal_pow (const unsigned char base, const int exponent) [inline, static, inherited]
Definition at line 573 of file op_misc_meat.hpp.
References pow().
  {
  typedef unsigned char out_type;
  return out_type( std::pow(double(base), exponent) );
  }
int op_pow_s32::internal_pow (const int base, const int exponent) [inline, static, inherited]
Definition at line 583 of file op_misc_meat.hpp.
References pow().
  {
  typedef int out_type;
  return out_type( std::pow(double(base), exponent) );
  }
unsigned int op_pow_s32::internal_pow (const unsigned int base, const int exponent) [inline, static, inherited]
Definition at line 593 of file op_misc_meat.hpp.
References pow().
  {
  typedef unsigned int out_type;
  return out_type( std::pow(double(base), exponent) );
  }
template<typename T1 > void op_pow_s32::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_pow_s32 > & in) [inline, static, inherited]
Definition at line 604 of file op_misc_meat.hpp.
References Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, op_pow_s32::internal_pow(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const int exponent = (in.aux_u32_b == 0) ? in.aux_u32_a : -in.aux_u32_a;
  for(u32 i=0; i<n_elem; ++i)
    {
    //out_mem[i] = std::pow(A_mem[i], exponent);  // causes problems with gcc 4.1/4.2 for base that has an integer type
    out_mem[i] = op_pow_s32::internal_pow(A_mem[i], exponent);
    }
  }
template<typename T1 > void op_pow_s32::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_pow_s32 > & in) [inline, static, inherited]
Definition at line 632 of file op_misc_meat.hpp.
References OpCube< T1, op_type >::aux_u32_a, OpCube< T1, op_type >::aux_u32_b, op_pow_s32::internal_pow(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const int exponent = (in.aux_u32_b == 0) ? in.aux_u32_a : -in.aux_u32_a;
  for(u32 i=0; i<n_elem; ++i)
    {
    //out_mem[i] = std::pow(A_mem[i], exponent);  // causes problems with gcc 4.1/4.2 for base that has an integer type
    out_mem[i] = op_pow_s32::internal_pow(A_mem[i], exponent);
    }
  }
template<typename T1 > void op_conj::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_conj > & in) [inline, static, inherited]
Definition at line 660 of file op_misc_meat.hpp.
References conj(), Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::conj(A_mem[i]);
    }
  }
template<typename T1 > void op_conj::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_conj > & in) [inline, static, inherited]
Definition at line 684 of file op_misc_meat.hpp.
References conj(), OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = std::conj(A_mem[i]);
    }
  }