Armadillo Technical: Mat
Mat
Classes
class Mat< eT >
Dense matrix class.
class Mat_aux
Functions
Mat::~Mat ()
Mat::Mat ()
Mat::Mat (const u32 in_rows, const u32 in_cols)
construct the matrix to have user specified dimensions
void Mat::init (const u32 in_rows, const u32 in_cols)
internal matrix construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
Mat::Mat (const char *text)
create the matrix from a textual description
const Mat & Mat::operator= (const char *text)
create the matrix from a textual description
Mat::Mat (const std::string &text)
create the matrix from a textual description
const Mat & Mat::operator= (const std::string &text)
create the matrix from a textual description
void Mat::init (const std::string &text)
internal function to create the matrix from a textual description
arma_inline const Mat & Mat::operator= (const eT val)
Set the matrix to be equal to the specified scalar. NOTE: the size of the matrix will be 1x1.
arma_inline const Mat & Mat::operator+= (const eT val)
In-place addition of a scalar to all elements of the matrix.
arma_inline const Mat & Mat::operator-= (const eT val)
In-place subtraction of a scalar from all elements of the matrix.
arma_inline const Mat & Mat::operator*= (const eT val)
In-place multiplication of all elements of the matrix with a scalar.
arma_inline const Mat & Mat::operator/= (const eT val)
In-place division of all elements of the matrix with a scalar.
Mat::Mat (const Mat &m)
construct a matrix from a given matrix
const Mat & Mat::operator= (const Mat &m)
construct a matrix from a given matrix
void Mat::init (const Mat &x)
construct a matrix from a given matrix
Mat::Mat (eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem=true)
construct a matrix from a given auxiliary array of eTs. if copy_aux_mem is true, new memory is allocated and the array is copied. if copy_aux_mem is false, the auxiliary array is used directly (without allocating memory and copying). the default is to copy the array.
Mat::Mat (const eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols)
construct a matrix from a given auxiliary read-only array of eTs. the array is copied.
Mat::Mat (const char junk, const eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols)
DANGEROUS! Construct a temporary matrix, using auxiliary memory. This constructor is NOT intended for usage by user code. Its sole purpose is to be used by the Cube class.
const Mat & Mat::operator+= (const Mat &m)
in-place matrix addition
const Mat & Mat::operator-= (const Mat &m)
in-place matrix subtraction
const Mat & Mat::operator*= (const Mat &m)
in-place matrix multiplication
const Mat & Mat::operator%= (const Mat &m)
in-place element-wise matrix multiplication
const Mat & Mat::operator/= (const Mat &m)
in-place element-wise matrix division
template<typename T1 , typename T2 >
Mat::Mat (const Base< pod_type, T1 > &A, const Base< pod_type, T2 > &B)
for constructing a complex matrix out of two non-complex matrices
Mat::Mat (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const Mat & Mat::operator= (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const Mat & Mat::operator+= (const subview< eT > &X)
in-place matrix addition (using a submatrix on the right-hand-side)
const Mat & Mat::operator-= (const subview< eT > &X)
in-place matrix subtraction (using a submatrix on the right-hand-side)
const Mat & Mat::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
const Mat & Mat::operator%= (const subview< eT > &X)
in-place element-wise matrix mutiplication (using a submatrix on the right-hand-side)
const Mat & Mat::operator/= (const subview< eT > &X)
in-place element-wise matrix division (using a submatrix on the right-hand-side)
Mat::Mat (const subview_cube< eT > &X)
construct a matrix from a subview_cube instance
const Mat & Mat::operator= (const subview_cube< eT > &X)
construct a matrix from a subview_cube instance
const Mat & Mat::operator+= (const subview_cube< eT > &X)
in-place matrix addition (using a single-slice subcube on the right-hand-side)
const Mat & Mat::operator-= (const subview_cube< eT > &X)
in-place matrix subtraction (using a single-slice subcube on the right-hand-side)
const Mat & Mat::operator*= (const subview_cube< eT > &X)
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
const Mat & Mat::operator%= (const subview_cube< eT > &X)
in-place element-wise matrix mutiplication (using a single-slice subcube on the right-hand-side)
const Mat & Mat::operator/= (const subview_cube< eT > &X)
in-place element-wise matrix division (using a single-slice subcube on the right-hand-side)
Mat::Mat (const diagview< eT > &X)
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
const Mat & Mat::operator= (const diagview< eT > &X)
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
arma_inline subview_row< eT > Mat::row (const u32 row_num)
creation of subview (row vector)
arma_inline const subview_row< eT > Mat::row (const u32 row_num) const
creation of subview (row vector)
arma_inline subview_col< eT > Mat::col (const u32 col_num)
creation of subview (column vector)
arma_inline const subview_col< eT > Mat::col (const u32 col_num) const
creation of subview (column vector)
arma_inline subview< eT > Mat::rows (const u32 in_row1, const u32 in_row2)
creation of subview (submatrix comprised of specified row vectors)
arma_inline const subview< eT > Mat::rows (const u32 in_row1, const u32 in_row2) const
creation of subview (submatrix comprised of specified row vectors)
arma_inline subview< eT > Mat::cols (const u32 in_col1, const u32 in_col2)
creation of subview (submatrix comprised of specified column vectors)
arma_inline const subview< eT > Mat::cols (const u32 in_col1, const u32 in_col2) const
creation of subview (submatrix comprised of specified column vectors)
arma_inline subview< eT > Mat::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2)
creation of subview (submatrix)
arma_inline const subview< eT > Mat::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const
creation of subview (generic submatrix)
arma_inline diagview< eT > Mat::diag (const s32 in_id=0)
creation of diagview (diagonal)
arma_inline const diagview< eT > Mat::diag (const s32 in_id=0) const
creation of diagview (diagonal)
void Mat::swap_rows (const u32 in_row1, const u32 in_row2)
void Mat::swap_cols (const u32 in_col1, const u32 in_col2)
template<typename T1 , typename op_type >
Mat::Mat (const Op< T1, op_type > &X)
create a matrix from Op, i.e. run the previously delayed unary operations
template<typename T1 , typename op_type >
const Mat & Mat::operator= (const Op< T1, op_type > &X)
create a matrix from Op, i.e. run the previously delayed unary operations
template<typename T1 , typename op_type >
const Mat & Mat::operator+= (const Op< T1, op_type > &X)
in-place matrix addition, with the right-hand-side operand having delayed operations
template<typename T1 , typename op_type >
const Mat & Mat::operator-= (const Op< T1, op_type > &X)
in-place matrix subtraction, with the right-hand-side operand having delayed operations
template<typename T1 , typename op_type >
const Mat & Mat::operator*= (const Op< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1 , typename op_type >
const Mat & Mat::operator%= (const Op< T1, op_type > &X)
in-place matrix element-wise multiplication, with the right-hand-side operand having delayed operations
template<typename T1 , typename op_type >
const Mat & Mat::operator/= (const Op< T1, op_type > &X)
in-place matrix element-wise division, with the right-hand-side operand having delayed operations
template<typename T1 , typename T2 , typename glue_type >
Mat::Mat (const Glue< T1, T2, glue_type > &X)
create a matrix from Glue, i.e. run the previously delayed binary operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator= (const Glue< T1, T2, glue_type > &X)
create a matrix from Glue, i.e. run the previously delayed binary operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator+= (const Glue< T1, T2, glue_type > &X)
in-place matrix addition, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator-= (const Glue< T1, T2, glue_type > &X)
in-place matrix subtraction, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator*= (const Glue< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator%= (const Glue< T1, T2, glue_type > &X)
in-place matrix element-wise multiplication, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename glue_type >
const Mat & Mat::operator/= (const Glue< T1, T2, glue_type > &X)
in-place matrix element-wise division, with the right-hand-side operands having delayed operations
arma_inline eT & Mat::operator() (const u32 i)
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
arma_inline eT Mat::operator() (const u32 i) const
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
arma_inline eT & Mat::operator[] (const u32 i)
linear element accessor (treats the matrix as a vector); no bounds check.
arma_inline eT Mat::operator[] (const u32 i) const
linear element accessor (treats the matrix as a vector); no bounds check
arma_inline eT & Mat::operator() (const u32 in_row, const u32 in_col)
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
arma_inline eT Mat::operator() (const u32 in_row, const u32 in_col) const
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
arma_inline eT & Mat::at (const u32 in_row, const u32 in_col)
element accessor; no bounds check
arma_inline eT Mat::at (const u32 in_row, const u32 in_col) const
element accessor; no bounds check
arma_inline const Mat & Mat::operator++ ()
prefix ++
arma_inline void Mat::operator++ (int)
postfix ++ (must not return the object by reference)
arma_inline const Mat & Mat::operator-- ()
prefix --
arma_inline void Mat::operator-- (int)
postfix -- (must not return the object by reference)
arma_inline bool Mat::is_vec () const
returns true if the object can be interpreted as a column or row vector
arma_inline bool Mat::is_square () const
returns true if the object has the same number of non-zero rows and columnns
arma_inline bool Mat::is_finite () const
returns true if all of the elements are finite
arma_inline eT * Mat::colptr (const u32 in_col)
returns a pointer to array of eTs for a specified column; no bounds check
arma_inline const eT * Mat::colptr (const u32 in_col) const
returns a pointer to array of eTs for a specified column; no bounds check
arma_inline eT * Mat::memptr ()
returns a pointer to array of eTs used by the matrix
arma_inline const eT * Mat::memptr () const
returns a pointer to array of eTs used by the matrix
void Mat::print (const std::string extra_text="") const
print contents of the matrix (to the cout stream), optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
void Mat::print (std::ostream &user_stream, const std::string extra_text="") const
print contents of the matrix to a user specified stream, optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
void Mat::print_trans (const std::string extra_text="") const
print contents of the transposed version of the matrix (to the cout stream), optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
void Mat::print_trans (std::ostream &user_stream, const std::string extra_text="") const
print contents of the transposed version of matrix to a user specified stream, optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
void Mat::raw_print (const std::string extra_text="") const
print contents of the matrix (to the cout stream), optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified (i.e. the precision and cell width are not modified).
void Mat::raw_print (std::ostream &user_stream, const std::string extra_text="") const
print contents of the matrix to a user specified stream, optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified. (i.e. the precision and cell width are not modified).
void Mat::raw_print_trans (const std::string extra_text="") const
print contents of the transposed version of the matrix (to the cout stream), optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified (i.e. the precision and cell width are not modified).
void Mat::raw_print_trans (std::ostream &user_stream, const std::string extra_text="") const
print contents of the transposed version of the matrix to a user specified stream, optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified. (i.e. the precision and cell width are not modified).
void Mat::set_size (const u32 in_rows, const u32 in_cols)
change the matrix to have user specified dimensions (data is not preserved)
template<typename eT2 >
void Mat::copy_size (const Mat< eT2 > &m)
change the matrix (without preserving data) to have the same dimensions as the given matrix
void Mat::fill (const eT val)
fill the matrix with the specified value
void Mat::zeros ()
void Mat::zeros (const u32 in_rows, const u32 in_cols)
void Mat::ones ()
void Mat::ones (const u32 in_rows, const u32 in_cols)
void Mat::reset ()
void Mat::save (const std::string name, const file_type type=arma_binary) const
save the matrix to a file
void Mat::load (const std::string name, const file_type type=auto_detect)
load a matrix from a file
template<typename eT >
static arma_inline void Mat_aux::prefix_pp (Mat< eT > &x)
prefix ++
template<typename T >
static arma_inline void Mat_aux::prefix_pp (Mat< std::complex< T > > &x)
prefix ++ for complex numbers (work around for limitations of the std::complex class)
template<typename eT >
static arma_inline void Mat_aux::postfix_pp (Mat< eT > &x)
postfix ++
template<typename T >
static arma_inline void Mat_aux::postfix_pp (Mat< std::complex< T > > &x)
postfix ++ for complex numbers (work around for limitations of the std::complex class)
template<typename eT >
static arma_inline void Mat_aux::prefix_mm (Mat< eT > &x)
prefix --
template<typename T >
static arma_inline void Mat_aux::prefix_mm (Mat< std::complex< T > > &x)
prefix -- for complex numbers (work around for limitations of the std::complex class)
template<typename eT >
static arma_inline void Mat_aux::postfix_mm (Mat< eT > &x)
postfix --
template<typename T >
static arma_inline void Mat_aux::postfix_mm (Mat< std::complex< T > > &x)
postfix ++ for complex numbers (work around for limitations of the std::complex class)
Function Documentation
template<typename eT > Mat< eT >::~Mat () [inline, inherited]
Definition at line 22 of file Mat_meat.hpp.
References arma_config::debug, Mat< eT >::mem, Mat< eT >::mem_local, Mat< eT >::n_cols, Mat< eT >::n_elem, Mat< eT >::n_rows, access::rw(), and Mat< eT >::use_aux_mem.
  {
  arma_extra_debug_sigprint_this(this);
  if(use_aux_mem == false)
    {
    if(n_elem > sizeof(mem_local)/sizeof(eT) )
      {
      delete [] mem;
      }
    }
  if(arma_config::debug == true)
    {
    // try to expose buggy user code that accesses deleted objects
    access::rw(n_rows) = 0;
    access::rw(n_cols) = 0;
    access::rw(n_elem) = 0;
    access::rw(mem)    = 0;
    }
  isnt_supported_elem_type<eT>::check();
  }
template<typename eT > Mat< eT >::Mat () [inline, inherited]
Definition at line 50 of file Mat_meat.hpp.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  }
template<typename eT > Mat< eT >::Mat (const u32 in_rows, const u32 in_cols) [inline, inherited]
construct the matrix to have user specified dimensions
Definition at line 65 of file Mat_meat.hpp.
References Mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(in_n_rows, in_n_cols);
  }
template<typename eT > void Mat< eT >::init (const u32 in_rows, const u32 in_cols) [inline, protected, inherited]
internal matrix construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
Definition at line 84 of file Mat_meat.hpp.
References arma_check(), Mat< eT >::mem, Mat< eT >::mem_local, Mat< eT >::n_cols, Mat< eT >::n_elem, Mat< eT >::n_rows, access::rw(), and Mat< eT >::use_aux_mem.
Referenced by Mat< eT >::copy_size(), Mat< eT >::init(), Mat< eT >::Mat(), Mat< eT >::operator=(), Mat< eT >::reset(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint( arma_boost::format("in_n_rows = %d, in_n_cols = %d") % in_n_rows % in_n_cols );
  const u32 new_n_elem = in_n_rows * in_n_cols;
  if(n_elem == new_n_elem)
    {
    access::rw(n_rows) = in_n_rows;
    access::rw(n_cols) = in_n_cols;
    }
  else
    {
    arma_debug_check
      (
      (use_aux_mem == true),
      "Mat::init(): can't change the amount of memory as auxiliary memory is in use"
      );
    if(n_elem > sizeof(mem_local)/sizeof(eT) )
      {
      delete [] mem;
      }
    if(new_n_elem <= sizeof(mem_local)/sizeof(eT) )
      {
      access::rw(mem) = mem_local;
      }
    else
      {
      access::rw(mem) = new(std::nothrow) eT[new_n_elem];
      arma_check( (mem == 0), "Mat::init(): out of memory" );
      }
    access::rw(n_elem) = new_n_elem;
    if(new_n_elem == 0)
      {
      access::rw(n_rows) = 0;
      access::rw(n_cols) = 0;
      }
    else
      {
      access::rw(n_rows) = in_n_rows;
      access::rw(n_cols) = in_n_cols;
      }
    }
  }
template<typename eT > Mat< eT >::Mat (const char * text) [inline, inherited]
create the matrix from a textual description
Definition at line 138 of file Mat_meat.hpp.
References Mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init( std::string(text) );
  }
template<typename eT > const Mat< eT > & Mat< eT >::operator= (const char * text) [inline, inherited]
create the matrix from a textual description
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 157 of file Mat_meat.hpp.
References Mat< eT >::init().
Referenced by Mat< eT >::Mat().
  {
  arma_extra_debug_sigprint();
  init( std::string(text) );
  return *this;
  }
template<typename eT > Mat< eT >::Mat (const std::string & text) [inline, inherited]
create the matrix from a textual description
Definition at line 170 of file Mat_meat.hpp.
References Mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(text);
  }
template<typename eT > const Mat< eT > & Mat< eT >::operator= (const std::string & text) [inline, inherited]
create the matrix from a textual description
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 189 of file Mat_meat.hpp.
References Mat< eT >::init().
  {
  arma_extra_debug_sigprint();
  init(text);
  return *this;
  }
template<typename eT > void Mat< eT >::init (const std::string & text) [inline, protected, inherited]
internal function to create the matrix from a textual description
Definition at line 203 of file Mat_meat.hpp.
References arma_check(), Mat< eT >::at(), Mat< eT >::col(), Mat< eT >::row(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  //
  // work out the size
  u32 t_n_rows = 0;
  u32 t_n_cols = 0;
  bool t_n_cols_found = false;
  std::string token;
  std::string::size_type line_start = 0;
  std::string::size_type   line_end = 0;
  while( line_start < text.length() )
    {
    line_end = text.find(';', line_start);
    if(line_end == std::string::npos)
      line_end = text.length()-1;
    std::string::size_type line_len = line_end - line_start + 1;
    std::stringstream line_stream( text.substr(line_start,line_len) );
    u32 line_n_cols = 0;
    while(line_stream >> token)
      {
      ++line_n_cols;
      }
    if(line_n_cols > 0)
      {
      if(t_n_cols_found == false)
        {
        t_n_cols = line_n_cols;
        t_n_cols_found = true;
        }
      else
        arma_check( (line_n_cols != t_n_cols), "Mat::init(): inconsistent number of columns in given string");
      ++t_n_rows;
      }
    line_start = line_end+1;
    }
  Mat<eT>& x = *this;
  x.set_size(t_n_rows, t_n_cols);
  line_start = 0;
  line_end = 0;
  u32 row = 0;
  while( line_start < text.length() )
    {
    line_end = text.find(';', line_start);
    if(line_end == std::string::npos)
      line_end = text.length()-1;
    std::string::size_type line_len = line_end - line_start + 1;
    std::stringstream line_stream( text.substr(line_start,line_len) );
//     u32 col = 0;
//     while(line_stream >> token)
//       {
//       x.at(row,col) = strtod(token.c_str(), 0);
//       ++col;
//       }
    u32 col = 0;
    eT val;
    while(line_stream >> val)
      {
      x.at(row,col) = val;
      ++col;
      }
    ++row;
    line_start = line_end+1;
    }
  }
template<typename eT> arma_inline const Mat< eT > & Mat< eT >::operator= (const eT val) [inline, inherited]
Set the matrix to be equal to the specified scalar. NOTE: the size of the matrix will be 1x1.
Definition at line 302 of file Mat_meat.hpp.
References Mat< eT >::init(), Mat< eT >::mem, and access::rw().
  {
  arma_extra_debug_sigprint();
  init(1,1);
  access::rw(mem[0]) = val;
  return *this;
  }
template<typename eT> arma_inline const Mat< eT > & Mat< eT >::operator+= (const eT val) [inline, inherited]
In-place addition of a scalar to all elements of the matrix.
Definition at line 317 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) += val;
    }
  return *this;
  }
template<typename eT> arma_inline const Mat< eT > & Mat< eT >::operator-= (const eT val) [inline, inherited]
In-place subtraction of a scalar from all elements of the matrix.
Definition at line 335 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) -= val;
    }
  return *this;
  }
template<typename eT> arma_inline const Mat< eT > & Mat< eT >::operator*= (const eT val) [inline, inherited]
In-place multiplication of all elements of the matrix with a scalar.
Definition at line 353 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) *= val;
    }
  return *this;
  }
template<typename eT> arma_inline const Mat< eT > & Mat< eT >::operator/= (const eT val) [inline, inherited]
In-place division of all elements of the matrix with a scalar.
Definition at line 371 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) /= val;
    }
  return *this;
  }
template<typename eT> Mat< eT >::Mat (const Mat< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Definition at line 388 of file Mat_meat.hpp.
References Mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x   in_mat = %x") % this % &in_mat);
  init(in_mat);
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator= (const Mat< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 407 of file Mat_meat.hpp.
References Mat< eT >::init().
  {
  arma_extra_debug_sigprint();
  init(x);
  return *this;
  }
template<typename eT > void Mat< eT >::init (const Mat< eT > & x) [inline, protected, inherited]
construct a matrix from a given matrix
Definition at line 421 of file Mat_meat.hpp.
References syslib::copy_elem(), Mat< eT >::init(), Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_cols, Mat< eT >::n_elem, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  if(this != &x)
    {
    init(x.n_rows, x.n_cols);
    syslib::copy_elem( memptr(), x.mem, n_elem );
    }
  }
template<typename eT> Mat< eT >::Mat (eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem = true) [inline, inherited]
construct a matrix from a given auxiliary array of eTs. if copy_aux_mem is true, new memory is allocated and the array is copied. if copy_aux_mem is false, the auxiliary array is used directly (without allocating memory and copying). the default is to copy the array.
Definition at line 441 of file Mat_meat.hpp.
References syslib::copy_elem(), Mat< eT >::init(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  : n_rows     (copy_aux_mem ? 0     : aux_n_rows           )
  , n_cols     (copy_aux_mem ? 0     : aux_n_cols           )
  , n_elem     (copy_aux_mem ? 0     : aux_n_rows*aux_n_cols)
  , use_aux_mem(copy_aux_mem ? false : true                 )
  , mem        (copy_aux_mem ? mem   : aux_mem              )
  {
  arma_extra_debug_sigprint_this(this);
  if(copy_aux_mem == true)
    {
    init(aux_n_rows, aux_n_cols);
    syslib::copy_elem( memptr(), aux_mem, n_elem );
    }
  }
template<typename eT> Mat< eT >::Mat (const eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols) [inline, inherited]
construct a matrix from a given auxiliary read-only array of eTs. the array is copied.
Definition at line 463 of file Mat_meat.hpp.
References syslib::copy_elem(), Mat< eT >::init(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(aux_n_rows, aux_n_cols);
  syslib::copy_elem( memptr(), aux_mem, n_elem );
  }
template<typename eT> Mat< eT >::Mat (const char junk, const eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols) [inline, protected, inherited]
DANGEROUS! Construct a temporary matrix, using auxiliary memory. This constructor is NOT intended for usage by user code. Its sole purpose is to be used by the Cube class.
Definition at line 485 of file Mat_meat.hpp.
  : n_rows     (aux_n_rows           )
  , n_cols     (aux_n_cols           )
  , n_elem     (aux_n_rows*aux_n_cols)
  , use_aux_mem(true                 )
  , mem        (aux_mem              )
  {
  arma_extra_debug_sigprint_this(this);
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator+= (const Mat< eT > & m) [inline, inherited]
in-place matrix addition
Definition at line 501 of file Mat_meat.hpp.
References glue_plus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_plus::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator-= (const Mat< eT > & m) [inline, inherited]
in-place matrix subtraction
Definition at line 515 of file Mat_meat.hpp.
References glue_minus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_minus::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator*= (const Mat< eT > & m) [inline, inherited]
in-place matrix multiplication
Reimplemented in Row< eT >.
Definition at line 529 of file Mat_meat.hpp.
References glue_times::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_times::apply_inplace(*this, m);
  return *this;
  }
template<typename eT > const Mat< eT > & Mat< eT >::operator%= (const Mat< eT > & m) [inline, inherited]
in-place element-wise matrix multiplication
Definition at line 543 of file Mat_meat.hpp.
References glue_schur::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_schur::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator/= (const Mat< eT > & m) [inline, inherited]
in-place element-wise matrix division
Definition at line 557 of file Mat_meat.hpp.
References glue_div::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_div::apply_inplace(*this, m);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 > Mat< eT >::Mat (const Base< pod_type, T1 > & A, const Base< pod_type, T2 > & B) [inline, explicit, inherited]
for constructing a complex matrix out of two non-complex matrices
< compile-time abort if eT isn't std::complex
< compile-time abort if T is std::complex
< compile-time abort if types are not compatible
Definition at line 572 of file Mat_meat.hpp.
References arma_assert_same_size(), Mat< eT >::mem, Mat< eT >::n_cols, and access::rw().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  arma_type_check< is_complex<eT>::value == false >::apply();   //!< compile-time abort if eT isn't std::complex
  typedef typename T1::elem_type T;
  arma_type_check< is_complex<T>::value == true >::apply();   //!< compile-time abort if T is std::complex
  isnt_same_type<std::complex<T>, eT>::check();   //!< compile-time abort if types are not compatible
  const unwrap<T1> tmp_A(A.get_ref());
  const unwrap<T2> tmp_B(B.get_ref());
  const Mat<T>& X = tmp_A.M;
  const Mat<T>& Y = tmp_B.M;
  arma_assert_same_size(X, Y, "Mat()");
  init(X.n_rows, Y.n_cols);
  const T* X_mem = X.mem;
  const T* Y_mem = Y.mem;
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) = std::complex<T>(X_mem[i], Y_mem[i]);
    }
  }
template<typename eT> Mat< eT >::Mat (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Definition at line 616 of file Mat_meat.hpp.
References Mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 635 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::extract(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator+= (const subview< eT > & X) [inline, inherited]
in-place matrix addition (using a submatrix on the right-hand-side)
Definition at line 648 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::plus_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator-= (const subview< eT > & X) [inline, inherited]
in-place matrix subtraction (using a submatrix on the right-hand-side)
Definition at line 661 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::minus_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 675 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::times_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator%= (const subview< eT > & X) [inline, inherited]
in-place element-wise matrix mutiplication (using a submatrix on the right-hand-side)
Definition at line 689 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::schur_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator/= (const subview< eT > & X) [inline, inherited]
in-place element-wise matrix division (using a submatrix on the right-hand-side)
Definition at line 703 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview<eT>::div_inplace(*this, X);
  return *this;
  }
template<typename eT> Mat< eT >::Mat (const subview_cube< eT > & X) [inline, inherited]
construct a matrix from a subview_cube instance
Definition at line 716 of file Mat_meat.hpp.
References Mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(x);
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator= (const subview_cube< eT > & X) [inline, inherited]
construct a matrix from a subview_cube instance
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 735 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview_cube<eT>::extract(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator+= (const subview_cube< eT > & X) [inline, inherited]
in-place matrix addition (using a single-slice subcube on the right-hand-side)
Definition at line 749 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview_cube<eT>::plus_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator-= (const subview_cube< eT > & X) [inline, inherited]
in-place matrix subtraction (using a single-slice subcube on the right-hand-side)
Definition at line 763 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview_cube<eT>::minus_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator*= (const subview_cube< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 777 of file Mat_meat.hpp.
References glue_times::apply_inplace().
  {
  arma_extra_debug_sigprint();
  const Mat<eT> tmp(X);
  glue_times::apply_inplace(*this, tmp);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator%= (const subview_cube< eT > & X) [inline, inherited]
in-place element-wise matrix mutiplication (using a single-slice subcube on the right-hand-side)
Definition at line 792 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview_cube<eT>::schur_inplace(*this, X);
  return *this;
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator/= (const subview_cube< eT > & X) [inline, inherited]
in-place element-wise matrix division (using a single-slice subcube on the right-hand-side)
Definition at line 806 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  subview_cube<eT>::div_inplace(*this, X);
  return *this;
  }
template<typename eT> Mat< eT >::Mat (const diagview< eT > & X) [inline, inherited]
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
Definition at line 819 of file Mat_meat.hpp.
References Mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT> const Mat< eT > & Mat< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 838 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  diagview<eT>::extract(*this, X);
  return *this;
  }
template<typename eT > arma_inline subview_row< eT > Mat< eT >::row (const u32 row_num) [inline, inherited]
creation of subview (row vector)
Reimplemented in Col< eT >.
Definition at line 852 of file Mat_meat.hpp.
References Mat< eT >::n_rows.
Referenced by op_shuffle::apply(), Mat< eT >::init(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), diskio::load_std_string(), diskio::save_arma_ascii(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), diskio::save_std_string(), and Mat< eT >::swap_cols().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( row_num >= n_rows, "Mat::row(): row out of bounds" );
  return subview_row<eT>(*this, row_num);
  }
template<typename eT > arma_inline const subview_row< eT > Mat< eT >::row (const u32 row_num) const [inline, inherited]
creation of subview (row vector)
Reimplemented in Col< eT >.
Definition at line 867 of file Mat_meat.hpp.
References Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( row_num >= n_rows, "Mat::row(): row out of bounds" );
  return subview_row<eT>(*this, row_num);
  }
template<typename eT > arma_inline subview_col< eT > Mat< eT >::col (const u32 col_num) [inline, inherited]
creation of subview (column vector)
Reimplemented in Row< eT >.
Definition at line 882 of file Mat_meat.hpp.
References Mat< eT >::n_cols.
Referenced by op_shuffle::apply(), Mat< eT >::init(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), diskio::load_std_string(), diskio::save_arma_ascii(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), diskio::save_std_string(), and Mat< eT >::swap_rows().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( col_num >= n_cols, "Mat::col(): out of bounds");
  return subview_col<eT>(*this, col_num);
  }
template<typename eT > arma_inline const subview_col< eT > Mat< eT >::col (const u32 col_num) const [inline, inherited]
creation of subview (column vector)
Reimplemented in Row< eT >.
Definition at line 897 of file Mat_meat.hpp.
References Mat< eT >::n_cols.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( col_num >= n_cols, "Mat::col(): out of bounds");
  return subview_col<eT>(*this, col_num);
  }
template<typename eT > arma_inline subview< eT > Mat< eT >::rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Reimplemented in Col< eT >.
Definition at line 912 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_row2 >= n_rows),
    "Mat::rows(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, 0, in_row2, ((n_cols>0) ? n_cols-1 : 0) );
  }
template<typename eT > arma_inline const subview< eT > Mat< eT >::rows (const u32 in_row1, const u32 in_row2) const [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Reimplemented in Col< eT >.
Definition at line 931 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_row2 >= n_rows),
    "Mat::rows(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, 0, in_row2, ((n_cols>0) ? n_cols-1 : 0) );
  }
template<typename eT > arma_inline subview< eT > Mat< eT >::cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Reimplemented in Row< eT >.
Definition at line 950 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
Referenced by op_pinv::direct_pinv().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 > in_col2) || (in_col2 >= n_cols),
    "Mat::cols(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, 0, in_col1, ((n_rows>0) ? n_rows-1 : 0), in_col2);
  }
template<typename eT > arma_inline const subview< eT > Mat< eT >::cols (const u32 in_col1, const u32 in_col2) const [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Reimplemented in Row< eT >.
Definition at line 969 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 > in_col2) || (in_col2 >= n_cols),
    "Mat::cols(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, 0, in_col1, ((n_rows>0) ? n_rows-1 : 0), in_col2);
  }
template<typename eT > arma_inline subview< eT > Mat< eT >::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) [inline, inherited]
creation of subview (submatrix)
Definition at line 988 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
Referenced by op_repmat::apply(), and glue_kron::direct_kron().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_col1 >  in_col2) || (in_row2 >= n_rows) || (in_col2 >= n_cols),
    "Mat::submat(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename eT > arma_inline const subview< eT > Mat< eT >::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const [inline, inherited]
creation of subview (generic submatrix)
Definition at line 1007 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_col1 >  in_col2) || (in_row2 >= n_rows) || (in_col2 >= n_cols),
    "Mat::submat(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename eT > arma_inline diagview< eT > Mat< eT >::diag (const s32 in_id = 0) [inline, inherited]
creation of diagview (diagonal)
Definition at line 1026 of file Mat_meat.hpp.
References min(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  const u32 row_offset = (in_id < 0) ? -in_id : 0;
  const u32 col_offset = (in_id > 0) ?  in_id : 0;
  arma_debug_check
    (
    (row_offset >= n_rows) || (col_offset >= n_cols),
    "Mat::diag(): out of bounds"
    );
  const u32 len = (std::min)(n_rows - row_offset, n_cols - col_offset);
  return diagview<eT>(*this, row_offset, col_offset, len);
  }
template<typename eT > arma_inline const diagview< eT > Mat< eT >::diag (const s32 in_id = 0) const [inline, inherited]
creation of diagview (diagonal)
Definition at line 1050 of file Mat_meat.hpp.
References min(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  const u32 row_offset = (in_id < 0) ? -in_id : 0;
  const u32 col_offset = (in_id > 0) ?  in_id : 0;
  arma_debug_check
    (
    (row_offset >= n_rows) || (col_offset >= n_cols),
    "Mat::diag(): out of bounds"
    );
  const u32 len = (std::min)(n_rows - row_offset, n_cols - col_offset);
  return diagview<eT>(*this, row_offset, col_offset, len);
  }
template<typename eT > void Mat< eT >::swap_rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
Definition at line 1074 of file Mat_meat.hpp.
References Mat< eT >::col(), Mat< eT >::mem, Mat< eT >::n_cols, Mat< eT >::n_rows, and access::rw().
Referenced by op_shuffle::apply(), and auxlib::lu().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 >= n_rows) || (in_row2 >= n_rows),
    "Mat::swap_rows(): out of bounds"
    );
  for(u32 col=0; col<n_cols; ++col)
    {
    const u32 offset = col*n_rows;
    const u32 pos1   = in_row1 + offset;
    const u32 pos2   = in_row2 + offset;
    const eT tmp          = mem[pos1];
    access::rw(mem[pos1]) = mem[pos2];
    access::rw(mem[pos2]) = tmp;
    }
  }
template<typename eT > void Mat< eT >::swap_cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
Definition at line 1102 of file Mat_meat.hpp.
References Mat< eT >::colptr(), Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::row().
Referenced by op_shuffle::apply().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 >= n_cols) || (in_col2 >= n_cols),
    "Mat::swap_cols(): out of bounds"
    );
  eT* ptr1 = colptr(in_col1);
  eT* ptr2 = colptr(in_col2);
  for(u32 row=0; row<n_rows; ++row)
    {
    const eT tmp = ptr1[row];
    ptr1[row]    = ptr2[row];
    ptr2[row]    = tmp;
    }
  }
template<typename eT > template<typename T1 , typename op_type > Mat< eT >::Mat (const Op< T1, op_type > & X) [inline, inherited]
create a matrix from Op, i.e. run the previously delayed unary operations
Definition at line 1130 of file Mat_meat.hpp.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  isnt_same_type<eT, typename T1::elem_type>::check();
  op_type::apply(*this, X);
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator= (const Op< T1, op_type > & X) [inline, inherited]
create a matrix from Op, i.e. run the previously delayed unary operations
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1152 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  op_type::apply(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator+= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix addition, with the right-hand-side operand having delayed operations
Definition at line 1170 of file Mat_meat.hpp.
References glue_plus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_plus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator-= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix subtraction, with the right-hand-side operand having delayed operations
Definition at line 1188 of file Mat_meat.hpp.
References glue_minus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_minus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator*= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1206 of file Mat_meat.hpp.
References glue_times::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_times::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator%= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix element-wise multiplication, with the right-hand-side operand having delayed operations
Definition at line 1224 of file Mat_meat.hpp.
References glue_schur::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_schur::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Mat< eT > & Mat< eT >::operator/= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix element-wise division, with the right-hand-side operand having delayed operations
Definition at line 1241 of file Mat_meat.hpp.
References glue_div::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_div::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > Mat< eT >::Mat (const Glue< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from Glue, i.e. run the previously delayed binary operations
Definition at line 1257 of file Mat_meat.hpp.
References Mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , use_aux_mem(false)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from Glue, i.e. run the previously delayed binary operations
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1276 of file Mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  // TODO:
  // it may be simpler to pass the two objects (currently wrapped in X)
  // directly to the apply function.
  // (many adjustments throughout the source code will be required)
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_type::apply(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator+= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix addition, with the right-hand-side operands having delayed operations
Definition at line 1299 of file Mat_meat.hpp.
References glue_plus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_plus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator-= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix subtraction, with the right-hand-side operands having delayed operations
Definition at line 1318 of file Mat_meat.hpp.
References glue_minus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_minus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator*= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1337 of file Mat_meat.hpp.
References glue_times::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_times::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator%= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix element-wise multiplication, with the right-hand-side operands having delayed operations
Definition at line 1355 of file Mat_meat.hpp.
References glue_schur::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_schur::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Mat< eT > & Mat< eT >::operator/= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix element-wise division, with the right-hand-side operands having delayed operations
Definition at line 1373 of file Mat_meat.hpp.
References glue_div::apply_inplace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_div::apply_inplace(*this, X);
  return *this;
  }
template<typename eT > arma_inline eT & Mat< eT >::operator() (const u32 i) [inline, inherited]
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1390 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
  {
  arma_debug_check( (i >= n_elem), "Mat::operator(): index out of bounds");
  return access::rw(mem[i]);
  }
template<typename eT > arma_inline eT Mat< eT >::operator() (const u32 i) const [inline, inherited]
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1402 of file Mat_meat.hpp.
References Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_debug_check( (i >= n_elem), "Mat::operator(): index out of bounds");
  return mem[i];
  }
template<typename eT > arma_inline eT & Mat< eT >::operator[] (const u32 i) [inline, inherited]
linear element accessor (treats the matrix as a vector); no bounds check.
Definition at line 1413 of file Mat_meat.hpp.
References Mat< eT >::mem, and access::rw().
  {
  return access::rw(mem[i]);
  }
template<typename eT > arma_inline eT Mat< eT >::operator[] (const u32 i) const [inline, inherited]
linear element accessor (treats the matrix as a vector); no bounds check
Definition at line 1424 of file Mat_meat.hpp.
References Mat< eT >::mem.
  {
  return mem[i];
  }
template<typename eT > arma_inline eT & Mat< eT >::operator() (const u32 in_row, const u32 in_col) [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1435 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_cols, Mat< eT >::n_rows, and access::rw().
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "Mat::operator(): index out of bounds");
  return access::rw(mem[in_row + in_col*n_rows]);
  }
template<typename eT > arma_inline eT Mat< eT >::operator() (const u32 in_row, const u32 in_col) const [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1447 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "Mat::operator(): index out of bounds");
  return mem[in_row + in_col*n_rows];
  }
template<typename eT > arma_inline eT & Mat< eT >::at (const u32 in_row, const u32 in_col) [inline, inherited]
element accessor; no bounds check
Definition at line 1459 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_rows, and access::rw().
Referenced by accu(), op_var::apply(), op_trans::apply(), op_sum::apply(), op_stddev::apply(), op_sort::apply(), op_reshape::apply(), op_prod::apply(), op_ones_diag::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_inv::apply(), op_diagmat_vec::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_times::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_plus::apply(), glue_minus_diag::apply(), gemv_arma< do_trans_A, use_alpha, use_beta >::apply(), gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), op_inv::apply_diagvec(), glue_times::apply_inplace(), op_trans::apply_noalias(), det(), auxlib::det(), diagmat(), glue_times::direct_rowvec_diagmat_colvec(), glue_times::direct_rowvec_invdiagmat_colvec(), glue_times::direct_rowvec_mat_colvec(), eig_gen(), subview< eT >::extract(), diagview< eT >::extract(), diagview< eT >::fill(), Mat< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), auxlib::lu(), operator*(), operator/(), operator<<(), diagview< eT >::operator=(), arma_ostream::print(), prod(), auxlib::qr(), diskio::save_arma_ascii(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), trace(), and diagview< eT >::zeros().
  {
  return access::rw( mem[in_row + in_col*n_rows] );
  }
template<typename eT > arma_inline eT Mat< eT >::at (const u32 in_row, const u32 in_col) const [inline, inherited]
element accessor; no bounds check
Definition at line 1470 of file Mat_meat.hpp.
References Mat< eT >::mem, and Mat< eT >::n_rows.
  {
  return mem[in_row + in_col*n_rows];
  }
template<typename eT > arma_inline const Mat< eT > & Mat< eT >::operator++ () [inline, inherited]
prefix ++
Definition at line 1481 of file Mat_meat.hpp.
References Mat_aux::prefix_pp().
  {
  Mat_aux::prefix_pp(*this);
  return *this;
  }
template<typename eT > arma_inline void Mat< eT >::operator++ (int) [inline, inherited]
postfix ++ (must not return the object by reference)
Definition at line 1493 of file Mat_meat.hpp.
References Mat_aux::postfix_pp().
  {
  Mat_aux::postfix_pp(*this);
  }
template<typename eT > arma_inline const Mat< eT > & Mat< eT >::operator-- () [inline, inherited]
prefix --
Definition at line 1504 of file Mat_meat.hpp.
References Mat_aux::prefix_mm().
  {
  Mat_aux::prefix_mm(*this);
  return *this;
  }
template<typename eT > arma_inline void Mat< eT >::operator-- (int) [inline, inherited]
postfix -- (must not return the object by reference)
Definition at line 1516 of file Mat_meat.hpp.
References Mat_aux::postfix_mm().
  {
  Mat_aux::postfix_mm(*this);
  }
template<typename eT > arma_inline bool Mat< eT >::is_vec () const [inline, inherited]
returns true if the object can be interpreted as a column or row vector
Definition at line 1527 of file Mat_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
Referenced by accu(), op_shuffle::apply(), op_inv::apply_diagvec(), glue_plus::apply_inplace(), det(), op_cor::direct_cor(), glue_cor::direct_cor(), op_cov::direct_cov(), glue_cov::direct_cov(), operator<<(), trace(), and running_stat_vec_aux::update_stats().
  {
  return ( (n_rows == 1) || (n_cols == 1) );
  }
template<typename eT > arma_inline bool Mat< eT >::is_square () const [inline, inherited]
returns true if the object has the same number of non-zero rows and columnns
Definition at line 1538 of file Mat_meat.hpp.
References Mat< eT >::n_cols, Mat< eT >::n_elem, and Mat< eT >::n_rows.
Referenced by accu(), op_inv::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_minus_diag::apply(), det(), operator<<(), and trace().
  {
  return ( (n_rows == n_cols) && (n_elem > 0) );
  }
template<typename eT > arma_inline bool Mat< eT >::is_finite () const [inline, inherited]
returns true if all of the elements are finite
Definition at line 1549 of file Mat_meat.hpp.
References arma_isfinite(), Mat< eT >::mem, and Mat< eT >::n_elem.
Referenced by op_sort::apply().
  {
  for(u32 i=0; i<n_elem; ++i)
    {
    if(arma_isfinite(mem[i]) == false)
      {
      return false;
      }
    }
  return true;
  }
template<typename eT > arma_inline eT * Mat< eT >::colptr (const u32 in_col) [inline, inherited]
returns a pointer to array of eTs for a specified column; no bounds check
Definition at line 1568 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_rows, and access::rw().
Referenced by op_var::apply(), op_trans::apply(), op_sum::apply(), op_stddev::apply(), op_sort::apply(), op_prod::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_times::apply(), gemv_arma< do_trans_A, use_alpha, use_beta >::apply(), gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), glue_times::apply_inplace(), auxlib::chol(), auxlib::det(), glue_times::direct_rowvec_mat_colvec(), subview< eT >::div_inplace(), subview_cube< eT >::div_inplace(), subview< eT >::extract(), subview_cube< eT >::extract(), auxlib::inv_inplace(), auxlib::inv_noalias(), subview< eT >::minus_inplace(), subview_cube< eT >::minus_inplace(), glue_times_vec::mul_col_row(), glue_times_vec::mul_col_row_inplace_add(), subview< eT >::plus_inplace(), subview_cube< eT >::plus_inplace(), subview< eT >::schur_inplace(), subview_cube< eT >::schur_inplace(), auxlib::solve_od(), auxlib::solve_ud(), Mat< eT >::swap_cols(), and op_diagmat::zero_offdiag().
  {
  return & access::rw(mem[in_col*n_rows]);
  }
template<typename eT > arma_inline const eT * Mat< eT >::colptr (const u32 in_col) const [inline, inherited]
returns a pointer to array of eTs for a specified column; no bounds check
Definition at line 1579 of file Mat_meat.hpp.
References Mat< eT >::mem, and Mat< eT >::n_rows.
  {
  return & mem[in_col*n_rows];
  }
template<typename eT > arma_inline eT * Mat< eT >::memptr () [inline, inherited]
returns a pointer to array of eTs used by the matrix
Definition at line 1590 of file Mat_meat.hpp.
References Mat< eT >::mem.
Referenced by abs(), op_atanh::apply(), op_tanh::apply(), op_atan::apply(), op_tan::apply(), op_asinh::apply(), op_sinh::apply(), op_asin::apply(), op_sin::apply(), op_acosh::apply(), op_cosh::apply(), op_acos::apply(), op_cos::apply(), op_sort::apply(), op_scalar_div_post::apply(), op_scalar_div_pre::apply(), op_scalar_times::apply(), op_scalar_minus_post::apply(), op_scalar_minus_pre::apply(), op_scalar_plus::apply(), op_reshape::apply(), op_randn::apply(), op_rand::apply(), op_neg::apply(), op_conj::apply(), op_pow_s32::apply(), op_pow::apply(), op_square::apply(), op_sqrt::apply(), op_trunc_exp::apply(), op_exp::apply(), op_log10::apply(), op_trunc_log::apply(), op_log::apply(), glue_times_vec::apply(), glue_schur::apply(), glue_plus::apply(), glue_minus::apply(), glue_div::apply(), gemm< do_trans_A, do_trans_B, use_alpha, use_beta >::apply_blas_type(), glue_schur::apply_inplace(), glue_plus::apply_inplace(), glue_minus::apply_inplace(), glue_div::apply_inplace(), op_trans::apply_noalias(), subview_cube< eT >::check_overlap(), auxlib::chol(), auxlib::det(), glue_cor::direct_cor(), glue_cov::direct_cov(), op_eps::direct_eps(), subview< eT >::div_inplace(), auxlib::eig_gen(), auxlib::eig_sym(), subview< eT >::extract(), diagview< eT >::extract(), conv_to< Col< out_eT > >::from(), conv_to< Row< out_eT > >::from(), conv_to< Mat< out_eT > >::from(), imag(), Mat< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), diskio::load_arma_binary(), auxlib::lu(), Mat< eT >::Mat(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), subview< eT >::plus_inplace(), Mat_aux::postfix_mm(), Mat_aux::postfix_pp(), Mat_aux::prefix_mm(), Mat_aux::prefix_pp(), arma_ostream::print(), prod(), auxlib::qr(), rank(), real(), subview< eT >::schur_inplace(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), and running_stat_vec_aux::update_stats().
  {
  return const_cast<eT*>(mem);
  }
template<typename eT > arma_inline const eT * Mat< eT >::memptr () const [inline, inherited]
returns a pointer to array of eTs used by the matrix
Definition at line 1601 of file Mat_meat.hpp.
References Mat< eT >::mem.
  {
  return mem;
  }
template<typename eT > void Mat< eT >::print (const std::string extra_text = "") const [inline, inherited]
print contents of the matrix (to the cout stream), optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
Definition at line 1615 of file Mat_meat.hpp.
Referenced by Mat< eT >::print(), Mat< eT >::print_trans(), and Mat< eT >::raw_print().
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    const std::streamsize orig_width = cout.width();
    cout << extra_text << '\n';
    cout.width(orig_width);
    }
  arma_ostream::print(cout, *this, true);
  }
template<typename eT > void Mat< eT >::print (std::ostream & user_stream, const std::string extra_text = "") const [inline, inherited]
print contents of the matrix to a user specified stream, optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
Definition at line 1640 of file Mat_meat.hpp.
References Mat< eT >::print().
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    const std::streamsize orig_width = user_stream.width();
    user_stream << extra_text << '\n';
    user_stream.width(orig_width);
    }
  arma_ostream::print(user_stream, *this, true);
  }
template<typename eT > void Mat< eT >::print_trans (const std::string extra_text = "") const [inline, inherited]
print contents of the transposed version of the matrix (to the cout stream), optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
Definition at line 1665 of file Mat_meat.hpp.
References op_trans::apply_noalias(), and Mat< eT >::print().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp;
  op_trans::apply_noalias(tmp, *this);
  tmp.print(extra_text);
  }
template<typename eT > void Mat< eT >::print_trans (std::ostream & user_stream, const std::string extra_text = "") const [inline, inherited]
print contents of the transposed version of matrix to a user specified stream, optionally preceding with a user specified line of text. the precision and cell width are modified. on return, the stream's flags are restored to their original values.
Definition at line 1684 of file Mat_meat.hpp.
References op_trans::apply_noalias(), and Mat< eT >::print().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp;
  op_trans::apply_noalias(tmp, *this);
  tmp.print(user_stream, extra_text);
  }
template<typename eT > void Mat< eT >::raw_print (const std::string extra_text = "") const [inline, inherited]
print contents of the matrix (to the cout stream), optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified (i.e. the precision and cell width are not modified).
Definition at line 1703 of file Mat_meat.hpp.
References Mat< eT >::print().
Referenced by Mat< eT >::raw_print_trans().
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    const std::streamsize orig_width = cout.width();
    cout << extra_text << '\n';
    cout.width(orig_width);
    }
  arma_ostream::print(cout, *this, false);
  }
template<typename eT > void Mat< eT >::raw_print (std::ostream & user_stream, const std::string extra_text = "") const [inline, inherited]
print contents of the matrix to a user specified stream, optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified. (i.e. the precision and cell width are not modified).
Definition at line 1728 of file Mat_meat.hpp.
References Mat< eT >::print().
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    const std::streamsize orig_width = user_stream.width();
    user_stream << extra_text << '\n';
    user_stream.width(orig_width);
    }
  arma_ostream::print(user_stream, *this, false);
  }
template<typename eT > void Mat< eT >::raw_print_trans (const std::string extra_text = "") const [inline, inherited]
print contents of the transposed version of the matrix (to the cout stream), optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified (i.e. the precision and cell width are not modified).
Definition at line 1753 of file Mat_meat.hpp.
References op_trans::apply_noalias(), and Mat< eT >::raw_print().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp;
  op_trans::apply_noalias(tmp, *this);
  tmp.raw_print(extra_text);
  }
template<typename eT > void Mat< eT >::raw_print_trans (std::ostream & user_stream, const std::string extra_text = "") const [inline, inherited]
print contents of the transposed version of the matrix to a user specified stream, optionally preceding with a user specified line of text. the stream's flags are used as is and are not modified. (i.e. the precision and cell width are not modified).
Definition at line 1772 of file Mat_meat.hpp.
References op_trans::apply_noalias(), and Mat< eT >::raw_print().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp;
  op_trans::apply_noalias(tmp, *this);
  tmp.raw_print(user_stream, extra_text);
  }
template<typename eT > void Mat< eT >::set_size (const u32 in_rows, const u32 in_cols) [inline, inherited]
change the matrix to have user specified dimensions (data is not preserved)
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1788 of file Mat_meat.hpp.
References Mat< eT >::init().
Referenced by op_var::apply(), op_trans::apply(), op_sum::apply(), op_stddev::apply(), op_reshape::apply(), op_repmat::apply(), op_randn::apply(), op_rand::apply(), op_prod::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_diagmat::apply(), glue_times_vec::apply(), glue_times_diag::apply(), glue_times::apply(), glue_schur::apply(), glue_plus::apply(), glue_minus::apply(), glue_div::apply(), op_trans::apply_noalias(), glue_times::apply_noalias(), op_cor::direct_cor(), glue_cor::direct_cor(), glue_cov::direct_cov(), glue_kron::direct_kron(), eig_gen(), auxlib::eig_gen(), subview< eT >::extract(), subview_cube< eT >::extract(), diagview< eT >::extract(), Mat< eT >::init(), auxlib::inv_noalias(), linspace(), diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), auxlib::lu(), Mat< eT >::ones(), auxlib::qr(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  init(in_n_rows, in_n_cols);
  }
template<typename eT > template<typename eT2 > void Mat< eT >::copy_size (const Mat< eT2 > & m) [inline, inherited]
change the matrix (without preserving data) to have the same dimensions as the given matrix
Definition at line 1802 of file Mat_meat.hpp.
References Mat< eT >::init(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
Referenced by op_atanh::apply(), op_tanh::apply(), op_atan::apply(), op_tan::apply(), op_asinh::apply(), op_sinh::apply(), op_asin::apply(), op_sin::apply(), op_acosh::apply(), op_cosh::apply(), op_acos::apply(), op_cos::apply(), op_sort::apply(), op_shuffle::apply(), op_scalar_div_post::apply(), op_scalar_div_pre::apply(), op_scalar_times::apply(), glue_schur::apply(), glue_plus_diag::apply(), glue_plus::apply(), glue_minus_diag::apply(), glue_minus::apply(), glue_div::apply(), op_eps::direct_eps(), unwrap_write< Col< eT > >::unwrap_write(), unwrap_write< Row< eT > >::unwrap_write(), and unwrap_write< Mat< eT > >::unwrap_write().
  {
  arma_extra_debug_sigprint();
  init(m.n_rows, m.n_cols);
  }
template<typename eT> void Mat< eT >::fill (const eT val) [inline, inherited]
fill the matrix with the specified value
Definition at line 1815 of file Mat_meat.hpp.
References Mat< eT >::mem, Mat< eT >::n_elem, and access::rw().
Referenced by Mat< eT >::ones(), operator*(), operator/(), and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) = val;
    }
  }
template<typename eT > void Mat< eT >::zeros () [inline, inherited]
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1830 of file Mat_meat.hpp.
References Mat< eT >::fill().
Referenced by op_zeros::apply(), op_ones_diag::apply(), op_inv::apply(), op_diagmat_vec::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_minus_diag::apply(), op_inv::apply_diagvec(), diagmat(), op_pinv::direct_pinv(), subview< eT >::minus_inplace(), operator*(), operator/(), auxlib::solve_ud(), and running_stat_vec_aux::update_stats().
  {
  arma_extra_debug_sigprint();
  fill(eT(0));
  }
template<typename eT > void Mat< eT >::zeros (const u32 in_rows, const u32 in_cols) [inline, inherited]
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1842 of file Mat_meat.hpp.
References Mat< eT >::fill(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint( arma_boost::format("in_rows = %d, in_cols = %d") % in_rows % in_cols );
  set_size(in_rows, in_cols);
  fill(eT(0));
  }
template<typename eT > void Mat< eT >::ones () [inline, inherited]
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1855 of file Mat_meat.hpp.
References Mat< eT >::fill().
Referenced by op_ones_full::apply().
  {
  arma_extra_debug_sigprint();
  fill(eT(1));
  }
template<typename eT > void Mat< eT >::ones (const u32 in_rows, const u32 in_cols) [inline, inherited]
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1867 of file Mat_meat.hpp.
References Mat< eT >::fill(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint( arma_boost::format("in_rows = %d, in_cols = %d") % in_rows % in_cols );
  set_size(in_rows, in_cols);
  fill(eT(1));
  }
template<typename eT > void Mat< eT >::reset () [inline, inherited]
Definition at line 1880 of file Mat_meat.hpp.
References Mat< eT >::init().
Referenced by diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), and running_stat_vec< eT >::reset().
  {
  arma_extra_debug_sigprint();
  init(0,0);
  }
template<typename eT > void Mat< eT >::save (const std::string name, const file_type type = arma_binary) const [inline, inherited]
save the matrix to a file
Definition at line 1893 of file Mat_meat.hpp.
References arma_ascii, arma_binary, arma_stop(), pgm_binary, raw_ascii, diskio::save_arma_ascii(), diskio::save_arma_binary(), diskio::save_pgm_binary(), and diskio::save_raw_ascii().
  {
  arma_extra_debug_sigprint();
  switch(type)
    {
    case raw_ascii:
      diskio::save_raw_ascii(*this, name);
      break;
    case arma_ascii:
      diskio::save_arma_ascii(*this, name);
      break;
    case arma_binary:
      diskio::save_arma_binary(*this, name);
      break;
    case pgm_binary:
      diskio::save_pgm_binary(*this, name);
      break;
    default:
      arma_stop("Mat::save(): unsupported file type");
    }
  }
template<typename eT > void Mat< eT >::load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file
Reimplemented in Col< eT >, and Row< eT >.
Definition at line 1927 of file Mat_meat.hpp.
References arma_ascii, arma_binary, arma_stop(), auto_detect, diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), pgm_binary, and raw_ascii.
Referenced by diskio::load_pgm_binary(), and diskio::load_raw_ascii().
  {
  arma_extra_debug_sigprint();
  switch(type)
    {
    case auto_detect:
      diskio::load_auto_detect(*this, name);
      break;
    case raw_ascii:
      diskio::load_raw_ascii(*this, name);
      break;
    case arma_ascii:
      diskio::load_arma_ascii(*this, name);
      break;
    case arma_binary:
      diskio::load_arma_binary(*this, name);
      break;
    case pgm_binary:
      diskio::load_pgm_binary(*this, name);
      break;
    default:
      arma_stop("Mat::load(): unsupported file type");
    }
  }
template<typename eT > arma_inline void Mat_aux::prefix_pp (Mat< eT > & x) [inline, static, inherited]
prefix ++
Definition at line 1965 of file Mat_meat.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by Mat< eT >::operator++().
  {
        eT* memptr = x.memptr();
  const u32 n_elem = x.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    ++(memptr[i]);
    }
  }
template<typename T > arma_inline void Mat_aux::prefix_pp (Mat< std::complex< T > > & x) [inline, static, inherited]
prefix ++ for complex numbers (work around for limitations of the std::complex class)
Definition at line 1982 of file Mat_meat.hpp.
  {
  x += T(1);
  }
template<typename eT > arma_inline void Mat_aux::postfix_pp (Mat< eT > & x) [inline, static, inherited]
postfix ++
Definition at line 1993 of file Mat_meat.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by Mat< eT >::operator++().
  {
        eT* memptr = x.memptr();
  const u32 n_elem = x.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    (memptr[i])++;
    }
  }
template<typename T > arma_inline void Mat_aux::postfix_pp (Mat< std::complex< T > > & x) [inline, static, inherited]
postfix ++ for complex numbers (work around for limitations of the std::complex class)
Definition at line 2010 of file Mat_meat.hpp.
  {
  x += T(1);
  }
template<typename eT > arma_inline void Mat_aux::prefix_mm (Mat< eT > & x) [inline, static, inherited]
prefix --
Definition at line 2021 of file Mat_meat.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by Mat< eT >::operator--().
  {
        eT* memptr = x.memptr();
  const u32 n_elem = x.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    --(memptr[i]);
    }
  }
template<typename T > arma_inline void Mat_aux::prefix_mm (Mat< std::complex< T > > & x) [inline, static, inherited]
prefix -- for complex numbers (work around for limitations of the std::complex class)
Definition at line 2038 of file Mat_meat.hpp.
  {
  x -= T(1);
  }
template<typename eT > arma_inline void Mat_aux::postfix_mm (Mat< eT > & x) [inline, static, inherited]
postfix --
Definition at line 2049 of file Mat_meat.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
Referenced by Mat< eT >::operator--().
  {
        eT* memptr = x.memptr();
  const u32 n_elem = x.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    (memptr[i])--;
    }
  }
template<typename T > arma_inline void Mat_aux::postfix_mm (Mat< std::complex< T > > & x) [inline, static, inherited]
postfix ++ for complex numbers (work around for limitations of the std::complex class)
Definition at line 2066 of file Mat_meat.hpp.
  {
  x -= T(1);
  }