Armadillo Technical: Debug
Debug
Namespaces
namespace junk
Functions
void arma_print ()
template<typename T1 >
void arma_print (const T1 &x)
template<typename T1 , typename T2 >
void arma_print (const T1 &x, const T2 &y)
template<typename T1 >
void arma_print (const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_print (const arma_boost::basic_format< T1, T2 > &x)
void arma_sigprint (const char *x)
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
void arma_bktprint ()
template<typename T1 >
void arma_bktprint (const T1 &x)
template<typename T1 , typename T2 >
void arma_bktprint (const T1 &x, const T2 &y)
template<typename T1 >
void arma_bktprint (const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_bktprint (const arma_boost::basic_format< T1, T2 > &x)
void arma_thisprint (void *this_ptr)
template<typename T1 >
void arma_hot arma_warn (const bool state, const T1 &x)
if state is true, print a message on cout
template<typename T1 , typename T2 >
void arma_hot arma_warn (const bool state, const T1 &x, const T2 &y)
template<typename T1 >
void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > &x)
template<typename T1 >
void arma_hot arma_check (const bool state, const T1 &x)
if state is true, throw a run-time error exception
template<typename T1 , typename T2 >
void arma_hot arma_check (const bool state, const T1 &x, const T2 &y)
template<typename T1 >
void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1, T2 > &x)
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const Mat< eT2 > &B, const char *x)
if given matrices have different sizes, throw a run-time error exception
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char *x)
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const Cube< eT2 > &B, const char *x)
if given cubes have different sizes, throw a run-time error exception
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const Cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const Cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
void arma_hot arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const Mat< eT1 > &A, const Mat< eT2 > &B, const char *x)
if given matrices are incompatible for multiplication, throw a run-time error exception
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const Mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const subview< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename T1 >
void arma_stop (const T1 &x)
throw a run-time error exception
Function Documentation
void arma_print () [inline]
Definition at line 26 of file debug.hpp.
Referenced by arma_warn(), chol(), field_aux::load(), diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), diskio::load_std_string(), qr(), rank(), field_aux::save(), diskio::save_arma_binary(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), diskio::save_std_string(), solve(), and svd().
  {
  std::cout << std::endl;
  }
template<typename T1 > void arma_print (const T1 & x) [inline]
Definition at line 35 of file debug.hpp.
  {
  std::cout << x << std::endl;
  }
template<typename T1 , typename T2 > void arma_print (const T1 & x, const T2 & y) [inline]
Definition at line 45 of file debug.hpp.
  {
  std::cout << x << y << std::endl;
  }
template<typename T1 > void arma_print (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 56 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
template<typename T1 , typename T2 > void arma_print (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 64 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
void arma_sigprint (const char * x) [inline]
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
Definition at line 80 of file debug.hpp.
  {
  std::cout << "@ " << x;
  }
void arma_bktprint () [inline]
Definition at line 93 of file debug.hpp.
  {
  std::cout << std::endl;
  }
template<typename T1 > void arma_bktprint (const T1 & x) [inline]
Definition at line 102 of file debug.hpp.
  {
  std::cout << " [" << x << ']' << std::endl;
  }
template<typename T1 , typename T2 > void arma_bktprint (const T1 & x, const T2 & y) [inline]
Definition at line 112 of file debug.hpp.
  {
  std::cout << " [" << x << y << ']' << std::endl;
  }
template<typename T1 > void arma_bktprint (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 123 of file debug.hpp.
    {
    std::cout << " [" << x << ']' << std::endl;
    }
template<typename T1 , typename T2 > void arma_bktprint (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 131 of file debug.hpp.
    {
    std::cout << " [" << x << ']' << std::endl;
    }
void arma_thisprint (void * this_ptr) [inline]
Definition at line 145 of file debug.hpp.
  {
  std::cout << " [this = " << this_ptr << ']' << std::endl;
  }
template<typename T1 > void arma_hot arma_warn (const bool state, const T1 & x) [inline]
if state is true, print a message on cout
Definition at line 160 of file debug.hpp.
References arma_print().
Referenced by diskio::safe_rename(), diskio::save_arma_ascii(), diskio::save_arma_binary(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), and diskio::save_std_string().
  {
  if(state==true)
    {
    arma_print(x);
    }
  }
template<typename T1 , typename T2 > void arma_hot arma_warn (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 173 of file debug.hpp.
References arma_print().
  {
  if(state==true)
    {
    arma_print(x,y);
    }
  }
template<typename T1 > void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 187 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1 , typename T2 > void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 197 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1 > void arma_hot arma_check (const bool state, const T1 & x) [inline]
if state is true, throw a run-time error exception
Definition at line 214 of file debug.hpp.
Referenced by arma_stop(), subview< eT >::at(), subview_field< oT >::at(), subview_cube< eT >::at(), subview< eT >::colptr(), Cube< eT >::create_mat(), diagview< eT >::fill(), Mat< eT >::init(), field< oT >::init(), Cube< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), subview< eT >::operator()(), subview_field< oT >::operator()(), subview_cube< eT >::operator()(), running_stat_vec< eT >::operator()(), running_stat< eT >::operator()(), diagview< eT >::operator()(), diagview< eT >::operator=(), subview< eT >::operator[](), subview_field< oT >::operator[](), subview_cube< eT >::operator[](), subview_cube< eT >::slice_colptr(), and diagview< eT >::zeros().
  {
  if(state==true)
    {
    throw std::runtime_error(x);
    }
  }
template<typename T1 , typename T2 > void arma_hot arma_check (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 227 of file debug.hpp.
  {
  if(state==true)
    {
    throw std::runtime_error( std::string(x) + std::string(y) );
    }
  }
template<typename T1 > void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 241 of file debug.hpp.
References arma_boost::str().
    {
    if(state==true)
      {
      throw std::runtime_error(str(x));
      }
    }
template<typename T1 , typename T2 > void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 253 of file debug.hpp.
References arma_boost::str().
    {
    if(state==true)
      {
      throw std::runtime_error(str(x));
      }
    }
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 271 of file debug.hpp.
Referenced by arma_assert_mul_size(), and arma_assert_same_size().
  {
  std::stringstream tmp;
  tmp << x << ": incompatible matrix dimensions: (" << A_n_rows << ',' << A_n_cols << ") and (" << B_n_rows << ',' << B_n_cols << ')';
  return tmp.str();
  }
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 285 of file debug.hpp.
References arma_incompat_size_string().
Referenced by Cube< eT >::Cube(), and Mat< eT >::Mat().
  {
  if( (A_n_rows != B_n_rows) || (A_n_cols != B_n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
if given matrices have different sizes, throw a run-time error exception
Definition at line 303 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 320 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, Mat< eT >::n_cols, subview< eT >::n_rows, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 337 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, subview< eT >::n_cols, Mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 354 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char * x) [inline]
Definition at line 374 of file debug.hpp.
  {
  std::stringstream tmp;
  tmp << x << ": incompatible cube dimensions: (" << A_n_rows << ',' << A_n_cols << ',' << A_n_slices << ") and (" << B_n_rows << ',' << B_n_cols << ',' << B_n_slices << ')';
  return tmp.str();
  }
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char * x) [inline]
Definition at line 388 of file debug.hpp.
References arma_incompat_size_string().
  {
  if( (A_n_rows != B_n_rows) || (A_n_cols != B_n_cols) || (A_n_slices != B_n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A_n_rows, A_n_cols, A_n_slices, B_n_rows, B_n_cols, B_n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
if given cubes have different sizes, throw a run-time error exception
Definition at line 406 of file debug.hpp.
References arma_incompat_size_string(), Cube< eT >::n_cols, Cube< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 423 of file debug.hpp.
References arma_incompat_size_string(), subview_cube< eT >::n_cols, Cube< eT >::n_cols, subview_cube< eT >::n_rows, Cube< eT >::n_rows, subview_cube< eT >::n_slices, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
Definition at line 440 of file debug.hpp.
References arma_incompat_size_string(), Cube< eT >::n_cols, subview_cube< eT >::n_cols, Cube< eT >::n_rows, subview_cube< eT >::n_rows, Cube< eT >::n_slices, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 457 of file debug.hpp.
References arma_incompat_size_string(), subview_cube< eT >::n_cols, subview_cube< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices))
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 479 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, Cube< eT >::n_cols, Mat< eT >::n_rows, Cube< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != 1) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, 1, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
Definition at line 496 of file debug.hpp.
References arma_incompat_size_string(), Cube< eT >::n_cols, Mat< eT >::n_cols, Cube< eT >::n_rows, Mat< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (1 != B.n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, 1, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 513 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, subview_cube< eT >::n_cols, Mat< eT >::n_rows, subview_cube< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != 1) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, 1, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 530 of file debug.hpp.
References arma_incompat_size_string(), subview_cube< eT >::n_cols, Mat< eT >::n_cols, subview_cube< eT >::n_rows, Mat< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (1 != B.n_slices) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, 1, B.n_rows, B.n_cols, B.n_slices, x)
      );
    }
  }
void arma_hot arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 551 of file debug.hpp.
References arma_incompat_size_string().
  {
  if(A_n_cols != B_n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const Mat< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
if given matrices are incompatible for multiplication, throw a run-time error exception
Definition at line 569 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const Mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 586 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, Mat< eT >::n_cols, Mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const subview< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 603 of file debug.hpp.
References arma_incompat_size_string(), Mat< eT >::n_cols, subview< eT >::n_cols, subview< eT >::n_rows, and Mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 620 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename T1 > void arma_stop (const T1 & x) [inline]
throw a run-time error exception
Definition at line 640 of file debug.hpp.
References arma_check().
Referenced by op_atanh::apply(), op_atan::apply(), op_asinh::apply(), op_asin::apply(), op_acosh::apply(), op_acos::apply(), auxlib::chol(), auxlib::det(), eig_gen(), auxlib::eig_gen(), auxlib::eig_sym(), auxlib::inv_inplace(), auxlib::inv_noalias(), Mat< eT >::load(), field_aux::load(), Cube< eT >::load(), auxlib::lu(), auxlib::qr(), Mat< eT >::save(), field_aux::save(), Cube< eT >::save(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), wall_clock::tic(), and wall_clock::toc().
  {
  arma_check(true, x);
  }