Armadillo Technical: Fn_trig
Fn_trig
Functions
template<typename T1 >
const Op< T1, op_cos > cos (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_acos > acos (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_cosh > cosh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_acosh > acosh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_sin > sin (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_asin > asin (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_sinh > sinh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_asinh > asinh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_tan > tan (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_atan > atan (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_tanh > tanh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const Op< T1, op_atanh > atanh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_cos > cos (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_acos > acos (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_cosh > cosh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_acosh > acosh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_sin > sin (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_asin > asin (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_sinh > sinh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_asinh > asinh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_tan > tan (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_atan > atan (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_tanh > tanh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
const OpCube< T1, op_atanh > atanh (const BaseCube< typename T1::elem_type, T1 > &A)
Function Documentation
template<typename T1 > const Op<T1, op_cos> cos (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 32 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_cos::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_cos>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_acos> acos (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 47 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_acos::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_acos>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_cosh> cosh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 62 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_cosh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_cosh>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_acosh> acosh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 77 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_acosh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_acosh>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_sin> sin (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 92 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_sin::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_sin>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_asin> asin (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 107 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_asin::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_asin>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_sinh> sinh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 122 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_sinh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_sinh>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_asinh> asinh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 137 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_asinh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_asinh>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_tan> tan (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 152 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_tan::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_tan>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_atan> atan (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 167 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_atan::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_atan>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_tanh> tanh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 182 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_tanh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_tanh>(A.get_ref());
  }
template<typename T1 > const Op<T1, op_atanh> atanh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 197 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_atanh::apply().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_atanh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_cos> cos (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 218 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_cos>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_acos> acos (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 233 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_acos>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_cosh> cosh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 248 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_cosh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_acosh> acosh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 263 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_acosh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_sin> sin (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 278 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_sin>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_asin> asin (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 293 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_asin>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_sinh> sinh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 308 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_sinh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_asinh> asinh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 323 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_asinh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_tan> tan (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 338 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_tan>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_atan> atan (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 353 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_atan>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_tanh> tanh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 368 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_tanh>(A.get_ref());
  }
template<typename T1 > const OpCube<T1, op_atanh> atanh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 383 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_atanh>(A.get_ref());
  }