Armadillo Technical: Fn_sort
Fn_sort
Functions
template<typename T1 >
const Op< T1, op_sort > sort (const Base< typename T1::elem_type, T1 > &X, const u32 sort_type=0, const u32 dim=0)
template<typename eT >
const Op< Col< eT >, op_sort > sort (const Col< eT > &X, const u32 sort_type=0)
template<typename eT >
const Op< Row< eT >, op_sort > sort (const Row< eT > &X, const u32 sort_type=0)
Function Documentation
template<typename T1 > const Op<T1, op_sort> sort (const Base< typename T1::elem_type, T1 > & X, const u32 sort_type = 0, const u32 dim = 0) [inline]
Definition at line 23 of file fn_sort.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_shuffle::apply(), op_median::direct_cx_median_index(), op_median::direct_median(), and sort_index_helper().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_sort>(X.get_ref(), sort_type, dim);
  }
template<typename eT > const Op<Col<eT>, op_sort> sort (const Col< eT > & X, const u32 sort_type = 0) [inline]
Definition at line 35 of file fn_sort.hpp.
  {
  arma_extra_debug_sigprint();
  const u32 dim = 0;
  return Op<Col<eT>, op_sort>(X, sort_type, dim);
  }
template<typename eT > const Op<Row<eT>, op_sort> sort (const Row< eT > & X, const u32 sort_type = 0) [inline]
Definition at line 49 of file fn_sort.hpp.
  {
  arma_extra_debug_sigprint();
  const u32 dim = 1;
  return Op<Row<eT>, op_sort>(X, sort_type, dim);
  }