Armadillo Technical: Fn_eps
Fn_eps
Functions
template<typename T1 >
const eOp< T1, eop_eps > eps (const Base< typename T1::elem_type, T1 > &X)
eps version for non-complex matrices and vectors
template<typename T1 >
Mat< typename T1::pod_type > eps (const Base< std::complex< typename T1::pod_type >, T1 > &X)
eps version for complex matrices and vectors
template<typename eT >
arma_inline arma_warn_unused
arma_integral_only< eT >
::result eps (const eT &x)
template<typename T >
arma_inline arma_warn_unused
arma_float_only< T >::result eps (const std::complex< T > &x)
Function Documentation
template<typename T1 > const eOp<T1, eop_eps> eps (const Base< typename T1::elem_type, T1 > & X) [inline]
eps version for non-complex matrices and vectors
Definition at line 29 of file fn_eps.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  return eOp<T1, eop_eps>(X.get_ref());
  }
template<typename T1 > Mat< typename T1::pod_type > eps (const Base< std::complex< typename T1::pod_type >, T1 > & X) [inline]
eps version for complex matrices and vectors
Definition at line 45 of file fn_eps.hpp.
References eop_aux::direct_eps(), and Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type   T;
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  Mat<T> out(A.n_rows, A.n_cols);
         T* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = eop_aux::direct_eps( A_mem[i] );
    }
  return out;
  }
template<typename eT > arma_inline arma_warn_unused arma_float_only< eT >::result eps (const eT & x) [inline]
Definition at line 87 of file fn_eps.hpp.
References eop_aux::direct_eps().
  {
  return eop_aux::direct_eps(x);
  }
template<typename T > arma_inline arma_warn_unused arma_float_only<T>::result eps (const std::complex< T > & x) [inline]
Definition at line 98 of file fn_eps.hpp.
References eop_aux::direct_eps().
  {
  return eop_aux::direct_eps(x);
  }