Armadillo Technical: Operator_schur
Operator_schur
Functions
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, T2 > &Y)
Base % Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, Op
< T2, op_diagmat >
, glue_schur_diag > operator% (const Base< typename T2::elem_type, T1 > &X, const Op< T2, op_diagmat > &Y)
Base % diagmat.
template<typename T1 , typename T2 >
arma_inline const Glue< Op< T1,
op_diagmat >, T2,
glue_schur_diag > operator% (const Op< T1, op_diagmat > &X, const Base< typename T1::elem_type, T2 > &Y)
diagmat % Base
template<typename T1 , typename T2 >
Mat< typename promote_type
< typename T1::elem_type,
typename T2::elem_type >
::result > operator% (const Op< T1, op_diagmat > &X, const Op< T2, op_diagmat > &Y)
diagmat % diagmat
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Mat< typename
promote_type< eT1, eT2 >
::result > operator% (const Base< eT1, T1 > &X, const Base< eT2, T2 > &Y)
Base % Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< std::complex< double >, T1 > &X, const Base< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< std::complex< float >, T1 > &X, const Base< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< double, T1 > &X, const Base< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< float, T1 > &X, const Base< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< s32, T1 > &X, const Base< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< u32, T1 > &X, const Base< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< s16, T1 > &X, const Base< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< u16, T1 > &X, const Base< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< s8, T1 > &X, const Base< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_schur > operator% (const Base< u8, T1 > &X, const Base< u8, T2 > &Y)
Function Documentation
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
Base % Base.
Definition at line 28 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, Op<T2,op_diagmat>, glue_schur_diag> operator% (const Base< typename T2::elem_type, T1 > & X, const Op< T2, op_diagmat > & Y) [inline]
Base % diagmat.
Definition at line 42 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, Op<T2,op_diagmat>, glue_schur_diag>(X.get_ref(), Y);
  }
template<typename T1 , typename T2 > arma_inline const Glue< Op<T1,op_diagmat>, T2, glue_schur_diag> operator% (const Op< T1, op_diagmat > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
diagmat % Base
Definition at line 56 of file operator_schur.hpp.
References Base< T1::elem_type, Op< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue< Op<T1,op_diagmat>, T2, glue_schur_diag>(X, Y.get_ref());
  }
template<typename T1 , typename T2 > Mat< typename promote_type<typename T1::elem_type, typename T2::elem_type>::result > operator% (const Op< T1, op_diagmat > & X, const Op< T2, op_diagmat > & Y) [inline]
diagmat % diagmat
Definition at line 70 of file operator_schur.hpp.
References upgrade_val< T1, T2 >::apply(), Mat< eT >::at(), promote_type< T1, T2 >::check(), Op< T1, op_type >::m, Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT1;
  typedef typename T2::elem_type eT2;
  typedef typename promote_type<eT1,eT2>::result out_eT;
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.m);
  const unwrap<T2> tmp2(Y.m);
  const Mat<eT1> A(tmp1.M);
  const Mat<eT2> B(tmp2.M);
  arma_debug_assert_same_size(A.n_rows, A.n_cols, B.n_rows, B.n_cols, "element-wise matrix multiplication");
  Mat<out_eT> out(A.n_rows, A.n_rows);
  out.zeros();
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = upgrade_val<eT1,eT2>::apply( A.at(i,i) ) * upgrade_val<eT1,eT2>::apply( B.at(i,i) );
    }
  return out;
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Mat<typename promote_type<eT1,eT2>::result> operator% (const Base< eT1, T1 > & X, const Base< eT2, T2 > & Y) [inline]
Base % Base.
Definition at line 113 of file operator_schur.hpp.
References glue_schur::apply_mixed(), promote_type< T1, T2 >::check(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const Mat<eT1>& A = tmp1.M;
  const Mat<eT2>& B = tmp2.M;
  Mat< typename promote_type<eT1,eT2>::result > out;
  glue_schur::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< std::complex< double >, T1 > & X, const Base< std::complex< double >, T2 > & Y) [inline]
Definition at line 143 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< std::complex< float >, T1 > & X, const Base< std::complex< float >, T2 > & Y) [inline]
Definition at line 156 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< double, T1 > & X, const Base< double, T2 > & Y) [inline]
Definition at line 169 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< float, T1 > & X, const Base< float, T2 > & Y) [inline]
Definition at line 182 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< s32, T1 > & X, const Base< s32, T2 > & Y) [inline]
Definition at line 195 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< u32, T1 > & X, const Base< u32, T2 > & Y) [inline]
Definition at line 208 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< s16, T1 > & X, const Base< s16, T2 > & Y) [inline]
Definition at line 221 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< u16, T1 > & X, const Base< u16, T2 > & Y) [inline]
Definition at line 234 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< s8, T1 > & X, const Base< s8, T2 > & Y) [inline]
Definition at line 247 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_schur> operator% (const Base< u8, T1 > & X, const Base< u8, T2 > & Y) [inline]
Definition at line 260 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }