Armadillo Technical: Operator_times
Operator_times
Functions
template<typename T1 >
arma_inline const Op< T1,
op_scalar_times > operator* (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base * scalar.
template<typename T1 >
arma_inline const Op< T1,
op_scalar_times > operator* (const Op< T1, op_scalar_times > &X, const typename T1::elem_type k)
op * scalar, level 2
template<typename eT >
arma_inline Mat< eT > operator* (const Op< Mat< eT >, op_ones_full > &X, const eT k)
Op<mat,op_ones_full> * scalar.
template<typename eT >
arma_inline Mat< eT > operator* (const Op< Mat< eT >, op_ones_diag > &X, const eT k)
Op<mat,op_ones_diag> * scalar.
template<typename T1 >
arma_inline const Op< T1,
op_scalar_times > operator* (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > &X)
scalar * Base
template<typename eT >
arma_inline Mat< eT > operator* (const eT k, const Op< Mat< eT >, op_ones_full > &X)
scalar * Op<mat,op_ones_full>
template<typename eT >
arma_inline Mat< eT > operator* (const eT k, const Op< Mat< eT >, op_ones_diag > &X)
scalar * Op<mat,op_ones_diag>
template<typename T1 , typename T2 >
arma_inline const Glue< T1, Op
< T2, op_diagmat >
, glue_times_diag > operator* (const Base< typename T2::elem_type, T1 > &X, const Op< T2, op_diagmat > &Y)
Base * diagmat.
template<typename T1 , typename T2 >
arma_inline const Glue< Op< T1,
op_diagmat >, T2,
glue_times_diag > operator* (const Op< T1, op_diagmat > &X, const Base< typename T1::elem_type, T2 > &Y)
diagmat * Base
template<typename T1 , typename T2 >
Mat< typename promote_type
< typename T1::elem_type,
typename T2::elem_type >
::result > operator* (const Op< T1, op_diagmat > &X, const Op< T2, op_diagmat > &Y)
diagmat * diagmat
template<typename eT >
arma_inline const Glue< Col
< eT >, Row< eT >
, glue_times_vec > operator* (const Col< eT > &X, const Row< eT > &Y)
colvec * rowvec
template<typename T1 >
arma_inline const Glue< T1,
Col< typename T1::elem_type >
, glue_times_vec > operator* (const Base< typename T1::elem_type, T1 > &X, const Col< typename T1::elem_type > &Y)
Base * colvec.
template<typename T1 >
arma_inline const Glue< T1,
Row< typename T1::elem_type >
, glue_times_vec > operator* (const Base< typename T1::elem_type, T1 > &X, const Row< typename T1::elem_type > &Y)
Base * rowvec.
template<typename T1 >
arma_inline const Glue< Col
< typename T1::elem_type >, T1,
glue_times_vec > operator* (const Col< typename T1::elem_type > &X, const Base< typename T1::elem_type, T1 > &Y)
colvec * Base
template<typename T1 >
arma_inline const Glue< Row
< typename T1::elem_type >, T1,
glue_times_vec > operator* (const Row< typename T1::elem_type > &X, const Base< typename T1::elem_type, T1 > &Y)
rowvec * Base
template<typename T1 >
arma_inline const Glue< Op< T1,
op_diagmat >, Col< typename
T1::elem_type >
, glue_times_diag > operator* (const Op< T1, op_diagmat > &X, const Col< typename T1::elem_type > &Y)
diagmat * colvec
template<typename T1 >
arma_inline const Glue< Op< T1,
op_diagmat >, Row< typename
T1::elem_type >
, glue_times_diag > operator* (const Op< T1, op_diagmat > &X, const Row< typename T1::elem_type > &Y)
diagmat * rowvec
template<typename T1 >
arma_inline const Glue< Col
< typename T1::elem_type >, Op
< T1, op_diagmat >
, glue_times_diag > operator* (const Col< typename T1::elem_type > &X, const Op< T1, op_diagmat > &Y)
colvec * diagmat
template<typename T1 >
arma_inline const Glue< Row
< typename T1::elem_type >, Op
< T1, op_diagmat >
, glue_times_diag > operator* (const Row< typename T1::elem_type > &X, const Op< T1, op_diagmat > &Y)
rowvec * diagmat
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Mat< typename
promote_type< eT1, eT2 >
::result > operator* (const Base< eT1, T1 > &X, const Base< eT2, T2 > &Y)
Base * Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< std::complex< double >, T1 > &X, const Base< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< std::complex< float >, T1 > &X, const Base< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< double, T1 > &X, const Base< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< float, T1 > &X, const Base< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< s32, T1 > &X, const Base< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< u32, T1 > &X, const Base< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< s16, T1 > &X, const Base< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< u16, T1 > &X, const Base< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< s8, T1 > &X, const Base< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_times > operator* (const Base< u8, T1 > &X, const Base< u8, T2 > &Y)
Function Documentation
template<typename T1 > arma_inline const Op<T1, op_scalar_times> operator* (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base * scalar.
Definition at line 32 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_times>(X.get_ref(),k);
  }
template<typename T1 > arma_inline const Op<T1,op_scalar_times> operator* (const Op< T1, op_scalar_times > & X, const typename T1::elem_type k) [inline]
op * scalar, level 2
Definition at line 46 of file operator_times.hpp.
References Op< T1, op_type >::aux, and Op< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_times>(X.m, X.aux * k);
  }
template<typename eT > arma_inline Mat<eT> operator* (const Op< Mat< eT >, op_ones_full > & X, const eT k) [inline]
Op<mat,op_ones_full> * scalar.
Definition at line 60 of file operator_times.hpp.
References Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, and Mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill(k);
  return tmp;
  }
template<typename eT > arma_inline Mat<eT> operator* (const Op< Mat< eT >, op_ones_diag > & X, const eT k) [inline]
Op<mat,op_ones_diag> * scalar.
Definition at line 77 of file operator_times.hpp.
References Mat< eT >::at(), Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  for(u32 i=0; i<out.n_rows; ++i)
    {
    out.at(i,i) = k;
    }
  return out;
  }
template<typename T1 > arma_inline const Op<T1, op_scalar_times> operator* (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > & X) [inline]
scalar * Base
Definition at line 99 of file operator_times.hpp.
References Base< T1::elem_type, Op< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_times>(X.get_ref(),k);  // NOTE: order is swapped
  }
template<typename eT > arma_inline Mat<eT> operator* (const eT k, const Op< Mat< eT >, op_ones_full > & X) [inline]
scalar * Op<mat,op_ones_full>
Definition at line 113 of file operator_times.hpp.
References Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, and Mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill(k);
  return tmp;
  }
template<typename eT > arma_inline Mat<eT> operator* (const eT k, const Op< Mat< eT >, op_ones_diag > & X) [inline]
scalar * Op<mat,op_ones_diag>
Definition at line 130 of file operator_times.hpp.
References Mat< eT >::at(), Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  for(u32 i=0; i<out.n_rows; ++i)
    out.at(i,i) = k;
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, Op<T2,op_diagmat>, glue_times_diag> operator* (const Base< typename T2::elem_type, T1 > & X, const Op< T2, op_diagmat > & Y) [inline]
Base * diagmat.
Definition at line 150 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, Op<T2,op_diagmat>, glue_times_diag>(X.get_ref(), Y);
  }
template<typename T1 , typename T2 > arma_inline const Glue<Op<T1,op_diagmat>, T2, glue_times_diag> operator* (const Op< T1, op_diagmat > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
diagmat * Base
Definition at line 164 of file operator_times.hpp.
References Base< T1::elem_type, Op< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<Op<T1,op_diagmat>, T2, glue_times_diag>(X, Y.get_ref());
  }
template<typename T1 , typename T2 > Mat< typename promote_type<typename T1::elem_type, typename T2::elem_type>::result > operator* (const Op< T1, op_diagmat > & X, const Op< T2, op_diagmat > & Y) [inline]
diagmat * diagmat
Definition at line 178 of file operator_times.hpp.
References upgrade_val< T1, T2 >::apply(), Mat< eT >::at(), promote_type< T1, T2 >::check(), Op< T1, op_type >::m, Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT1;
  typedef typename T2::elem_type eT2;
  typedef typename promote_type<eT1,eT2>::result out_eT;
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.m);
  const unwrap<T2> tmp2(Y.m);
  const Mat<eT1> A(tmp1.M);
  const Mat<eT2> B(tmp2.M);
  arma_debug_assert_same_size(A.n_rows, A.n_cols, B.n_rows, B.n_cols, "matrix multiplication");
  Mat<out_eT> out(A.n_rows, A.n_rows);
  out.zeros();
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = upgrade_val<eT1,eT2>::apply( A.at(i,i) ) * upgrade_val<eT1,eT2>::apply( B.at(i,i) );
    }
  return out;
  }
template<typename eT > arma_inline const Glue<Col<eT>, Row<eT>, glue_times_vec> operator* (const Col< eT > & X, const Row< eT > & Y) [inline]
colvec * rowvec
Definition at line 215 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return Glue<Col<eT>, Row<eT>, glue_times_vec>(X, Y);
  }
template<typename T1 > arma_inline const Glue<T1, Col<typename T1::elem_type>, glue_times_vec> operator* (const Base< typename T1::elem_type, T1 > & X, const Col< typename T1::elem_type > & Y) [inline]
Base * colvec.
Definition at line 229 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, Col<typename T1::elem_type>, glue_times_vec>(X.get_ref(), Y);
  }
template<typename T1 > arma_inline const Glue<T1, Row<typename T1::elem_type>, glue_times_vec> operator* (const Base< typename T1::elem_type, T1 > & X, const Row< typename T1::elem_type > & Y) [inline]
Base * rowvec.
Definition at line 243 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, Row<typename T1::elem_type>, glue_times_vec>(X.get_ref(), Y);
  }
template<typename T1 > arma_inline const Glue<Col<typename T1::elem_type>, T1, glue_times_vec> operator* (const Col< typename T1::elem_type > & X, const Base< typename T1::elem_type, T1 > & Y) [inline]
colvec * Base
Definition at line 257 of file operator_times.hpp.
References Base< eT, Mat< eT > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<Col<typename T1::elem_type>, T1, glue_times_vec>(X, Y.get_ref());
  }
template<typename T1 > arma_inline const Glue<Row<typename T1::elem_type>, T1, glue_times_vec> operator* (const Row< typename T1::elem_type > & X, const Base< typename T1::elem_type, T1 > & Y) [inline]
rowvec * Base
Definition at line 271 of file operator_times.hpp.
References Base< eT, Mat< eT > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<Row<typename T1::elem_type>, T1, glue_times_vec>(X, Y.get_ref());
  }
template<typename T1 > arma_inline const Glue<Op<T1, op_diagmat>, Col<typename T1::elem_type>, glue_times_diag> operator* (const Op< T1, op_diagmat > & X, const Col< typename T1::elem_type > & Y) [inline]
diagmat * colvec
Definition at line 285 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return Glue<Op<T1, op_diagmat>, Col<typename T1::elem_type>, glue_times_diag>(X, Y);
  }
template<typename T1 > arma_inline const Glue<Op<T1, op_diagmat>, Row<typename T1::elem_type>, glue_times_diag> operator* (const Op< T1, op_diagmat > & X, const Row< typename T1::elem_type > & Y) [inline]
diagmat * rowvec
Definition at line 299 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return Glue<Op<T1, op_diagmat>, Row<typename T1::elem_type>, glue_times_diag>(X, Y);
  }
template<typename T1 > arma_inline const Glue<Col<typename T1::elem_type>, Op<T1, op_diagmat>, glue_times_diag> operator* (const Col< typename T1::elem_type > & X, const Op< T1, op_diagmat > & Y) [inline]
colvec * diagmat
Definition at line 313 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return Glue<Col<typename T1::elem_type>, Op<T1, op_diagmat>, glue_times_diag>(X, Y);
  }
template<typename T1 > arma_inline const Glue<Row<typename T1::elem_type>, Op<T1, op_diagmat>, glue_times_diag> operator* (const Row< typename T1::elem_type > & X, const Op< T1, op_diagmat > & Y) [inline]
rowvec * diagmat
Definition at line 327 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return Glue<Row<typename T1::elem_type>, Op<T1, op_diagmat>, glue_times_diag>(X, Y);
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Mat<typename promote_type<eT1,eT2>::result> operator* (const Base< eT1, T1 > & X, const Base< eT2, T2 > & Y) [inline]
Base * Base.
Definition at line 347 of file operator_times.hpp.
References glue_times::apply_mixed(), promote_type< T1, T2 >::check(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const Mat< eT1 >& A = tmp1.M;
  const Mat< eT2 >& B = tmp2.M;
  Mat< typename promote_type<eT1,eT2>::result > out;
  glue_times::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< std::complex< double >, T1 > & X, const Base< std::complex< double >, T2 > & Y) [inline]
Definition at line 378 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< std::complex< float >, T1 > & X, const Base< std::complex< float >, T2 > & Y) [inline]
Definition at line 391 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< double, T1 > & X, const Base< double, T2 > & Y) [inline]
Definition at line 404 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< float, T1 > & X, const Base< float, T2 > & Y) [inline]
Definition at line 417 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< s32, T1 > & X, const Base< s32, T2 > & Y) [inline]
Definition at line 430 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< u32, T1 > & X, const Base< u32, T2 > & Y) [inline]
Definition at line 443 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< s16, T1 > & X, const Base< s16, T2 > & Y) [inline]
Definition at line 456 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< u16, T1 > & X, const Base< u16, T2 > & Y) [inline]
Definition at line 469 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< s8, T1 > & X, const Base< s8, T2 > & Y) [inline]
Definition at line 482 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_times> operator* (const Base< u8, T1 > & X, const Base< u8, T2 > & Y) [inline]
Definition at line 495 of file operator_times.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }