Armadillo Technical: Operator_minus
Operator_minus
Functions
template<typename T1 >
arma_inline const Op< T1, op_neg > operator- (const Base< typename T1::elem_type, T1 > &X)
unary -
template<typename T1 >
arma_inline const T1 & operator- (const Op< T1, op_neg > &X)
cancellation of two consecutive negations: -(-T1)
template<typename T1 >
arma_inline const Op< T1,
op_scalar_minus_post > operator- (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base - scalar.
template<typename T1 >
arma_inline const Op< T1,
op_scalar_minus_pre > operator- (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > &X)
scalar - Base
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_plus > operator- (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, Op< T2, op_neg > > &Y)
Base - - Base = Base + Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, Op
< T2, op_diagmat >
, glue_minus_diag > operator- (const Base< typename T2::elem_type, T1 > &X, const Op< T2, op_diagmat > &Y)
Base - diagmat.
template<typename T1 , typename T2 >
arma_inline const Glue< Op< T1,
op_diagmat >, T2,
glue_minus_diag > operator- (const Op< T1, op_diagmat > &X, const Base< typename T1::elem_type, T2 > &Y)
diagmat - Base
template<typename T1 , typename T2 >
Mat< typename promote_type
< typename T1::elem_type,
typename T2::elem_type >
::result > operator- (const Op< T1, op_diagmat > &X, const Op< T2, op_diagmat > &Y)
diagmat - diagmat
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_plus > operator- (const Base< typename T2::elem_type, T1 > &X, const Op< T2, op_neg > &Y)
Base - Op<T2,op_neg> = Base + T2.
template<typename T1 , typename T2 >
arma_inline const Glue< Op< T1,
op_diagmat >, T2,
glue_plus_diag > operator- (const Base< typename T1::elem_type, Op< T1, op_diagmat > > &X, const Base< typename T1::elem_type, Op< T2, op_neg > > &Y)
diagmat - Op<T2,op_neg> = diagmat + T2
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Mat< typename
promote_type< eT1, eT2 >
::result > operator- (const Base< eT1, T1 > &X, const Base< eT2, T2 > &Y)
Base - Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< std::complex< double >, T1 > &X, const Base< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< std::complex< float >, T1 > &X, const Base< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< double, T1 > &X, const Base< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< float, T1 > &X, const Base< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< s32, T1 > &X, const Base< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< u32, T1 > &X, const Base< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< s16, T1 > &X, const Base< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< u16, T1 > &X, const Base< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< s8, T1 > &X, const Base< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_minus > operator- (const Base< u8, T1 > &X, const Base< u8, T2 > &Y)
Function Documentation
template<typename T1 > arma_inline const Op<T1, op_neg> operator- (const Base< typename T1::elem_type, T1 > & X) [inline]
unary -
Definition at line 26 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return Op<T1,op_neg>(X.get_ref());
  }
template<typename T1 > arma_inline const T1& operator- (const Op< T1, op_neg > & X) [inline]
cancellation of two consecutive negations: -(-T1)
Definition at line 40 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return X.m;
  }
template<typename T1 > arma_inline const Op<T1, op_scalar_minus_post> operator- (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base - scalar.
Definition at line 54 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_minus_post>(X.get_ref(), k);
  }
template<typename T1 > arma_inline const Op<T1, op_scalar_minus_pre> operator- (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > & X) [inline]
scalar - Base
Definition at line 68 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_minus_pre>(X.get_ref(), k);
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_plus> operator- (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, Op< T2, op_neg > > & Y) [inline]
Base - - Base = Base + Base.
Definition at line 82 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const T1& A = X.get_ref();
  const T2& B = (Y.get_ref()).m;
  return Glue<T1, T2, glue_plus>(A,B);
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, Op<T2,op_diagmat>, glue_minus_diag> operator- (const Base< typename T2::elem_type, T1 > & X, const Op< T2, op_diagmat > & Y) [inline]
Base - diagmat.
Definition at line 102 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, Op<T1,op_diagmat>, glue_minus_diag>(X.get_ref(), Y);
  }
template<typename T1 , typename T2 > arma_inline const Glue< Op<T1,op_diagmat>, T2, glue_minus_diag> operator- (const Op< T1, op_diagmat > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
diagmat - Base
Definition at line 116 of file operator_minus.hpp.
References Base< T1::elem_type, Op< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue< Op<T1,op_diagmat>, T2, glue_minus_diag>(X, Y.get_ref());
  }
template<typename T1 , typename T2 > Mat< typename promote_type<typename T1::elem_type, typename T2::elem_type>::result > operator- (const Op< T1, op_diagmat > & X, const Op< T2, op_diagmat > & Y) [inline]
diagmat - diagmat
Definition at line 130 of file operator_minus.hpp.
References upgrade_val< T1, T2 >::apply(), Mat< eT >::at(), promote_type< T1, T2 >::check(), Op< T1, op_type >::m, Mat< eT >::n_cols, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT1;
  typedef typename T2::elem_type eT2;
  typedef typename promote_type<eT1,eT2>::result out_eT;
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.m);
  const unwrap<T2> tmp2(Y.m);
  const Mat<eT1> A(tmp1.M);
  const Mat<eT2> B(tmp2.M);
  arma_debug_assert_same_size(A.n_rows, A.n_cols, B.n_rows, B.n_cols, "matrix subtraction");
  Mat<out_eT> out(A.n_rows, A.n_rows);
  out.zeros();
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = upgrade_val<eT1,eT2>::apply( A.at(i,i) ) - upgrade_val<eT1,eT2>::apply( B.at(i,i) );
    }
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_plus> operator- (const Base< typename T2::elem_type, T1 > & X, const Op< T2, op_neg > & Y) [inline]
Base - Op<T2,op_neg> = Base + T2.
Definition at line 167 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_plus>(X.get_ref(), Y.m);
  }
template<typename T1 , typename T2 > arma_inline const Glue< Op<T1,op_diagmat>, T2, glue_plus_diag> operator- (const Base< typename T1::elem_type, Op< T1, op_diagmat > > & X, const Base< typename T1::elem_type, Op< T2, op_neg > > & Y) [inline]
diagmat - Op<T2,op_neg> = diagmat + T2
Definition at line 181 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue< Op<T1,op_diagmat>, T2, glue_plus_diag>(X.get_ref(), (Y.get_ref()).m);
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Mat<typename promote_type<eT1,eT2>::result> operator- (const Base< eT1, T1 > & X, const Base< eT2, T2 > & Y) [inline]
Base - Base.
Definition at line 204 of file operator_minus.hpp.
References glue_minus::apply_mixed(), promote_type< T1, T2 >::check(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const Mat<eT1>& A = tmp1.M;
  const Mat<eT2>& B = tmp2.M;
  Mat< typename promote_type<eT1,eT2>::result > out;
  glue_minus::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< std::complex< double >, T1 > & X, const Base< std::complex< double >, T2 > & Y) [inline]
Definition at line 234 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< std::complex< float >, T1 > & X, const Base< std::complex< float >, T2 > & Y) [inline]
Definition at line 247 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< double, T1 > & X, const Base< double, T2 > & Y) [inline]
Definition at line 260 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< float, T1 > & X, const Base< float, T2 > & Y) [inline]
Definition at line 273 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< s32, T1 > & X, const Base< s32, T2 > & Y) [inline]
Definition at line 286 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< u32, T1 > & X, const Base< u32, T2 > & Y) [inline]
Definition at line 299 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< s16, T1 > & X, const Base< s16, T2 > & Y) [inline]
Definition at line 312 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< u16, T1 > & X, const Base< u16, T2 > & Y) [inline]
Definition at line 325 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< s8, T1 > & X, const Base< s8, T2 > & Y) [inline]
Definition at line 338 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_minus> operator- (const Base< u8, T1 > & X, const Base< u8, T2 > & Y) [inline]
Definition at line 351 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }