Armadillo Technical: Fn_conv_to
Fn_conv_to
Classes
class conv_to< out_eT >
class conv_to< Mat< out_eT > >
class conv_to< Row< out_eT > >
class conv_to< Col< out_eT > >
class conv_to< Cube< out_eT > >
class conv_to< itpp::Mat< out_eT > >
class conv_to< itpp::Vec< out_eT > >
Functions
template<typename out_eT , typename in_eT >
arma_inline void copy_complex_elem (out_eT &out, const in_eT &in)
template<typename out_eT , typename in_T >
arma_inline void copy_complex_elem (out_eT &out, const std::complex< in_T > &in)
template<typename out_T , typename in_T >
arma_inline void copy_complex_elem (std::complex< out_T > &out, const std::complex< in_T > &in)
static out_eT conv_to::from (const Mat< out_eT > &in)
template<typename in_eT >
static out_eT conv_to::from (const Mat< in_eT > &in)
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const Base< in_eT, T1 > &in)
static out_eT conv_to::from (const Cube< out_eT > &in)
template<typename in_eT >
static out_eT conv_to::from (const Cube< in_eT > &in)
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const BaseCube< in_eT, T1 > &in)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const Mat< in_eT > &in)
template<typename in_T >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const Mat< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > &in)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > &in)
template<typename in_T >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< std::complex< in_T > > &in)
static Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< out_eT > &in)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< in_eT > &in)
template<typename in_T >
static Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > &in)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > &in)
template<typename in_T >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< std::complex< in_T > > &in)
static Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< out_eT > &in)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< in_eT > &in)
template<typename in_T >
static Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > &in)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > &in)
template<typename in_T >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< std::complex< in_T > > &in)
template<typename in_eT >
static Cube< out_eT > conv_to< Cube< out_eT > >::from (const Cube< in_eT > &in)
template<typename in_T >
static Cube< out_eT > conv_to< Cube< out_eT > >::from (const Cube< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< out_eT > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< out_eT > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< out_eT > &in)
template<typename in_eT >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< in_eT > &in)
template<typename in_eT >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< in_eT > &in)
template<typename in_eT >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< in_eT > &in)
template<typename in_T >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< std::complex< in_T > > &in)
template<typename in_T >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< std::complex< in_T > > &in)
template<typename in_T >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > &in)
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< out_eT > &in)
template<typename in_eT >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< in_eT > &in)
template<typename in_T >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< std::complex< in_T > > &in)
template<typename in_eT >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Col< in_eT > &in)
template<typename in_T >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Col< std::complex< in_T > > &in)
template<typename in_eT >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Row< in_eT > &in)
template<typename in_T >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Row< std::complex< in_T > > &in)
template<typename in_eT , typename T1 >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > &in)
Function Documentation
template<typename out_eT , typename in_eT > arma_inline void copy_complex_elem (out_eT & out, const in_eT & in) [inline]
Definition at line 28 of file fn_conv_to.hpp.
Referenced by conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< Cube< out_eT > >::from(), conv_to< Col< out_eT > >::from(), conv_to< Row< out_eT > >::from(), conv_to< Mat< out_eT > >::from(), and conv_to< out_eT >::from().
  {
  //arma_extra_debug_sigprint();
  out = out_eT(in);
  }
template<typename out_eT , typename in_T > arma_inline void copy_complex_elem (out_eT & out, const std::complex< in_T > & in) [inline]
Definition at line 40 of file fn_conv_to.hpp.
  {
  //arma_extra_debug_sigprint();
  out = out_eT( in.real() );
  }
template<typename out_T , typename in_T > arma_inline void copy_complex_elem (std::complex< out_T > & out, const std::complex< in_T > & in) [inline]
Definition at line 52 of file fn_conv_to.hpp.
  {
  //arma_extra_debug_sigprint();
  typedef std::complex<out_T> out_eT;
  out = out_eT(in);
  }
template<typename out_eT > out_eT conv_to< out_eT >::from (const Mat< out_eT > & in) [inline, static, inherited]
Definition at line 95 of file fn_conv_to.hpp.
References Mat< eT >::mem, and Mat< eT >::n_elem.
Referenced by conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: matrix doesn't have exactly one element" );
  return in.mem[0];
  }
template<typename out_eT > template<typename in_eT > out_eT conv_to< out_eT >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 110 of file fn_conv_to.hpp.
References copy_complex_elem(), Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: matrix doesn't have exactly one element" );
  out_eT out;
  copy_complex_elem(out, in.mem[0]);
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 130 of file fn_conv_to.hpp.
References conv_to< out_eT >::from(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to<out_eT>::from( tmp.M );
  }
template<typename out_eT > out_eT conv_to< out_eT >::from (const Cube< out_eT > & in) [inline, static, inherited]
Definition at line 146 of file fn_conv_to.hpp.
References Cube< eT >::mem, and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: cube doesn't have exactly one element" );
  return in.mem[0];
  }
template<typename out_eT > template<typename in_eT > out_eT conv_to< out_eT >::from (const Cube< in_eT > & in) [inline, static, inherited]
Definition at line 161 of file fn_conv_to.hpp.
References copy_complex_elem(), Cube< eT >::mem, and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: cube doesn't have exactly one element" );
  out_eT out;
  copy_complex_elem(out, in.mem[0]);
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const BaseCube< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 181 of file fn_conv_to.hpp.
References conv_to< out_eT >::from(), and BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap_cube<T1> tmp(in.get_ref());
  return conv_to<out_eT>::from( tmp.M );
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 234 of file fn_conv_to.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Mat< out_eT > conv_to< Mat< out_eT > >::from (const Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 257 of file fn_conv_to.hpp.
References copy_complex_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 282 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< Mat<out_eT> >::from( tmp.M );
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > & in) [inline, static, inherited]
Definition at line 297 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.rows(), in.cols());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 320 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  Mat<out_eT> out(in.rows(), in.cols());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< out_eT > & in) [inline, static, inherited]
Definition at line 380 of file fn_conv_to.hpp.
References syslib::copy_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  Row<out_eT> out(in.n_cols);
  syslib::copy_elem(out.memptr(), in.mem, out.n_elem);
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 399 of file fn_conv_to.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  Row<out_eT> out(in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Row< out_eT > conv_to< Row< out_eT > >::from (const Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 423 of file fn_conv_to.hpp.
References copy_complex_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  Row<out_eT> out(in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 449 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< Row<out_eT> >::from( tmp.M );
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > & in) [inline, static, inherited]
Definition at line 464 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Row<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 487 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  Row<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< out_eT > & in) [inline, static, inherited]
Definition at line 607 of file fn_conv_to.hpp.
References syslib::copy_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  Col<out_eT> out(in.n_rows);
  syslib::copy_elem(out.memptr(), in.mem, out.n_elem);
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 625 of file fn_conv_to.hpp.
References Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  Col<out_eT> out(in.n_rows);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Col< out_eT > conv_to< Col< out_eT > >::from (const Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 649 of file fn_conv_to.hpp.
References copy_complex_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  Col<out_eT> out(in.n_rows);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 675 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< Col<out_eT> >::from( tmp.M );
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > & in) [inline, static, inherited]
Definition at line 690 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Col<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 713 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  Col<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Cube< out_eT > conv_to< Cube< out_eT > >::from (const Cube< in_eT > & in) [inline, static, inherited]
Definition at line 819 of file fn_conv_to.hpp.
References Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  Cube<out_eT> out(in.n_rows, in.n_cols, in.n_slices);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > Cube< out_eT > conv_to< Cube< out_eT > >::from (const Cube< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 842 of file fn_conv_to.hpp.
References copy_complex_elem(), Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  Cube<out_eT> out(in.n_rows, in.n_cols, in.n_slices);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 867 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> tmp(in.get_ref());
  return conv_to< Mat<out_eT> >::from( tmp.M );
  }
template<typename out_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< out_eT > & in) [inline, static, inherited]
Definition at line 928 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and syslib::copy_elem().
  {
  arma_extra_debug_sigprint();
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  syslib::copy_elem(out._data(), in.mem, in.n_elem);
  return out;
  }
template<typename out_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< out_eT > & in) [inline, static, inherited]
Definition at line 944 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat<out_eT>& >(in) );
  }
template<typename out_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< out_eT > & in) [inline, static, inherited]
Definition at line 956 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat<out_eT>& >(in) );
  }
template<typename out_eT > template<typename in_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 969 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT* in_mem = in.memptr();
  out_eT*     out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< in_eT > & in) [inline, static, inherited]
Definition at line 992 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat<in_eT>& >(in) );
  }
template<typename out_eT > template<typename in_eT > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< in_eT > & in) [inline, static, inherited]
Definition at line 1005 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat<in_eT>& >(in) );
  }
template<typename out_eT > template<typename in_T > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1018 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT* in_mem = in.memptr();
  out_eT*     out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_T > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Col< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1043 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat< std::complex<in_T> >& >(in) );
  }
template<typename out_eT > template<typename in_T > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Row< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1056 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const Mat< std::complex<in_T> >& >(in) );
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 1069 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< itpp::Mat<out_eT> >::from( tmp.M );
  }
template<typename out_eT > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< out_eT > & in) [inline, static, inherited]
Definition at line 1124 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and syslib::copy_elem().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  syslib::copy_elem(out._data(), in.mem, in.n_elem);
  return out;
  }
template<typename out_eT > template<typename in_eT > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< in_eT > & in) [inline, static, inherited]
Definition at line 1143 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1167 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Col< in_eT > & in) [inline, static, inherited]
Definition at line 1194 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Col< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1217 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Row< in_eT > & in) [inline, static, inherited]
Definition at line 1242 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT > template<typename in_T > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Row< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1265 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 1290 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< itpp::Vec<out_eT> >::from( tmp.M );
  }