Armadillo Technical: Operator_div
Operator_div
Functions
template<typename T1 >
arma_inline const Op< T1,
op_scalar_div_post > operator/ (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base / scalar.
template<typename eT >
arma_inline Mat< eT > operator/ (const Op< Mat< eT >, op_ones_full > &X, const eT k)
Op<mat,op_ones_full> / scalar.
template<typename eT >
arma_inline Mat< eT > operator/ (const Op< Mat< eT >, op_ones_diag > &X, const eT k)
Op<mat,op_ones_diag> / scalar.
template<typename T1 >
arma_inline const Op< T1,
op_scalar_div_pre > operator/ (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > &X)
scalar / Base
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Mat< typename
promote_type< eT1, eT2 >
::result > operator/ (const Base< eT1, T1 > &X, const Base< eT2, T2 > &Y)
Base / Base.
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< std::complex< double >, T1 > &X, const Base< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< std::complex< float >, T1 > &X, const Base< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< double, T1 > &X, const Base< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< float, T1 > &X, const Base< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< s32, T1 > &X, const Base< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< u32, T1 > &X, const Base< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< s16, T1 > &X, const Base< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< u16, T1 > &X, const Base< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< s8, T1 > &X, const Base< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const Glue< T1, T2,
glue_div > operator/ (const Base< u8, T1 > &X, const Base< u8, T2 > &Y)
Function Documentation
template<typename T1 > arma_inline const Op<T1, op_scalar_div_post> operator/ (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base / scalar.
Definition at line 26 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_div_post>(X.get_ref(), k);
  }
template<typename eT > arma_inline Mat<eT> operator/ (const Op< Mat< eT >, op_ones_full > & X, const eT k) [inline]
Op<mat,op_ones_full> / scalar.
Definition at line 40 of file operator_div.hpp.
References Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, and Mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill( eT(1)/k );
  return tmp;
  }
template<typename eT > arma_inline Mat<eT> operator/ (const Op< Mat< eT >, op_ones_diag > & X, const eT k) [inline]
Op<mat,op_ones_diag> / scalar.
Definition at line 57 of file operator_div.hpp.
References Mat< eT >::at(), Op< T1, op_type >::aux_u32_a, Op< T1, op_type >::aux_u32_b, Mat< eT >::n_rows, and Mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  const eT inv_k = eT(1)/k;
  for(u32 i=0; i<out.n_rows; ++i)
    {
    out.at(i,i) = inv_k;
    }
  return out;
  }
template<typename T1 > arma_inline const Op<T1, op_scalar_div_pre> operator/ (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > & X) [inline]
scalar / Base
Definition at line 81 of file operator_div.hpp.
References Base< T1::elem_type, Op< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_scalar_div_pre>(X.get_ref(), k);
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Mat<typename promote_type<eT1,eT2>::result> operator/ (const Base< eT1, T1 > & X, const Base< eT2, T2 > & Y) [inline]
Base / Base.
Definition at line 101 of file operator_div.hpp.
References glue_div::apply_mixed(), promote_type< T1, T2 >::check(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const Mat<eT1>& A = tmp1.M;
  const Mat<eT2>& B = tmp2.M;
  Mat< typename promote_type<eT1,eT2>::result > out;
  glue_div::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< std::complex< double >, T1 > & X, const Base< std::complex< double >, T2 > & Y) [inline]
Definition at line 131 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< std::complex< float >, T1 > & X, const Base< std::complex< float >, T2 > & Y) [inline]
Definition at line 144 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< double, T1 > & X, const Base< double, T2 > & Y) [inline]
Definition at line 157 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< float, T1 > & X, const Base< float, T2 > & Y) [inline]
Definition at line 170 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< s32, T1 > & X, const Base< s32, T2 > & Y) [inline]
Definition at line 183 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< u32, T1 > & X, const Base< u32, T2 > & Y) [inline]
Definition at line 196 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< s16, T1 > & X, const Base< s16, T2 > & Y) [inline]
Definition at line 209 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< u16, T1 > & X, const Base< u16, T2 > & Y) [inline]
Definition at line 222 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< s8, T1 > & X, const Base< s8, T2 > & Y) [inline]
Definition at line 235 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const Glue<T1, T2, glue_div> operator/ (const Base< u8, T1 > & X, const Base< u8, T2 > & Y) [inline]
Definition at line 248 of file operator_div.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Glue<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }