Armadillo Technical: Fn_misc
Fn_misc
Functions
template<typename vec_type >
vec_type linspace (const typename vec_type::pod_type start, const typename vec_type::pod_type end, const u32 num, const u32 dim=0)
Generate a vector with 'num' elements. The values of the elements linearly increase from 'start' upto (and including) 'end'.
mat linspace (const double start, const double end, const u32 num, const u32 dim=0)
template<typename T1 >
arma_inline const T1 & real (const Base< typename T1::pod_type, T1 > &X)
template<typename T1 >
arma_inline const T1 & real (const BaseCube< typename T1::pod_type, T1 > &X)
template<typename T1 >
Mat< typename T1::pod_type > real (const Base< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
Cube< typename T1::pod_type > real (const BaseCube< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
const eOp< Mat< typename
T1::pod_type >, eop_zeros > imag (const Base< typename T1::pod_type, T1 > &X)
template<typename T1 >
const eOpCube< Cube< typename
T1::pod_type >, eop_cube_zeros > imag (const BaseCube< typename T1::pod_type, T1 > &X)
template<typename T1 >
Mat< typename T1::pod_type > imag (const Base< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
Cube< typename T1::pod_type > imag (const BaseCube< std::complex< typename T1::pod_type >, T1 > &X)
template<typename eT >
eT log_add (eT log_a, eT log_b)
template<typename T1 >
arma_inline const eOp< T1,
eop_log > log (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_log > log (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_trunc_log > trunc_log (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_trunc_log > trunc_log (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_log10 > log10 (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_log10 > log10 (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_exp > exp (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_exp > exp (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_trunc_exp > trunc_exp (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_trunc_exp > trunc_exp (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_abs > abs (const Base< typename T1::elem_type, T1 > &X)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_abs > abs (const BaseCube< typename T1::elem_type, T1 > &X)
template<typename T1 >
Mat< typename T1::pod_type > abs (const Base< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
Mat< typename T1::pod_type > abs (const BaseCube< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
arma_inline const eOp< T1,
eop_abs > fabs (const Base< typename T1::pod_type, T1 > &X)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_abs > fabs (const BaseCube< typename T1::pod_type, T1 > &X)
template<typename T1 >
arma_inline Mat< typename
T1::pod_type > fabs (const Base< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
arma_inline Mat< typename
T1::pod_type > fabs (const BaseCube< std::complex< typename T1::pod_type >, T1 > &X)
template<typename T1 >
arma_inline const eOp< T1,
eop_square > square (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_square > square (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_sqrt > sqrt (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_sqrt > sqrt (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const T1 & conj (const Base< typename T1::pod_type, T1 > &A)
template<typename T1 >
arma_inline const T1 & conj (const BaseCube< typename T1::pod_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_conj > conj (const Base< std::complex< typename T1::pod_type >, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_conj > conj (const BaseCube< std::complex< typename T1::pod_type >, T1 > &A)
template<typename T1 >
arma_inline const T1 & conj (const eOp< T1, eop_conj > &A)
template<typename T1 >
arma_inline const T1 & conj (const eOpCube< T1, eop_cube_conj > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_pow > pow (const Base< typename T1::elem_type, T1 > &A, const typename T1::elem_type exponent)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_pow > pow (const BaseCube< typename T1::elem_type, T1 > &A, const typename T1::elem_type exponent)
template<typename T1 >
arma_inline const eOp< T1,
eop_pow > pow (const Base< typename T1::elem_type, T1 > &A, const typename T1::elem_type::value_type exponent)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_pow > pow (const BaseCube< typename T1::elem_type, T1 > &A, const typename T1::elem_type::value_type exponent)
template<typename T1 >
arma_inline const eOp< T1,
eop_pow_int > pow (const Base< typename T1::elem_type, T1 > &A, const int exponent)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_pow_int > pow (const BaseCube< typename T1::elem_type, T1 > &A, const int exponent)
Function Documentation
template<typename vec_type > vec_type linspace (const typename vec_type::pod_type start, const typename vec_type::pod_type end, const u32 num, const u32 dim = 0) [inline]
Generate a vector with 'num' elements. The values of the elements linearly increase from 'start' upto (and including) 'end'.
Definition at line 30 of file fn_misc.hpp.
References arma_warn(), and Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_type_check< (is_Mat<vec_type>::value == false) >::apply();
  arma_debug_check( (num < 2), "linspace(): num must be >= 2");
  arma_warn( (dim != 0), "linspace(): the 'dim' argument is deprecated -- please use template based specification instead" );
  typedef typename vec_type::elem_type eT;
  typedef typename vec_type::pod_type   T;
  // // this will be the default in the future:
  // const u32 n_rows = (is_Row<vec_type>::value == true) ? 1   : num;
  // const u32 n_cols = (is_Row<vec_type>::value == true) ? num : 1;
  // for temporary compatibility with old user code:
  const u32 n_rows = (is_Row<vec_type>::value == true) ? 1   : ( (dim == 0) ? num : 1   );
  const u32 n_cols = (is_Row<vec_type>::value == true) ? num : ( (dim == 0) ? 1   : num );
  const eT delta = (end-start)/T(num-1);
  Mat<eT> x(n_rows, n_cols);
  eT* x_mem = x.memptr();
  x_mem[0] = start;
  for(u32 i=1; i<num; ++i)
    {
    x_mem[i] = x_mem[i-1] + delta;
    }
  return x;
  }
mat linspace (const double start, const double end, const u32 num, const u32 dim = 0) [inline]
Definition at line 75 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return linspace<mat>(start, end, num, dim);
  }
template<typename T1 > arma_inline const T1& real (const Base< typename T1::pod_type, T1 > & X) [inline]
Definition at line 89 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by real(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  return X.get_ref();
  }
template<typename T1 > arma_inline const T1& real (const BaseCube< typename T1::pod_type, T1 > & X) [inline]
Definition at line 101 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return X.get_ref();
  }
template<typename T1 > Mat<typename T1::pod_type> real (const Base< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 113 of file fn_misc.hpp.
References real().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type T;
  const Proxy<T1> A(X.get_ref());
  Mat<T> out(A.n_rows, A.n_cols);
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::real(A[i]);
    }
  return out;
  }
template<typename T1 > Cube<typename T1::pod_type> real (const BaseCube< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 138 of file fn_misc.hpp.
References real().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type T;
  const ProxyCube<T1> A(X.get_ref());
  Cube<T> out(A.n_rows, A.n_cols, A.n_slices);
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::real(A[i]);
    }
  return out;
  }
template<typename T1 > const eOp<Mat<typename T1::pod_type>, eop_zeros> imag (const Base< typename T1::pod_type, T1 > & X) [inline]
Definition at line 166 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by imag().
  {
  arma_extra_debug_sigprint();
  const Proxy<T1> A(X.get_ref());
  return eOp<Mat<typename T1::pod_type>, eop_zeros>(A.n_rows, A.n_cols);
  }
template<typename T1 > const eOpCube<Cube<typename T1::pod_type>, eop_cube_zeros> imag (const BaseCube< typename T1::pod_type, T1 > & X) [inline]
Definition at line 180 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const ProxyCube<T1> A(X.get_ref());
  return eOpCube<Cube<typename T1::pod_type>, eop_cube_zeros>(A.n_rows, A.n_cols, A.n_slices);
  }
template<typename T1 > Mat<typename T1::pod_type> imag (const Base< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 194 of file fn_misc.hpp.
References imag().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type T;
  const Proxy<T1> A(X.get_ref());
  Mat<T> out(A.n_rows, A.n_cols);
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::imag(A[i]);
    }
  return out;
  }
template<typename T1 > Cube<typename T1::pod_type> imag (const BaseCube< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 219 of file fn_misc.hpp.
References imag().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::pod_type T;
  const ProxyCube<T1> A(X.get_ref());
  Cube<T> out(A.n_rows, A.n_cols, A.n_slices);
  T* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::imag(A[i]);
    }
  return out;
  }
template<typename eT > eT log_add (eT log_a, eT log_b) [inline]
Definition at line 247 of file fn_misc.hpp.
References arma_isfinite(), exp(), and log().
  {
  if(log_a < log_b)
    {
    std::swap(log_a, log_b);
    }
  const eT negdelta = log_b - log_a;
  if( (negdelta < Math<eT>::log_min()) || (arma_isfinite(negdelta) == false) )
    {
    return log_a;
    }
  else
    {
    #if defined(ARMA_HAVE_LOG1P)
      return (log_a + log1p(std::exp(negdelta)));
    #else
      return (log_a + std::log(1.0 + std::exp(negdelta)));
    #endif
    }
  }
template<typename T1 > arma_inline const eOp<T1, eop_log> log (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 278 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by log_add(), log_det(), auxlib::log_det(), Math< eT >::log_max(), Math< eT >::log_min(), eop_cube_core< eop_cube_type >::process(), eop_core< eop_type >::process(), and eop_aux::trunc_log().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_log>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_log> log (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 290 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_log>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_trunc_log> trunc_log (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 305 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_trunc_log>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_trunc_log> trunc_log (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 317 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_trunc_log>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_log10> log10 (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 332 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_aux::direct_eps(), eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_log10>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_log10> log10 (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 344 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_log10>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_exp> exp (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 359 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by log_add(), eop_cube_core< eop_cube_type >::process(), eop_core< eop_type >::process(), and eop_aux::trunc_exp().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_exp>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_exp> exp (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 371 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_exp>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_trunc_exp> trunc_exp (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 386 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_trunc_exp>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_trunc_exp> trunc_exp (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 398 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_trunc_exp>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_abs> abs (const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 414 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by abs(), op_min::apply(), op_median::apply(), op_max::apply(), eop_aux::arma_abs(), arma_qsort_helper< std::complex< T > >::ascend_compare(), arma_qsort_helper< std::complex< T > >::descend_compare(), op_median::direct_cx_median_index(), eop_aux::direct_eps(), op_max::direct_max(), op_min::direct_min(), fabs(), norm_proxy(), and norm_unwrap().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_abs>(X.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_abs> abs (const BaseCube< typename T1::elem_type, T1 > & X) [inline]
Definition at line 426 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_abs>(X.get_ref());
  }
template<typename T1 > Mat<typename T1::pod_type> abs (const Base< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 438 of file fn_misc.hpp.
References abs(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const Proxy<T1> A(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  Mat<out_eT> out(A.n_rows, A.n_cols);
  out_eT* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::abs(A[i]);
    }
  return out;
  }
template<typename T1 > Mat<typename T1::pod_type> abs (const BaseCube< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 468 of file fn_misc.hpp.
References abs(), Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const ProxyCube<T1> A(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  Cube<out_eT> out(A.n_rows, A.n_cols, A.n_slices);
  out_eT* out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = std::abs(A[i]);
    }
  return out;
  }
template<typename T1 > arma_inline const eOp<T1, eop_abs> fabs (const Base< typename T1::pod_type, T1 > & X) [inline]
Definition at line 501 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_abs>(X.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_abs> fabs (const BaseCube< typename T1::pod_type, T1 > & X) [inline]
Definition at line 513 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_abs>(X.get_ref());
  }
template<typename T1 > arma_inline Mat<typename T1::pod_type> fabs (const Base< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 525 of file fn_misc.hpp.
References abs().
  {
  arma_extra_debug_sigprint();
  return abs(X);
  }
template<typename T1 > arma_inline Mat<typename T1::pod_type> fabs (const BaseCube< std::complex< typename T1::pod_type >, T1 > & X) [inline]
Definition at line 537 of file fn_misc.hpp.
References abs().
  {
  arma_extra_debug_sigprint();
  return abs(X);
  }
template<typename T1 > arma_inline const eOp<T1, eop_square> square (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 552 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_square>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_square> square (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 564 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_square>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_sqrt> sqrt (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 579 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_stddev::apply(), op_norm_dot::apply_proxy(), op_norm_dot::apply_unwrap(), op_princomp::direct_princomp(), norm_proxy(), norm_unwrap(), eop_cube_core< eop_cube_type >::process(), eop_core< eop_type >::process(), running_stat_vec< eT >::stddev(), running_stat< eT >::stddev(), and stddev().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_sqrt>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_sqrt> sqrt (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 591 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_sqrt>(A.get_ref());
  }
template<typename T1 > arma_inline const T1& conj (const Base< typename T1::pod_type, T1 > & A) [inline]
Definition at line 606 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_htrans::apply(), op_htrans::apply_noalias(), op_cor::direct_cor(), glue_cor::direct_cor(), op_cov::direct_cov(), glue_cov::direct_cov(), eig_gen(), eop_cube_core< eop_cube_type >::process(), eop_core< eop_type >::process(), auxlib::svd(), and running_stat_vec_aux::update_stats().
  {
  arma_extra_debug_sigprint();
  return A.get_ref();
  }
template<typename T1 > arma_inline const T1& conj (const BaseCube< typename T1::pod_type, T1 > & A) [inline]
Definition at line 618 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return A.get_ref();
  }
template<typename T1 > arma_inline const eOp<T1, eop_conj> conj (const Base< std::complex< typename T1::pod_type >, T1 > & A) [inline]
Definition at line 630 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_conj>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_conj> conj (const BaseCube< std::complex< typename T1::pod_type >, T1 > & A) [inline]
Definition at line 642 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_conj>(A.get_ref());
  }
template<typename T1 > arma_inline const T1& conj (const eOp< T1, eop_conj > & A) [inline]
Definition at line 654 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return A.m;
  }
template<typename T1 > arma_inline const T1& conj (const eOpCube< T1, eop_cube_conj > & A) [inline]
Definition at line 666 of file fn_misc.hpp.
  {
  arma_extra_debug_sigprint();
  return A.m;
  }
template<typename T1 > arma_inline const eOp<T1, eop_pow> pow (const Base< typename T1::elem_type, T1 > & A, const typename T1::elem_type exponent) [inline]
Definition at line 696 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by norm_proxy(), norm_unwrap(), eop_aux::pow(), eop_aux::pow_int(), eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_pow>(A.get_ref(), exponent);
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_pow> pow (const BaseCube< typename T1::elem_type, T1 > & A, const typename T1::elem_type exponent) [inline]
Definition at line 708 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_pow>(A.get_ref(), exponent);
  }
template<typename T1 > arma_inline const eOp<T1, eop_pow> pow (const Base< typename T1::elem_type, T1 > & A, const typename T1::elem_type::value_type exponent) [inline]
Definition at line 722 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  return eOp<T1, eop_pow>(A.get_ref(), eT(exponent));
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_pow> pow (const BaseCube< typename T1::elem_type, T1 > & A, const typename T1::elem_type::value_type exponent) [inline]
Definition at line 736 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  return eOpCube<T1, eop_cube_pow>(A.get_ref(), eT(exponent));
  }
template<typename T1 > arma_inline const eOp<T1, eop_pow_int> pow (const Base< typename T1::elem_type, T1 > & A, const int exponent) [inline]
Definition at line 755 of file fn_misc.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  if(exponent >= 0)
    {
    return eOp<T1, eop_pow_int>(A.get_ref(), exponent, 0);
    }
  else
    {
    return eOp<T1, eop_pow_int>(A.get_ref(), -exponent, 1);
    }
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_pow_int> pow (const BaseCube< typename T1::elem_type, T1 > & A, const int exponent) [inline]
Definition at line 774 of file fn_misc.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  if(exponent >= 0)
    {
    return eOpCube<T1, eop_cube_pow_int>(A.get_ref(),  exponent, 0);
    }
  else
    {
    return eOpCube<T1, eop_cube_pow_int>(A.get_ref(), -exponent, 1);
    }
  }