Armadillo Technical: Col
Col
Classes
class Col< eT >
Class for column vectors (matrices with only column).
Functions
Col::Col ()
construct an empty column vector
Col::Col (const u32 n_elem)
construct a column vector with the specified number of n_elem
Col::Col (const u32 in_rows, const u32 in_cols)
Col::Col (const char *text)
construct a column vector from specified text
const Col & Col::operator= (const char *text)
construct a column vector from specified text
Col::Col (const std::string &text)
construct a column vector from specified text
const Col & Col::operator= (const std::string &text)
construct a column vector from specified text
Col::Col (const Col &X)
construct a column vector from a given column vector
const Col & Col::operator= (const Col &X)
construct a column vector from a given column vector
Col::Col (const Mat< eT > &X)
construct a column vector from a given matrix; the matrix must have exactly one column
const Col & Col::operator= (const Mat< eT > &X)
construct a column vector from a given matrix; the matrix must have exactly one column
const Col & Col::operator*= (const Mat< eT > &X)
Col::Col (eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem=true)
construct a column vector from a given auxiliary array of eTs
Col::Col (const eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols)
construct a column vector from a given auxiliary array of eTs
Col::Col (eT *aux_mem, const u32 aux_length, const bool copy_aux_mem=true)
construct a column vector from a given auxiliary array of eTs
Col::Col (const eT *aux_mem, const u32 aux_length)
construct a column vector from a given auxiliary array of eTs
template<typename T1 , typename T2 >
Col::Col (const Base< pod_type, T1 > &A, const Base< pod_type, T2 > &B)
Col::Col (const subview< eT > &X)
construct a column vector from given a submatrix; the submatrix must have exactly one column
const Col & Col::operator= (const subview< eT > &X)
construct a column vector from given a submatrix; the submatrix must have exactly one column
const Col & Col::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Col::Col (const subview_cube< eT > &X)
construct a column vector from given a subcube; the subcube must have exactly one column
const Col & Col::operator= (const subview_cube< eT > &X)
construct a column vector from given a subcube; the subcube must have exactly one column
const Col & Col::operator*= (const subview_cube< eT > &X)
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
Col::Col (const diagview< eT > &X)
construct a column vector from given a diagview
const Col & Col::operator= (const diagview< eT > &X)
construct a column vector from given a diagview
const Col & Col::operator*= (const diagview< eT > &X)
in-place matrix mutiplication (using a diagview on the right-hand-side)
arma_inline eT & Col::row (const u32 row_num)
creation of subview (row vector)
arma_inline eT Col::row (const u32 row_num) const
creation of subview (row vector)
arma_inline subview_col< eT > Col::rows (const u32 in_row1, const u32 in_row2)
creation of subview (submatrix comprised of specified row vectors)
arma_inline const subview_col< eT > Col::rows (const u32 in_row1, const u32 in_row2) const
creation of subview (submatrix comprised of specified row vectors)
template<typename T1 , typename op_type >
Col::Col (const Op< T1, op_type > &X)
construct a column vector from Op, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1 , typename op_type >
const Col & Col::operator= (const Op< T1, op_type > &X)
construct a column vector from Op, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1 , typename op_type >
const Col & Col::operator*= (const Op< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1 , typename eop_type >
Col::Col (const eOp< T1, eop_type > &X)
template<typename T1 , typename eop_type >
const Col & Col::operator= (const eOp< T1, eop_type > &X)
create a matrix from eOp, i.e. run the previously delayed unary operations
template<typename T1 , typename eop_type >
const Col & Col::operator*= (const eOp< T1, eop_type > &X)
template<typename T1 , typename T2 , typename glue_type >
Col::Col (const Glue< T1, T2, glue_type > &X)
construct a column vector from Glue, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1 , typename T2 , typename glue_type >
const Col & Col::operator= (const Glue< T1, T2, glue_type > &X)
construct a column vector from Glue, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1 , typename T2 , typename glue_type >
const Col & Col::operator*= (const Glue< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename eglue_type >
Col::Col (const eGlue< T1, T2, eglue_type > &X)
template<typename T1 , typename T2 , typename eglue_type >
const Col & Col::operator= (const eGlue< T1, T2, eglue_type > &X)
create a matrix from eGlue, i.e. run the previously delayed binary operations
template<typename T1 , typename T2 , typename eglue_type >
const Col & Col::operator*= (const eGlue< T1, T2, eglue_type > &X)
void Col::set_size (const u32 n_elem)
change the number of rows
void Col::set_size (const u32 n_rows, const u32 n_cols)
change the number of n_rows (this function re-implements mat::set_size() in order to check the number of columns)
template<typename eT2 >
void Col::copy_size (const Mat< eT2 > &m)
change the number of n_rows (this function re-implements mat::copy_size() in order to check the number of columns)
void Col::zeros ()
void Col::zeros (const u32 n_elem)
void Col::zeros (const u32 n_rows, const u32 n_cols)
void Col::ones ()
void Col::ones (const u32 n_elem)
void Col::ones (const u32 n_rows, const u32 n_cols)
void Col::load (const std::string name, const file_type type=auto_detect)
load a matrix from a file
void Col::load (std::istream &is, const file_type type=auto_detect)
load a matrix from a stream
row_iterator Col::begin_row (const u32 row_num)
const_row_iterator Col::begin_row (const u32 row_num) const
row_iterator Col::end_row (const u32 row_num)
const_row_iterator Col::end_row (const u32 row_num) const
Function Documentation
template<typename eT > Col< eT >::Col () [inline, inherited]
construct an empty column vector
Definition at line 24 of file Col_meat.hpp.
  : Mat<eT>()
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > Col< eT >::Col (const u32 n_elem) [inline, explicit, inherited]
construct a column vector with the specified number of n_elem
Definition at line 35 of file Col_meat.hpp.
  : Mat<eT>(in_n_elem, 1)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > Col< eT >::Col (const u32 in_rows, const u32 in_cols) [inline, inherited]
Definition at line 45 of file Col_meat.hpp.
  : Mat<eT>(in_n_rows, in_n_cols)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > Col< eT >::Col (const char * text) [inline, inherited]
construct a column vector from specified text
Definition at line 58 of file Col_meat.hpp.
References access::rw().
  : Mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > const Col< eT > & Col< eT >::operator= (const char * text) [inline, inherited]
construct a column vector from specified text
Reimplemented from Mat< eT >.
Definition at line 74 of file Col_meat.hpp.
References access::rw().
Referenced by Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(text);
  std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > Col< eT >::Col (const std::string & text) [inline, inherited]
construct a column vector from specified text
Definition at line 92 of file Col_meat.hpp.
References access::rw().
  : Mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > const Col< eT > & Col< eT >::operator= (const std::string & text) [inline, inherited]
construct a column vector from specified text
Reimplemented from Mat< eT >.
Definition at line 108 of file Col_meat.hpp.
References Col< eT >::operator=(), and access::rw().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(text);
  std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > Col< eT >::Col (const Col< eT > & X) [inline, inherited]
construct a column vector from a given column vector
Definition at line 126 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > const Col< eT > & Col< eT >::operator= (const Col< eT > & X) [inline, inherited]
construct a column vector from a given column vector
Reimplemented from Mat< eT >.
Definition at line 138 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  return *this;
  }
template<typename eT> Col< eT >::Col (const Mat< eT > & X) [inline, inherited]
construct a column vector from a given matrix; the matrix must have exactly one column
Definition at line 152 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> const Col< eT > & Col< eT >::operator= (const Mat< eT > & X) [inline, inherited]
construct a column vector from a given matrix; the matrix must have exactly one column
Definition at line 166 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Col< eT > & Col< eT >::operator*= (const Mat< eT > & X) [inline, inherited]
Definition at line 182 of file Col_meat.hpp.
Referenced by Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Col< eT >::Col (eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem = true) [inline, inherited]
construct a column vector from a given auxiliary array of eTs
Definition at line 198 of file Col_meat.hpp.
  : Mat<eT>(aux_mem, aux_n_rows, aux_n_cols, copy_aux_mem)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> Col< eT >::Col (const eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols) [inline, inherited]
construct a column vector from a given auxiliary array of eTs
Definition at line 211 of file Col_meat.hpp.
  : Mat<eT>(aux_mem, aux_n_rows, aux_n_cols)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> Col< eT >::Col (eT * aux_mem, const u32 aux_length, const bool copy_aux_mem = true) [inline, inherited]
construct a column vector from a given auxiliary array of eTs
Definition at line 224 of file Col_meat.hpp.
  : Mat<eT>(aux_mem, aux_length, 1, copy_aux_mem)
  {
  arma_extra_debug_sigprint();
//   set_size(aux_length, 1);
//
//   arma_check((Mat<eT>::n_elem != aux_length), "Col::Col(): don't know how to handle the given array");
//
//   syslib::copy_elem(Mat<eT>::memptr(), aux_mem, Mat<eT>::n_elem);
  }
template<typename eT> Col< eT >::Col (const eT * aux_mem, const u32 aux_length) [inline, inherited]
construct a column vector from a given auxiliary array of eTs
Definition at line 241 of file Col_meat.hpp.
  : Mat<eT>(aux_mem, aux_length, 1)
  {
  arma_extra_debug_sigprint();
//   set_size(aux_length, 1);
//
//   arma_check((Mat<eT>::n_elem != aux_length), "Col::Col(): don't know how to handle the given array");
//
//   syslib::copy_elem(Mat<eT>::memptr(), aux_mem, Mat<eT>::n_elem);
  }
template<typename eT > template<typename T1 , typename T2 > Col< eT >::Col (const Base< pod_type, T1 > & A, const Base< pod_type, T2 > & B) [inline, explicit, inherited]
Definition at line 259 of file Col_meat.hpp.
  : Mat<eT>(A,B)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> Col< eT >::Col (const subview< eT > & X) [inline, inherited]
construct a column vector from given a submatrix; the submatrix must have exactly one column
Definition at line 275 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> const Col< eT > & Col< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a column vector from given a submatrix; the submatrix must have exactly one column
Reimplemented from Mat< eT >.
Definition at line 289 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Col< eT > & Col< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 305 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Col< eT >::Col (const subview_cube< eT > & X) [inline, inherited]
construct a column vector from given a subcube; the subcube must have exactly one column
Definition at line 321 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> const Col< eT > & Col< eT >::operator= (const subview_cube< eT > & X) [inline, inherited]
construct a column vector from given a subcube; the subcube must have exactly one column
Reimplemented from Mat< eT >.
Definition at line 335 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Col< eT > & Col< eT >::operator*= (const subview_cube< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 351 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Col< eT >::Col (const diagview< eT > & X) [inline, inherited]
construct a column vector from given a diagview
Definition at line 367 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT> const Col< eT > & Col< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a column vector from given a diagview
Reimplemented from Mat< eT >.
Definition at line 381 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Col< eT > & Col< eT >::operator*= (const diagview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a diagview on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 397 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > arma_inline eT & Col< eT >::row (const u32 row_num) [inline, inherited]
creation of subview (row vector)
Reimplemented from Mat< eT >.
Definition at line 413 of file Col_meat.hpp.
References access::rw().
  {
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "Col::row(): out of bounds" );
  return access::rw(Mat<eT>::mem[row_num]);
  }
template<typename eT > arma_inline eT Col< eT >::row (const u32 row_num) const [inline, inherited]
creation of subview (row vector)
Reimplemented from Mat< eT >.
Definition at line 425 of file Col_meat.hpp.
  {
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "Col::row(): out of bounds" );
  return Mat<eT>::mem[row_num];
  }
template<typename eT > arma_inline subview_col< eT > Col< eT >::rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Reimplemented from Mat< eT >.
Definition at line 438 of file Col_meat.hpp.
Referenced by op_pinv::direct_pinv(), and op_princomp::direct_princomp().
  {
  arma_debug_check( ( (in_row1 > in_row2) || (in_row2 >= Mat<eT>::n_rows) ), "Col::rows(): indices out of bounds or incorrectly used");
  return subview_col<eT>(*this, 0, in_row1, in_row2);
  }
template<typename eT > arma_inline const subview_col< eT > Col< eT >::rows (const u32 in_row1, const u32 in_row2) const [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Reimplemented from Mat< eT >.
Definition at line 450 of file Col_meat.hpp.
  {
  arma_debug_check( ( (in_row1 > in_row2) || (in_row2 >= Mat<eT>::n_rows) ), "Col::rows(): indices out of bounds or incorrectly used");
  return subview_col<eT>(*this, 0, in_row1, in_row2);
  }
template<typename eT > template<typename T1 , typename op_type > Col< eT >::Col (const Op< T1, op_type > & X) [inline, inherited]
construct a column vector from Op, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Definition at line 464 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename op_type > const Col< eT > & Col< eT >::operator= (const Op< T1, op_type > & X) [inline, inherited]
construct a column vector from Op, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Reimplemented from Mat< eT >.
Definition at line 479 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col::operator=(): given matrix can't be interpreted as a column vector" );
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Col< eT > & Col< eT >::operator*= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented from Mat< eT >.
Definition at line 494 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col::operator=(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename eop_type > Col< eT >::Col (const eOp< T1, eop_type > & X) [inline, inherited]
Definition at line 510 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename eop_type > const Col< eT > & Col< eT >::operator= (const eOp< T1, eop_type > & X) [inline, inherited]
create a matrix from eOp, i.e. run the previously delayed unary operations
Reimplemented from Mat< eT >.
Definition at line 524 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col::operator=(): given matrix can't be interpreted as a column vector" );
  return *this;
  }
template<typename eT > template<typename T1 , typename eop_type > const Col< eT > & Col< eT >::operator*= (const eOp< T1, eop_type > & X) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 539 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col::operator=(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > Col< eT >::Col (const Glue< T1, T2, glue_type > & X) [inline, inherited]
construct a column vector from Glue, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Definition at line 556 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Col< eT > & Col< eT >::operator= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
construct a column vector from Glue, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Reimplemented from Mat< eT >.
Definition at line 571 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename glue_type > const Col< eT > & Col< eT >::operator*= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented from Mat< eT >.
Definition at line 588 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename eglue_type > Col< eT >::Col (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
Definition at line 604 of file Col_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename T2 , typename eglue_type > const Col< eT > & Col< eT >::operator= (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
create a matrix from eGlue, i.e. run the previously delayed binary operations
Reimplemented from Mat< eT >.
Definition at line 618 of file Col_meat.hpp.
References Col< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename T2 , typename eglue_type > const Col< eT > & Col< eT >::operator*= (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 635 of file Col_meat.hpp.
References Col< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  return *this;
  }
template<typename eT > void Col< eT >::set_size (const u32 n_elem) [inline, inherited]
change the number of rows
Definition at line 652 of file Col_meat.hpp.
Referenced by Col< eT >::copy_size(), op_princomp::direct_princomp(), auxlib::eig_sym(), Col< eT >::set_size(), svd(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::set_size(in_n_elem,1);
  }
template<typename eT > void Col< eT >::set_size (const u32 n_rows, const u32 n_cols) [inline, inherited]
change the number of n_rows (this function re-implements mat::set_size() in order to check the number of columns)
Reimplemented from Mat< eT >.
Definition at line 665 of file Col_meat.hpp.
References min(), and Col< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  // min() is used in case in_n_cols is zero
  Mat<eT>::set_size( in_n_rows, (std::min)( u32(1), in_n_cols ) );
  arma_debug_check( (in_n_cols > 1), "Col::set_size(): incompatible dimensions" );
  }
template<typename eT > template<typename eT2 > void Col< eT >::copy_size (const Mat< eT2 > & m) [inline, inherited]
change the number of n_rows (this function re-implements mat::copy_size() in order to check the number of columns)
Definition at line 682 of file Col_meat.hpp.
References min(), Mat< eT >::n_cols, Mat< eT >::n_rows, and Col< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  // min() is used in case x.n_cols is zero
  Mat<eT>::set_size( x.n_rows, (std::min)( u32(1), x.n_cols ) );
  arma_debug_check( (x.n_cols > 1), "Col::copy_size(): incompatible dimensions" );
  }
template<typename eT > void Col< eT >::zeros () [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 697 of file Col_meat.hpp.
Referenced by op_princomp::direct_princomp(), and Col< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::zeros();
  }
template<typename eT > void Col< eT >::zeros (const u32 n_elem) [inline, inherited]
Definition at line 709 of file Col_meat.hpp.
References Col< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::zeros(in_n_elem, 1);
  }
template<typename eT > void Col< eT >::zeros (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 721 of file Col_meat.hpp.
References min(), and Col< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  // min() is used in case in_n_cols is zero
  Mat<eT>::zeros( in_n_rows, (std::min)( u32(1), in_n_cols ) );
  arma_debug_check( (in_n_cols > 1), "Col::zeros(): incompatible dimensions" );
  }
template<typename eT > void Col< eT >::ones () [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 736 of file Col_meat.hpp.
Referenced by Col< eT >::ones().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::ones();
  }
template<typename eT > void Col< eT >::ones (const u32 n_elem) [inline, inherited]
Definition at line 748 of file Col_meat.hpp.
References Col< eT >::ones().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::ones(in_n_elem, 1);
  }
template<typename eT > void Col< eT >::ones (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 760 of file Col_meat.hpp.
References min(), and Col< eT >::ones().
  {
  arma_extra_debug_sigprint();
  // min() is used in case in_n_cols is zero
  Mat<eT>::ones( in_n_rows, (std::min)( u32(1), in_n_cols ) );
  arma_debug_check( (in_n_cols > 1), "Col::ones(): incompatible dimensions" );
  }
template<typename eT > void Col< eT >::load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file
Reimplemented from Mat< eT >.
Definition at line 775 of file Col_meat.hpp.
Referenced by Col< eT >::load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::load(name,type);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > void Col< eT >::load (std::istream & is, const file_type type = auto_detect) [inline, inherited]
load a matrix from a stream
Reimplemented from Mat< eT >.
Definition at line 789 of file Col_meat.hpp.
References Col< eT >::load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::load(is, type);
  arma_debug_check( (Mat<eT>::n_cols > 1), "Col(): incompatible dimensions" );
  }
template<typename eT > Col< eT >::row_iterator Col< eT >::begin_row (const u32 row_num) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 803 of file Col_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "begin_row(): index out of bounds");
  return Mat<eT>::memptr() + row_num;
  }
template<typename eT > Col< eT >::const_row_iterator Col< eT >::begin_row (const u32 row_num) const [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 817 of file Col_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "begin_row(): index out of bounds");
  return Mat<eT>::memptr() + row_num;
  }
template<typename eT > Col< eT >::row_iterator Col< eT >::end_row (const u32 row_num) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 831 of file Col_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "end_row(): index out of bounds");
  return Mat<eT>::memptr() + row_num + 1;
  }
template<typename eT > Col< eT >::const_row_iterator Col< eT >::end_row (const u32 row_num) const [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 845 of file Col_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "end_row(): index out of bounds");
  return Mat<eT>::memptr() + row_num + 1;
  }