Armadillo Technical: Op_trig
Op_trig
Classes
class op_cos
class op_acos
class op_cosh
class op_acosh
class op_sin
class op_asin
class op_sinh
class op_asinh
class op_tan
class op_atan
class op_tanh
class op_atanh
Functions
template<typename T1 >
static void op_cos::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_cos > &in)
template<typename T1 >
static void op_cos::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_cos > &in)
template<typename T1 >
static void op_acos::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_acos > &in)
template<typename T1 >
static void op_acos::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_acos > &in)
template<typename T , typename T1 >
static void op_acos::apply (Mat< std::complex< T > > &out, const Op< T1, op_acos > &in)
template<typename T , typename T1 >
static void op_acos::apply (Cube< std::complex< T > > &out, const OpCube< T1, op_acos > &in)
template<typename T1 >
static void op_cosh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_cosh > &in)
template<typename T1 >
static void op_cosh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_cosh > &in)
template<typename T1 >
static void op_acosh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_acosh > &in)
template<typename T1 >
static void op_acosh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_acosh > &in)
template<typename T1 >
static void op_sin::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_sin > &in)
template<typename T1 >
static void op_sin::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_sin > &in)
template<typename T1 >
static void op_asin::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_asin > &in)
template<typename T1 >
static void op_asin::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_asin > &in)
template<typename T , typename T1 >
static void op_asin::apply (Mat< std::complex< T > > &out, const Op< T1, op_asin > &in)
template<typename T , typename T1 >
static void op_asin::apply (Cube< std::complex< T > > &out, const OpCube< T1, op_asin > &in)
template<typename T1 >
static void op_sinh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_sinh > &in)
template<typename T1 >
static void op_sinh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_sinh > &in)
template<typename T1 >
static void op_asinh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_asinh > &in)
template<typename T1 >
static void op_asinh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_asinh > &in)
template<typename T1 >
static void op_tan::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_tan > &in)
template<typename T1 >
static void op_tan::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_tan > &in)
template<typename T1 >
static void op_atan::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_atan > &in)
template<typename T1 >
static void op_atan::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_atan > &in)
template<typename T , typename T1 >
static void op_atan::apply (Mat< std::complex< T > > &out, const Op< T1, op_atan > &in)
template<typename T , typename T1 >
static void op_atan::apply (Cube< std::complex< T > > &out, const OpCube< T1, op_atan > &in)
template<typename T1 >
static void op_tanh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_tanh > &in)
template<typename T1 >
static void op_tanh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_tanh > &in)
template<typename T1 >
static void op_atanh::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_atanh > &in)
template<typename T1 >
static void op_atanh::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_atanh > &in)
Function Documentation
template<typename T1 > void op_cos::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_cos > & in) [inline, static, inherited]
Definition at line 32 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), cos(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::cos(A.mem[i]);
    }
  }
template<typename T1 > void op_cos::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_cos > & in) [inline, static, inherited]
Definition at line 60 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), cos(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::cos(A.mem[i]);
    }
  }
template<typename T1 > void op_acos::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_acos > & in) [inline, static, inherited]
Definition at line 88 of file op_trig_meat.hpp.
References acos(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::acos(A.mem[i]);
    }
  }
template<typename T1 > void op_acos::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_acos > & in) [inline, static, inherited]
Definition at line 116 of file op_trig_meat.hpp.
References acos(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::acos(A.mem[i]);
    }
  }
template<typename T , typename T1 > void op_acos::apply (Mat< std::complex< T > > & out, const Op< T1, op_acos > & in) [inline, static, inherited]
Definition at line 144 of file op_trig_meat.hpp.
References acos(), arma_stop(), Op< T1, op_type >::m, Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::acos(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("acos(): need Boost libraries");
    }
  #endif
  }
template<typename T , typename T1 > void op_acos::apply (Cube< std::complex< T > > & out, const OpCube< T1, op_acos > & in) [inline, static, inherited]
Definition at line 180 of file op_trig_meat.hpp.
References acos(), arma_stop(), OpCube< T1, op_type >::m, Cube< eT >::mem, and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem  = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::acos(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("acos(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_cosh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_cosh > & in) [inline, static, inherited]
Definition at line 216 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), cosh(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::cosh(A.mem[i]);
    }
  }
template<typename T1 > void op_cosh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_cosh > & in) [inline, static, inherited]
Definition at line 244 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), cosh(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::cosh(A.mem[i]);
    }
  }
template<typename T1 > void op_acosh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_acosh > & in) [inline, static, inherited]
Definition at line 272 of file op_trig_meat.hpp.
References acosh(), arma_stop(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::acosh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("acosh(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_acosh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_acosh > & in) [inline, static, inherited]
Definition at line 308 of file op_trig_meat.hpp.
References acosh(), arma_stop(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem  = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::acosh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("acosh(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_sin::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_sin > & in) [inline, static, inherited]
Definition at line 346 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_elem, and sin().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::sin(A.mem[i]);
    }
  }
template<typename T1 > void op_sin::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_sin > & in) [inline, static, inherited]
Definition at line 374 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), Cube< eT >::n_elem, and sin().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::sin(A.mem[i]);
    }
  }
template<typename T1 > void op_asin::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_asin > & in) [inline, static, inherited]
Definition at line 402 of file op_trig_meat.hpp.
References asin(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::asin(A.mem[i]);
    }
  }
template<typename T1 > void op_asin::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_asin > & in) [inline, static, inherited]
Definition at line 430 of file op_trig_meat.hpp.
References asin(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::asin(A.mem[i]);
    }
  }
template<typename T , typename T1 > void op_asin::apply (Mat< std::complex< T > > & out, const Op< T1, op_asin > & in) [inline, static, inherited]
Definition at line 458 of file op_trig_meat.hpp.
References arma_stop(), asin(), Op< T1, op_type >::m, Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::asin(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("asin(): need Boost libraries");
    }
  #endif
  }
template<typename T , typename T1 > void op_asin::apply (Cube< std::complex< T > > & out, const OpCube< T1, op_asin > & in) [inline, static, inherited]
Definition at line 494 of file op_trig_meat.hpp.
References arma_stop(), asin(), OpCube< T1, op_type >::m, Cube< eT >::mem, and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem  = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::asin(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("asin(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_sinh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_sinh > & in) [inline, static, inherited]
Definition at line 530 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_elem, and sinh().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::sinh(A.mem[i]);
    }
  }
template<typename T1 > void op_sinh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_sinh > & in) [inline, static, inherited]
Definition at line 558 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), Cube< eT >::n_elem, and sinh().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::sinh(A.mem[i]);
    }
  }
template<typename T1 > void op_asinh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_asinh > & in) [inline, static, inherited]
Definition at line 586 of file op_trig_meat.hpp.
References arma_stop(), asinh(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::asinh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("asinh(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_asinh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_asinh > & in) [inline, static, inherited]
Definition at line 621 of file op_trig_meat.hpp.
References arma_stop(), asinh(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::asinh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("asinh(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_tan::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_tan > & in) [inline, static, inherited]
Definition at line 658 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_elem, and tan().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::tan(A.mem[i]);
    }
  }
template<typename T1 > void op_tan::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_tan > & in) [inline, static, inherited]
Definition at line 686 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), Cube< eT >::n_elem, and tan().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::tan(A.mem[i]);
    }
  }
template<typename T1 > void op_atan::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_atan > & in) [inline, static, inherited]
Definition at line 714 of file op_trig_meat.hpp.
References atan(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::atan(A.mem[i]);
    }
  }
template<typename T1 > void op_atan::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_atan > & in) [inline, static, inherited]
Definition at line 742 of file op_trig_meat.hpp.
References atan(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::atan(A.mem[i]);
    }
  }
template<typename T , typename T1 > void op_atan::apply (Mat< std::complex< T > > & out, const Op< T1, op_atan > & in) [inline, static, inherited]
Definition at line 770 of file op_trig_meat.hpp.
References arma_stop(), atan(), Op< T1, op_type >::m, Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::atan(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("atan(): need Boost libraries");
    }
  #endif
  }
template<typename T , typename T1 > void op_atan::apply (Cube< std::complex< T > > & out, const OpCube< T1, op_atan > & in) [inline, static, inherited]
Definition at line 806 of file op_trig_meat.hpp.
References arma_stop(), atan(), OpCube< T1, op_type >::m, Cube< eT >::mem, and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename std::complex<T> eT;
    isnt_same_type<eT, typename T1::elem_type>::check();
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem  = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::atan(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("atan(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_tanh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_tanh > & in) [inline, static, inherited]
Definition at line 842 of file op_trig_meat.hpp.
References Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), Mat< eT >::n_elem, and tanh().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const Mat<eT>& A = tmp.M;
  const u32 n_elem = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::tanh(A.mem[i]);
    }
  }
template<typename T1 > void op_tanh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_tanh > & in) [inline, static, inherited]
Definition at line 870 of file op_trig_meat.hpp.
References Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), Cube< eT >::n_elem, and tanh().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube<T1> tmp(in.m);
  const Cube<eT>& A = tmp.M;
  const u32 n_elem  = A.n_elem;
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
  eT* out_ptr = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_ptr[i] = std::tanh(A.mem[i]);
    }
  }
template<typename T1 > void op_atanh::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_atanh > & in) [inline, static, inherited]
Definition at line 898 of file op_trig_meat.hpp.
References arma_stop(), atanh(), Mat< eT >::copy_size(), Op< T1, op_type >::m, Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap<T1> tmp(in.m);
    const Mat<eT>& A = tmp.M;
    const u32 n_elem = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::atanh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("atanh(): need Boost libraries");
    }
  #endif
  }
template<typename T1 > void op_atanh::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_atanh > & in) [inline, static, inherited]
Definition at line 934 of file op_trig_meat.hpp.
References arma_stop(), atanh(), Cube< eT >::copy_size(), OpCube< T1, op_type >::m, Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  #if defined(ARMA_USE_BOOST)
    {
    typedef typename T1::elem_type eT;
    const unwrap_cube<T1> tmp(in.m);
    const Cube<eT>& A = tmp.M;
    const u32 n_elem  = A.n_elem;
    //out.set_size(A.n_rows, A.n_cols, A.n_slices);
    out.copy_size(A);
    eT* out_ptr = out.memptr();
    for(u32 i=0; i<n_elem; ++i)
      {
      out_ptr[i] = boost::math::atanh(A.mem[i]);
      }
    }
  #else
    {
    arma_stop("atanh(): need Boost libraries");
    }
  #endif
  }