Armadillo Technical: Debug
Debug
Namespaces
namespace junk
Functions
template<typename T1 >
void arma_stop (const T1 &x)
print a message to std::cout and/or throw a run-time error exception
void arma_print ()
template<typename T1 >
void arma_print (const T1 &x)
template<typename T1 , typename T2 >
void arma_print (const T1 &x, const T2 &y)
template<typename T1 >
void arma_print (const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_print (const arma_boost::basic_format< T1, T2 > &x)
void arma_sigprint (const char *x)
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
void arma_bktprint ()
template<typename T1 >
void arma_bktprint (const T1 &x)
template<typename T1 , typename T2 >
void arma_bktprint (const T1 &x, const T2 &y)
template<typename T1 >
void arma_bktprint (const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_bktprint (const arma_boost::basic_format< T1, T2 > &x)
void arma_thisprint (void *this_ptr)
template<typename T1 >
void arma_hot arma_warn (const bool state, const T1 &x)
if state is true, print a message on cout
template<typename T1 , typename T2 >
void arma_hot arma_warn (const bool state, const T1 &x, const T2 &y)
template<typename T1 >
void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > &x)
template<typename T1 >
void arma_hot arma_check (const bool state, const T1 &x)
if state is true, abort program
template<typename T1 , typename T2 >
void arma_hot arma_check (const bool state, const T1 &x, const T2 &y)
template<typename T1 >
void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1 , typename T2 >
void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1, T2 > &x)
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const Mat< eT2 > &B, const char *x)
stop if given matrices have different sizes
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Proxy< eT1 > &A, const Proxy< eT2 > &B, const char *x)
stop if given proxies have different sizes
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const Proxy< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Proxy< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Proxy< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview< eT1 > &A, const Proxy< eT2 > &B, const char *x)
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char *x)
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const Cube< eT2 > &B, const char *x)
stop if given cubes have different sizes
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const Cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const ProxyCube< eT1 > &A, const ProxyCube< eT2 > &B, const char *x)
stop if given cube proxies have different sizes
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Cube< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const Cube< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const subview_cube< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_same_size (const Mat< eT1 > &A, const subview_cube< eT2 > &B, const char *x)
void arma_hot arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const Mat< eT1 > &A, const Mat< eT2 > &B, const char *x)
stop if given matrices are incompatible for multiplication
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const Mat< eT1 > &A, const Mat< eT2 > &B, const bool do_trans_A, const bool do_trans_B, const char *x)
stop if given matrices are incompatible for multiplication
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const Mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const subview< eT1 > &A, const Mat< eT2 > &B, const char *x)
template<typename eT1 , typename eT2 >
void arma_hot arma_assert_mul_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
Function Documentation
template<typename T1 > void arma_stop (const T1 & x) [inline]
print a message to std::cout and/or throw a run-time error exception
Definition at line 28 of file debug.hpp.
Referenced by eglue_cube_core< eglue_type >::apply(), eglue_cube_core< eglue_type >::apply_inplace_div(), eglue_core< eglue_type >::apply_inplace_div(), eglue_cube_core< eglue_type >::apply_inplace_minus(), eglue_core< eglue_type >::apply_inplace_minus(), eglue_cube_core< eglue_type >::apply_inplace_plus(), eglue_core< eglue_type >::apply_inplace_plus(), eglue_cube_core< eglue_type >::apply_inplace_schur(), eglue_core< eglue_type >::apply_inplace_schur(), eglue_core< eglue_type >::apply_proxy(), eglue_core< eglue_type >::apply_unwrap(), arma_assert_mul_size(), arma_assert_same_size(), arma_check(), auxlib::chol(), auxlib::det(), eig_gen(), auxlib::eig_gen(), auxlib::eig_sym(), eglue_cube_core< eglue_type >::get_elem(), eglue_core< eglue_type >::get_elem(), auxlib::inv_inplace(), auxlib::inv_noalias(), Mat< eT >::load(), field_aux::load(), Cube< eT >::load(), auxlib::log_det(), auxlib::lu(), eop_cube_core< eop_cube_type >::process(), eop_core< eop_type >::process(), auxlib::qr(), Mat< eT >::save(), field_aux::save(), Cube< eT >::save(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), wall_clock::tic(), and wall_clock::toc().
  {
  std::cerr.flush();
  std::cout.flush();
  std::cout << '\n';
  std::cout << "run-time error: " << x << '\n';
  std::cout << '\n';
  std::cout.flush();
  throw std::runtime_error("");
  }
void arma_print () [inline]
Definition at line 49 of file debug.hpp.
Referenced by arma_warn(), chol(), op_princomp::direct_princomp(), op_princomp_cov::direct_princomp_cov(), field_aux::load(), diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), diskio::load_ppm_binary(), diskio::load_raw_ascii(), diskio::load_std_string(), qr(), rank(), field_aux::save(), diskio::save_arma_binary(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), diskio::save_std_string(), solve(), and svd().
  {
  std::cout << std::endl;
  }
template<typename T1 > void arma_print (const T1 & x) [inline]
Definition at line 58 of file debug.hpp.
  {
  std::cout << x << std::endl;
  }
template<typename T1 , typename T2 > void arma_print (const T1 & x, const T2 & y) [inline]
Definition at line 68 of file debug.hpp.
  {
  std::cout << x << y << std::endl;
  }
template<typename T1 > void arma_print (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 79 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
template<typename T1 , typename T2 > void arma_print (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 87 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
void arma_sigprint (const char * x) [inline]
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
Definition at line 103 of file debug.hpp.
  {
  std::cout << "@ " << x;
  }
void arma_bktprint () [inline]
Definition at line 116 of file debug.hpp.
  {
  std::cout << std::endl;
  }
template<typename T1 > void arma_bktprint (const T1 & x) [inline]
Definition at line 125 of file debug.hpp.
  {
  std::cout << " [" << x << ']' << std::endl;
  }
template<typename T1 , typename T2 > void arma_bktprint (const T1 & x, const T2 & y) [inline]
Definition at line 135 of file debug.hpp.
  {
  std::cout << " [" << x << y << ']' << std::endl;
  }
template<typename T1 > void arma_bktprint (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 146 of file debug.hpp.
    {
    std::cout << " [" << x << ']' << std::endl;
    }
template<typename T1 , typename T2 > void arma_bktprint (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 154 of file debug.hpp.
    {
    std::cout << " [" << x << ']' << std::endl;
    }
void arma_thisprint (void * this_ptr) [inline]
Definition at line 168 of file debug.hpp.
  {
  std::cout << " [this = " << this_ptr << ']' << std::endl;
  }
template<typename T1 > void arma_hot arma_warn (const bool state, const T1 & x) [inline]
if state is true, print a message on cout
Definition at line 183 of file debug.hpp.
References arma_print().
Referenced by op_inv::apply(), det(), linspace(), diskio::safe_rename(), diskio::save_arma_ascii(), diskio::save_arma_binary(), diskio::save_pgm_binary(), diskio::save_ppm_binary(), diskio::save_raw_ascii(), and diskio::save_std_string().
  {
  if(state==true)
    {
    arma_print(x);
    }
  }
template<typename T1 , typename T2 > void arma_hot arma_warn (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 196 of file debug.hpp.
References arma_print().
  {
  if(state==true)
    {
    arma_print(x,y);
    }
  }
template<typename T1 > void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 210 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1 , typename T2 > void arma_hot arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 220 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1 > void arma_hot arma_check (const bool state, const T1 & x) [inline]
if state is true, abort program
Definition at line 237 of file debug.hpp.
References arma_stop().
Referenced by subview< eT >::at(), subview_field< oT >::at(), subview_cube< eT >::at(), subview< eT >::colptr(), Cube< eT >::create_mat(), diagview< eT >::fill(), Mat< eT >::init(), field< oT >::init(), Cube< eT >::init(), diagview< eT >::ones(), subview< eT >::operator()(), subview_field< oT >::operator()(), subview_cube< eT >::operator()(), running_stat_vec< eT >::operator()(), running_stat< eT >::operator()(), diagview< eT >::operator()(), diagview< eT >::operator=(), subview< eT >::operator[](), subview_field< oT >::operator[](), subview_cube< eT >::operator[](), subview_cube< eT >::slice_colptr(), and diagview< eT >::zeros().
  {
  if(state==true)
    {
    arma_stop(x);
    }
  }
template<typename T1 , typename T2 > void arma_hot arma_check (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 250 of file debug.hpp.
References arma_stop().
  {
  if(state==true)
    {
    arma_stop( std::string(x) + std::string(y) );
    }
  }
template<typename T1 > void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 264 of file debug.hpp.
References arma_stop(), and arma_boost::str().
    {
    if(state==true)
      {
      arma_stop(str(x));
      }
    }
template<typename T1 , typename T2 > void arma_hot arma_check (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 276 of file debug.hpp.
References arma_stop(), and arma_boost::str().
    {
    if(state==true)
      {
      arma_stop(str(x));
      }
    }
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 294 of file debug.hpp.
Referenced by arma_assert_mul_size(), and arma_assert_same_size().
  {
  std::stringstream tmp;
  tmp << x << ": incompatible matrix dimensions: (" << A_n_rows << ',' << A_n_cols << ") and (" << B_n_rows << ',' << B_n_cols << ')';
  return tmp.str();
  }
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 308 of file debug.hpp.
References arma_incompat_size_string(), and arma_stop().
Referenced by eglue_cube_core< eglue_type >::apply_inplace_div(), eglue_core< eglue_type >::apply_inplace_div(), eglue_cube_core< eglue_type >::apply_inplace_minus(), eglue_core< eglue_type >::apply_inplace_minus(), glue_times::apply_inplace_plus(), eglue_cube_core< eglue_type >::apply_inplace_plus(), eglue_core< eglue_type >::apply_inplace_plus(), eglue_cube_core< eglue_type >::apply_inplace_schur(), eglue_core< eglue_type >::apply_inplace_schur(), Cube< eT >::Cube(), eGlue< T1, T2, eglue_type >::eGlue(), eGlueCube< T1, T2, eglue_type >::eGlueCube(), and Mat< eT >::Mat().
  {
  if( (A_n_rows != B_n_rows) || (A_n_cols != B_n_cols) )
    {
    arma_stop( arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
stop if given matrices have different sizes
Definition at line 323 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Proxy< eT1 > & A, const Proxy< eT2 > & B, const char * x) [inline]
stop if given proxies have different sizes
Definition at line 338 of file debug.hpp.
References arma_incompat_size_string(), and arma_stop().
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 352 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 366 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, Mat< eT >::n_cols, subview< eT >::n_rows, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 380 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, subview< eT >::n_cols, Mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const Proxy< eT2 > & B, const char * x) [inline]
Definition at line 394 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop ( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Proxy< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 408 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Proxy< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 422 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview< eT1 > & A, const Proxy< eT2 > & B, const char * x) [inline]
Definition at line 436 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char * x) [inline]
Definition at line 453 of file debug.hpp.
  {
  std::stringstream tmp;
  tmp << x << ": incompatible cube dimensions: (" << A_n_rows << ',' << A_n_cols << ',' << A_n_slices << ") and (" << B_n_rows << ',' << B_n_cols << ',' << B_n_slices << ')';
  return tmp.str();
  }
void arma_hot arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 A_n_slices, const u32 B_n_rows, const u32 B_n_cols, const u32 B_n_slices, const char * x) [inline]
Definition at line 467 of file debug.hpp.
References arma_incompat_size_string(), and arma_stop().
  {
  if( (A_n_rows != B_n_rows) || (A_n_cols != B_n_cols) || (A_n_slices != B_n_slices) )
    {
    arma_stop( arma_incompat_size_string(A_n_rows, A_n_cols, A_n_slices, B_n_rows, B_n_cols, B_n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
stop if given cubes have different sizes
Definition at line 482 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Cube< eT >::n_cols, Cube< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 496 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview_cube< eT >::n_cols, Cube< eT >::n_cols, subview_cube< eT >::n_rows, Cube< eT >::n_rows, subview_cube< eT >::n_slices, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
Definition at line 510 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Cube< eT >::n_cols, subview_cube< eT >::n_cols, Cube< eT >::n_rows, subview_cube< eT >::n_rows, Cube< eT >::n_slices, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 524 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview_cube< eT >::n_cols, subview_cube< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices))
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const ProxyCube< eT1 > & A, const ProxyCube< eT2 > & B, const char * x) [inline]
stop if given cube proxies have different sizes
Definition at line 539 of file debug.hpp.
References arma_incompat_size_string(), and arma_stop().
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != B.n_slices))
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Cube< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 558 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, Cube< eT >::n_cols, Mat< eT >::n_rows, Cube< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != 1) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, 1, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const Cube< eT2 > & B, const char * x) [inline]
Definition at line 572 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Cube< eT >::n_cols, Mat< eT >::n_cols, Cube< eT >::n_rows, Mat< eT >::n_rows, and Cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (1 != B.n_slices) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, 1, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const subview_cube< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 586 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, subview_cube< eT >::n_cols, Mat< eT >::n_rows, subview_cube< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (A.n_slices != 1) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, A.n_slices, B.n_rows, B.n_cols, 1, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_same_size (const Mat< eT1 > & A, const subview_cube< eT2 > & B, const char * x) [inline]
Definition at line 600 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview_cube< eT >::n_cols, Mat< eT >::n_cols, subview_cube< eT >::n_rows, Mat< eT >::n_rows, and subview_cube< eT >::n_slices.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) || (1 != B.n_slices) )
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, 1, B.n_rows, B.n_cols, B.n_slices, x) );
    }
  }
void arma_hot arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 618 of file debug.hpp.
References arma_incompat_size_string(), and arma_stop().
  {
  if(A_n_cols != B_n_rows)
    {
    arma_stop( arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const Mat< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
stop if given matrices are incompatible for multiplication
Definition at line 633 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const Mat< eT1 > & A, const Mat< eT2 > & B, const bool do_trans_A, const bool do_trans_B, const char * x) [inline]
stop if given matrices are incompatible for multiplication
Definition at line 648 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  const u32 final_A_n_cols = (do_trans_A == false) ? A.n_cols : A.n_rows;
  const u32 final_B_n_rows = (do_trans_B == false) ? B.n_rows : B.n_cols;
  if(final_A_n_cols != final_B_n_rows)
    {
    const u32 final_A_n_rows = (do_trans_A == false) ? A.n_rows : A.n_cols;
    const u32 final_B_n_cols = (do_trans_B == false) ? B.n_cols : B.n_rows;
    arma_stop( arma_incompat_size_string(final_A_n_rows, final_A_n_cols, final_B_n_rows, final_B_n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const Mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 668 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, Mat< eT >::n_cols, Mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const subview< eT1 > & A, const Mat< eT2 > & B, const char * x) [inline]
Definition at line 682 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), Mat< eT >::n_cols, subview< eT >::n_cols, subview< eT >::n_rows, and Mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }
template<typename eT1 , typename eT2 > void arma_hot arma_assert_mul_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 696 of file debug.hpp.
References arma_incompat_size_string(), arma_stop(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    arma_stop( arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x) );
    }
  }