Armadillo Technical: Fn_chol
Fn_chol
Functions
template<typename T1 >
bool chol (Mat< typename T1::elem_type > &out, const Base< typename T1::elem_type, T1 > &X)
template<typename T1 >
Mat< typename T1::elem_type > chol (const Base< typename T1::elem_type, T1 > &X)
Function Documentation
template<typename T1 > bool chol (Mat< typename T1::elem_type > & out, const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 25 of file fn_chol.hpp.
References auxlib::chol(), and Base< elem_type, derived >::get_ref().
Referenced by chol().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_check<T1> tmp(X.get_ref(), out);
  const Mat<eT>&     A = tmp.M;
  arma_debug_check( (A.is_square() == false), "chol(): given matrix is not square");
  return auxlib::chol(out, A);
  }
template<typename T1 > Mat<typename T1::elem_type> chol (const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 44 of file fn_chol.hpp.
References arma_print(), and chol().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  Mat<eT> out;
  const bool ok = chol(out, X);
  if(ok == false)
    {
    arma_print("chol(): matrix factorisation failed");
    }
  return out;
  }