Armadillo Technical: Operator_cube_schur
Operator_cube_schur
Functions
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< typename T1::elem_type, T1 > &X, const BaseCube< typename T1::elem_type, T2 > &Y)
Base % Base.
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Cube< typename
promote_type< eT1, eT2 >
::result > operator% (const BaseCube< eT1, T1 > &X, const BaseCube< eT2, T2 > &Y)
Base % Base.
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< std::complex< double >, T1 > &X, const BaseCube< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< std::complex< float >, T1 > &X, const BaseCube< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< double, T1 > &X, const BaseCube< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< float, T1 > &X, const BaseCube< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< s32, T1 > &X, const BaseCube< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< u32, T1 > &X, const BaseCube< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< s16, T1 > &X, const BaseCube< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< u16, T1 > &X, const BaseCube< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< s8, T1 > &X, const BaseCube< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_schur > operator% (const BaseCube< u8, T1 > &X, const BaseCube< u8, T2 > &Y)
Function Documentation
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< typename T1::elem_type, T1 > & X, const BaseCube< typename T1::elem_type, T2 > & Y) [inline]
Base % Base.
Definition at line 28 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Cube<typename promote_type<eT1,eT2>::result> operator% (const BaseCube< eT1, T1 > & X, const BaseCube< eT2, T2 > & Y) [inline]
Base % Base.
Definition at line 48 of file operator_cube_schur.hpp.
References glue_cube_schur::apply_mixed(), promote_type< T1, T2 >::check(), and BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap_cube<T1> tmp1(X.get_ref());
  const unwrap_cube<T2> tmp2(Y.get_ref());
  const Cube<eT1>& A = tmp1.M;
  const Cube<eT2>& B = tmp2.M;
  Cube< typename promote_type<eT1,eT2>::result > out;
  glue_cube_schur::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< std::complex< double >, T1 > & X, const BaseCube< std::complex< double >, T2 > & Y) [inline]
Definition at line 78 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< std::complex< float >, T1 > & X, const BaseCube< std::complex< float >, T2 > & Y) [inline]
Definition at line 91 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< double, T1 > & X, const BaseCube< double, T2 > & Y) [inline]
Definition at line 104 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< float, T1 > & X, const BaseCube< float, T2 > & Y) [inline]
Definition at line 117 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< s32, T1 > & X, const BaseCube< s32, T2 > & Y) [inline]
Definition at line 130 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< u32, T1 > & X, const BaseCube< u32, T2 > & Y) [inline]
Definition at line 143 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< s16, T1 > & X, const BaseCube< s16, T2 > & Y) [inline]
Definition at line 156 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< u16, T1 > & X, const BaseCube< u16, T2 > & Y) [inline]
Definition at line 169 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< s8, T1 > & X, const BaseCube< s8, T2 > & Y) [inline]
Definition at line 182 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_schur> operator% (const BaseCube< u8, T1 > & X, const BaseCube< u8, T2 > & Y) [inline]
Definition at line 195 of file operator_cube_schur.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_schur>(X.get_ref(), Y.get_ref());
  }