Armadillo Technical: Fn_trig
Fn_trig
Functions
template<typename T1 >
arma_inline const eOp< T1,
eop_cos > cos (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_cos > cos (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_acos > acos (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_acos > acos (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_cosh > cosh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_cosh > cosh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_acosh > acosh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_acosh > acosh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_sin > sin (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_sin > sin (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_asin > asin (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_asin > asin (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_sinh > sinh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_sinh > sinh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_asinh > asinh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_asinh > asinh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_tan > tan (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_tan > tan (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_atan > atan (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_atan > atan (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_tanh > tanh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_tanh > tanh (const BaseCube< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOp< T1,
eop_atanh > atanh (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_atanh > atanh (const BaseCube< typename T1::elem_type, T1 > &A)
Function Documentation
template<typename T1 > arma_inline const eOp<T1, eop_cos> cos (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 33 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_cos>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_cos> cos (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 45 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_cos>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_acos> acos (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 60 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_acos>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_acos> acos (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 72 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_acos>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_cosh> cosh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 87 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_cosh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_cosh> cosh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 99 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_cosh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_acosh> acosh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 114 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_acosh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_acosh> acosh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 126 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_acosh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_sin> sin (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 141 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_sin>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_sin> sin (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 153 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_sin>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_asin> asin (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 168 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_asin>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_asin> asin (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 180 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_asin>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_sinh> sinh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 195 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_sinh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_sinh> sinh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 207 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_sinh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_asinh> asinh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 222 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_asinh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_asinh> asinh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 234 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_asinh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_tan> tan (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 249 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_tan>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_tan> tan (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 261 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_tan>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_atan> atan (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 276 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_atan>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_atan> atan (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 288 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_atan>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_tanh> tanh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 303 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_tanh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_tanh> tanh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 315 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_tanh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOp<T1, eop_atanh> atanh (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 330 of file fn_trig.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_atanh>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_atanh> atanh (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 342 of file fn_trig.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_atanh>(A.get_ref());
  }