Armadillo Technical: Operator_cube_div
Operator_cube_div
Functions
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_div_post > operator/ (const BaseCube< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base / scalar.
template<typename eT >
arma_inline Cube< eT > operator/ (const OpCube< Cube< eT >, op_ones_full > &X, const eT k)
OpCube<mat,op_ones_full> / scalar.
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_div_pre > operator/ (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > &X)
scalar / Base
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Cube< typename
promote_type< eT1, eT2 >
::result > operator/ (const BaseCube< eT1, T1 > &X, const BaseCube< eT2, T2 > &Y)
Base / Base.
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< std::complex< double >, T1 > &X, const BaseCube< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< std::complex< float >, T1 > &X, const BaseCube< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< double, T1 > &X, const BaseCube< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< float, T1 > &X, const BaseCube< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< s32, T1 > &X, const BaseCube< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< u32, T1 > &X, const BaseCube< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< s16, T1 > &X, const BaseCube< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< u16, T1 > &X, const BaseCube< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< s8, T1 > &X, const BaseCube< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_div > operator/ (const BaseCube< u8, T1 > &X, const BaseCube< u8, T2 > &Y)
Function Documentation
template<typename T1 > arma_inline const OpCube<T1, op_scalar_div_post> operator/ (const BaseCube< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base / scalar.
Definition at line 26 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_div_post>(X.get_ref(), k);
  }
template<typename eT > arma_inline Cube<eT> operator/ (const OpCube< Cube< eT >, op_ones_full > & X, const eT k) [inline]
OpCube<mat,op_ones_full> / scalar.
Definition at line 40 of file operator_cube_div.hpp.
References OpCube< T1, op_type >::aux_u32_a, OpCube< T1, op_type >::aux_u32_b, OpCube< T1, op_type >::aux_u32_c, and Cube< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Cube<eT> tmp(X.aux_u32_a, X.aux_u32_b, X.aux_u32_c);
  tmp.fill( eT(1)/k );
  return tmp;
  }
template<typename T1 > arma_inline const OpCube<T1, op_scalar_div_pre> operator/ (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > & X) [inline]
scalar / Base
Definition at line 57 of file operator_cube_div.hpp.
References BaseCube< T1::elem_type, OpCube< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_div_pre>(X.get_ref(), k);
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Cube<typename promote_type<eT1,eT2>::result> operator/ (const BaseCube< eT1, T1 > & X, const BaseCube< eT2, T2 > & Y) [inline]
Base / Base.
Definition at line 77 of file operator_cube_div.hpp.
References glue_cube_div::apply_mixed(), promote_type< T1, T2 >::check(), and BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap_cube<T1> tmp1(X.get_ref());
  const unwrap_cube<T2> tmp2(Y.get_ref());
  const Cube<eT1>& A = tmp1.M;
  const Cube<eT2>& B = tmp2.M;
  Cube< typename promote_type<eT1,eT2>::result > out;
  glue_cube_div::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< std::complex< double >, T1 > & X, const BaseCube< std::complex< double >, T2 > & Y) [inline]
Definition at line 107 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< std::complex< float >, T1 > & X, const BaseCube< std::complex< float >, T2 > & Y) [inline]
Definition at line 120 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< double, T1 > & X, const BaseCube< double, T2 > & Y) [inline]
Definition at line 133 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< float, T1 > & X, const BaseCube< float, T2 > & Y) [inline]
Definition at line 146 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< s32, T1 > & X, const BaseCube< s32, T2 > & Y) [inline]
Definition at line 159 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< u32, T1 > & X, const BaseCube< u32, T2 > & Y) [inline]
Definition at line 172 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< s16, T1 > & X, const BaseCube< s16, T2 > & Y) [inline]
Definition at line 185 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< u16, T1 > & X, const BaseCube< u16, T2 > & Y) [inline]
Definition at line 198 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< s8, T1 > & X, const BaseCube< s8, T2 > & Y) [inline]
Definition at line 211 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_div> operator/ (const BaseCube< u8, T1 > & X, const BaseCube< u8, T2 > & Y) [inline]
Definition at line 224 of file operator_cube_div.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_div>(X.get_ref(), Y.get_ref());
  }