Armadillo Technical: Op_scalar_misc
Op_scalar_misc
Classes
class op_scalar_plus
'add scalar to a matrix/cube' operation
class op_scalar_minus_pre
'subtract matrix/cube from a scalar' operation
class op_scalar_minus_post
'subtract scalar from a matrix/cube' operation
class op_scalar_times
'multiply matrix/cube by a scalar' operation
class op_scalar_div_pre
'divide scalar by a matrix/cube' operation
class op_scalar_div_post
'divide matrix/cube by a scalar' operation
Functions
template<typename T1 >
static void op_scalar_plus::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_plus > &in)
Add a scalar to all elements of a matrix.
template<typename T1 >
static void op_scalar_plus::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_plus > &in)
Add a scalar to all elements of a cube.
template<typename T1 >
static void op_scalar_minus_pre::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_minus_pre > &in)
For each element of a matrix, subtract it from a scalar.
template<typename T1 >
static void op_scalar_minus_pre::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_minus_pre > &in)
For each element of a cube, subtract it from a scalar.
template<typename T1 >
static void op_scalar_minus_post::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_minus_post > &in)
subtract a scalar from each element of a matrix
template<typename T1 >
static void op_scalar_minus_post::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_minus_post > &in)
subtract a scalar from each element of a cube
template<typename T1 >
static void op_scalar_times::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_times > &in)
Multiply all elements of a matrix by a scalar.
template<typename T1 >
static void op_scalar_times::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_times > &in)
Multiply all elements of a cube by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_plus >, op_scalar_times > &in)
Evaluate A + B, and then multiply each element of the result by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_times > &in)
Evaluate A + B, and then multiply each element of the result by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_minus >, op_scalar_times > &in)
Evaluate A - B, and then multiply each element of the result by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_times > &in)
Evaluate A - B, and then multiply each element of the result by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_schur >, op_scalar_times > &in)
Evaluate A % B (where % is the element-wise multiply operation) and then multiply each element of the result by a scalar.
template<typename T1 , typename T2 >
static void op_scalar_times::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_times > &in)
Evaluate A % B (where % is the element-wise multiply operation) and then multiply each element of the result by a scalar.
template<typename T1 >
static void op_scalar_div_pre::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_div_pre > &in)
template<typename T1 >
static void op_scalar_div_pre::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_plus >, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_minus >, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_schur >, op_scalar_div_pre > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_pre::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_div_pre > &in)
template<typename T1 >
static void op_scalar_div_post::apply (Mat< typename T1::elem_type > &out, const Op< T1, op_scalar_div_post > &in)
template<typename T1 >
static void op_scalar_div_post::apply (Cube< typename T1::elem_type > &out, const OpCube< T1, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_plus >, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_minus >, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Mat< typename T1::elem_type > &out, const Op< Glue< T1, T2, glue_schur >, op_scalar_div_post > &in)
template<typename T1 , typename T2 >
static void op_scalar_div_post::apply (Cube< typename T1::elem_type > &out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_div_post > &in)
Function Documentation
template<typename T1 > void op_scalar_plus::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_plus > & in) [inline, static, inherited]
Add a scalar to all elements of a matrix.
Definition at line 26 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] + k;
    }
  }
template<typename T1 > void op_scalar_plus::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_plus > & in) [inline, static, inherited]
Add a scalar to all elements of a cube.
Definition at line 52 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] + k;
    }
  }
template<typename T1 > void op_scalar_minus_pre::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_minus_pre > & in) [inline, static, inherited]
For each element of a matrix, subtract it from a scalar.
Definition at line 78 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k - A_mem[i];
    }
  }
template<typename T1 > void op_scalar_minus_pre::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_minus_pre > & in) [inline, static, inherited]
For each element of a cube, subtract it from a scalar.
Definition at line 104 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k - A_mem[i];
    }
  }
template<typename T1 > void op_scalar_minus_post::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_minus_post > & in) [inline, static, inherited]
subtract a scalar from each element of a matrix
Definition at line 130 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] - k;
    }
  }
template<typename T1 > void op_scalar_minus_post::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_minus_post > & in) [inline, static, inherited]
subtract a scalar from each element of a cube
Definition at line 156 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] - k ;
    }
  }
template<typename T1 > void op_scalar_times::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_times > & in) [inline, static, inherited]
Multiply all elements of a matrix by a scalar.
Definition at line 182 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] * k;
    }
  }
template<typename T1 > void op_scalar_times::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_times > & in) [inline, static, inherited]
Multiply all elements of a cube by a scalar.
Definition at line 208 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_plus >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A + B, and then multiply each element of the result by a scalar.
Definition at line 238 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] + B_mem[i]) * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A + B, and then multiply each element of the result by a scalar.
Definition at line 276 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> tmp1(in.m.A);
  const unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] + B_mem[i]) * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_minus >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A - B, and then multiply each element of the result by a scalar.
Definition at line 314 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] - B_mem[i]) * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A - B, and then multiply each element of the result by a scalar.
Definition at line 352 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> tmp1(in.m.A);
  const unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] - B_mem[i]) * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_schur >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A % B (where % is the element-wise multiply operation) and then multiply each element of the result by a scalar.
Definition at line 390 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] * B_mem[i]) * k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_times::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_times > & in) [inline, static, inherited]
Evaluate A % B (where % is the element-wise multiply operation) and then multiply each element of the result by a scalar.
Definition at line 428 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> tmp1(in.m.A);
  const unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] * B_mem[i]) * k;
    }
  }
template<typename T1 > void op_scalar_div_pre::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 475 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / A_mem[i];
    }
  }
template<typename T1 > void op_scalar_div_pre::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 500 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / A_mem[i];
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_plus >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 529 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] + B_mem[i]);
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 566 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] + B_mem[i]);
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_minus >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 603 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] - B_mem[i]);
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 640 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] - B_mem[i]);
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_schur >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 677 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] * B_mem[i]);
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_pre::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_div_pre > & in) [inline, static, inherited]
Definition at line 714 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k / (A_mem[i] * B_mem[i]);
    }
  }
template<typename T1 > void op_scalar_div_post::apply (Mat< typename T1::elem_type > & out, const Op< T1, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 761 of file op_scalar_misc_meat.hpp.
References Op< T1, op_type >::aux, Op< T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_write<T1> tmp(out, in.m);
  const Mat<eT>& A     = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] / k;
    }
  }
template<typename T1 > void op_scalar_div_post::apply (Cube< typename T1::elem_type > & out, const OpCube< T1, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 786 of file op_scalar_misc_meat.hpp.
References OpCube< T1, op_type >::aux, OpCube< T1, op_type >::m, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_cube_write<T1> tmp(out, in.m);
  const Cube<eT>& A         = tmp.M;
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.memptr();
  const u32 n_elem  = out.n_elem;
  const eT  k       = in.aux;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_plus >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 815 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] + B_mem[i]) / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_plus >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 852 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube addition");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] + B_mem[i]) / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_minus >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 889 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] - B_mem[i]) / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_minus >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 926 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "cube subtraction");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] - B_mem[i]) / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Mat< typename T1::elem_type > & out, const Op< Glue< T1, T2, glue_schur >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 963 of file op_scalar_misc_meat.hpp.
References Mat< eT >::copy_size(), Mat< eT >::mem, Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap<T1> tmp1(in.m.A);
  unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] * B_mem[i]) / k;
    }
  }
template<typename T1 , typename T2 > void op_scalar_div_post::apply (Cube< typename T1::elem_type > & out, const OpCube< GlueCube< T1, T2, glue_cube_schur >, op_scalar_div_post > & in) [inline, static, inherited]
Definition at line 1000 of file op_scalar_misc_meat.hpp.
References Cube< eT >::copy_size(), Cube< eT >::mem, Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  unwrap_cube<T1> tmp1(in.m.A);
  unwrap_cube<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const Cube<eT>& A = tmp1.M;
  const Cube<eT>& B = tmp2.M;
  arma_debug_assert_same_size(A, B, "schur product");
  // no alias problems
  //out.set_size(A.n_rows, A.n_cols, A.n_slices);
  out.copy_size(A);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT  k       = in.aux;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A_mem[i] * B_mem[i]) / k;
    }
  }