Armadillo Technical: Fn_var
Fn_var
Functions
template<typename T1 >
Mat< typename T1::pod_type > var (const Base< typename T1::elem_type, T1 > &X, const u32 norm_type=0, const u32 dim=0)
template<typename eT >
get_pod_type< eT >::result var (const Row< eT > &A, const u32 norm_type=0)
Immediate 'find the variance of a row vector' operation.
template<typename eT >
get_pod_type< eT >::result var (const Col< eT > &A, const u32 norm_type=0)
Immediate 'find the variance of a column vector' operation.
template<typename eT >
get_pod_type< eT >::result var (const subview_row< eT > &A, const u32 norm_type=0)
template<typename eT >
get_pod_type< eT >::result var (const subview_col< eT > &A, const u32 norm_type=0)
template<typename eT >
get_pod_type< eT >::result var (const diagview< eT > &A, const u32 norm_type=0)
Function Documentation
template<typename T1 > Mat<typename T1::pod_type> var (const Base< typename T1::elem_type, T1 > & X, const u32 norm_type = 0, const u32 dim = 0) [inline]
Definition at line 25 of file fn_var.hpp.
References op_var::apply(), and Base< elem_type, derived >::get_ref().
Referenced by op_cov::direct_cov().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  const unwrap<T1>      tmp(X.get_ref());
  const Mat<in_eT>& A = tmp.M;
  Mat<out_eT> out;
  op_var::apply(out, A, norm_type, dim);
  return out;
  }
template<typename eT > get_pod_type<eT>::result var (const Row< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a row vector' operation.
Definition at line 48 of file fn_var.hpp.
References op_var::direct_var(), Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename eT > get_pod_type<eT>::result var (const Col< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a column vector' operation.
Definition at line 63 of file fn_var.hpp.
References op_var::direct_var(), Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename eT > get_pod_type<eT>::result var (const subview_row< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 77 of file fn_var.hpp.
References op_var::direct_var(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename eT > get_pod_type<eT>::result var (const subview_col< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 91 of file fn_var.hpp.
References op_var::direct_var(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename eT > get_pod_type<eT>::result var (const diagview< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 105 of file fn_var.hpp.
References op_var::direct_var(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }