Armadillo Technical: Operator_cube_minus
Operator_cube_minus
Functions
template<typename T1 >
arma_inline const OpCube< T1,
op_neg > operator- (const BaseCube< typename T1::elem_type, T1 > &X)
unary -
template<typename T1 >
arma_inline const T1 & operator- (const OpCube< T1, op_neg > &X)
cancellation of two consecutive negations: -(-T1)
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_minus_post > operator- (const BaseCube< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base - scalar.
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_minus_pre > operator- (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > &X)
scalar - Base
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_plus > operator- (const BaseCube< typename T1::elem_type, T1 > &X, const BaseCube< typename T1::elem_type, OpCube< T2, op_neg > > &Y)
Base - - Base = Base + Base.
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_plus > operator- (const BaseCube< typename T2::elem_type, T1 > &X, const OpCube< T2, op_neg > &Y)
Base - OpCube<T2,op_neg> = Base + T2.
template<typename eT1 , typename T1 , typename eT2 , typename T2 >
arma_inline Cube< typename
promote_type< eT1, eT2 >
::result > operator- (const BaseCube< eT1, T1 > &X, const BaseCube< eT2, T2 > &Y)
Base - Base.
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< std::complex< double >, T1 > &X, const BaseCube< std::complex< double >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< std::complex< float >, T1 > &X, const BaseCube< std::complex< float >, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< double, T1 > &X, const BaseCube< double, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< float, T1 > &X, const BaseCube< float, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< s32, T1 > &X, const BaseCube< s32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< u32, T1 > &X, const BaseCube< u32, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< s16, T1 > &X, const BaseCube< s16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< u16, T1 > &X, const BaseCube< u16, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< s8, T1 > &X, const BaseCube< s8, T2 > &Y)
template<typename T1 , typename T2 >
arma_inline const GlueCube< T1,
T2, glue_cube_minus > operator- (const BaseCube< u8, T1 > &X, const BaseCube< u8, T2 > &Y)
Function Documentation
template<typename T1 > arma_inline const OpCube<T1, op_neg> operator- (const BaseCube< typename T1::elem_type, T1 > & X) [inline]
unary -
Definition at line 26 of file operator_cube_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return OpCube<T1,op_neg>(X.get_ref());
  }
template<typename T1 > arma_inline const T1& operator- (const OpCube< T1, op_neg > & X) [inline]
cancellation of two consecutive negations: -(-T1)
Definition at line 40 of file operator_cube_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return X.m;
  }
template<typename T1 > arma_inline const OpCube<T1, op_scalar_minus_post> operator- (const BaseCube< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base - scalar.
Definition at line 54 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_minus_post>(X.get_ref(), k);
  }
template<typename T1 > arma_inline const OpCube<T1, op_scalar_minus_pre> operator- (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > & X) [inline]
scalar - Base
Definition at line 68 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_minus_pre>(X.get_ref(), k);
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_plus> operator- (const BaseCube< typename T1::elem_type, T1 > & X, const BaseCube< typename T1::elem_type, OpCube< T2, op_neg > > & Y) [inline]
Base - - Base = Base + Base.
Definition at line 82 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const T1& A = X.get_ref();
  const T2& B = (Y.get_ref()).m;
  return GlueCube<T1, T2, glue_cube_plus>(A,B);
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_plus> operator- (const BaseCube< typename T2::elem_type, T1 > & X, const OpCube< T2, op_neg > & Y) [inline]
Base - OpCube<T2,op_neg> = Base + T2.
Definition at line 102 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_plus>(X.get_ref(), Y.m);
  }
template<typename eT1 , typename T1 , typename eT2 , typename T2 > arma_inline Cube<typename promote_type<eT1,eT2>::result> operator- (const BaseCube< eT1, T1 > & X, const BaseCube< eT2, T2 > & Y) [inline]
Base - Base.
Definition at line 122 of file operator_cube_minus.hpp.
References glue_cube_minus::apply_mixed(), promote_type< T1, T2 >::check(), and BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap_cube<T1> tmp1(X.get_ref());
  const unwrap_cube<T2> tmp2(Y.get_ref());
  const Cube<eT1>& A = tmp1.M;
  const Cube<eT2>& B = tmp2.M;
  Cube< typename promote_type<eT1,eT2>::result > out;
  glue_cube_minus::apply_mixed(out, A, B);
  return out;
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< std::complex< double >, T1 > & X, const BaseCube< std::complex< double >, T2 > & Y) [inline]
Definition at line 152 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< std::complex< float >, T1 > & X, const BaseCube< std::complex< float >, T2 > & Y) [inline]
Definition at line 165 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< double, T1 > & X, const BaseCube< double, T2 > & Y) [inline]
Definition at line 178 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< float, T1 > & X, const BaseCube< float, T2 > & Y) [inline]
Definition at line 191 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< s32, T1 > & X, const BaseCube< s32, T2 > & Y) [inline]
Definition at line 204 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< u32, T1 > & X, const BaseCube< u32, T2 > & Y) [inline]
Definition at line 217 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< s16, T1 > & X, const BaseCube< s16, T2 > & Y) [inline]
Definition at line 230 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< u16, T1 > & X, const BaseCube< u16, T2 > & Y) [inline]
Definition at line 243 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< s8, T1 > & X, const BaseCube< s8, T2 > & Y) [inline]
Definition at line 256 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline const GlueCube<T1, T2, glue_cube_minus> operator- (const BaseCube< u8, T1 > & X, const BaseCube< u8, T2 > & Y) [inline]
Definition at line 269 of file operator_cube_minus.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return GlueCube<T1, T2, glue_cube_minus>(X.get_ref(), Y.get_ref());
  }