Armadillo Technical: Operator_cube_times
Operator_cube_times
Functions
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_times > operator* (const BaseCube< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
BaseCube * scalar.
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_times > operator* (const OpCube< T1, op_scalar_times > &X, const typename T1::elem_type k)
op * scalar, level 2
template<typename eT >
arma_inline Cube< eT > operator* (const OpCube< Cube< eT >, op_ones_full > &X, const eT k)
OpCube<cube,op_ones_full> * scalar.
template<typename T1 >
arma_inline const OpCube< T1,
op_scalar_times > operator* (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > &X)
scalar * Base
template<typename eT >
arma_inline Cube< eT > operator* (const eT k, const OpCube< Cube< eT >, op_ones_full > &X)
scalar * OpCube<cube,op_ones_full>
Function Documentation
template<typename T1 > arma_inline const OpCube<T1, op_scalar_times> operator* (const BaseCube< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
BaseCube * scalar.
Definition at line 28 of file operator_cube_times.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_times>(X.get_ref(),k);
  }
template<typename T1 > arma_inline const OpCube<T1,op_scalar_times> operator* (const OpCube< T1, op_scalar_times > & X, const typename T1::elem_type k) [inline]
op * scalar, level 2
Definition at line 42 of file operator_cube_times.hpp.
References OpCube< T1, op_type >::aux, and OpCube< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_times>(X.m, X.aux * k);
  }
template<typename eT > arma_inline Cube<eT> operator* (const OpCube< Cube< eT >, op_ones_full > & X, const eT k) [inline]
OpCube<cube,op_ones_full> * scalar.
Definition at line 56 of file operator_cube_times.hpp.
References OpCube< T1, op_type >::aux_u32_a, OpCube< T1, op_type >::aux_u32_b, OpCube< T1, op_type >::aux_u32_c, and Cube< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Cube<eT> tmp(X.aux_u32_a, X.aux_u32_b, X.aux_u32_c);
  tmp.fill(k);
  return tmp;
  }
template<typename T1 > arma_inline const OpCube<T1, op_scalar_times> operator* (const typename T1::elem_type k, const BaseCube< typename T1::elem_type, T1 > & X) [inline]
scalar * Base
Definition at line 73 of file operator_cube_times.hpp.
References BaseCube< T1::elem_type, OpCube< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return OpCube<T1, op_scalar_times>(X.get_ref(),k);  // NOTE: order is swapped
  }
template<typename eT > arma_inline Cube<eT> operator* (const eT k, const OpCube< Cube< eT >, op_ones_full > & X) [inline]
scalar * OpCube<cube,op_ones_full>
Definition at line 87 of file operator_cube_times.hpp.
References OpCube< T1, op_type >::aux_u32_a, OpCube< T1, op_type >::aux_u32_b, OpCube< T1, op_type >::aux_u32_c, and Cube< eT >::fill().
  {
  arma_extra_debug_sigprint();
  Cube<eT> tmp(X.aux_u32_a, X.aux_u32_b, X.aux_u32_c);
  tmp.fill(k);
  return tmp;
  }