Armadillo Technical: Operator_minus
Operator_minus
Functions
template<typename T1 >
arma_inline const eOp< T1,
eop_neg > operator- (const Base< typename T1::elem_type, T1 > &X)
unary -
template<typename T1 >
arma_inline const T1 & operator- (const eOp< T1, eop_neg > &X)
cancellation of two consecutive negations: -(-T1)
template<typename T1 >
arma_inline const eOp< T1,
eop_scalar_minus_post > operator- (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
Base - scalar.
template<typename T1 >
arma_inline const eOp< T1,
eop_scalar_minus_pre > operator- (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > &X)
scalar - Base
template<typename T1 >
arma_inline Mat< typename
std::complex< typename
T1::pod_type > > operator- (const Base< typename T1::pod_type, T1 > &X, const std::complex< typename T1::pod_type > &k)
non-complex Base - complex scalar (experimental)
template<typename T1 >
arma_inline Mat< typename
std::complex< typename
T1::pod_type > > operator- (const std::complex< typename T1::pod_type > &k, const Base< typename T1::pod_type, T1 > &X)
complex scalar - non-complex Base (experimental)
template<typename T1 , typename T2 >
arma_inline const eGlue< T1,
T2, eglue_minus > operator- (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, T2 > &Y)
subtraction of Base objects with same element type
template<typename T1 , typename T2 >
arma_inline Mat< typename
promote_type< typename
T1::elem_type, typename
T2::elem_type >::result > operator- (const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T1_result, T1 > &X, const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T2_result, T2 > &Y)
subtraction of Base objects with different element types
Function Documentation
template<typename T1 > arma_inline const eOp<T1, eop_neg> operator- (const Base< typename T1::elem_type, T1 > & X) [inline]
unary -
Definition at line 27 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return eOp<T1,eop_neg>(X.get_ref());
  }
template<typename T1 > arma_inline const T1& operator- (const eOp< T1, eop_neg > & X) [inline]
cancellation of two consecutive negations: -(-T1)
Definition at line 41 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return X.m;
  }
template<typename T1 > arma_inline const eOp<T1, eop_scalar_minus_post> operator- (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
Base - scalar.
Definition at line 55 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_scalar_minus_post>(X.get_ref(), k);
  }
template<typename T1 > arma_inline const eOp<T1, eop_scalar_minus_pre> operator- (const typename T1::elem_type k, const Base< typename T1::elem_type, T1 > & X) [inline]
scalar - Base
Definition at line 72 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_scalar_minus_pre>(X.get_ref(), k);
  }
template<typename T1 > arma_inline Mat<typename std::complex<typename T1::pod_type> > operator- (const Base< typename T1::pod_type, T1 > & X, const std::complex< typename T1::pod_type > & k) [inline]
non-complex Base - complex scalar (experimental)
Definition at line 89 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename std::complex<typename T1::pod_type> eT;
  typedef typename T1::pod_type                         T;
  const Proxy<T1> A(X.get_ref());
  Mat<eT> out(A.n_rows, A.n_cols);
  const u32 n_elem  = A.n_elem;
        eT* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A[i] - k;
    }
  return out;
  }
template<typename T1 > arma_inline Mat<typename std::complex<typename T1::pod_type> > operator- (const std::complex< typename T1::pod_type > & k, const Base< typename T1::pod_type, T1 > & X) [inline]
complex scalar - non-complex Base (experimental)
Definition at line 121 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename std::complex<typename T1::pod_type> eT;
  typedef typename T1::pod_type                         T;
  const Proxy<T1> A(X.get_ref());
  Mat<eT> out(A.n_rows, A.n_cols);
  const u32 n_elem  = A.n_elem;
        eT* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = k - A[i];
    }
  return out;
  }
template<typename T1 , typename T2 > arma_inline const eGlue<T1, T2, eglue_minus> operator- (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
subtraction of Base objects with same element type
Definition at line 153 of file operator_minus.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eGlue<T1, T2, eglue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > arma_inline Mat<typename promote_type<typename T1::elem_type, typename T2::elem_type>::result> operator- (const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T1_result, T1 > & X, const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T2_result, T2 > & Y) [inline]
subtraction of Base objects with different element types
Definition at line 170 of file operator_minus.hpp.
References upgrade_val< T1, T2 >::apply(), promote_type< T1, T2 >::check(), Base< elem_type, derived >::get_ref(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT1;
  typedef typename T2::elem_type eT2;
  typedef typename promote_type<eT1,eT2>::result out_eT;
  promote_type<eT1,eT2>::check();
  const Proxy<T1> A(X.get_ref());
  const Proxy<T2> B(Y.get_ref());
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  Mat<out_eT> out(A.n_rows, A.n_cols);
        out_eT* out_mem = out.memptr();
  const u32     n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = upgrade_val<eT1,eT2>::apply(A[i]) - upgrade_val<eT1,eT2>::apply(B[i]);
    }
  return out;
  }