Armadillo Technical: Fn_princomp_cov
Fn_princomp_cov
Functions
template<typename T1 >
void princomp_cov (Mat< typename T1::elem_type > &coeff_out, Col< typename T1::pod_type > &latent_out, Col< typename T1::pod_type > &explained_out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis of a covariance matrix -- 3 arguments version coeff_out -> principal component coefficients latent_out -> principal component variances explained_out -> percentage of the total variance explained by each principal component.
template<typename T1 >
void princomp_cov (Mat< typename T1::elem_type > &coeff_out, Col< typename T1::pod_type > &latent_out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis of a covariance matrix -- 2 arguments version coeff_out -> principal component coefficients latent_out -> principal component variances
template<typename T1 >
const Op< T1, op_princomp_cov > princomp_cov (const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis of a covariance matrix -- 1 argument version coeff_out -> principal component coefficients
Function Documentation
template<typename T1 > void princomp_cov (Mat< typename T1::elem_type > & coeff_out, Col< typename T1::pod_type > & latent_out, Col< typename T1::pod_type > & explained_out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis of a covariance matrix -- 3 arguments version coeff_out -> principal component coefficients latent_out -> principal component variances explained_out -> percentage of the total variance explained by each principal component.
Definition at line 32 of file fn_princomp_cov.hpp.
References op_princomp_cov::direct_princomp_cov(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  op_princomp_cov::direct_princomp_cov(coeff_out, latent_out, explained_out, A);
  }
template<typename T1 > void princomp_cov (Mat< typename T1::elem_type > & coeff_out, Col< typename T1::pod_type > & latent_out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis of a covariance matrix -- 2 arguments version coeff_out -> principal component coefficients latent_out -> principal component variances
Definition at line 60 of file fn_princomp_cov.hpp.
References op_princomp_cov::direct_princomp_cov(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  op_princomp_cov::direct_princomp_cov(coeff_out, latent_out, A);
  }
template<typename T1 > const Op<T1, op_princomp_cov> princomp_cov (const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis of a covariance matrix -- 1 argument version coeff_out -> principal component coefficients
Definition at line 86 of file fn_princomp_cov.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_princomp_cov>(X.get_ref());
  }