Armadillo Technical: Fn_trunc_log
Fn_trunc_log
Functions
template<typename eT >
static arma_float_only< eT >
::result trunc_log (const eT x)
template<typename T >
static std::complex< T > trunc_log (const std::complex< T > &x)
template<typename T1 >
arma_inline const eOp< T1,
eop_trunc_log > trunc_log (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_trunc_log > trunc_log (const BaseCube< typename T1::elem_type, T1 > &A)
Function Documentation
template<typename eT > static arma_integral_only< eT >::result trunc_log (const eT x) [inline, static]
Definition at line 51 of file fn_trunc_log.hpp.
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  return eT( trunc_log( double(x) ) );
  }
template<typename T > static std::complex<T> trunc_log (const std::complex< T > & x) [inline, static]
Definition at line 62 of file fn_trunc_log.hpp.
References log().
  {
  return std::log(x);
  }
template<typename T1 > arma_inline const eOp<T1, eop_trunc_log> trunc_log (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 72 of file fn_trunc_log.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_trunc_log>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_trunc_log> trunc_log (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 84 of file fn_trunc_log.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_trunc_log>(A.get_ref());
  }