Armadillo Technical: Fn_max
Fn_max
Functions
template<typename T1 >
arma_inline const Op< T1, op_max > max (const Base< typename T1::elem_type, T1 > &X, const u32 dim=0)
Delayed 'maximum values' operation. The dimension, along which the maxima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
template<typename eT >
arma_warn_unused eT max (const Row< eT > &A)
Immediate 'find the maximum value in a row vector' operation.
template<typename eT >
arma_warn_unused eT max (const Col< eT > &A)
Immediate 'find the maximum value in a column vector' operation.
template<typename T1 >
arma_warn_unused T1::elem_type max (const Op< T1, op_max > &in)
Immediate 'find maximum value' operation, invoked, for example, by: max(max(A)).
template<typename T1 >
arma_inline const Op< Op< T1,
op_max >, op_max > max (const Op< T1, op_max > &in, const u32 dim)
template<typename eT >
arma_warn_unused eT max (const subview_row< eT > &A)
template<typename eT >
arma_warn_unused eT max (const subview_col< eT > &A)
template<typename eT >
arma_warn_unused eT max (const Op< subview< eT >, op_max > &in)
template<typename eT >
arma_warn_unused eT max (const diagview< eT > &A)
Function Documentation
template<typename T1 > arma_inline const Op<T1, op_max> max (const Base< typename T1::elem_type, T1 > & X, const u32 dim = 0) [inline]
Delayed 'maximum values' operation. The dimension, along which the maxima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
Definition at line 32 of file fn_max.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_pinv::direct_pinv(), auxlib::eig_gen(), auxlib::eig_sym(), auxlib::inv_inplace(), auxlib::inv_noalias(), Math< eT >::log_max(), auxlib::qr(), rank(), auxlib::solve_od(), auxlib::solve_ud(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_max>(X.get_ref(), dim, 0);
  }
template<typename eT > arma_warn_unused eT max (const Row< eT > & A) [inline]
Immediate 'find the maximum value in a row vector' operation.
Definition at line 45 of file fn_max.hpp.
References op_max::direct_max(), Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A.mem, A.n_elem);
  }
template<typename eT > arma_warn_unused eT max (const Col< eT > & A) [inline]
Immediate 'find the maximum value in a column vector' operation.
Definition at line 61 of file fn_max.hpp.
References op_max::direct_max(), Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A.mem, A.n_elem);
  }
template<typename T1 > arma_warn_unused T1::elem_type max (const Op< T1, op_max > & in) [inline]
Immediate 'find maximum value' operation, invoked, for example, by: max(max(A)).
Definition at line 79 of file fn_max.hpp.
References op_max::direct_max(), unwrap< T1 >::M, Op< T1, op_type >::m, Mat< eT >::mem, and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("max(): two consecutive max() calls detected");
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.m);
  const Mat<eT>& X = tmp1.M;
  arma_debug_check( (X.n_elem == 0), "max(): given matrix has no elements" );
  return op_max::direct_max(X.mem, X.n_elem);
  }
template<typename T1 > arma_inline const Op< Op<T1, op_max>, op_max> max (const Op< T1, op_max > & in, const u32 dim) [inline]
Definition at line 99 of file fn_max.hpp.
  {
  arma_extra_debug_sigprint();
  return Op< Op<T1, op_max>, op_max>(in, dim, 0);
  }
template<typename eT > arma_warn_unused eT max (const subview_row< eT > & A) [inline]
Definition at line 112 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }
template<typename eT > arma_warn_unused eT max (const subview_col< eT > & A) [inline]
Definition at line 127 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }
template<typename eT > arma_warn_unused eT max (const Op< subview< eT >, op_max > & in) [inline]
Definition at line 142 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("max(): two consecutive max() calls detected");
  const subview<eT>& X = in.m;
  arma_debug_check( (X.n_elem == 0), "max(): given matrix has no elements" );
  return op_max::direct_max(X);
  }
template<typename eT > arma_warn_unused eT max (const diagview< eT > & A) [inline]
Definition at line 160 of file fn_max.hpp.
References op_max::direct_max(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }