Armadillo Technical: Fn_princomp
Fn_princomp
Functions
template<typename T1 >
void princomp (Mat< typename T1::elem_type > &coeff_out, Mat< typename T1::elem_type > &score_out, Col< typename T1::pod_type > &latent_out, Col< typename T1::elem_type > &tsquared_out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis -- 4 arguments version coeff_out -> principal component coefficients score_out -> projected samples latent_out -> eigenvalues of principal vectors tsquared_out -> Hotelling's T^2 statistic
template<typename T1 >
void princomp (Mat< typename T1::elem_type > &coeff_out, Mat< typename T1::elem_type > &score_out, Col< typename T1::pod_type > &latent_out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis -- 3 arguments version coeff_out -> principal component coefficients score_out -> projected samples latent_out -> eigenvalues of principal vectors
template<typename T1 >
void princomp (Mat< typename T1::elem_type > &coeff_out, Mat< typename T1::elem_type > &score_out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis -- 2 arguments version coeff_out -> principal component coefficients score_out -> projected samples
template<typename T1 >
const Op< T1, op_princomp > princomp (const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
principal component analysis -- 1 argument version coeff_out -> principal component coefficients
Function Documentation
template<typename T1 > void princomp (Mat< typename T1::elem_type > & coeff_out, Mat< typename T1::elem_type > & score_out, Col< typename T1::pod_type > & latent_out, Col< typename T1::elem_type > & tsquared_out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis -- 4 arguments version coeff_out -> principal component coefficients score_out -> projected samples latent_out -> eigenvalues of principal vectors tsquared_out -> Hotelling's T^2 statistic
Definition at line 33 of file fn_princomp.hpp.
References op_princomp::direct_princomp(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  op_princomp::direct_princomp(coeff_out, score_out, latent_out, tsquared_out, A);
  }
template<typename T1 > void princomp (Mat< typename T1::elem_type > & coeff_out, Mat< typename T1::elem_type > & score_out, Col< typename T1::pod_type > & latent_out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis -- 3 arguments version coeff_out -> principal component coefficients score_out -> projected samples latent_out -> eigenvalues of principal vectors
Definition at line 63 of file fn_princomp.hpp.
References op_princomp::direct_princomp(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  op_princomp::direct_princomp(coeff_out, score_out, latent_out, A);
  }
template<typename T1 > void princomp (Mat< typename T1::elem_type > & coeff_out, Mat< typename T1::elem_type > & score_out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis -- 2 arguments version coeff_out -> principal component coefficients score_out -> projected samples
Definition at line 91 of file fn_princomp.hpp.
References op_princomp::direct_princomp(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1>   tmp(X.get_ref());
  const Mat<eT>& A = tmp.M;
  op_princomp::direct_princomp(coeff_out, score_out, A);
  }
template<typename T1 > const Op<T1, op_princomp> princomp (const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
principal component analysis -- 1 argument version coeff_out -> principal component coefficients
Definition at line 117 of file fn_princomp.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_princomp>(X.get_ref());
  }