Armadillo Technical: Fn_trunc_exp
Fn_trunc_exp
Functions
template<typename eT >
static arma_float_only< eT >
::result trunc_exp (const eT x)
template<typename T >
static arma_inline
std::complex< T > trunc_exp (const std::complex< T > &x)
template<typename T1 >
arma_inline const eOp< T1,
eop_trunc_exp > trunc_exp (const Base< typename T1::elem_type, T1 > &A)
template<typename T1 >
arma_inline const eOpCube< T1,
eop_cube_trunc_exp > trunc_exp (const BaseCube< typename T1::elem_type, T1 > &A)
Function Documentation
template<typename eT > static arma_integral_only< eT >::result trunc_exp (const eT x) [inline, static]
Definition at line 45 of file fn_trunc_exp.hpp.
Referenced by eop_cube_core< eop_cube_type >::process(), and eop_core< eop_type >::process().
  {
  return eT( trunc_exp( double(x) ) );
  }
template<typename T > static arma_inline std::complex<T> trunc_exp (const std::complex< T > & x) [inline, static]
Definition at line 56 of file fn_trunc_exp.hpp.
References exp().
  {
  return std::exp(x);
  }
template<typename T1 > arma_inline const eOp<T1, eop_trunc_exp> trunc_exp (const Base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 66 of file fn_trunc_exp.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOp<T1, eop_trunc_exp>(A.get_ref());
  }
template<typename T1 > arma_inline const eOpCube<T1, eop_cube_trunc_exp> trunc_exp (const BaseCube< typename T1::elem_type, T1 > & A) [inline]
Definition at line 78 of file fn_trunc_exp.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eOpCube<T1, eop_cube_trunc_exp>(A.get_ref());
  }