Armadillo Technical: Fn_cov
Fn_cov
Functions
template<typename T1 >
const Op< T1, op_cov > cov (const Base< typename T1::elem_type, T1 > &X, const u32 norm_type=0)
template<typename T1 , typename T2 >
const Glue< T1, T2, glue_cov > cov (const Base< typename T1::elem_type, T1 > &A, const Base< typename T1::elem_type, T2 > &B, const u32 norm_type=0)
Function Documentation
template<typename T1 > const Op<T1, op_cov> cov (const Base< typename T1::elem_type, T1 > & X, const u32 norm_type = 0) [inline]
Definition at line 26 of file fn_cov.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_princomp_cov::direct_princomp_cov().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (norm_type > 1), "cov(): norm_type must be 0 or 1");
  return Op<T1, op_cov>(X.get_ref(), norm_type, 0);
  }
template<typename T1 , typename T2 > const Glue<T1,T2,glue_cov> cov (const Base< typename T1::elem_type, T1 > & A, const Base< typename T1::elem_type, T2 > & B, const u32 norm_type = 0) [inline]
Definition at line 40 of file fn_cov.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (norm_type > 1), "cov(): norm_type must be 0 or 1");
  return Glue<T1, T2, glue_cov>(A.get_ref(), B.get_ref(), norm_type);
  }