Armadillo Technical: Fn_randu
Fn_randu
Functions
double randu ()
arma_inline const eOp< colvec,
eop_randu > randu (const u32 n_elem, const arma_Mat_Col_Row_only< colvec >::result *junk=0)
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
template<typename vec_type >
arma_inline const eOp
< vec_type, eop_randu > randu (const u32 n_elem, const typename arma_Mat_Col_Row_only< vec_type >::result *junk=0)
arma_inline const eOp< mat,
eop_randu > randu (const u32 n_rows, const u32 n_cols, const arma_Mat_Col_Row_only< mat >::result *junk=0)
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
template<typename mat_type >
arma_inline const eOp
< mat_type, eop_randu > randu (const u32 n_rows, const u32 n_cols, const typename arma_Mat_Col_Row_only< mat_type >::result *junk=0)
arma_inline const eOpCube
< cube, eop_cube_randu > randu (const u32 n_rows, const u32 n_cols, const u32 n_slices, const arma_Cube_only< cube >::result *junk=0)
template<typename cube_type >
arma_inline const eOpCube
< cube_type, eop_cube_randu > randu (const u32 n_rows, const u32 n_cols, const u32 n_slices, const typename arma_Cube_only< cube_type >::result *junk=0)
arma_deprecated const eOp< mat,
eop_randu > rand (const u32 n_rows, const u32 n_cols)
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
arma_deprecated const eOpCube
< cube, eop_cube_randu > rand (const u32 n_rows, const u32 n_cols, const u32 n_slices)
arma_deprecated const eOp
< colvec, eop_randu > rand (const u32 n_elem)
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
Function Documentation
arma_scalar_only< eT >::result randu () [inline]
Definition at line 32 of file fn_randu.hpp.
  {
  return eT(eop_aux_randu<eT>());
  }
arma_inline const eOp<colvec, eop_randu> randu (const u32 n_elem, const arma_Mat_Col_Row_only< colvec >::result * junk = 0)
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 42 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  return eOp<colvec, eop_randu>(n_elem, 1);
  }
template<typename vec_type > arma_inline const eOp<vec_type, eop_randu> randu (const u32 n_elem, const typename arma_Mat_Col_Row_only< vec_type >::result * junk = 0) [inline]
Definition at line 54 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  if(is_Row<vec_type>::value == true)
    {
    return eOp<vec_type, eop_randu>(1, n_elem);
    }
  else
    {
    return eOp<vec_type, eop_randu>(n_elem, 1);
    }
  }
arma_inline const eOp<mat, eop_randu> randu (const u32 n_rows, const u32 n_cols, const arma_Mat_Col_Row_only< mat >::result * junk = 0)
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 73 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  return eOp<mat, eop_randu>(n_rows, n_cols);
  }
template<typename mat_type > arma_inline const eOp<mat_type, eop_randu> randu (const u32 n_rows, const u32 n_cols, const typename arma_Mat_Col_Row_only< mat_type >::result * junk = 0) [inline]
Definition at line 85 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  return eOp<mat_type, eop_randu>(n_rows, n_cols);
  }
arma_inline const eOpCube<cube, eop_cube_randu> randu (const u32 n_rows, const u32 n_cols, const u32 n_slices, const arma_Cube_only< cube >::result * junk = 0)
Definition at line 96 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  return eOpCube<cube, eop_cube_randu>(n_rows, n_cols, n_slices);
  }
template<typename cube_type > arma_inline const eOpCube<cube_type, eop_cube_randu> randu (const u32 n_rows, const u32 n_cols, const u32 n_slices, const typename arma_Cube_only< cube_type >::result * junk = 0) [inline]
Definition at line 108 of file fn_randu.hpp.
  {
  arma_extra_debug_sigprint();
  return eOpCube<cube_type, eop_cube_randu>(n_rows, n_cols, n_slices);
  }
arma_deprecated const eOp< mat_type, eop_randu > rand (const u32 n_rows, const u32 n_cols) [inline]
Generate a dense matrix with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 154 of file fn_randu.hpp.
References arma_print().
Referenced by op_shuffle::apply(), eop_aux_randn< eT >::operator eT(), and eop_aux_randu< eT >::operator eT().
  {
  arma_extra_debug_sigprint();
  arma_type_check<is_Mat<mat_type>::value == false>::apply();
  arma_print("rand() is deprecated; please use randu() instead");
  return eOp<mat_type, eop_randu>(n_rows, n_cols);
  }
arma_deprecated const eOpCube< cube_type, eop_cube_randu > rand (const u32 n_rows, const u32 n_cols, const u32 n_slices) [inline]
Definition at line 171 of file fn_randu.hpp.
References arma_print().
  {
  arma_extra_debug_sigprint();
  arma_type_check<is_Cube<cube_type>::value == false>::apply();
  arma_print("rand() is deprecated; please use randu() instead");
  return eOpCube<cube_type, eop_cube_randu>(n_rows, n_cols, n_slices);
  }
arma_deprecated const eOp< vec_type, eop_randu > rand (const u32 n_elem) [inline]
Generate a vector with all elements set to random values in the [0,1] interval (uniform distribution).
Definition at line 203 of file fn_randu.hpp.
References arma_print().
  {
  arma_extra_debug_sigprint();
  arma_print("rand() is deprecated; please use randu() instead");
  arma_type_check< (is_Col<vec_type>::value == false) && (is_Row<vec_type>::value == false) >::apply();
  if(is_Row<vec_type>::value == true)
    {
    return eOp<vec_type, eop_randu>(1, n_elem);
    }
  else
    {
    return eOp<vec_type, eop_randu>(n_elem, 1);
    }
  }