Armadillo Technical: Fn_conv_to
Fn_conv_to
Classes
class conv_to< out_eT >
conversion from Armadillo Base and BaseCube objects to scalars (kept only for compatibility with old code; use as_scalar() instead for Base objects like Mat)
class conv_to< Mat< out_eT > >
conversion to Armadillo matrices from Armadillo Base objects, as well as from std::vector, itpp::Mat and itpp::Vec
class conv_to< Row< out_eT > >
conversion to Armadillo row vectors from Armadillo Base objects, as well as from std::vector, itpp::Mat and itpp::Vec
class conv_to< Col< out_eT > >
conversion to Armadillo column vectors from Armadillo Base objects, as well as from std::vector, itpp::Mat and itpp::Vec
class conv_to< Cube< out_eT > >
conversion to Armadillo cubes from Armadillo BaseCube objects
class conv_to< std::vector< out_eT > >
conversion to std::vector from Armadillo Base objects
class conv_to< itpp::Mat< out_eT > >
conversion to itpp::Mat from Armadillo Base objects
class conv_to< itpp::Vec< out_eT > >
conversion to itpp::Vec from Armadillo Base objects
Functions
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const BaseCube< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static out_eT conv_to::from (const BaseCube< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const std::vector< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Mat< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT >
static Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static std::vector< out_eT > conv_to< std::vector< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static std::vector< out_eT > conv_to< std::vector< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_not_cx< in_eT >::result *junk=0)
template<typename in_eT , typename T1 >
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > &in, const typename arma_cx_only< in_eT >::result *junk=0)
Function Documentation
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 48 of file fn_conv_to.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.n_elem != 1), "conv_to(): given object doesn't have exactly one element" );
  return out_eT(X.mem[0]);
  }
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 68 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.n_elem != 1), "conv_to(): given object doesn't have exactly one element" );
  out_eT out;
  syslib::convert_cx_scalar(out, X.mem[0]);
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const BaseCube< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 92 of file fn_conv_to.hpp.
References BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap_cube<T1>  tmp(in.get_ref());
  const Cube<in_eT>& X = tmp.M;
  arma_debug_check( (X.n_elem != 1), "conv_to(): given object doesn't have exactly one element" );
  return out_eT(X.mem[0]);
  }
template<typename out_eT > template<typename in_eT , typename T1 > out_eT conv_to< out_eT >::from (const BaseCube< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 112 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar(), and BaseCube< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap_cube<T1>  tmp(in.get_ref());
  const Cube<in_eT>& X = tmp.M;
  arma_debug_check( (X.n_elem != 1), "conv_to(): given object doesn't have exactly one element" );
  out_eT out;
  syslib::convert_cx_scalar(out, X.mem[0]);
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 176 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  Mat<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Mat< out_eT > conv_to< Mat< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 196 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  Mat<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_cx_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 216 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.size(), 1);
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Mat<out_eT>::iterator out_begin = out.begin();
  typename Mat<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Mat<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
    (*out_it) = out_eT(*in_it);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 245 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar().
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.size(), 1);
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Mat<out_eT>::iterator out_begin = out.begin();
  typename Mat<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Mat<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
          out_eT& out_elem = (*out_it);
    const in_eT&  in_elem  = (*in_it);
    syslib::convert_cx_scalar(out_elem, in_elem);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 277 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.rows(), in.cols());
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 294 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.rows(), in.cols());
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 311 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.length(), 1);
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Mat< out_eT > conv_to< Mat< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 328 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  Mat<out_eT> out(in.length(), 1);
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 385 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  Row<out_eT> out(X.n_elem);
  syslib::copy_and_convert_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Row< out_eT > conv_to< Row< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 407 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  Row<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_cx_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 429 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Row<out_eT> out( in.size() );
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Col<out_eT>::iterator out_begin = out.begin();
  typename Col<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Col<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
    (*out_it) = out_eT(*in_it);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 458 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar().
  {
  arma_extra_debug_sigprint();
  Row<out_eT> out( in.size() );
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Col<out_eT>::iterator out_begin = out.begin();
  typename Col<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Col<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
          out_eT& out_elem = (*out_it);
    const in_eT&  in_elem  = (*in_it);
    syslib::convert_cx_scalar(out_elem, in_elem);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 490 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  const bool is_vec = ( (in.rows() == 1) || (in.cols() == 1) );
  arma_debug_check( (is_vec == false), "conv_to(): given object can't be interpreted as a vector" );
  Row<out_eT> out(in.rows() * in.cols());
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 511 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  const bool is_vec = ( (in.rows() == 1) || (in.cols() == 1) );
  Row<out_eT> out(in.rows() * in.cols());
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 530 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  Row<out_eT> out(in.length());
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Row< out_eT > conv_to< Row< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 547 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  Row<out_eT> out(in.length());
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 604 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  Col<out_eT> out(X.n_elem);
  syslib::copy_and_convert_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Col< out_eT > conv_to< Col< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 626 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem(), Mat< eT >::memptr(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  Col<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_cx_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 648 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  Col<out_eT> out( in.size() );
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Col<out_eT>::iterator out_begin = out.begin();
  typename Col<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Col<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
    (*out_it) = out_eT(*in_it);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const std::vector< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 677 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar().
  {
  arma_extra_debug_sigprint();
  Col<out_eT> out( in.size() );
  typename std::vector<in_eT>::const_iterator in_begin = in.begin();
  typename std::vector<in_eT>::const_iterator in_end   = in.end();
  typename Col<out_eT>::iterator out_begin = out.begin();
  typename Col<out_eT>::iterator out_end   = out.end();
  typename std::vector<in_eT>::const_iterator in_it;
  typename Col<out_eT>::iterator              out_it;
  for(in_it = in_begin, out_it = out_begin; (in_it != in_end) && (out_it != out_end); ++in_it, ++out_it)
    {
          out_eT& out_elem = (*out_it);
    const in_eT&  in_elem  = (*in_it);
    syslib::convert_cx_scalar(out_elem, in_elem);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 709 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  const bool is_vec = ( (in.rows() == 1) || (in.cols() == 1) );
  arma_debug_check( (is_vec == false), "conv_to(): given object can't be interpreted as a vector" );
  Col<out_eT> out(in.rows() * in.cols());
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Mat< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 730 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  const bool is_vec = ( (in.rows() == 1) || (in.cols() == 1) );
  Col<out_eT> out(in.rows() * in.cols());
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 749 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  Col<out_eT> out( in.length() );
  syslib::copy_and_convert_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT > Col< out_eT > conv_to< Col< out_eT > >::from (const itpp::Vec< in_eT > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 766 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  Col<out_eT> out( in.length() );
  syslib::copy_and_convert_cx_elem( out.memptr(), in._data(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 798 of file fn_conv_to.hpp.
References syslib::copy_and_convert_elem(), Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1>  tmp( in.get_ref() );
  const Cube<in_eT>& X = tmp.M;
  Cube<out_eT> out(X.n_rows, X.n_cols, X.n_slices);
  syslib::copy_and_convert_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > Cube< out_eT > conv_to< Cube< out_eT > >::from (const BaseCube< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 818 of file fn_conv_to.hpp.
References syslib::copy_and_convert_cx_elem(), Cube< eT >::memptr(), and Cube< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1>  tmp( in.get_ref() );
  const Cube<in_eT>& X = tmp.M;
  Cube<out_eT> out(X.n_rows, X.n_cols, X.n_slices);
  syslib::copy_and_convert_cx_elem( out.memptr(), X.memptr(), out.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > std::vector< out_eT > conv_to< std::vector< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 853 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  std::vector<out_eT> out(X.n_elem);
  typename Mat<in_eT>::const_iterator X_begin = X.begin();
  typename Mat<in_eT>::const_iterator X_end   = X.end();
  typename std::vector<out_eT>::iterator out_begin = out.begin();
  typename std::vector<out_eT>::iterator out_end   = out.end();
  typename Mat<in_eT>::const_iterator    X_it;
  typename std::vector<out_eT>::iterator out_it;
  for(X_it = X_begin, out_it = out_begin; (X_it != X_end) && (out_it != out_end); ++X_it, ++out_it)
    {
    (*out_it) = out_eT(*X_it);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > std::vector< out_eT > conv_to< std::vector< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 887 of file fn_conv_to.hpp.
References syslib::convert_cx_scalar().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp(in.get_ref());
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  std::vector<out_eT> out(X.n_elem);
  typename Mat<in_eT>::const_iterator X_begin = X.begin();
  typename Mat<in_eT>::const_iterator X_end   = X.end();
  typename std::vector<out_eT>::iterator out_begin = out.begin();
  typename std::vector<out_eT>::iterator out_end   = out.end();
  typename Mat<in_eT>::const_iterator    X_it;
  typename std::vector<out_eT>::iterator out_it;
  for(X_it = X_begin, out_it = out_begin; (X_it != X_end) && (out_it != out_end); ++X_it, ++out_it)
    {
          out_eT& out_elem = (*out_it);
    const in_eT&  X_elem   = (*X_it);
    syslib::convert_cx_scalar(out_elem, X_elem);
    }
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 939 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp( in.get_ref() );
  const Mat<in_eT>& X = tmp.M;
  itpp::Mat<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_elem( out._data(), X.memptr(), X.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 959 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp( in.get_ref() );
  const Mat<in_eT>& X = tmp.M;
  itpp::Mat<out_eT> out(X.n_rows, X.n_cols);
  syslib::copy_and_convert_cx_elem( out._data(), X.memptr(), X.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_not_cx< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 995 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and syslib::copy_and_convert_elem().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp( in.get_ref() );
  const Mat<in_eT>& X = tmp.M;
  arma_debug_check( (X.is_vec() == false), "conv_to(): given object can't be interpreted as a vector" );
  itpp::Vec<out_eT> out(X.n_elem);
  syslib::copy_and_convert_elem( out._data(), X.memptr(), X.n_elem );
  return out;
  }
template<typename out_eT > template<typename in_eT , typename T1 > itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const Base< in_eT, T1 > & in, const typename arma_cx_only< in_eT >::result * junk = 0) [inline, static, inherited]
Definition at line 1017 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and syslib::copy_and_convert_cx_elem().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1>      tmp( in.get_ref() );
  const Mat<in_eT>& X = tmp.M;
  itpp::Vec<out_eT> out(X.n_elem);
  syslib::copy_and_convert_cx_elem( out._data(), X.memptr(), X.n_elem );
  return out;
  }