Armadillo Technical: Fn_trace
Fn_trace
Functions
template<typename T1 >
arma_warn_unused T1::elem_type trace (const Base< typename T1::elem_type, T1 > &X)
Immediate trace (sum of diagonal elements) of a square dense matrix.
template<typename T1 >
arma_warn_unused T1::elem_type trace (const Op< T1, op_diagmat > &X)
template<typename T1 , typename T2 >
arma_warn_unused T1::elem_type trace (const Glue< T1, T2, glue_times > &X)
speedup for trace(A*B), where the result of A*B is a square sized matrix
Function Documentation
template<typename T1 > arma_warn_unused T1::elem_type trace (const Base< typename T1::elem_type, T1 > & X) [inline]
Immediate trace (sum of diagonal elements) of a square dense matrix.
Definition at line 26 of file fn_trace.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.get_ref());
  arma_debug_check( (A.n_rows != A.n_cols), "trace(): matrix must be square sized" );
  const u32 N   = A.n_rows;
        eT  val = eT(0);
  for(u32 i=0; i<N; ++i)
    {
    val += A.at(i,i);
    }
  return val;
  }
template<typename T1 > arma_warn_unused T1::elem_type trace (const Op< T1, op_diagmat > & X) [inline]
Definition at line 53 of file fn_trace.hpp.
References Op< T1, op_type >::m, and diagmat_proxy< T1 >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const diagmat_proxy<T1> A(X.m);
  const u32 N = A.n_elem;
  eT val = eT(0);
  for(u32 i=0; i<N; ++i)
    {
    val += A[i];
    }
  return val;
  }
template<typename T1 , typename T2 > arma_warn_unused T1::elem_type trace (const Glue< T1, T2, glue_times > & X) [inline]
speedup for trace(A*B), where the result of A*B is a square sized matrix
Definition at line 79 of file fn_trace.hpp.
References Glue< T1, T2, glue_type >::A, Mat< eT >::at(), Glue< T1, T2, glue_type >::B, Mat< eT >::colptr(), unwrap< T1 >::M, Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(X.A);
  const unwrap<T2> tmp2(X.B);
  const Mat<eT>& A = tmp1.M;
  const Mat<eT>& B = tmp2.M;
  arma_debug_assert_mul_size(A, B, "matrix multiply");
  arma_debug_check( (A.n_rows != B.n_cols), "trace(): matrix must be square sized" );
  const u32 N1  = A.n_rows;
  const u32 N2  = A.n_cols;
        eT  val = eT(0);
  for(u32 i=0; i<N1; ++i)
    {
    const eT* B_colmem = B.colptr(i);
          eT  acc      = eT(0);
    for(u32 j=0; j<N2; ++j)
      {
      acc += A.at(i,j) * B_colmem[j];
      }
    val += acc;
    }
  return val;
  }