Armadillo Technical: Glue_kron
Glue_kron
Classes
class glue_kron
Functions
template<typename eT >
static void glue_kron::direct_kron (Mat< eT > &out, const Mat< eT > &A, const Mat< eT > &B)
both input matrices have the same element type
template<typename T >
static void glue_kron::direct_kron (Mat< std::complex< T > > &out, const Mat< std::complex< T > > &A, const Mat< T > &B)
different types of input matrices A -> complex, B -> basic element type
template<typename T >
static void glue_kron::direct_kron (Mat< std::complex< T > > &out, const Mat< T > &A, const Mat< std::complex< T > > &B)
different types of input matrices A -> basic element type, B -> complex
template<typename T1 , typename T2 >
static void glue_kron::apply (Mat< typename T1::elem_type > &out, const Glue< T1, T2, glue_kron > &X)
apply Kronecker product for two objects with same element type
Function Documentation
template<typename eT > void glue_kron::direct_kron (Mat< eT > & out, const Mat< eT > & A, const Mat< eT > & B) [inline, static, inherited]
both input matrices have the same element type
Definition at line 28 of file glue_kron_meat.hpp.
References Mat< eT >::n_cols, Mat< eT >::n_rows, Mat< eT >::set_size(), and Mat< eT >::submat().
Referenced by apply(), and kron().
  {
  arma_extra_debug_sigprint();
  const u32 A_rows = A.n_rows;
  const u32 A_cols = A.n_cols;
  const u32 B_rows = B.n_rows;
  const u32 B_cols = B.n_cols;
  out.set_size(A_rows*B_rows, A_cols*B_cols);
  for(u32 i = 0; i < A_rows; i++)
    {
    for(u32 j = 0; j < A_cols; j++)
      {
      out.submat(i*B_rows, j*B_cols, (i+1)*B_rows-1, (j+1)*B_cols-1) = A(i,j) * B;
      }
    }
  }
template<typename T > void glue_kron::direct_kron (Mat< std::complex< T > > & out, const Mat< std::complex< T > > & A, const Mat< T > & B) [inline, static, inherited]
different types of input matrices A -> complex, B -> basic element type
Definition at line 56 of file glue_kron_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  typedef typename std::complex<T> eT;
  const u32 A_rows = A.n_rows;
  const u32 A_cols = A.n_cols;
  const u32 B_rows = B.n_rows;
  const u32 B_cols = B.n_cols;
  out.set_size(A_rows*B_rows, A_cols*B_cols);
  Mat<eT> tmp_B = conv_to< Mat<eT> >::from(B);
  for(u32 i = 0; i < A_rows; i++)
    {
    for(u32 j = 0; j < A_cols; j++)
      {
      out.submat(i*B_rows, j*B_cols, (i+1)*B_rows-1, (j+1)*B_cols-1) = A(i,j) * tmp_B;
      }
    }
  }
template<typename T > void glue_kron::direct_kron (Mat< std::complex< T > > & out, const Mat< T > & A, const Mat< std::complex< T > > & B) [inline, static, inherited]
different types of input matrices A -> basic element type, B -> complex
Definition at line 88 of file glue_kron_meat.hpp.
References Mat< eT >::n_cols, and Mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  const u32 A_rows = A.n_rows;
  const u32 A_cols = A.n_cols;
  const u32 B_rows = B.n_rows;
  const u32 B_cols = B.n_cols;
  out.set_size(A_rows*B_rows, A_cols*B_cols);
  for(u32 i = 0; i < A_rows; i++)
    {
    for(u32 j = 0; j < A_cols; j++)
      {
      out.submat(i*B_rows, j*B_cols, (i+1)*B_rows-1, (j+1)*B_cols-1) = A(i,j) * B;
      }
    }
  }
template<typename T1 , typename T2 > void glue_kron::apply (Mat< typename T1::elem_type > & out, const Glue< T1, T2, glue_kron > & X) [inline, static, inherited]
apply Kronecker product for two objects with same element type
Definition at line 115 of file glue_kron_meat.hpp.
References Glue< T1, T2, glue_type >::A, Glue< T1, T2, glue_type >::B, direct_kron(), and unwrap_check< T1 >::M.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_check<T1> A_tmp(X.A, out);
  const unwrap_check<T2> B_tmp(X.B, out);
  const Mat<eT>& A = A_tmp.M;
  const Mat<eT>& B = B_tmp.M;
  glue_kron::direct_kron(out, A, B);
  }