Armadillo Technical: Fn_chol
Fn_chol
Functions
template<typename T1 >
const Op< T1, op_chol > chol (const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
template<typename T1 >
bool chol (Mat< typename T1::elem_type > &out, const Base< typename T1::elem_type, T1 > &X, const typename arma_blas_type_only< typename T1::elem_type >::result *junk=0)
Function Documentation
template<typename T1 > const Op<T1, op_chol> chol (const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
Definition at line 25 of file fn_chol.hpp.
References Base< elem_type, derived >::get_ref().
Referenced by op_chol::apply(), and chol().
  {
  arma_extra_debug_sigprint();
  return Op<T1, op_chol>(X.get_ref());
  }
template<typename T1 > bool chol (Mat< typename T1::elem_type > & out, const Base< typename T1::elem_type, T1 > & X, const typename arma_blas_type_only< typename T1::elem_type >::result * junk = 0) [inline]
Definition at line 37 of file fn_chol.hpp.
References chol(), and Mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  out = chol(X);
  return (out.n_elem == 0) ? false : true;
  }