Armadillo Technical: Operator_ostream
Operator_ostream
Functions
template<typename eT , typename T1 >
std::ostream & operator<< (std::ostream &o, const Base< eT, T1 > &X)
template<typename T1 >
std::ostream & operator<< (std::ostream &o, const BaseCube< typename T1::elem_type, T1 > &X)
template<typename T1 >
std::ostream & operator<< (std::ostream &o, const field< T1 > &X)
Print the contents of a field to the specified stream.
template<typename T1 >
std::ostream & operator<< (std::ostream &o, const subview_field< T1 > &X)
Print the contents of a subfield to the specified stream.
Function Documentation
template<typename eT , typename T1 > std::ostream& operator<< (std::ostream & o, const Base< eT, T1 > & X) [inline]
Definition at line 25 of file operator_ostream.hpp.
References arma_ostream::print().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  arma_ostream::print(o, tmp.M, true);
  return o;
  }
template<typename T1 > std::ostream& operator<< (std::ostream & o, const BaseCube< typename T1::elem_type, T1 > & X) [inline]
Definition at line 41 of file operator_ostream.hpp.
References arma_ostream::print().
  {
  arma_extra_debug_sigprint();
  const unwrap_cube<T1> tmp(X.get_ref());
  arma_ostream::print(o, tmp.M, true);
  return o;
  }
template<typename T1 > std::ostream& operator<< (std::ostream & o, const field< T1 > & X) [inline]
Print the contents of a field to the specified stream.
Definition at line 58 of file operator_ostream.hpp.
References arma_ostream::print().
  {
  arma_extra_debug_sigprint();
  arma_ostream::print(o, X);
  return o;
  }
template<typename T1 > std::ostream& operator<< (std::ostream & o, const subview_field< T1 > & X) [inline]
Print the contents of a subfield to the specified stream.
Definition at line 73 of file operator_ostream.hpp.
References arma_ostream::print().
  {
  arma_extra_debug_sigprint();
  arma_ostream::print(o, X);
  return o;
  }