Armadillo Technical: Row
Row
Classes
class Row< eT >
Class for row vectors (matrices with only one row).
Functions
Row::Row ()
Row::Row (const u32 N)
Row::Row (const u32 in_rows, const u32 in_cols)
Row::Row (const char *text)
const Row & Row::operator= (const char *text)
create the matrix from a textual description
Row::Row (const std::string &text)
const Row & Row::operator= (const std::string &text)
create the matrix from a textual description
Row::Row (const Row &X)
const Row & Row::operator= (const Row &X)
construct a matrix from a given matrix
Row::Row (const Mat< eT > &X)
const Row & Row::operator= (const Mat< eT > &X)
const Row & Row::operator*= (const Mat< eT > &X)
Row::Row (eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem=true)
construct a row vector from a given auxiliary array
Row::Row (const eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols)
construct a row vector from a given auxiliary array
Row::Row (eT *aux_mem, const u32 aux_length, const bool copy_aux_mem=true)
construct a row vector from a given auxiliary array
Row::Row (const eT *aux_mem, const u32 aux_length)
construct a row vector from a given auxiliary array
template<typename T1 , typename T2 >
Row::Row (const Base< pod_type, T1 > &A, const Base< pod_type, T2 > &B)
Row::Row (const subview< eT > &X)
const Row & Row::operator= (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const Row & Row::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Row::Row (const subview_cube< eT > &X)
const Row & Row::operator= (const subview_cube< eT > &X)
construct a matrix from a subview_cube instance
const Row & Row::operator*= (const subview_cube< eT > &X)
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
Row::Row (const diagview< eT > &X)
construct a row vector from given a diagview
const Row & Row::operator= (const diagview< eT > &X)
construct a row vector from given a diagview
const Row & Row::operator*= (const diagview< eT > &X)
in-place matrix mutiplication (using a diagview on the right-hand-side)
arma_inline eT & Row::col (const u32 col_num)
creation of subview (column vector)
arma_inline eT Row::col (const u32 col_num) const
creation of subview (column vector)
arma_inline subview_row< eT > Row::cols (const u32 in_col1, const u32 in_col2)
creation of subview (submatrix comprised of specified column vectors)
arma_inline const subview_row< eT > Row::cols (const u32 in_col1, const u32 in_col2) const
creation of subview (submatrix comprised of specified column vectors)
template<typename T1 , typename op_type >
Row::Row (const Op< T1, op_type > &X)
template<typename T1 , typename op_type >
const Row & Row::operator= (const Op< T1, op_type > &X)
create a matrix from Op, i.e. run the previously delayed unary operations
template<typename T1 , typename op_type >
const Row & Row::operator*= (const Op< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1 , typename eop_type >
Row::Row (const eOp< T1, eop_type > &X)
template<typename T1 , typename eop_type >
const Row & Row::operator= (const eOp< T1, eop_type > &X)
create a matrix from eOp, i.e. run the previously delayed unary operations
template<typename T1 , typename eop_type >
const Row & Row::operator*= (const eOp< T1, eop_type > &X)
template<typename T1 , typename op_type >
Row::Row (const mtOp< eT, T1, op_type > &X)
template<typename T1 , typename op_type >
const Row & Row::operator= (const mtOp< eT, T1, op_type > &X)
EXPERIMENTAL.
template<typename T1 , typename op_type >
const Row & Row::operator*= (const mtOp< eT, T1, op_type > &X)
EXPERIMENTAL.
template<typename T1 , typename T2 , typename glue_type >
Row::Row (const Glue< T1, T2, glue_type > &X)
template<typename T1 , typename T2 , typename glue_type >
const Row & Row::operator= (const Glue< T1, T2, glue_type > &X)
create a matrix from Glue, i.e. run the previously delayed binary operations
template<typename T1 , typename T2 , typename glue_type >
const Row & Row::operator*= (const Glue< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
template<typename T1 , typename T2 , typename eglue_type >
Row::Row (const eGlue< T1, T2, eglue_type > &X)
template<typename T1 , typename T2 , typename eglue_type >
const Row & Row::operator= (const eGlue< T1, T2, eglue_type > &X)
create a matrix from eGlue, i.e. run the previously delayed binary operations
template<typename T1 , typename T2 , typename eglue_type >
const Row & Row::operator*= (const eGlue< T1, T2, eglue_type > &X)
template<typename T1 , typename T2 , typename glue_type >
Row::Row (const mtGlue< eT, T1, T2, glue_type > &X)
template<typename T1 , typename T2 , typename glue_type >
const Row & Row::operator= (const mtGlue< eT, T1, T2, glue_type > &X)
EXPERIMENTAL: create a matrix from Glue, i.e. run the previously delayed binary operations.
template<typename T1 , typename T2 , typename glue_type >
const Row & Row::operator*= (const mtGlue< eT, T1, T2, glue_type > &X)
EXPERIMENTAL: in-place matrix multiplications, with the right-hand-side operands having delayed operations.
void Row::set_size (const u32 N)
void Row::set_size (const u32 n_rows, const u32 n_cols)
change the matrix to have user specified dimensions (data is not preserved)
template<typename eT2 >
void Row::copy_size (const Mat< eT2 > &m)
void Row::zeros ()
void Row::zeros (const u32 N)
void Row::zeros (const u32 n_rows, const u32 n_cols)
void Row::ones ()
void Row::ones (const u32 N)
void Row::ones (const u32 n_rows, const u32 n_cols)
void Row::load (const std::string name, const file_type type=auto_detect, const bool print_status=true)
load a matrix from a file
void Row::load (std::istream &is, const file_type type=auto_detect, const bool print_status=true)
load a matrix from a stream
void Row::quiet_load (const std::string name, const file_type type=auto_detect)
load a matrix from a file, without printing any error messages
void Row::quiet_load (std::istream &is, const file_type type=auto_detect)
load a matrix from a stream, without printing any error messages
row_iterator Row::begin_row (const u32 row_num)
const_row_iterator Row::begin_row (const u32 row_num) const
row_iterator Row::end_row (const u32 row_num)
const_row_iterator Row::end_row (const u32 row_num) const
Function Documentation
template<typename eT > Row< eT >::Row () [inline, inherited]
Definition at line 22 of file Row_meat.hpp.
  : Mat<eT>()
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > Row< eT >::Row (const u32 N) [inline, explicit, inherited]
Definition at line 32 of file Row_meat.hpp.
  : Mat<eT>(1,in_n_elem)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > Row< eT >::Row (const u32 in_rows, const u32 in_cols) [inline, inherited]
Definition at line 42 of file Row_meat.hpp.
  : Mat<eT>(in_n_rows, in_n_cols)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > Row< eT >::Row (const char * text) [inline, inherited]
Definition at line 54 of file Row_meat.hpp.
  : Mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > const Row< eT > & Row< eT >::operator= (const char * text) [inline, inherited]
create the matrix from a textual description
Reimplemented from Mat< eT >.
Definition at line 67 of file Row_meat.hpp.
Referenced by Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(text);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > Row< eT >::Row (const std::string & text) [inline, inherited]
Definition at line 82 of file Row_meat.hpp.
  : Mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > const Row< eT > & Row< eT >::operator= (const std::string & text) [inline, inherited]
create the matrix from a textual description
Reimplemented from Mat< eT >.
Definition at line 95 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(text);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > Row< eT >::Row (const Row< eT > & X) [inline, inherited]
Definition at line 110 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT > const Row< eT > & Row< eT >::operator= (const Row< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Reimplemented from Mat< eT >.
Definition at line 121 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  return *this;
  }
template<typename eT> Row< eT >::Row (const Mat< eT > & X) [inline, inherited]
Definition at line 133 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> const Row< eT > & Row< eT >::operator= (const Mat< eT > & X) [inline, inherited]
Definition at line 146 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Row< eT > & Row< eT >::operator*= (const Mat< eT > & X) [inline, inherited]
Definition at line 160 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Row< eT >::Row (eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols, const bool copy_aux_mem = true) [inline, inherited]
construct a row vector from a given auxiliary array
Definition at line 174 of file Row_meat.hpp.
  : Mat<eT>(aux_mem, aux_n_rows, aux_n_cols, copy_aux_mem)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> Row< eT >::Row (const eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols) [inline, inherited]
construct a row vector from a given auxiliary array
Definition at line 187 of file Row_meat.hpp.
  : Mat<eT>(aux_mem, aux_n_rows, aux_n_cols)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> Row< eT >::Row (eT * aux_mem, const u32 aux_length, const bool copy_aux_mem = true) [inline, inherited]
construct a row vector from a given auxiliary array
Definition at line 200 of file Row_meat.hpp.
  : Mat<eT>(aux_mem, 1, aux_length, copy_aux_mem)
  {
  arma_extra_debug_sigprint();
//   Mat<eT>::set_size(1, aux_length);
//   arma_check((Mat<eT>::n_elem != aux_length), "Row(): don't know how to handle the given array");
//
//   syslib::copy_elem(Mat<eT>::memptr(), aux_mem, Mat<eT>::n_elem);
  }
template<typename eT> Row< eT >::Row (const eT * aux_mem, const u32 aux_length) [inline, inherited]
construct a row vector from a given auxiliary array
Definition at line 216 of file Row_meat.hpp.
  : Mat<eT>(aux_mem, 1, aux_length)
  {
  arma_extra_debug_sigprint();
//   Mat<eT>::set_size(1, aux_length);
//   arma_check((Mat<eT>::n_elem != aux_length), "Row(): don't know how to handle the given array");
//
//   syslib::copy_elem(Mat<eT>::memptr(), aux_mem, Mat<eT>::n_elem);
  }
template<typename eT > template<typename T1 , typename T2 > Row< eT >::Row (const Base< pod_type, T1 > & A, const Base< pod_type, T2 > & B) [inline, explicit, inherited]
Definition at line 233 of file Row_meat.hpp.
  : Mat<eT>(A,B)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> Row< eT >::Row (const subview< eT > & X) [inline, inherited]
Definition at line 248 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> const Row< eT > & Row< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Reimplemented from Mat< eT >.
Definition at line 261 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Row< eT > & Row< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 277 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Row< eT >::Row (const subview_cube< eT > & X) [inline, inherited]
Definition at line 292 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> const Row< eT > & Row< eT >::operator= (const subview_cube< eT > & X) [inline, inherited]
construct a matrix from a subview_cube instance
Reimplemented from Mat< eT >.
Definition at line 305 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Row< eT > & Row< eT >::operator*= (const subview_cube< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a single-slice subcube on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 321 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> Row< eT >::Row (const diagview< eT > & X) [inline, explicit, inherited]
construct a row vector from given a diagview
Definition at line 337 of file Row_meat.hpp.
References access::rw().
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> const Row< eT > & Row< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a row vector from given a diagview
Reimplemented from Mat< eT >.
Definition at line 353 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  //std::swap( access::rw(Mat<eT>::n_rows), access::rw(Mat<eT>::n_cols) );
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const Row< eT > & Row< eT >::operator*= (const diagview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a diagview on the right-hand-side)
Reimplemented from Mat< eT >.
Definition at line 370 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > arma_inline eT & Row< eT >::col (const u32 col_num) [inline, inherited]
creation of subview (column vector)
Reimplemented from Mat< eT >.
Definition at line 386 of file Row_meat.hpp.
References access::rw().
  {
  arma_debug_check( (col_num >= Mat<eT>::n_cols), "Row::col(): out of bounds" );
  return access::rw(Mat<eT>::mem[col_num]);
  }
template<typename eT > arma_inline eT Row< eT >::col (const u32 col_num) const [inline, inherited]
creation of subview (column vector)
Reimplemented from Mat< eT >.
Definition at line 398 of file Row_meat.hpp.
  {
  arma_debug_check( (col_num >= Mat<eT>::n_cols), "Row::col(): out of bounds" );
  return Mat<eT>::mem[col_num];
  }
template<typename eT > arma_inline subview_row< eT > Row< eT >::cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Reimplemented from Mat< eT >.
Definition at line 411 of file Row_meat.hpp.
  {
  arma_debug_check( ( (in_col1 > in_col2) || (in_col2 >= Mat<eT>::n_cols) ), "Row::cols(): indices out of bounds or incorrectly used");
  return subview_row<eT>(*this, 0, in_col1, in_col2);
  }
template<typename eT > arma_inline const subview_row< eT > Row< eT >::cols (const u32 in_col1, const u32 in_col2) const [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Reimplemented from Mat< eT >.
Definition at line 423 of file Row_meat.hpp.
  {
  arma_debug_check( ( (in_col1 > in_col2) || (in_col2 >= Mat<eT>::n_cols) ), "Row::cols(): indices out of bounds or incorrectly used");
  return subview_row<eT>(*this, 0, in_col1, in_col2);
  }
template<typename eT > template<typename T1 , typename op_type > Row< eT >::Row (const Op< T1, op_type > & X) [inline, inherited]
Definition at line 436 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename op_type > const Row< eT > & Row< eT >::operator= (const Op< T1, op_type > & X) [inline, inherited]
create a matrix from Op, i.e. run the previously delayed unary operations
Reimplemented from Mat< eT >.
Definition at line 450 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename op_type > const Row< eT > & Row< eT >::operator*= (const Op< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented from Mat< eT >.
Definition at line 467 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename eop_type > Row< eT >::Row (const eOp< T1, eop_type > & X) [inline, inherited]
Definition at line 483 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > template<typename T1 , typename eop_type > const Row< eT > & Row< eT >::operator= (const eOp< T1, eop_type > & X) [inline, inherited]
create a matrix from eOp, i.e. run the previously delayed unary operations
Reimplemented from Mat< eT >.
Definition at line 497 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > template<typename T1 , typename eop_type > const Row< eT > & Row< eT >::operator*= (const eOp< T1, eop_type > & X) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 514 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename op_type > Row< eT >::Row (const mtOp< eT, T1, op_type > & X) [inline, inherited]
Definition at line 530 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> template<typename T1 , typename op_type > const Row< eT > & Row< eT >::operator= (const mtOp< eT, T1, op_type > & X) [inline, inherited]
EXPERIMENTAL.
Reimplemented from Mat< eT >.
Definition at line 544 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename op_type > const Row< eT > & Row< eT >::operator*= (const mtOp< eT, T1, op_type > & X) [inline, inherited]
EXPERIMENTAL.
Reimplemented from Mat< eT >.
Definition at line 561 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > Row< eT >::Row (const Glue< T1, T2, glue_type > & X) [inline, inherited]
Definition at line 577 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > const Row< eT > & Row< eT >::operator= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from Glue, i.e. run the previously delayed binary operations
Reimplemented from Mat< eT >.
Definition at line 591 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > const Row< eT > & Row< eT >::operator*= (const Glue< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented from Mat< eT >.
Definition at line 608 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename eglue_type > Row< eT >::Row (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
Definition at line 624 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> template<typename T1 , typename T2 , typename eglue_type > const Row< eT > & Row< eT >::operator= (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
create a matrix from eGlue, i.e. run the previously delayed binary operations
Reimplemented from Mat< eT >.
Definition at line 638 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename eglue_type > const Row< eT > & Row< eT >::operator*= (const eGlue< T1, T2, eglue_type > & X) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 655 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > Row< eT >::Row (const mtGlue< eT, T1, T2, glue_type > & X) [inline, inherited]
Definition at line 671 of file Row_meat.hpp.
  : Mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > const Row< eT > & Row< eT >::operator= (const mtGlue< eT, T1, T2, glue_type > & X) [inline, inherited]
EXPERIMENTAL: create a matrix from Glue, i.e. run the previously delayed binary operations.
Reimplemented from Mat< eT >.
Definition at line 685 of file Row_meat.hpp.
References Row< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1 , typename T2 , typename glue_type > const Row< eT > & Row< eT >::operator*= (const mtGlue< eT, T1, T2, glue_type > & X) [inline, inherited]
EXPERIMENTAL: in-place matrix multiplications, with the right-hand-side operands having delayed operations.
Reimplemented from Mat< eT >.
Definition at line 702 of file Row_meat.hpp.
References Row< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::operator*=(X);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  return *this;
  }
template<typename eT > void Row< eT >::set_size (const u32 N) [inline, inherited]
Definition at line 718 of file Row_meat.hpp.
Referenced by Row< eT >::copy_size(), and Row< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::set_size(1,in_n_elem);
  }
template<typename eT > void Row< eT >::set_size (const u32 in_rows, const u32 in_cols) [inline, inherited]
change the matrix to have user specified dimensions (data is not preserved)
Reimplemented from Mat< eT >.
Definition at line 730 of file Row_meat.hpp.
References min(), and Row< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  // min is used in case in_n_rows is zero
  Mat<eT>::set_size( (std::min)( u32(1), in_n_rows), in_n_cols );
  arma_debug_check( (in_n_rows > 1), "Row::set_size(): incompatible dimensions" );
  }
template<typename eT > template<typename eT2 > void Row< eT >::copy_size (const Mat< eT2 > & m) [inline, inherited]
Definition at line 746 of file Row_meat.hpp.
References min(), Mat< eT >::n_cols, Mat< eT >::n_rows, and Row< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  // min is used in case x.n_rows is zero
  Mat<eT>::set_size( (std::min)( u32(1), x.n_rows), x.n_cols );
  arma_debug_check( (x.n_rows > 1), "Row::copy_size(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::zeros () [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 761 of file Row_meat.hpp.
Referenced by Row< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::zeros();
  }
template<typename eT > void Row< eT >::zeros (const u32 N) [inline, inherited]
Definition at line 773 of file Row_meat.hpp.
References Row< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::zeros(1, in_n_elem);
  }
template<typename eT > void Row< eT >::zeros (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 785 of file Row_meat.hpp.
References min(), and Row< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  // min is used in case in_n_rows is zero
  Mat<eT>::zeros( (std::min)( u32(1), in_n_rows), in_n_cols );
  arma_debug_check( (in_n_rows > 1), "Row<eT>::zeros(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::ones () [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 800 of file Row_meat.hpp.
Referenced by Row< eT >::ones().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::ones();
  }
template<typename eT > void Row< eT >::ones (const u32 N) [inline, inherited]
Definition at line 812 of file Row_meat.hpp.
References Row< eT >::ones().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::ones(1, in_n_elem);
  }
template<typename eT > void Row< eT >::ones (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 824 of file Row_meat.hpp.
References min(), and Row< eT >::ones().
  {
  arma_extra_debug_sigprint();
  // min is used in case in_n_rows is zero
  Mat<eT>::ones( (std::min)( u32(1), in_n_rows), in_n_cols );
  arma_debug_check( (in_n_rows > 1), "Row<eT>::ones(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::load (const std::string name, const file_type type = auto_detect, const bool print_status = true) [inline, inherited]
load a matrix from a file
Reimplemented from Mat< eT >.
Definition at line 839 of file Row_meat.hpp.
Referenced by Row< eT >::load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::load(name, type, print_status);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::load (std::istream & is, const file_type type = auto_detect, const bool print_status = true) [inline, inherited]
load a matrix from a stream
Reimplemented from Mat< eT >.
Definition at line 853 of file Row_meat.hpp.
References Row< eT >::load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::load(is, type, print_status);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::quiet_load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file, without printing any error messages
Reimplemented from Mat< eT >.
Definition at line 867 of file Row_meat.hpp.
Referenced by Row< eT >::quiet_load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::quiet_load(name, type);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > void Row< eT >::quiet_load (std::istream & is, const file_type type = auto_detect) [inline, inherited]
load a matrix from a stream, without printing any error messages
Reimplemented from Mat< eT >.
Definition at line 881 of file Row_meat.hpp.
References Row< eT >::quiet_load().
  {
  arma_extra_debug_sigprint();
  Mat<eT>::quiet_load(is, type);
  arma_debug_check( (Mat<eT>::n_rows > 1), "Row(): incompatible dimensions" );
  }
template<typename eT > Row< eT >::row_iterator Row< eT >::begin_row (const u32 row_num) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 895 of file Row_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "begin_row(): index out of bounds");
  return Mat<eT>::memptr();
  }
template<typename eT > Row< eT >::const_row_iterator Row< eT >::begin_row (const u32 row_num) const [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 909 of file Row_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "begin_row(): index out of bounds");
  return Mat<eT>::memptr();
  }
template<typename eT > Row< eT >::row_iterator Row< eT >::end_row (const u32 row_num) [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 923 of file Row_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "end_row(): index out of bounds");
  return Mat<eT>::memptr() + Mat<eT>::n_cols;
  }
template<typename eT > Row< eT >::const_row_iterator Row< eT >::end_row (const u32 row_num) const [inline, inherited]
Reimplemented from Mat< eT >.
Definition at line 937 of file Row_meat.hpp.
References Mat< eT >::memptr().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= Mat<eT>::n_rows), "end_row(): index out of bounds");
  return Mat<eT>::memptr() + Mat<eT>::n_cols;
  }