Armadillo Technical: Operator_schur
Operator_schur
Functions
template<typename T1 , typename T2 >
arma_inline const eGlue< T1,
T2, eglue_schur > operator% (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, T2 > &Y)
element-wise multiplication of Base objects with same element type
template<typename T1 , typename T2 >
const mtGlue< typename
promote_type< typename
T1::elem_type, typename
T2::elem_type >::result, T1,
T2, glue_mixed_schur > operator% (const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T1_result, T1 > &X, const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T2_result, T2 > &Y)
element-wise multiplication of Base objects with different element types
Function Documentation
template<typename T1 , typename T2 > arma_inline const eGlue<T1, T2, eglue_schur> operator% (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
element-wise multiplication of Base objects with same element type
Definition at line 29 of file operator_schur.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return eGlue<T1, T2, eglue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1 , typename T2 > const mtGlue<typename promote_type<typename T1::elem_type, typename T2::elem_type>::result, T1, T2, glue_mixed_schur> operator% (const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T1_result, T1 > & X, const Base< typename force_different_type< typename T1::elem_type, typename T2::elem_type >::T2_result, T2 > & Y) [inline]
element-wise multiplication of Base objects with different element types
Definition at line 46 of file operator_schur.hpp.
References promote_type< T1, T2 >::check(), and Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT1;
  typedef typename T2::elem_type eT2;
  typedef typename promote_type<eT1,eT2>::result out_eT;
  promote_type<eT1,eT2>::check();
  return mtGlue<out_eT, T1, T2, glue_mixed_schur>( X.get_ref(), Y.get_ref() );
  }