Armadillo Technical: Operator_relational
Operator_relational
Functions
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_lt > operator< (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > &Y)
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_gt > operator> (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > &Y)
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_lteq > operator<= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > &Y)
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_gteq > operator>= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > &Y)
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_eq > operator== (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, T2 > &Y)
template<typename T1 , typename T2 >
const mtGlue< u32, T1, T2,
glue_rel_noteq > operator!= (const Base< typename T1::elem_type, T1 > &X, const Base< typename T1::elem_type, T2 > &Y)
template<typename T1 >
const mtOp< u32, T1,
op_rel_lt_pre > operator< (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X)
template<typename T1 >
const mtOp< u32, T1,
op_rel_lt_post > operator< (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const typename arma_not_cx< typename T1::elem_type >::result val)
template<typename T1 >
const mtOp< u32, T1,
op_rel_gt_pre > operator> (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X)
template<typename T1 >
const mtOp< u32, T1,
op_rel_gt_post > operator> (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const typename arma_not_cx< typename T1::elem_type >::result val)
template<typename T1 >
const mtOp< u32, T1,
op_rel_lteq_pre > operator<= (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X)
template<typename T1 >
const mtOp< u32, T1,
op_rel_lteq_post > operator<= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const typename arma_not_cx< typename T1::elem_type >::result val)
template<typename T1 >
const mtOp< u32, T1,
op_rel_gteq_pre > operator>= (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X)
template<typename T1 >
const mtOp< u32, T1,
op_rel_gteq_post > operator>= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > &X, const typename arma_not_cx< typename T1::elem_type >::result val)
template<typename T1 >
const mtOp< u32, T1, op_rel_eq > operator== (const typename T1::elem_type val, const Base< typename T1::elem_type, T1 > &X)
template<typename T1 >
const mtOp< u32, T1, op_rel_eq > operator== (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type val)
template<typename T1 >
const mtOp< u32, T1, op_rel_noteq > operator!= (const typename T1::elem_type val, const Base< typename T1::elem_type, T1 > &X)
template<typename T1 >
const mtOp< u32, T1, op_rel_noteq > operator!= (const Base< typename T1::elem_type, T1 > &X, const typename T1::elem_type val)
Function Documentation
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_lt> operator< (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > & Y) [inline]
Definition at line 34 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_lt>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_gt> operator> (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > & Y) [inline]
Definition at line 47 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_gt>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_lteq> operator<= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > & Y) [inline]
Definition at line 60 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_lteq>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_gteq> operator>= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const Base< typename arma_not_cx< typename T1::elem_type >::result, T2 > & Y) [inline]
Definition at line 73 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_gteq>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_eq> operator== (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
Definition at line 86 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_eq>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 , typename T2 > const mtGlue<u32, T1, T2, glue_rel_noteq> operator!= (const Base< typename T1::elem_type, T1 > & X, const Base< typename T1::elem_type, T2 > & Y) [inline]
Definition at line 99 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtGlue<u32, T1, T2, glue_rel_noteq>( X.get_ref(), Y.get_ref() );
  }
template<typename T1 > const mtOp<u32, T1, op_rel_lt_pre> operator< (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X) [inline]
Definition at line 118 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_lt_pre>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_lt_post> operator< (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const typename arma_not_cx< typename T1::elem_type >::result val) [inline]
Definition at line 131 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_lt_post>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_gt_pre> operator> (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X) [inline]
Definition at line 144 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_gt_pre>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_gt_post> operator> (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const typename arma_not_cx< typename T1::elem_type >::result val) [inline]
Definition at line 157 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_gt_post>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_lteq_pre> operator<= (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X) [inline]
Definition at line 170 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_lteq_pre>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_lteq_post> operator<= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const typename arma_not_cx< typename T1::elem_type >::result val) [inline]
Definition at line 183 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_lteq_post>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_gteq_pre> operator>= (const typename arma_not_cx< typename T1::elem_type >::result val, const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X) [inline]
Definition at line 196 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_gteq_pre>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_gteq_post> operator>= (const Base< typename arma_not_cx< typename T1::elem_type >::result, T1 > & X, const typename arma_not_cx< typename T1::elem_type >::result val) [inline]
Definition at line 209 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_gteq_post>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_eq> operator== (const typename T1::elem_type val, const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 222 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_eq>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_eq> operator== (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type val) [inline]
Definition at line 235 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_eq>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_noteq> operator!= (const typename T1::elem_type val, const Base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 248 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_noteq>(X.get_ref(), val);
  }
template<typename T1 > const mtOp<u32, T1, op_rel_noteq> operator!= (const Base< typename T1::elem_type, T1 > & X, const typename T1::elem_type val) [inline]
Definition at line 261 of file operator_relational.hpp.
References Base< elem_type, derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return mtOp<u32, T1, op_rel_noteq>(X.get_ref(), val);
  }