Armadillo Technical: Op_relational
Op_relational
Classes
class op_rel_lt_pre
class op_rel_lt_post
class op_rel_gt_pre
class op_rel_gt_post
class op_rel_lteq_pre
class op_rel_lteq_post
class op_rel_gteq_pre
class op_rel_gteq_post
class op_rel_eq
class op_rel_noteq
Functions
template<typename T1 >
static void op_rel_lt_pre::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_lt_pre > &X)
template<typename T1 >
static void op_rel_lt_post::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_lt_post > &X)
template<typename T1 >
static void op_rel_gt_pre::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_gt_pre > &X)
template<typename T1 >
static void op_rel_gt_post::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_gt_post > &X)
template<typename T1 >
static void op_rel_lteq_pre::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_lteq_pre > &X)
template<typename T1 >
static void op_rel_lteq_post::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_lteq_post > &X)
template<typename T1 >
static void op_rel_gteq_pre::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_gteq_pre > &X)
template<typename T1 >
static void op_rel_gteq_post::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_gteq_post > &X)
template<typename T1 >
static void op_rel_eq::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_eq > &X)
template<typename T1 >
static void op_rel_noteq::apply (Mat< u32 > &out, const mtOp< u32, T1, op_rel_noteq > &X)
Function Documentation
template<typename T1 > void op_rel_lt_pre::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_lt_pre > & X) [inline, static, inherited]
Definition at line 25 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (val < A[i]) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_lt_post::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_lt_post > & X) [inline, static, inherited]
Definition at line 50 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] < val) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_gt_pre::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_gt_pre > & X) [inline, static, inherited]
Definition at line 75 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (val > A[i]) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_gt_post::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_gt_post > & X) [inline, static, inherited]
Definition at line 100 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] > val) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_lteq_pre::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_lteq_pre > & X) [inline, static, inherited]
Definition at line 125 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (val <= A[i]) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_lteq_post::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_lteq_post > & X) [inline, static, inherited]
Definition at line 150 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] <= val) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_gteq_pre::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_gteq_pre > & X) [inline, static, inherited]
Definition at line 175 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (val >= A[i]) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_gteq_post::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_gteq_post > & X) [inline, static, inherited]
Definition at line 200 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] >= val) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_eq::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_eq > & X) [inline, static, inherited]
Definition at line 225 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] == val) ? u32(1) : u32(0);
    }
  }
template<typename T1 > void op_rel_noteq::apply (Mat< u32 > & out, const mtOp< u32, T1, op_rel_noteq > & X) [inline, static, inherited]
Definition at line 250 of file op_relational_meat.hpp.
References mtOp< out_eT, T1, op_type >::aux, mtOp< out_eT, T1, op_type >::m, Mat< eT >::memptr(), and Mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const Proxy<T1> A(X.m);
  out.set_size(A.n_rows, A.n_cols);
  const u32  n_elem  = A.n_elem;
  const eT   val     = X.aux;
        u32* out_mem = out.memptr();
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = (A[i] != val) ? u32(1) : u32(0);
    }
  }