Armadillo Technical: basic_math< eT > Class Template Reference
basic_math< eT > Class Template Reference
[Constants]
#include <constants.hpp>
Detailed Description
template<typename eT>
class basic_math< eT >
Definition at line 24 of file constants.hpp.
Static Public Member Functions
static const eT pi ()
ratio of any circle's circumference to its diameter
static const eT e ()
base of the natural logarithm
static const eT euler ()
Euler's constant, aka Euler-Mascheroni constant.
static const eT gratio ()
golden ratio
static const eT sqrt2 ()
square root of 2
static const eT eps ()
the difference between 1 and the least value greater than 1 that is representable
static const eT log_min ()
log of the minimum representable value
static const eT log_max ()
log of the maximum representable value
Member Function Documentation
template<typename eT> static const eT basic_math< eT >::pi () [inline, static]
ratio of any circle's circumference to its diameter
Definition at line 29 of file constants.hpp.
{ return eT(3.1415926535897932384626433832795028841971693993751058209749445923078164062862089986280348253421170679); }
template<typename eT> static const eT basic_math< eT >::e () [inline, static]
base of the natural logarithm
Definition at line 32 of file constants.hpp.
{ return eT(2.7182818284590452353602874713526624977572470936999595749669676277240766303535475945713821785251664274); }
template<typename eT> static const eT basic_math< eT >::euler () [inline, static]
Euler's constant, aka Euler-Mascheroni constant.
Definition at line 35 of file constants.hpp.
{ return eT(0.5772156649015328606065120900824024310421593359399235988057672348848677267776646709369470632917467495); }
template<typename eT> static const eT basic_math< eT >::gratio () [inline, static]
golden ratio
Definition at line 38 of file constants.hpp.
{ return eT(1.6180339887498948482045868343656381177203091798057628621354486227052604628189024497072072041893911374); }
template<typename eT> static const eT basic_math< eT >::sqrt2 () [inline, static]
square root of 2
Definition at line 41 of file constants.hpp.
{ return eT(1.4142135623730950488016887242096980785696718753769480731766797379907324784621070388503875343276415727); }
template<typename eT> static const eT basic_math< eT >::eps () [inline, static]
the difference between 1 and the least value greater than 1 that is representable
Definition at line 44 of file constants.hpp.
{ return std::numeric_limits<eT>::epsilon(); }
template<typename eT> static const eT basic_math< eT >::log_min () [inline, static]
log of the minimum representable value
Definition at line 47 of file constants.hpp.
References log(), and min().
Referenced by trunc_log().
{ static const eT out = std::log(std::numeric_limits<eT>::min()); return out; }
template<typename eT> static const eT basic_math< eT >::log_max () [inline, static]
log of the maximum representable value
Definition at line 50 of file constants.hpp.
References log(), and max().
Referenced by trunc_log().
{ static const eT out = std::log(std::numeric_limits<eT>::max()); return out; }