Armadillo Technical: gemm_mixed< do_trans_A, do_trans_B, use_alpha, use_beta > Class Template Reference
gemm_mixed< do_trans_A, do_trans_B, use_alpha, use_beta > Class Template Reference
[Gemm_mixed]
#include <gemm_mixed.hpp>
Detailed Description
template<const bool do_trans_A = false, const bool do_trans_B = false, const bool use_alpha = false, const bool use_beta = false>
class gemm_mixed< do_trans_A, do_trans_B, use_alpha, use_beta >
Matrix multplication where the matrices have different element types.
Definition at line 404 of file gemm_mixed.hpp.
Static Public Member Functions
template<typename out_eT, typename in_eT1, typename in_eT2>
static void apply (basic_mat< out_eT > &C, const basic_mat< in_eT1 > &A, const basic_mat< in_eT2 > &B, const out_eT alpha=out_eT(1), const out_eT beta=out_eT(0))
immediate multiplication of matrices A and B, storing the result in C
Member Function Documentation
template<const bool do_trans_A = false, const bool do_trans_B = false, const bool use_alpha = false, const bool use_beta = false> template<typename out_eT, typename in_eT1, typename in_eT2> static void gemm_mixed< do_trans_A, do_trans_B, use_alpha, use_beta >::apply (basic_mat< out_eT > & C, const basic_mat< in_eT1 > & A, const basic_mat< in_eT2 > & B, const out_eT alpha = out_eT(1), const out_eT beta = out_eT(0)) [inline, static]
immediate multiplication of matrices A and B, storing the result in C
Definition at line 414 of file gemm_mixed.hpp.
References gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), and basic_mat< eT >::n_elem.
Referenced by glue_times::apply_mixed().
    {
    arma_extra_debug_sigprint();
    if( (A.n_elem <= 64u) && (B.n_elem <= 64u) )
      {
      gemm_mixed_simple<do_trans_A, do_trans_B, use_alpha, use_beta>::apply(C,A,B,alpha,beta);
      }
    else
      {
      gemm_mixed_cache<do_trans_A, do_trans_B, use_alpha, use_beta>::apply(C,A,B,alpha,beta);
      }
    }