Armadillo Technical: access Class Reference
access Class Reference
[Access]
#include <access.hpp>
Detailed Description
Definition at line 20 of file access.hpp.
Static Public Member Functions
template<typename T1>
static T1 & rw (const T1 &x)
internal function to allow modification of data declared as read-only
Member Function Documentation
template<typename T1> static T1& access::rw (const T1 & x) [inline, static]
internal function to allow modification of data declared as read-only
Definition at line 28 of file access.hpp.
Referenced by subview< eT >::at(), basic_mat< eT >::at(), basic_colvec< eT >::basic_colvec(), basic_mat< eT >::basic_mat(), basic_rowvec< eT >::basic_rowvec(), subview< eT >::colptr(), basic_mat< eT >::colptr(), podarray< T1 >::fill(), basic_mat< eT >::fill(), podarray< T1 >::init(), field< oT >::init(), basic_mat< eT >::init(), subview< eT >::operator()(), podarray< T1 >::operator()(), basic_mat< eT >::operator()(), basic_mat< eT >::operator*=(), basic_mat< eT >::operator+=(), basic_mat< eT >::operator-=(), basic_mat< eT >::operator/=(), podarray< T1 >::operator=(), basic_mat< eT >::operator=(), basic_colvec< eT >::operator=(), subview< eT >::operator[](), podarray< T1 >::operator[](), basic_mat< eT >::operator[](), reshape(), basic_mat< eT >::swap_rows(), basic_mat< eT >::~basic_mat(), and podarray< T1 >::~podarray().
{ return const_cast<T1&>(x); }