Armadillo Technical: auxlib Class Reference
auxlib Class Reference
[Auxlib]
#include <auxlib_proto.hpp>
Detailed Description
wrapper for accessing external functions defined in ATLAS, LAPACK or BLAS libraries
Definition at line 21 of file auxlib_proto.hpp.
Static Public Member Functions
template<typename eT>
static const eT & tmp_real (const eT &X)
template<typename T>
static const T & tmp_real (const std::complex< T > &X)
template<typename eT>
static void inv_noalias (basic_mat< eT > &out, const basic_mat< eT > &X)
immediate matrix inverse
template<typename eT>
static void inv_inplace (basic_mat< eT > &X)
immediate inplace matrix inverse
template<typename eT>
static eT det (const basic_mat< eT > &X)
immediate determinant of a matrix using ATLAS or LAPACK
template<typename eT>
static void lu (basic_mat< eT > &L, basic_mat< eT > &U, podarray< int > &ipiv, const basic_mat< eT > &X_orig)
immediate LU decomposition of a matrix using ATLAS or LAPACK
template<typename eT>
static void lu (basic_mat< eT > &L, basic_mat< eT > &U, basic_mat< eT > &P, const basic_mat< eT > &X)
template<typename eT>
static void lu (basic_mat< eT > &L, basic_mat< eT > &U, const basic_mat< eT > &X)
template<typename eT>
static void eig (basic_colvec< eT > &eigval, const basic_mat< eT > &A)
immediate eigenvalues of a symmetric matrix using LAPACK
template<typename eT>
static void eig (basic_colvec< eT > &eigval, basic_mat< eT > &eigvec, const basic_mat< eT > &A)
immediate eigenvalues and eigenvectors of a symmetric matrix using LAPACK
template<typename eT>
static bool chol (basic_mat< eT > &out, const basic_mat< eT > &X)
template<typename eT>
static bool qr (basic_mat< eT > &Q, basic_mat< eT > &R, const basic_mat< eT > &X)
template<typename eT>
static bool svd (basic_colvec< eT > &S, const basic_mat< eT > &X)
template<typename T>
static bool svd (basic_colvec< T > &S, const basic_mat< std::complex< T > > &X)
template<typename eT>
static bool svd (basic_mat< eT > &U, basic_colvec< eT > &S, basic_mat< eT > &V, const basic_mat< eT > &X)
template<typename T>
static bool svd (basic_mat< std::complex< T > > &U, basic_colvec< T > &S, basic_mat< std::complex< T > > &V, const basic_mat< std::complex< T > > &X)
template<typename eT>
static bool solve (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B)
Solve a system of linear equations Assumes that A.n_rows = A.n_cols and B.n_rows = A.n_rows.
template<typename eT>
static bool solve_od (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B)
Solve an over-determined system. Assumes that A.n_rows > A.n_cols and B.n_rows = A.n_rows.
template<typename eT>
static bool solve_ud (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B)
Solve an under-determined system. Assumes that A.n_rows < A.n_cols and B.n_rows = A.n_rows.
Member Function Documentation
template<typename eT> static const eT& auxlib::tmp_real (const eT & X) [inline, static]
Definition at line 26 of file auxlib_proto.hpp.
Referenced by inv_inplace(), inv_noalias(), and qr().
{ return X; }
template<typename T> static const T& auxlib::tmp_real (const std::complex< T > & X) [inline, static]
Definition at line 29 of file auxlib_proto.hpp.
{ return X.real(); }