Armadillo Technical: gemv_arma< do_trans_A, use_alpha, use_beta > Class Template Reference
gemv_arma< do_trans_A, use_alpha, use_beta > Class Template Reference
[Gemv]
#include <gemv.hpp>
Detailed Description
template<const bool do_trans_A = false, const bool use_alpha = false, const bool use_beta = false>
class gemv_arma< do_trans_A, use_alpha, use_beta >
Partial emulation of ATLAS/BLAS gemv(). 'y' is assumed to have been set to the correct size (i.e. taking into account the transpose).
Definition at line 26 of file gemv.hpp.
Static Public Member Functions
template<typename eT>
static void apply (eT *y, const basic_mat< eT > &A, const eT *x, const eT alpha=eT(1), const eT beta=eT(0))
Member Function Documentation
template<const bool do_trans_A = false, const bool use_alpha = false, const bool use_beta = false> template<typename eT> static void gemv_arma< do_trans_A, use_alpha, use_beta >::apply (eT * y, const basic_mat< eT > & A, const eT * x, const eT alpha = eT(1), const eT beta = eT(0)) [inline, static]
Definition at line 34 of file gemv.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::colptr(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
Referenced by gemv< do_trans_A, use_alpha, use_beta >::apply().
    {
    arma_extra_debug_sigprint();
    const u32 A_n_rows = A.n_rows;
    const u32 A_n_cols = A.n_cols;
    if(do_trans_A == false)
      {
      for(u32 row=0; row < A_n_rows; ++row)
        {
        eT acc = eT(0);
        for(u32 col=0; col < A_n_cols; ++col)
          {
          acc += A.at(row,col) * x[col];
          }
        if( (use_alpha == false) && (use_beta == false) )
          {
          y[row] = acc;
          }
        else
        if( (use_alpha == true) && (use_beta == false) )
          {
          y[row] = alpha * acc;
          }
        else
        if( (use_alpha == false) && (use_beta == true) )
          {
          y[row] = acc + beta*y[row];
          }
        else
        if( (use_alpha == true) && (use_beta == true) )
          {
          y[row] = alpha*acc + beta*y[row];
          }
        }
      }
    else
    if(do_trans_A == true)
      {
      for(u32 col=0; col < A_n_cols; ++col)
        {
        // col is interpreted as row when storing the results in 'y'
        const eT* A_coldata = A.colptr(col);
        eT acc = eT(0);
        for(u32 row=0; row < A_n_rows; ++row)
          {
          acc += A_coldata[row] * x[row];
          }
        if( (use_alpha == false) && (use_beta == false) )
          {
          y[col] = acc;
          }
        else
        if( (use_alpha == true) && (use_beta == false) )
          {
          y[col] = alpha * acc;
          }
        else
        if( (use_alpha == false) && (use_beta == true) )
          {
          y[col] = acc + beta*y[col];
          }
        else
        if( (use_alpha == true) && (use_beta == true) )
          {
          y[col] = alpha*acc + beta*y[col];
          }
        }
      }
    }