Armadillo Technical: syslib Class Reference
syslib Class Reference
[Syslib]
#include <syslib_proto.hpp>
Detailed Description
Definition at line 20 of file syslib_proto.hpp.
Static Public Member Functions
template<typename eT>
static void copy_elem (eT *dest, const eT *src, const u32 n_elem)
Member Function Documentation
template<typename eT> static void syslib::copy_elem (eT * dest, const eT * src, const u32 n_elem) [inline, static]
Definition at line 28 of file syslib_proto.hpp.
Referenced by op_trans::apply_noalias(), basic_colvec< eT >::basic_colvec(), basic_mat< eT >::basic_mat(), basic_rowvec< eT >::basic_rowvec(), conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< basic_colvec< out_eT > >::from(), conv_to< basic_rowvec< out_eT > >::from(), basic_mat< eT >::init(), auxlib::solve_od(), and auxlib::solve_ud().
    {
    if( n_elem <= (128/sizeof(eT)) )
      {
      for(u32 i=0; i<n_elem; ++i)
        {
        dest[i] = src[i];
        }
      }
    else
      {
      std::memcpy(dest, src, n_elem*sizeof(eT));
      }
    }