Armadillo Technical: Fn_solve
Fn_solve
Functions
template<typename eT, typename T1, typename T2>
bool solve (basic_mat< eT > &X, const arma_base< eT, T1 > &A_in, const arma_base< eT, T2 > &B_in)
Solve a system of linear equations, i.e., A*X = B, where X is unknown. For a square matrix A, this function is conceptually the same as X = inv(A)*B, but is done more efficiently. The number of rows in A and B must be the same. B can be either a column vector or a matrix. This function will also try to provide approximate solutions to under-determined as well as over-determined systems (non-square A matrices).
template<typename eT, typename T1, typename T2>
basic_mat< eT > solve (const arma_base< eT, T1 > &A_in, const arma_base< eT, T2 > &B_in)
Function Documentation
template<typename eT, typename T1, typename T2> bool solve (basic_mat< eT > & X, const arma_base< eT, T1 > & A_in, const arma_base< eT, T2 > & B_in) [inline]
Solve a system of linear equations, i.e., A*X = B, where X is unknown. For a square matrix A, this function is conceptually the same as X = inv(A)*B, but is done more efficiently. The number of rows in A and B must be the same. B can be either a column vector or a matrix. This function will also try to provide approximate solutions to under-determined as well as over-determined systems (non-square A matrices).
Definition at line 32 of file fn_solve.hpp.
References arma_base< elem_type, arma_derived >::get_ref(), basic_mat< eT >::n_rows, auxlib::solve(), auxlib::solve_od(), and auxlib::solve_ud().
Referenced by solve().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(A_in.get_ref());
  const unwrap<T2> tmp2(B_in.get_ref());
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (A.n_rows != B.n_rows), "solve(): number of rows in A and B must be the same" );
  if(A.n_rows == A.n_cols)
    {
    return auxlib::solve(X, A, B);
    }
  else
  if(A.n_rows > A.n_cols)
    {
    arma_extra_debug_print("solve(): detected over-determined system");
    return auxlib::solve_od(X, A, B);
    }
  else
    {
    arma_extra_debug_print("solve(): detected under-determined system");
    return auxlib::solve_ud(X, A, B);
    }
  }
template<typename eT, typename T1, typename T2> basic_mat<eT> solve (const arma_base< eT, T1 > & A_in, const arma_base< eT, T2 > & B_in) [inline]
Definition at line 66 of file fn_solve.hpp.
References arma_print(), and solve().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> X;
  bool info = solve(X, A_in, B_in);
  if(info == false)
    {
    arma_print("solve(): solution not found");
    }
  return X;
  }