Armadillo Technical: Podarray
Podarray
Classes
class podarray< T1 >
A lightweight array for POD types. If the amount of memory requested is small, the stack is used.
Functions
podarray::~podarray ()
podarray::podarray ()
podarray::podarray (const podarray &x)
const podarray & podarray::operator= (const podarray &x)
podarray::podarray (const u32 new_N)
T1 podarray::operator[] (const u32 i) const
T1 & podarray::operator[] (const u32 i)
T1 podarray::operator() (const u32 i) const
T1 & podarray::operator() (const u32 i)
void podarray::set_size (const u32 new_n_elem)
void podarray::fill (const T1 val)
void podarray::zeros ()
void podarray::zeros (const u32 new_n_elem)
T1 * podarray::memptr ()
void podarray::init (const u32 new_n_elem)
Function Documentation
template<typename T1> podarray< T1 >::~podarray () [inline, inherited]
Definition at line 22 of file podarray_meat.hpp.
References arma_config::debug, podarray< T1 >::mem, podarray< T1 >::mem_local, podarray< T1 >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint_this(this);
  if(n_elem > sizeof(mem_local)/sizeof(T1) )
    {
    delete [] mem;
    }
  if(arma_config::debug == true)
    {
    access::rw(mem) = 0;
    }
  }
template<typename T1> podarray< T1 >::podarray () [inline, inherited]
Definition at line 41 of file podarray_meat.hpp.
  : n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint_this(this);
  }
template<typename T1> podarray< T1 >::podarray (const podarray< T1 > & x) [inline, inherited]
Definition at line 52 of file podarray_meat.hpp.
References podarray< T1 >::operator=().
  : n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint();
  this->operator=(x);
  }
template<typename T1> const podarray< T1 > & podarray< T1 >::operator= (const podarray< T1 > & x) [inline, inherited]
Definition at line 66 of file podarray_meat.hpp.
References podarray< T1 >::init(), podarray< T1 >::mem, podarray< T1 >::n_elem, and access::rw().
Referenced by podarray< T1 >::podarray().
  {
  arma_extra_debug_sigprint();
  if(this != &x)
    {
    init(x.n_elem);
    for(u32 i=0; i<n_elem; ++i)
      {
      access::rw(mem[i]) = x.mem[i];
      }
    }
  return *this;
  }
template<typename T1> podarray< T1 >::podarray (const u32 new_N) [inline, inherited]
Definition at line 87 of file podarray_meat.hpp.
References podarray< T1 >::init().
  : n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint_this(this);
  init(new_n_elem);
  }
template<typename T1> T1 podarray< T1 >::operator[] (const u32 i) const [inline, inherited]
Definition at line 100 of file podarray_meat.hpp.
References podarray< T1 >::mem.
  {
  return mem[i];
  }
template<typename T1> T1 & podarray< T1 >::operator[] (const u32 i) [inline, inherited]
Definition at line 110 of file podarray_meat.hpp.
References podarray< T1 >::mem, and access::rw().
  {
  return access::rw(mem[i]);
  }
template<typename T1> T1 podarray< T1 >::operator() (const u32 i) const [inline, inherited]
Definition at line 120 of file podarray_meat.hpp.
References podarray< T1 >::mem, and podarray< T1 >::n_elem.
  {
  arma_debug_check( (i >= n_elem), "index out of bounds");
  return mem[i];
  }
template<typename T1> T1 & podarray< T1 >::operator() (const u32 i) [inline, inherited]
Definition at line 131 of file podarray_meat.hpp.
References podarray< T1 >::mem, podarray< T1 >::n_elem, and access::rw().
  {
  arma_debug_check( (i >= n_elem), "index out of bounds");
  return access::rw(mem[i]);
  }
template<typename T1> void podarray< T1 >::set_size (const u32 new_n_elem) [inline, inherited]
Definition at line 141 of file podarray_meat.hpp.
References podarray< T1 >::init().
Referenced by auxlib::inv_inplace(), auxlib::inv_noalias(), auxlib::lu(), auxlib::qr(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  init(new_n_elem);
  }
template<typename T1> void podarray< T1 >::fill (const T1 val) [inline, inherited]
Definition at line 152 of file podarray_meat.hpp.
References podarray< T1 >::mem, podarray< T1 >::n_elem, and access::rw().
Referenced by podarray< T1 >::zeros().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) = val;
    }
  }
template<typename T1> void podarray< T1 >::zeros () [inline, inherited]
Definition at line 166 of file podarray_meat.hpp.
References podarray< T1 >::fill().
  {
  arma_extra_debug_sigprint();
  fill(0);
  }
template<typename T1> void podarray< T1 >::zeros (const u32 new_n_elem) [inline, inherited]
Definition at line 177 of file podarray_meat.hpp.
References podarray< T1 >::fill(), and podarray< T1 >::init().
  {
  arma_extra_debug_sigprint();
  init(new_n_elem);
  fill(0);
  }
template<typename T1> T1 * podarray< T1 >::memptr () [inline, inherited]
Definition at line 190 of file podarray_meat.hpp.
References podarray< T1 >::mem.
Referenced by op_sort::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), glue_times::apply_inplace(), auxlib::det(), auxlib::inv_inplace(), auxlib::inv_noalias(), diskio::load_pgm_binary(), auxlib::lu(), auxlib::qr(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), and auxlib::svd().
  {
  return const_cast<T1*>(mem);
  }
template<typename T1> void podarray< T1 >::init (const u32 new_n_elem) [inline, protected, inherited]
Definition at line 200 of file podarray_meat.hpp.
References podarray< T1 >::mem, podarray< T1 >::mem_local, podarray< T1 >::n_elem, and access::rw().
Referenced by podarray< T1 >::operator=(), podarray< T1 >::podarray(), podarray< T1 >::set_size(), and podarray< T1 >::zeros().
  {
  arma_extra_debug_sigprint();
  if(n_elem == new_n_elem)
    {
    return;
    }
  if(n_elem > sizeof(mem_local)/sizeof(T1) )
    {
    delete [] mem;
    }
  if(new_n_elem <= sizeof(mem_local)/sizeof(T1) )
    {
    access::rw(mem) = mem_local;
    }
  else
    {
    access::rw(mem) = new T1[new_n_elem];
    }
  access::rw(n_elem) = new_n_elem;
  }