Armadillo Technical: Fn_diagmat
Fn_diagmat
Functions
template<typename eT, typename T1>
const op_data< T1, op_diagmat > diagmat (const arma_base< eT, T1 > &X)
interpret a mat as a diagonal matrix (i.e. off-diagonal entries are zero)
template<typename eT>
const op_data< basic_mat< eT >
, op_diagmat_vec > diagmat (const basic_colvec< eT > &X)
interpret a colvec as a diagonal matrix
template<typename eT>
const op_data< basic_mat< eT >
, op_diagmat_vec > diagmat (const basic_rowvec< eT > &X)
interpret a rowvec as a diagonal matrix
template<typename eT>
basic_mat< eT > diagmat (const subview_col< eT > &X)
create a diagonal matrix out of subview_col
template<typename eT>
basic_mat< eT > diagmat (const subview_row< eT > &X)
create a diagonal matrix out of subview_row
template<typename eT>
basic_mat< eT > diagmat (const diagview< eT > &X)
create a diagonal matrix out of diagview
template<typename T1>
const op_data< T1, op_diagmat > & diagmat (const op_data< T1, op_diagmat > &X)
two consecutive diagmat operations are equivalent to one diagmat operation
Function Documentation
template<typename eT, typename T1> const op_data<T1, op_diagmat> diagmat (const arma_base< eT, T1 > & X) [inline]
interpret a mat as a diagonal matrix (i.e. off-diagonal entries are zero)
Definition at line 24 of file fn_diagmat.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_diagmat>(X.get_ref());
  }
template<typename eT> const op_data<basic_mat<eT>, op_diagmat_vec> diagmat (const basic_colvec< eT > & X) [inline]
interpret a colvec as a diagonal matrix
Definition at line 37 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<basic_mat<eT>, op_diagmat_vec>(X);
  }
template<typename eT> const op_data<basic_mat<eT>, op_diagmat_vec> diagmat (const basic_rowvec< eT > & X) [inline]
interpret a rowvec as a diagonal matrix
Definition at line 50 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<basic_mat<eT>, op_diagmat_vec>(X);
  }
template<typename eT> basic_mat<eT> diagmat (const subview_col< eT > & X) [inline]
create a diagonal matrix out of subview_col
Definition at line 63 of file fn_diagmat.hpp.
References basic_mat< eT >::at(), subview< eT >::n_elem, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename eT> basic_mat<eT> diagmat (const subview_row< eT > & X) [inline]
create a diagonal matrix out of subview_row
Definition at line 84 of file fn_diagmat.hpp.
References basic_mat< eT >::at(), subview< eT >::n_elem, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename eT> basic_mat<eT> diagmat (const diagview< eT > & X) [inline]
create a diagonal matrix out of diagview
Definition at line 105 of file fn_diagmat.hpp.
References basic_mat< eT >::at(), diagview< eT >::n_elem, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.n_elem, X.n_elem);
  for(u32 i=0; i<X.n_elem; ++i)
    {
    out.at(i,i) = X[i];
    }
  return out;
  }
template<typename T1> const op_data<T1, op_diagmat>& diagmat (const op_data< T1, op_diagmat > & X) [inline]
two consecutive diagmat operations are equivalent to one diagmat operation
Definition at line 126 of file fn_diagmat.hpp.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("diagmat(): two consecutive diagmat() operations detected");
  return X;
  }