Armadillo Technical: Fn_trans
Fn_trans
Functions
template<typename T1>
const op_data< T1, op_trans > trans (const arma_base< typename T1::elem_type, T1 > &X)
template<typename eT>
const op_data< basic_rowvec
< eT >, op_trans > trans (const basic_rowvec< eT > &X)
template<typename eT>
const op_data< basic_colvec
< eT >, op_trans > trans (const basic_colvec< eT > &X)
template<typename T1>
const T1 & trans (const op_data< T1, op_trans > &X)
two consecutive transpose operations cancel each other
template<typename T1>
const op_data< T1, op_diagmat > trans (const op_data< T1, op_diagmat > &X)
transpose of a diagonal matrix gives you the original matrix back
template<typename T1>
const op_data< T1, op_htrans > trans (const op_data< T1, op_conj > &X)
the transpose of the conjugate of a complex matrix is equivalent to the hermitian transpose
Function Documentation
template<typename T1> const op_data<T1, op_trans> trans (const arma_base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 23 of file fn_trans.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), auxlib::solve_od(), and auxlib::solve_ud().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_trans>(X.get_ref());
  }
template<typename eT> const op_data<basic_rowvec<eT>, op_trans> trans (const basic_rowvec< eT > & X) [inline]
Definition at line 35 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<basic_rowvec<eT>, op_trans>(X);
  }
template<typename eT> const op_data<basic_colvec<eT>, op_trans> trans (const basic_colvec< eT > & X) [inline]
Definition at line 47 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<basic_colvec<eT>, op_trans>(X);
  }
template<typename T1> const T1& trans (const op_data< T1, op_trans > & X) [inline]
two consecutive transpose operations cancel each other
Definition at line 60 of file fn_trans.hpp.
References op_data< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("trans(): removing op_trans");
  return X.m;
  }
template<typename T1> const op_data<T1, op_diagmat> trans (const op_data< T1, op_diagmat > & X) [inline]
transpose of a diagonal matrix gives you the original matrix back
Definition at line 74 of file fn_trans.hpp.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("trans(): not applying op_trans to diagonal matrix");
  return X;
  }
template<typename T1> const op_data<T1, op_htrans> trans (const op_data< T1, op_conj > & X) [inline]
the transpose of the conjugate of a complex matrix is equivalent to the hermitian transpose
Definition at line 88 of file fn_trans.hpp.
References op_data< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_complex<typename T1::elem_type>::value == false >::apply();
  return op_data<T1, op_htrans>(X.m);
  }