Armadillo Technical: Fn_trig
Fn_trig
Functions
template<typename T1>
const op_data< T1, op_cos > cos (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_acos > acos (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_cosh > cosh (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_acosh > acosh (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_sin > sin (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_asin > asin (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_sinh > sinh (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_asinh > asinh (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_tan > tan (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_atan > atan (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_tanh > tanh (const arma_base< typename T1::elem_type, T1 > &A)
template<typename T1>
const op_data< T1, op_atanh > atanh (const arma_base< typename T1::elem_type, T1 > &A)
Function Documentation
template<typename T1> const op_data<T1, op_cos> cos (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 32 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_cos::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_cos>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_acos> acos (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 47 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_asin::apply(), and op_acos::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_acos>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_cosh> cosh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 62 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_cosh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_cosh>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_acosh> acosh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 77 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_acosh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_acosh>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_sin> sin (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 92 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_sin::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_sin>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_asin> asin (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 107 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_asin::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_asin>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_sinh> sinh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 122 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_sinh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_sinh>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_asinh> asinh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 137 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_asinh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_asinh>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_tan> tan (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 152 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_tan::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_tan>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_atan> atan (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 167 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_atan::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_atan>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_tanh> tanh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 182 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_tanh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_tanh>(A.get_ref());
  }
template<typename T1> const op_data<T1, op_atanh> atanh (const arma_base< typename T1::elem_type, T1 > & A) [inline]
Definition at line 197 of file fn_trig.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_atanh::apply().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_atanh>(A.get_ref());
  }