Armadillo Technical: Operator_plus
Operator_plus
Functions
template<typename T1>
const arma_base< typename
T1::elem_type, T1 > & operator+ (const arma_base< typename T1::elem_type, T1 > &X)
unary plus operation (does nothing, but is required for completeness)
template<typename T1>
const op_data< T1, op_scalar_plus > operator+ (const arma_base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
arma_base + scalar
template<typename T1>
const op_data< T1, op_scalar_plus > operator+ (const op_data< T1, op_scalar_plus > &X, const typename T1::elem_type k)
op + scalar, level 2
template<typename T1>
const op_data< T1, op_scalar_plus > operator+ (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > &X)
scalar + arma_base
template<typename T1, typename T2>
const glue_data< T1, op_data
< T2, op_diagmat >
, glue_plus_diag > operator+ (const arma_base< typename T2::elem_type, T1 > &X, const op_data< T2, op_diagmat > &Y)
arma_base + diagmat
template<typename T1, typename T2>
const glue_data< T1, op_data
< T2, op_diagmat >
, glue_plus_diag > operator+ (const op_data< T2, op_diagmat > &Y, const arma_base< typename T1::elem_type, T1 > &X)
diagmat + arma_base
template<typename eT1, typename T1, typename eT2, typename T2>
basic_mat< typename
promote_type< eT1, eT2 >
::result > operator+ (const arma_base< eT1, T1 > &X, const arma_base< eT2, T2 > &Y)
arma_base + arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< std::complex< double >, T1 > &X, const arma_base< std::complex< double >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< std::complex< float >, T1 > &X, const arma_base< std::complex< float >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< double, T1 > &X, const arma_base< double, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< float, T1 > &X, const arma_base< float, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< s32, T1 > &X, const arma_base< s32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< u32, T1 > &X, const arma_base< u32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< s16, T1 > &X, const arma_base< s16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< u16, T1 > &X, const arma_base< u16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< s8, T1 > &X, const arma_base< s8, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator+ (const arma_base< u8, T1 > &X, const arma_base< u8, T2 > &Y)
Function Documentation
template<typename T1> const arma_base<typename T1::elem_type,T1>& operator+ (const arma_base< typename T1::elem_type, T1 > & X) [inline]
unary plus operation (does nothing, but is required for completeness)
Definition at line 26 of file operator_plus.hpp.
  {
  arma_extra_debug_sigprint();
  return X;
  }
template<typename T1> const op_data<T1, op_scalar_plus> operator+ (const arma_base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
arma_base + scalar
Definition at line 40 of file operator_plus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_plus>(X.get_ref(), k);
  }
template<typename T1> const op_data<T1,op_scalar_plus> operator+ (const op_data< T1, op_scalar_plus > & X, const typename T1::elem_type k) [inline]
op + scalar, level 2
Definition at line 54 of file operator_plus.hpp.
References op_data< T1, op_type >::aux, and op_data< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_plus>(X.m, X.aux + k);
  }
template<typename T1> const op_data<T1, op_scalar_plus> operator+ (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > & X) [inline]
scalar + arma_base
Definition at line 68 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_plus>(X.get_ref(), k);  // NOTE: order is swapped
  }
template<typename T1, typename T2> const glue_data<T1, op_data<T2,op_diagmat>, glue_plus_diag> operator+ (const arma_base< typename T2::elem_type, T1 > & X, const op_data< T2, op_diagmat > & Y) [inline]
arma_base + diagmat
Definition at line 82 of file operator_plus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, op_data<T2,op_diagmat>, glue_plus_diag>(X.get_ref(), Y);
  }
template<typename T1, typename T2> const glue_data<T1, op_data<T2,op_diagmat>, glue_plus_diag> operator+ (const op_data< T2, op_diagmat > & Y, const arma_base< typename T1::elem_type, T1 > & X) [inline]
diagmat + arma_base
Definition at line 96 of file operator_plus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, op_data<T2,op_diagmat>, glue_plus_diag>(X.get_ref(), Y);  // NOTE: order is swapped
  }
template<typename eT1, typename T1, typename eT2, typename T2> basic_mat<typename promote_type<eT1,eT2>::result> operator+ (const arma_base< eT1, T1 > & X, const arma_base< eT2, T2 > & Y) [inline]
arma_base + arma_base
Definition at line 116 of file operator_plus.hpp.
References glue_plus::apply_mixed(), promote_type< T1, T2 >::check(), arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const basic_mat<eT1>& A = tmp1.M;
  const basic_mat<eT2>& B = tmp2.M;
  basic_mat< typename promote_type<eT1,eT2>::result > out;
  glue_plus::apply_mixed(out, A, B);
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< std::complex< double >, T1 > & X, const arma_base< std::complex< double >, T2 > & Y) [inline]
Definition at line 146 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< std::complex< float >, T1 > & X, const arma_base< std::complex< float >, T2 > & Y) [inline]
Definition at line 159 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< double, T1 > & X, const arma_base< double, T2 > & Y) [inline]
Definition at line 172 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< float, T1 > & X, const arma_base< float, T2 > & Y) [inline]
Definition at line 185 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< s32, T1 > & X, const arma_base< s32, T2 > & Y) [inline]
Definition at line 198 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< u32, T1 > & X, const arma_base< u32, T2 > & Y) [inline]
Definition at line 211 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< s16, T1 > & X, const arma_base< s16, T2 > & Y) [inline]
Definition at line 224 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< u16, T1 > & X, const arma_base< u16, T2 > & Y) [inline]
Definition at line 237 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< s8, T1 > & X, const arma_base< s8, T2 > & Y) [inline]
Definition at line 250 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator+ (const arma_base< u8, T1 > & X, const arma_base< u8, T2 > & Y) [inline]
Definition at line 263 of file operator_plus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.get_ref());
  }