Armadillo Technical: Op_dot
Op_dot
Classes
class op_dot
dot product operation
class op_norm_dot
normalised dot product operation
Functions
template<typename eT>
static eT op_dot::direct_dot (const u32 n_elem, const eT *const A, const eT *const B)
for two arrays
template<typename eT>
static eT op_dot::direct_dot (const u32 n_elem, const eT *const A, const eT *const B, const eT *C)
for three arrays
template<typename T1, typename T2>
static T1::elem_type op_dot::apply (const arma_base< typename T1::elem_type, T1 > &A_orig, const arma_base< typename T1::elem_type, T2 > &B_orig)
template<typename T1, typename T2>
static T1::elem_type op_norm_dot::apply (const arma_base< typename T1::elem_type, T1 > &A_orig, const arma_base< typename T1::elem_type, T2 > &B_orig)
Function Documentation
template<typename eT> eT op_dot::direct_dot (const u32 n_elem, const eT *const A, const eT *const B) [inline, static, inherited]
for two arrays
Definition at line 25 of file op_dot_meat.hpp.
Referenced by glue_times::direct_rowvec_mat_colvec(), and operator*().
  {
  arma_extra_debug_sigprint();
  eT val1 = eT(0);
  eT val2 = eT(0);
  u32 i,j;
  for(i=0, j=1; j<n_elem; i+=2, j+=2)
    {
    val1 += A[i] * B[i];
    val2 += A[j] * B[j];
    }
  if(i < n_elem)
    {
    val1 += A[i] * B[i];
    }
  return val1+val2;
  }
template<typename eT> eT op_dot::direct_dot (const u32 n_elem, const eT *const A, const eT *const B, const eT * C) [inline, static, inherited]
for three arrays
Definition at line 53 of file op_dot_meat.hpp.
  {
  arma_extra_debug_sigprint();
  eT val = eT(0);
  for(u32 i=0; i<n_elem; ++i)
    {
    val += A[i] * B[i] * C[i];
    }
  return val;
  }
template<typename T1, typename T2> T1::elem_type op_dot::apply (const arma_base< typename T1::elem_type, T1 > & A_orig, const arma_base< typename T1::elem_type, T2 > & B_orig) [inline, static, inherited]
Definition at line 72 of file op_dot_meat.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by dot().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_to_elem_access<T1> A(A_orig.get_ref());
  const unwrap_to_elem_access<T2> B(B_orig.get_ref());
  arma_debug_check( (A.M.n_elem != B.M.n_elem), "dot(): objects must have the same number of elements" );
  const u32 n_elem = A.M.n_elem;
  eT val = eT(0);
  for(u32 i=0; i<n_elem; ++i)
    {
    val += A[i] * B[i];
    }
  return val;
  }
template<typename T1, typename T2> T1::elem_type op_norm_dot::apply (const arma_base< typename T1::elem_type, T1 > & A_orig, const arma_base< typename T1::elem_type, T2 > & B_orig) [inline, static, inherited]
Definition at line 99 of file op_dot_meat.hpp.
References arma_base< elem_type, arma_derived >::get_ref(), and sqrt().
Referenced by norm_dot().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap_to_elem_access<T1> A(A_orig.get_ref());
  const unwrap_to_elem_access<T2> B(B_orig.get_ref());
  arma_debug_check( (A.M.n_elem != B.M.n_elem), "norm_dot(): objects must have the same number of elements" );
  const u32 n_elem = A.M.n_elem;
  eT acc1 = eT(0);
  eT acc2 = eT(0);
  eT acc3 = eT(0);
  for(u32 i=0; i<n_elem; ++i)
    {
    const eT tmpA = A[i];
    const eT tmpB = B[i];
    acc1 += tmpA * tmpA;
    acc2 += tmpB * tmpB;
    acc3 += tmpA * tmpB;
    }
  return acc3 / ( std::sqrt(acc1 * acc2) );   // TODO: this only makes sense for eT = float, double or complex
  }