Armadillo Technical: Op_sort
Op_sort
Classes
class arma_qsort_helper< eT >
class arma_qsort_helper< std::complex< T > >
class op_sort
Functions
template<typename eT>
static void op_sort::direct_sort (eT *X, const u32 N, const u32 sort_type=0)
template<typename T1>
static void op_sort::apply (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_sort > &in)
Function Documentation
template<typename eT> void op_sort::direct_sort (eT * X, const u32 N, const u32 sort_type = 0) [inline, static, inherited]
Definition at line 149 of file op_sort_meat.hpp.
Referenced by apply().
  {
  arma_extra_debug_sigprint();
  if(sort_type == 0)
    {
    std::qsort(X, n_elem, sizeof(eT), arma_qsort_helper<eT>::ascend_compare);
    }
  else
    {
    std::qsort(X, n_elem, sizeof(eT), arma_qsort_helper<eT>::descend_compare);
    }
  }
template<typename T1> void op_sort::apply (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_sort > & in) [inline, static, inherited]
Definition at line 168 of file op_sort_meat.hpp.
References basic_mat< eT >::at(), op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, basic_mat< eT >::colptr(), direct_sort(), op_data< T1, op_type >::m, basic_mat< eT >::memptr(), podarray< T1 >::memptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  unwrap<T1> tmp(in.m);
  const basic_mat<eT>& X = tmp.M;
  const u32 sort_type = in.aux_u32_a;
  const u32 dim       = in.aux_u32_b;
  arma_debug_check( (sort_type > 1), "op_sort::apply(): incorrect usage. sort_type must be 0 or 1");
  arma_debug_check( (dim > 1),       "op_sort::apply(): incorrect usage. dim must be 0 or 1"      );
  if(dim == 0)  // column-wise
    {
    arma_extra_debug_print("op_sort::apply(), dim = 0");
    out = X;
    for(u32 col=0; col<out.n_cols; ++col)
      {
      op_sort::direct_sort( out.colptr(col), out.n_rows, sort_type );
      }
    }
  else
  if(dim == 1)  // row-wise
    {
    if(X.n_rows != 1)  // not a row vector
      {
      arma_extra_debug_print("op_sort::apply(), dim = 1, generic");
      out.set_size(X.n_rows, X.n_cols);
      podarray<eT> tmp(X.n_cols);
      for(u32 row=0; row<out.n_rows; ++row)
        {
        for(u32 col=0; col<out.n_cols; ++col)
          {
          tmp[col] = X.at(row,col);
          }
        op_sort::direct_sort( tmp.memptr(), out.n_cols, sort_type );
        for(u32 col=0; col<out.n_cols; ++col)
          {
          out.at(row,col) = tmp[col];
          }
        }
      }
    else  // a row vector
      {
      arma_extra_debug_print("op_sort::apply(), dim = 1, vector specific");
      out = X;
      op_sort::direct_sort(out.memptr(), out.n_elem, sort_type);
      }
    }
  }