Armadillo Technical: Operator_schur
Operator_schur
Functions
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< typename T1::elem_type, T1 > &X, const arma_base< typename T1::elem_type, T2 > &Y)
arma_base % arma_base
template<typename T1, typename T2>
const glue_data< T1, op_data
< T2, op_diagmat >
, glue_schur_diag > operator% (const arma_base< typename T2::elem_type, T1 > &X, const op_data< T2, op_diagmat > &Y)
arma_base % diagmat
template<typename T1, typename T2>
const glue_data< op_data< T1,
op_diagmat >, T2,
glue_schur_diag > operator% (const op_data< T1, op_diagmat > &X, const arma_base< typename T1::elem_type, T2 > &Y)
diagmat % arma_base
template<typename eT1, typename T1, typename eT2, typename T2>
basic_mat< typename
promote_type< eT1, eT2 >
::result > operator% (const arma_base< eT1, T1 > &X, const arma_base< eT2, T2 > &Y)
arma_base % arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< std::complex< double >, T1 > &X, const arma_base< std::complex< double >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< std::complex< float >, T1 > &X, const arma_base< std::complex< float >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< double, T1 > &X, const arma_base< double, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< float, T1 > &X, const arma_base< float, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< s32, T1 > &X, const arma_base< s32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< u32, T1 > &X, const arma_base< u32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< s16, T1 > &X, const arma_base< s16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< u16, T1 > &X, const arma_base< u16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< s8, T1 > &X, const arma_base< s8, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_schur > operator% (const arma_base< u8, T1 > &X, const arma_base< u8, T2 > &Y)
Function Documentation
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< typename T1::elem_type, T1 > & X, const arma_base< typename T1::elem_type, T2 > & Y) [inline]
arma_base % arma_base
Definition at line 28 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, op_data<T2,op_diagmat>, glue_schur_diag> operator% (const arma_base< typename T2::elem_type, T1 > & X, const op_data< T2, op_diagmat > & Y) [inline]
arma_base % diagmat
Definition at line 42 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, op_data<T2,op_diagmat>, glue_schur_diag>(X.get_ref(), Y);
  }
template<typename T1, typename T2> const glue_data< op_data<T1,op_diagmat>, T2, glue_schur_diag> operator% (const op_data< T1, op_diagmat > & X, const arma_base< typename T1::elem_type, T2 > & Y) [inline]
diagmat % arma_base
Definition at line 56 of file operator_schur.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data< op_data<T1,op_diagmat>, T2, glue_schur_diag>(X, Y.get_ref());
  }
template<typename eT1, typename T1, typename eT2, typename T2> basic_mat<typename promote_type<eT1,eT2>::result> operator% (const arma_base< eT1, T1 > & X, const arma_base< eT2, T2 > & Y) [inline]
arma_base % arma_base
Definition at line 76 of file operator_schur.hpp.
References glue_schur::apply_mixed(), promote_type< T1, T2 >::check(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const basic_mat<eT1>& A = tmp1.M;
  const basic_mat<eT2>& B = tmp2.M;
  basic_mat< typename promote_type<eT1,eT2>::result > out;
  glue_schur::apply_mixed(out, A, B);
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< std::complex< double >, T1 > & X, const arma_base< std::complex< double >, T2 > & Y) [inline]
Definition at line 106 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< std::complex< float >, T1 > & X, const arma_base< std::complex< float >, T2 > & Y) [inline]
Definition at line 119 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< double, T1 > & X, const arma_base< double, T2 > & Y) [inline]
Definition at line 132 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< float, T1 > & X, const arma_base< float, T2 > & Y) [inline]
Definition at line 145 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< s32, T1 > & X, const arma_base< s32, T2 > & Y) [inline]
Definition at line 158 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< u32, T1 > & X, const arma_base< u32, T2 > & Y) [inline]
Definition at line 171 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< s16, T1 > & X, const arma_base< s16, T2 > & Y) [inline]
Definition at line 184 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< u16, T1 > & X, const arma_base< u16, T2 > & Y) [inline]
Definition at line 197 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< s8, T1 > & X, const arma_base< s8, T2 > & Y) [inline]
Definition at line 210 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_schur> operator% (const arma_base< u8, T1 > & X, const arma_base< u8, T2 > & Y) [inline]
Definition at line 223 of file operator_schur.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_schur>(X.get_ref(), Y.get_ref());
  }