Armadillo Technical: Operator_minus
Operator_minus
Functions
template<typename T1>
const op_data< T1, op_neg > operator- (const arma_base< typename T1::elem_type, T1 > &X)
unary -
template<typename T1>
const T1 & operator- (const op_data< T1, op_neg > &X)
cancellation of two consecutive negations: -(-T1)
template<typename T1>
const op_data< T1,
op_scalar_minus_post > operator- (const arma_base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
arma_base - scalar
template<typename T1>
const op_data< T1,
op_scalar_minus_pre > operator- (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > &X)
scalar - arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator- (const arma_base< typename T1::elem_type, T1 > &X, const arma_base< typename T1::elem_type, op_data< T2, op_neg > > &Y)
arma_base - - arma_base = arma_base + arma_base
template<typename T1, typename T2>
const glue_data< T1, op_data
< T2, op_diagmat >
, glue_minus_diag > operator- (const arma_base< typename T2::elem_type, T1 > &X, const op_data< T2, op_diagmat > &Y)
arma_base - diagmat
template<typename T1, typename T2>
const glue_data< op_data< T1,
op_diagmat >, T2,
glue_minus_diag > operator- (const op_data< T1, op_diagmat > &X, const arma_base< typename T1::elem_type, T2 > &Y)
diagmat - arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_plus > operator- (const arma_base< typename T2::elem_type, T1 > &X, const op_data< T2, op_neg > &Y)
arma_base - op_data<T2,op_neg> = arma_base + T2
template<typename T1, typename T2>
const glue_data< op_data< T1,
op_diagmat >, T2,
glue_plus_diag > operator- (const arma_base< typename T1::elem_type, op_data< T1, op_diagmat > > &X, const arma_base< typename T1::elem_type, op_data< T2, op_neg > > &Y)
diagmat - op_data<T2,op_neg> = diagmat + T2
template<typename eT1, typename T1, typename eT2, typename T2>
basic_mat< typename
promote_type< eT1, eT2 >
::result > operator- (const arma_base< eT1, T1 > &X, const arma_base< eT2, T2 > &Y)
arma_base - arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< std::complex< double >, T1 > &X, const arma_base< std::complex< double >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< std::complex< float >, T1 > &X, const arma_base< std::complex< float >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< double, T1 > &X, const arma_base< double, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< float, T1 > &X, const arma_base< float, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< s32, T1 > &X, const arma_base< s32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< u32, T1 > &X, const arma_base< u32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< s16, T1 > &X, const arma_base< s16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< u16, T1 > &X, const arma_base< u16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< s8, T1 > &X, const arma_base< s8, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_minus > operator- (const arma_base< u8, T1 > &X, const arma_base< u8, T2 > &Y)
Function Documentation
template<typename T1> const op_data<T1, op_neg> operator- (const arma_base< typename T1::elem_type, T1 > & X) [inline]
unary -
Definition at line 26 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<T1,op_neg>(X.get_ref());
  }
template<typename T1> const T1& operator- (const op_data< T1, op_neg > & X) [inline]
cancellation of two consecutive negations: -(-T1)
Definition at line 40 of file operator_minus.hpp.
  {
  arma_extra_debug_sigprint();
  return X.m;
  }
template<typename T1> const op_data<T1, op_scalar_minus_post> operator- (const arma_base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
arma_base - scalar
Definition at line 54 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_minus_post>(X.get_ref(), k);
  }
template<typename T1> const op_data<T1, op_scalar_minus_pre> operator- (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > & X) [inline]
scalar - arma_base
Definition at line 68 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_minus_pre>(X.get_ref(), k);
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator- (const arma_base< typename T1::elem_type, T1 > & X, const arma_base< typename T1::elem_type, op_data< T2, op_neg > > & Y) [inline]
arma_base - - arma_base = arma_base + arma_base
Definition at line 82 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const T1& A = X.get_ref();
  const T2& B = (Y.get_ref()).m;
  return glue_data<T1, T2, glue_plus>(A,B);
  }
template<typename T1, typename T2> const glue_data<T1, op_data<T2,op_diagmat>, glue_minus_diag> operator- (const arma_base< typename T2::elem_type, T1 > & X, const op_data< T2, op_diagmat > & Y) [inline]
arma_base - diagmat
Definition at line 102 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, op_data<T1,op_diagmat>, glue_minus_diag>(X.get_ref(), Y);
  }
template<typename T1, typename T2> const glue_data< op_data<T1,op_diagmat>, T2, glue_minus_diag> operator- (const op_data< T1, op_diagmat > & X, const arma_base< typename T1::elem_type, T2 > & Y) [inline]
diagmat - arma_base
Definition at line 116 of file operator_minus.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data< op_data<T1,op_diagmat>, T2, glue_minus_diag>(X, Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_plus> operator- (const arma_base< typename T2::elem_type, T1 > & X, const op_data< T2, op_neg > & Y) [inline]
arma_base - op_data<T2,op_neg> = arma_base + T2
Definition at line 130 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_plus>(X.get_ref(), Y.m);
  }
template<typename T1, typename T2> const glue_data< op_data<T1,op_diagmat>, T2, glue_plus_diag> operator- (const arma_base< typename T1::elem_type, op_data< T1, op_diagmat > > & X, const arma_base< typename T1::elem_type, op_data< T2, op_neg > > & Y) [inline]
diagmat - op_data<T2,op_neg> = diagmat + T2
Definition at line 144 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data< op_data<T1,op_diagmat>, T2, glue_plus_diag>(X.get_ref(), (Y.get_ref()).m);
  }
template<typename eT1, typename T1, typename eT2, typename T2> basic_mat<typename promote_type<eT1,eT2>::result> operator- (const arma_base< eT1, T1 > & X, const arma_base< eT2, T2 > & Y) [inline]
arma_base - arma_base
Definition at line 167 of file operator_minus.hpp.
References glue_minus::apply_mixed(), promote_type< T1, T2 >::check(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const basic_mat<eT1>& A = tmp1.M;
  const basic_mat<eT2>& B = tmp2.M;
  basic_mat< typename promote_type<eT1,eT2>::result > out;
  glue_minus::apply_mixed(out, A, B);
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< std::complex< double >, T1 > & X, const arma_base< std::complex< double >, T2 > & Y) [inline]
Definition at line 197 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< std::complex< float >, T1 > & X, const arma_base< std::complex< float >, T2 > & Y) [inline]
Definition at line 210 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< double, T1 > & X, const arma_base< double, T2 > & Y) [inline]
Definition at line 223 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< float, T1 > & X, const arma_base< float, T2 > & Y) [inline]
Definition at line 236 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< s32, T1 > & X, const arma_base< s32, T2 > & Y) [inline]
Definition at line 249 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< u32, T1 > & X, const arma_base< u32, T2 > & Y) [inline]
Definition at line 262 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< s16, T1 > & X, const arma_base< s16, T2 > & Y) [inline]
Definition at line 275 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< u16, T1 > & X, const arma_base< u16, T2 > & Y) [inline]
Definition at line 288 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< s8, T1 > & X, const arma_base< s8, T2 > & Y) [inline]
Definition at line 301 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_minus> operator- (const arma_base< u8, T1 > & X, const arma_base< u8, T2 > & Y) [inline]
Definition at line 314 of file operator_minus.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_minus>(X.get_ref(), Y.get_ref());
  }