Armadillo Technical: Fn_chol
Fn_chol
Functions
template<typename eT, typename T1>
bool chol (basic_mat< eT > &out, const arma_base< eT, T1 > &X)
template<typename eT, typename T1>
basic_mat< eT > chol (const arma_base< eT, T1 > &X)
Function Documentation
template<typename eT, typename T1> bool chol (basic_mat< eT > & out, const arma_base< eT, T1 > & X) [inline]
Definition at line 23 of file fn_chol.hpp.
References auxlib::chol(), and arma_base< elem_type, arma_derived >::get_ref().
Referenced by chol().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  arma_debug_check( !tmp.M.is_square(), "chol(): given matrix is not square");
  return auxlib::chol(out, tmp.M);
  }
template<typename eT, typename T1> basic_mat<eT> chol (const arma_base< eT, T1 > & X) [inline]
Definition at line 38 of file fn_chol.hpp.
References arma_print(), and chol().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  const bool ok = chol(out, X);
  if(ok == false)
    {
    arma_print("chol(): matrix factorisation failed");
    }
  return out;
  }