Armadillo Technical: Glue_minus
Glue_minus
Classes
class glue_minus
Class for the minus operation, where the result is always a dense matrix.
class glue_minus_diag
Class for the minus operation, where one of the operands is a diagonal matrix.
Functions
template<typename eT>
static void glue_minus::apply (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B)
Immediate out = A-B.
template<typename eT>
static void glue_minus::apply (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B, const basic_mat< eT > &C)
Immediate out = A-B-C.
template<typename eT>
static void glue_minus::apply (basic_mat< eT > &out, const glue_data< basic_mat< eT >, basic_mat< eT >, glue_minus > &X)
Immediate out = A-B (operands obtained from glue_data).
template<typename eT>
static void glue_minus::apply (basic_mat< eT > &out, const glue_data< glue_data< basic_mat< eT >, basic_mat< eT >, glue_minus >, basic_mat< eT >, glue_minus > &X)
Immediate out = A-B-C (operands obtained from glue_data).
template<typename T1, typename T2>
static void glue_minus::apply (basic_mat< typename T1::elem_type > &out, const glue_data< T1, T2, glue_minus > &X)
Immediate out = A-B-...-Z (operands obtained from glue_data).
template<typename eT>
static void glue_minus::apply_inplace (basic_mat< eT > &out, const basic_mat< eT > &B)
Immediate out -= B.
template<typename T1, typename op_type>
static void glue_minus::apply_inplace (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_type > &X)
template<typename T1, typename T2, typename glue_type>
static void glue_minus::apply_inplace (basic_mat< typename T1::elem_type > &out, const glue_data< T1, T2, glue_type > &X)
template<typename eT1, typename eT2>
static void glue_minus::apply_mixed (basic_mat< typename promote_type< eT1, eT2 >::result > &out, const basic_mat< eT1 > &X, const basic_mat< eT2 > &Y)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const T1 &A, const op_data< T2, op_diagmat > &B)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_diagmat > &A, const T2 &B)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_diagmat > &A, const op_data< T2, op_diagmat > &B)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const glue_data< T1, op_data< T2, op_diagmat >, glue_minus_diag > &X)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const glue_data< op_data< T1, op_diagmat >, T2, glue_minus_diag > &X)
template<typename T1, typename T2>
static void glue_minus_diag::apply (basic_mat< typename T1::elem_type > &out, const glue_data< op_data< T1, op_diagmat >, op_data< T2, op_diagmat >, glue_minus_diag > &X)
Function Documentation
template<typename eT> void glue_minus::apply (basic_mat< eT > & out, const basic_mat< eT > & A, const basic_mat< eT > & B) [inline, static, inherited]
Immediate out = A-B.
Definition at line 24 of file glue_minus_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::memptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
Referenced by apply(), and apply_inplace().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no aliasing problem
  out.set_size(A.n_rows,A.n_cols);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const u32 n_elem  = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] - B_mem[i];
    }
  }
template<typename eT> void glue_minus::apply (basic_mat< eT > & out, const basic_mat< eT > & A, const basic_mat< eT > & B, const basic_mat< eT > & C) [inline, static, inherited]
Immediate out = A-B-C.
Definition at line 52 of file glue_minus_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::memptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  arma_debug_assert_same_size(A, C, "matrix subtraction");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
        eT* out_mem = out.memptr();
  const eT* A_mem   = A.mem;
  const eT* B_mem   = B.mem;
  const eT* C_mem   = C.mem;
  const u32 n_elem = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = A_mem[i] - B_mem[i] - C_mem[i];
    }
  }
template<typename eT> void glue_minus::apply (basic_mat< eT > & out, const glue_data< basic_mat< eT >, basic_mat< eT >, glue_minus > & X) [inline, static, inherited]
Immediate out = A-B (operands obtained from glue_data).
Definition at line 82 of file glue_minus_meat.hpp.
References apply().
  {
  glue_minus::apply(out, X.A, X.B);
  }
template<typename eT> void glue_minus::apply (basic_mat< eT > & out, const glue_data< glue_data< basic_mat< eT >, basic_mat< eT >, glue_minus >, basic_mat< eT >, glue_minus > & X) [inline, static, inherited]
Immediate out = A-B-C (operands obtained from glue_data).
Definition at line 93 of file glue_minus_meat.hpp.
References apply().
  {
  glue_minus::apply(out, X.A.A, X.A.B, X.B);
  }
template<typename T1, typename T2> void glue_minus::apply (basic_mat< typename T1::elem_type > & out, const glue_data< T1, T2, glue_minus > & X) [inline, static, inherited]
Immediate out = A-B-...-Z (operands obtained from glue_data).
Definition at line 104 of file glue_minus_meat.hpp.
References glue_data< T1, T2, glue_type >::A, apply(), glue_data< T1, T2, glue_type >::B, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const u32 N_mat = 1 + depth_lhs< glue_minus, glue_data<T1,T2,glue_minus> >::num;
  arma_extra_debug_print( arma_boost::format("N_mat = %d") % N_mat );
  if(N_mat == 2)
    {
    unwrap<T1> tmp1(X.A);
    unwrap<T2> tmp2(X.B);
    glue_minus::apply(out, tmp1.M, tmp2.M);
    }
  else
    {
    const basic_mat<eT>* ptrs[N_mat];
    bool                 del[N_mat];
    mat_ptrs<glue_minus, glue_data<T1,T2,glue_minus> >::get_ptrs(ptrs, del, X);
    //mat_ptrs_outcheck<glue_minus, glue_data<T1,T2,glue_minus> >::get_ptrs(ptrs, del, X, &out);
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format("ptrs[%d] = %x")  % i % ptrs[i] );
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format(" del[%d] = %d")  % i %  del[i] );
    const basic_mat<eT>& tmp_mat = *(ptrs[0]);
    for(u32 i=1; i<N_mat; ++i)
      {
      arma_debug_assert_same_size(tmp_mat, *(ptrs[i]), "matrix subtraction");
      }
    const u32 n_rows = ptrs[0]->n_rows;
    const u32 n_cols = ptrs[0]->n_cols;
    // no aliasing problem
    out.set_size(n_rows,n_cols);
    const u32 n_elem = ptrs[0]->n_elem;
    for(u32 j=0; j<n_elem; ++j)
      {
      eT acc = ptrs[0]->mem[j];
      for(u32 i=1; i<N_mat; ++i)
        {
        acc -= ptrs[i]->mem[j];
        }
      out[j] = acc;
      }
    for(u32 i=0; i<N_mat; ++i)
      {
      if(del[i] == true)
        {
        arma_extra_debug_print( arma_boost::format("delete ptrs[%d]") % i );
        delete ptrs[i];
        }
      }
    }
  }
template<typename eT> void glue_minus::apply_inplace (basic_mat< eT > & out, const basic_mat< eT > & B) [inline, static, inherited]
Immediate out -= B.
Definition at line 176 of file glue_minus_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
Referenced by basic_mat< eT >::operator-=().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(out, B, "matrix subtraction");
        eT* out_mem = out.memptr();
  const eT* B_mem   = B.mem;
  const u32 n_elem  = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] -= B_mem[i];
    }
  }
template<typename T1, typename op_type> void glue_minus::apply_inplace (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_type > & X) [inline, static, inherited]
Definition at line 199 of file glue_minus_meat.hpp.
References apply().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const basic_mat<eT> tmp(X);
  glue_minus::apply(out, out, tmp);
  }
template<typename T1, typename T2, typename glue_type> void glue_minus::apply_inplace (basic_mat< typename T1::elem_type > & out, const glue_data< T1, T2, glue_type > & X) [inline, static, inherited]
Definition at line 214 of file glue_minus_meat.hpp.
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  out = out - X;
  }
template<typename eT1, typename eT2> void glue_minus::apply_mixed (basic_mat< typename promote_type< eT1, eT2 >::result > & out, const basic_mat< eT1 > & X, const basic_mat< eT2 > & Y) [inline, static, inherited]
Definition at line 231 of file glue_minus_meat.hpp.
References upgrade_val< T1, T2 >::apply(), basic_mat< eT >::mem, basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
Referenced by operator-().
  {
  arma_extra_debug_sigprint();
  typedef typename promote_type<eT1,eT2>::result out_eT;
  arma_debug_assert_same_size(X,Y, "matrix subtraction");
  out.set_size(X.n_rows, X.n_cols);
        out_eT* out_mem = out.memptr();
  const eT1*    X_mem   = X.mem;
  const eT2*    Y_mem   = Y.mem;
  const u32 n_elem = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = upgrade_val<eT1,eT2>::apply(X_mem[i]) - upgrade_val<eT1,eT2>::apply(Y_mem[i]);
    }
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const T1 & A, const op_data< T2, op_diagmat > & B) [inline, static, inherited]
Definition at line 262 of file glue_minus_meat.hpp.
References basic_mat< eT >::at(), isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), op_data< T1, op_type >::m, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
Referenced by glue_minus_diag::apply().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(A_orig);
  const unwrap<T2> tmp2(B_orig.m);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( !B.is_square(), "glue_minus_diag::apply(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
  for(u32 col=0; col<A.n_cols; ++col)
    {
    for(u32 row=0; row<A.n_rows; ++row)
      {
      if(col != row)
        {
        out.at(row,col) = A.at(row,col);
        }
      else
        {
        out.at(row,col) = A.at(row,col) - B.at(row,col);
        }
      }
    }
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_diagmat > & A, const T2 & B) [inline, static, inherited]
Definition at line 305 of file glue_minus_meat.hpp.
References basic_mat< eT >::at(), isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), op_data< T1, op_type >::m, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(A_orig.m);
  const unwrap<T2> tmp2(B_orig);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( !A.is_square(), "glue_minus_diag::apply(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
  for(u32 col=0; col<A.n_cols; ++col)
    {
    for(u32 row=0; row<A.n_rows; ++row)
      {
      if(col != row)
        {
        out.at(row,col) = -B.at(row,col);
        }
      else
        {
        out.at(row,col) = A.at(row,col) - B.at(row,col);
        }
      }
    }
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_diagmat > & A, const op_data< T2, op_diagmat > & B) [inline, static, inherited]
Definition at line 348 of file glue_minus_meat.hpp.
References basic_mat< eT >::at(), isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), op_data< T1, op_type >::m, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(A_orig.m);
  const unwrap<T2> tmp2(B_orig.m);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( !A.is_square(), "glue_minus_diag::apply(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  if( (&out != &A) && (&out != &B) )
    {
    out.zeros(A.n_rows, A.n_cols);
    for(u32 i=0; i<A.n_rows; ++i)
      {
      out.at(i,i) = A.at(i,i) - B.at(i,i);
      }
    }
  else
    {
    for(u32 col=0; col<A.n_cols; ++col)
      {
      for(u32 row=0; row<A.n_rows; ++row)
        {
        if(col != row)
          {
          out.at(row,col) = 0.0;
          }
        else
          {
          out.at(row,col) = A.at(row,col) - B.at(row,col);
          }
        }
      }
    }
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const glue_data< T1, op_data< T2, op_diagmat >, glue_minus_diag > & X) [inline, static, inherited]
Definition at line 400 of file glue_minus_meat.hpp.
References glue_minus_diag::apply().
  {
  glue_minus_diag::apply(out, X.A, X.B);
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const glue_data< op_data< T1, op_diagmat >, T2, glue_minus_diag > & X) [inline, static, inherited]
Definition at line 410 of file glue_minus_meat.hpp.
References glue_minus_diag::apply().
  {
  glue_minus_diag::apply(out, X.A, X.B);
  }
template<typename T1, typename T2> void glue_minus_diag::apply (basic_mat< typename T1::elem_type > & out, const glue_data< op_data< T1, op_diagmat >, op_data< T2, op_diagmat >, glue_minus_diag > & X) [inline, static, inherited]
Definition at line 420 of file glue_minus_meat.hpp.
References glue_minus_diag::apply().
  {
  glue_minus_diag::apply(out, X.A, X.B);
  }