Armadillo Technical: Ostream
Ostream
Classes
class arma_ostream
Functions
template<typename T1>
std::ostream & operator<< (std::ostream &o, const op_data< T1, op_diagmat > &X)
Print a diagonal matrix to the specified stream.
template<typename T1>
std::ostream & operator<< (std::ostream &o, const field< T1 > &X)
Print the contents of a field to the specified stream Assumes type T1 can be printed, i.e. T1 has std::ostream& operator<< (std::ostream&, const T1&).
template<typename T1>
std::ostream & operator<< (std::ostream &o, const subview_field< T1 > &X)
Print the contents of a subfield to the specified stream Assumes type T1 can be printed, i.e. T1 has std::ostream& operator<< (std::ostream&, const T1&).
template<typename eT>
std::ostream & operator<< (std::ostream &o, const basic_mat< eT > &m)
Print a matrix to the specified stream.
template<typename T1>
std::ostream & operator<< (std::ostream &o, const arma_base< typename T1::elem_type, T1 > &X)
template<typename eT>
static u32 arma_ostream::set_flags (std::ostream &o, const basic_mat< eT > &m)
template<typename T>
static u32 arma_ostream::set_flags (std::ostream &o, const basic_mat< std::complex< T > > &m)
"better than nothing" settings for complex numbers
Function Documentation
template<typename T1> std::ostream& operator<< (std::ostream & o, const op_data< T1, op_diagmat > & X) [inline]
Print a diagonal matrix to the specified stream.
Definition at line 24 of file ostream_diagmat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), basic_mat< eT >::is_vec(), max(), basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and arma_ostream::set_flags().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(X.m);
  const basic_mat<eT>& m = tmp.M;
  arma_debug_check( ((m.is_vec() == false) && (m.is_square() == false)), "operator<<(): incompatible dimensions for diagmat operation" );
  const ios::fmtflags orig_flags = o.flags();
  const u32 cell_width = arma_ostream::set_flags(o, m);
  const u32 local_n_rows = (std::max)(m.n_rows, m.n_cols);
  for(u32 row=0; row < local_n_rows; ++row)
    {
    for(u32 col=0; col < local_n_rows; ++col)
      {
      if(row != col)
        {
        o.width(cell_width);
        if(is_complex<eT>::value == false)
          {
          o << "0.0";
          }
        else
          {
          o << "(0.0,0.0)";
          }
        }
      else
        {
        const eT val = m.is_vec() ? m.mem[row] : m.at(row,row);
        o.width(cell_width);
        o << val;
        }
      }
      o << '\n';
    }
  o.flags(orig_flags);
  return o;
  }
template<typename T1> std::ostream& operator<< (std::ostream & o, const field< T1 > & X) [inline]
Print the contents of a field to the specified stream Assumes type T1 can be printed, i.e. T1 has std::ostream& operator<< (std::ostream&, const T1&).
Definition at line 26 of file ostream_field.hpp.
  {
  arma_extra_debug_sigprint();
  const ios::fmtflags orig_flags = o.flags();
  for(u32 col=0; col<X.n_cols; ++col)
    {
    o << "[field column " << col << ']' << '\n';
    for(u32 row=0; row<X.n_rows; ++row)
      {
      o << X.at(row,col) << '\n';
      }
    o << '\n';
    }
  o.flush();
  o.flags(orig_flags);
  return o;
  }
template<typename T1> std::ostream& operator<< (std::ostream & o, const subview_field< T1 > & X) [inline]
Print the contents of a subfield to the specified stream Assumes type T1 can be printed, i.e. T1 has std::ostream& operator<< (std::ostream&, const T1&).
Definition at line 57 of file ostream_field.hpp.
  {
  arma_extra_debug_sigprint();
  const ios::fmtflags orig_flags = o.flags();
  for(u32 col=0; col<X.n_cols; ++col)
    {
    for(u32 row=0; row<X.n_rows; ++row)
      {
      o << X.at(row,col) << '\n';
      }
    o << '\n';
    }
  o.flush();
  o.flags(orig_flags);
  return o;
  }
template<typename eT> std::ostream& operator<< (std::ostream & o, const basic_mat< eT > & m) [inline]
Print a matrix to the specified stream.
Definition at line 121 of file ostream_mat.hpp.
References arma_ostream::set_flags().
  {
  arma_extra_debug_sigprint();
  const ios::fmtflags orig_flags = o.flags();
  const u32 cell_width = arma_ostream::set_flags(o, m);
  for(u32 row=0; row != m.n_rows; ++row)
    {
    for(u32 col=0; col != m.n_cols; ++col)
      {
      o.width(cell_width);
      o << m.at(row,col);
      }
    o << '\n';
    }
  o.flush();
  o.flags(orig_flags);
  return o;
  }
template<typename T1> std::ostream& operator<< (std::ostream & o, const arma_base< typename T1::elem_type, T1 > & X) [inline]
Definition at line 22 of file ostream_misc.hpp.
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  o << tmp.M;
  return o;
  }
template<typename eT> u32 arma_ostream::set_flags (std::ostream & o, const basic_mat< eT > & m) [inline, static, inherited]
Definition at line 36 of file ostream_mat.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
Referenced by operator<<().
  {
  o.unsetf(ios::showbase);
  o.unsetf(ios::uppercase);
  o.fill(' ');
  bool use_layout_B = false;
  bool use_layout_C = false;
  for(u32 i=0; i<m.n_elem; ++i)
    {
    const eT val = m.mem[i];
    if(
      val >= eT(+100) ||
      ( (is_signed<eT>::value == true) && (val <= eT(-100)) ) ||
      ( (is_non_integral<eT>::value == true) && (val > eT(0)) && (val <= eT(+1e-4)) ) ||
      ( (is_non_integral<eT>::value == true) && (is_signed<eT>::value == true) && (val < eT(0)) && (val >= eT(-1e-4)) )
      )
      {
      use_layout_C = true;
      break;
      }
    if(
      (val >= eT(+10)) || ( (is_signed<eT>::value == true) && (val <= eT(-10)) )
      )
      {
      use_layout_B = true;
      }
    }
  u32 cell_width;
  if(use_layout_C == true)
    {
    o.setf(ios::scientific);
    o.unsetf(ios::fixed);
    o.precision(4);
    cell_width = 13;
    }
  else
  if(use_layout_B == true)
    {
    o.unsetf(ios::scientific);
    o.setf(ios::fixed);
    o.precision(4);
    cell_width = 10;
    }
  else
    {
    o.unsetf(ios::scientific);
    o.setf(ios::fixed);
    o.precision(4);
    cell_width = 9;
    }
  return cell_width;
  }
template<typename T> u32 arma_ostream::set_flags (std::ostream & o, const basic_mat< std::complex< T > > & m) [inline, static, inherited]
"better than nothing" settings for complex numbers
Definition at line 102 of file ostream_mat.hpp.
  {
  o.unsetf(ios::showbase);
  o.unsetf(ios::uppercase);
  o.fill(' ');
  o.setf(ios::scientific);
  o.unsetf(ios::fixed);
  o.precision(3);
  const u32 cell_width = 27;
  return cell_width;
  }