Armadillo Technical: Fn_max
Fn_max
Functions
template<typename T1>
const op_data< T1, op_max > max (const arma_base< typename T1::elem_type, T1 > &X, const u32 dim=0)
Delayed 'maximum values' operation. The dimension, along which the maxima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
template<typename eT>
eT max (const basic_rowvec< eT > &A)
Immediate 'find the maximum value in a row vector' operation.
template<typename eT>
eT max (const basic_colvec< eT > &A)
Immediate 'find the maximum value in a column vector' operation.
template<typename T1>
T1::elem_type max (const op_data< T1, op_max > &in)
Immediate 'find maximum value' operation, invoked, for example, by: max(max(A)).
template<typename T1>
const op_data< op_data< T1,
op_max >, op_max > max (const op_data< T1, op_max > &in, const u32 dim)
template<typename eT>
eT max (const subview_row< eT > &A)
template<typename eT>
eT max (const subview_col< eT > &A)
template<typename eT>
eT max (const op_data< subview< eT >, op_max > &in)
template<typename eT>
eT max (const diagview< eT > &A)
Function Documentation
template<typename T1> const op_data<T1, op_max> max (const arma_base< typename T1::elem_type, T1 > & X, const u32 dim = 0) [inline]
Delayed 'maximum values' operation. The dimension, along which the maxima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
Definition at line 31 of file fn_max.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by auxlib::eig(), auxlib::inv_inplace(), auxlib::inv_noalias(), basic_math< eT >::log_max(), operator<<(), auxlib::qr(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), and trunc_exp().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_max>(X.get_ref(), dim, 0);
  }
template<typename eT> eT max (const basic_rowvec< eT > & A) [inline]
Immediate 'find the maximum value in a row vector' operation.
Definition at line 43 of file fn_max.hpp.
References op_max::direct_max(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A.mem, A.n_elem);
  }
template<typename eT> eT max (const basic_colvec< eT > & A) [inline]
Immediate 'find the maximum value in a column vector' operation.
Definition at line 58 of file fn_max.hpp.
References op_max::direct_max(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A.mem, A.n_elem);
  }
template<typename T1> T1::elem_type max (const op_data< T1, op_max > & in) [inline]
Immediate 'find maximum value' operation, invoked, for example, by: max(max(A)).
Definition at line 75 of file fn_max.hpp.
References op_max::direct_max(), op_data< T1, op_type >::m, basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("max(): two consecutive max() calls detected");
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.m);
  const basic_mat<eT>& X = tmp1.M;
  arma_debug_check( (X.n_elem == 0), "max(): given matrix has no elements" );
  return op_max::direct_max(X.mem, X.n_elem);
  }
template<typename T1> const op_data< op_data<T1, op_max>, op_max> max (const op_data< T1, op_max > & in, const u32 dim) [inline]
Definition at line 95 of file fn_max.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data< op_data<T1, op_max>, op_max>(in, dim, 0);
  }
template<typename eT> eT max (const subview_row< eT > & A) [inline]
Definition at line 107 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }
template<typename eT> eT max (const subview_col< eT > & A) [inline]
Definition at line 121 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }
template<typename eT> eT max (const op_data< subview< eT >, op_max > & in) [inline]
Definition at line 135 of file fn_max.hpp.
References op_max::direct_max(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("max(): two consecutive max() calls detected");
  const subview<eT>& X = in.m;
  arma_debug_check( (X.n_elem == 0), "max(): given matrix has no elements" );
  return op_max::direct_max(X);
  }
template<typename eT> eT max (const diagview< eT > & A) [inline]
Definition at line 152 of file fn_max.hpp.
References op_max::direct_max(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "max(): given vector has no elements" );
  return op_max::direct_max(A);
  }