Armadillo Technical: Op_randn
Op_randn
Classes
class op_randn
'generate matrix with random values' operation
Functions
template<typename eT>
static eT op_randn::randn ()
template<typename eT>
static void op_randn::direct_randn (eT *x, const u32 n_elem)
template<typename eT>
static void op_randn::apply (basic_mat< eT > &out, const op_data< basic_mat< eT >, op_randn > &in)
template<typename eT>
static void op_randn::apply (basic_mat< eT > &out, const op_data< basic_colvec< eT >, op_randn > &in)
template<typename eT>
static void op_randn::apply (basic_mat< eT > &out, const op_data< basic_rowvec< eT >, op_randn > &in)
template<typename eT>
static void op_randn::apply (basic_colvec< eT > &out, const op_data< basic_colvec< eT >, op_randn > &in)
template<typename eT>
static void op_randn::apply (basic_rowvec< eT > &out, const op_data< basic_rowvec< eT >, op_randn > &in)
Function Documentation
template<typename eT> eT op_randn::randn () [inline, static, private, inherited]
Definition at line 34 of file op_randn_meat.hpp.
References rand().
  {
  const u32 N = 12;
  eT acc = eT(0);
  for(u32 i=0; i<N; ++i)
    {
    acc += eT(std::rand()) / eT(RAND_MAX);
    }
  return acc/eT(N) - eT(0.5);
  }
template<typename eT> void op_randn::direct_randn (eT * x, const u32 n_elem) [inline, static, private, inherited]
Definition at line 52 of file op_randn_meat.hpp.
Referenced by apply().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    x[i] = eT(op_randn::randn<eT>());
    }
  }
template<typename eT> void op_randn::apply (basic_mat< eT > & out, const op_data< basic_mat< eT >, op_randn > & in) [inline, static, inherited]
Definition at line 68 of file op_randn_meat.hpp.
References direct_randn(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  const u32 n_rows = in.aux_u32_a;
  const u32 n_cols = (in.aux_u32_b > 0) ? in.aux_u32_b : 1;
  out.set_size(n_rows, n_cols);
  op_randn::direct_randn(out.memptr(), out.n_elem);
  }
template<typename eT> void op_randn::apply (basic_mat< eT > & out, const op_data< basic_colvec< eT >, op_randn > & in) [inline, static, inherited]
Definition at line 85 of file op_randn_meat.hpp.
References direct_randn(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a, 1);
  op_randn::direct_randn(out.memptr(), out.n_elem);
  }
template<typename eT> void op_randn::apply (basic_mat< eT > & out, const op_data< basic_rowvec< eT >, op_randn > & in) [inline, static, inherited]
Definition at line 99 of file op_randn_meat.hpp.
References direct_randn(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(1, in.aux_u32_a);
  op_randn::direct_randn(out.memptr(), out.n_elem);
  }
template<typename eT> void op_randn::apply (basic_colvec< eT > & out, const op_data< basic_colvec< eT >, op_randn > & in) [inline, static, inherited]
Definition at line 113 of file op_randn_meat.hpp.
References direct_randn(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_colvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  op_randn::direct_randn(out.memptr(), out.n_elem);
  }
template<typename eT> void op_randn::apply (basic_rowvec< eT > & out, const op_data< basic_rowvec< eT >, op_randn > & in) [inline, static, inherited]
Definition at line 127 of file op_randn_meat.hpp.
References direct_randn(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_rowvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  op_randn::direct_randn(out.memptr(), out.n_elem);
  }