Armadillo Technical: Fn_sum
Fn_sum
Functions
template<typename T1>
const op_data< T1, op_sum > sum (const arma_base< typename T1::elem_type, T1 > &X, const u32 dim=0)
Delayed sum of elements of a matrix along a specified dimension (either rows or columns). The result is stored in a dense matrix that has either one column or one row. For dim = 0, find the sum of each column. For dim = 1, find the sum of each row. The default is dim = 0. NOTE: this function works differently than in Matlab/Octave.
template<typename eT>
eT sum (const basic_rowvec< eT > &X)
Immediate 'sum all values' operation for a row vector.
template<typename eT>
eT sum (const basic_colvec< eT > &X)
Immediate 'sum all values' operation for a column vector.
template<typename T1>
T1::elem_type sum (const op_data< T1, op_sum > &in)
Immediate 'sum all values' operation, invoked, for example, by: sum(sum(A)).
template<typename T1>
const op_data< op_data< T1,
op_sum >, op_sum > sum (const op_data< T1, op_sum > &in, const u32 dim)
template<typename eT>
eT sum (const subview_row< eT > &X)
sum all values of a subview_row
template<typename eT>
eT sum (const subview_col< eT > &X)
sum all values of a subview_col
template<typename eT>
eT sum (const diagview< eT > &X)
sum all values of a diagview
Function Documentation
template<typename T1> const op_data<T1, op_sum> sum (const arma_base< typename T1::elem_type, T1 > & X, const u32 dim = 0) [inline]
Delayed sum of elements of a matrix along a specified dimension (either rows or columns). The result is stored in a dense matrix that has either one column or one row. For dim = 0, find the sum of each column. For dim = 1, find the sum of each row. The default is dim = 0. NOTE: this function works differently than in Matlab/Octave.
Definition at line 31 of file fn_sum.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by diskio::gen_tmp_name().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_sum>(X.get_ref(), dim, 0);
  }
template<typename eT> eT sum (const basic_rowvec< eT > & X) [inline]
Immediate 'sum all values' operation for a row vector.
Definition at line 44 of file fn_sum.hpp.
References accu().
  {
  arma_extra_debug_sigprint();
  return accu(X);
  }
template<typename eT> eT sum (const basic_colvec< eT > & X) [inline]
Immediate 'sum all values' operation for a column vector.
Definition at line 58 of file fn_sum.hpp.
References accu().
  {
  arma_extra_debug_sigprint();
  return accu(X);
  }
template<typename T1> T1::elem_type sum (const op_data< T1, op_sum > & in) [inline]
Immediate 'sum all values' operation, invoked, for example, by: sum(sum(A)).
Definition at line 74 of file fn_sum.hpp.
References accu(), and op_data< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("sum(): two consecutive sum() calls detected");
  return accu(in.m);
  }
template<typename T1> const op_data<op_data<T1, op_sum>, op_sum> sum (const op_data< T1, op_sum > & in, const u32 dim) [inline]
Definition at line 87 of file fn_sum.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data<op_data<T1, op_sum>, op_sum>(in, dim, 0);
  }
template<typename eT> eT sum (const subview_row< eT > & X) [inline]
sum all values of a subview_row
Definition at line 100 of file fn_sum.hpp.
References accu().
  {
  arma_extra_debug_sigprint();
  return accu(X);
  }
template<typename eT> eT sum (const subview_col< eT > & X) [inline]
sum all values of a subview_col
Definition at line 113 of file fn_sum.hpp.
References accu().
  {
  arma_extra_debug_sigprint();
  return accu(X);
  }
template<typename eT> eT sum (const diagview< eT > & X) [inline]
sum all values of a diagview
Definition at line 126 of file fn_sum.hpp.
References accu().
  {
  arma_extra_debug_sigprint();
  return accu(X);
  }