Armadillo Technical: Fn_lu
Fn_lu
Functions
template<typename eT, typename T1>
void lu (basic_mat< eT > &L, basic_mat< eT > &U, const arma_base< eT, T1 > &X)
immediate lower upper decomposition
template<typename eT, typename T1>
void lu (basic_mat< eT > &L, basic_mat< eT > &U, basic_mat< eT > &P, const arma_base< eT, T1 > &X)
immediate lower upper decomposition, also providing the permutation matrix
Function Documentation
template<typename eT, typename T1> void lu (basic_mat< eT > & L, basic_mat< eT > & U, const arma_base< eT, T1 > & X) [inline]
immediate lower upper decomposition
Definition at line 24 of file fn_lu.hpp.
References arma_base< elem_type, arma_derived >::get_ref(), and auxlib::lu().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  auxlib::lu(L, U, tmp.M);
  }
template<typename eT, typename T1> void lu (basic_mat< eT > & L, basic_mat< eT > & U, basic_mat< eT > & P, const arma_base< eT, T1 > & X) [inline]
immediate lower upper decomposition, also providing the permutation matrix
Definition at line 39 of file fn_lu.hpp.
References arma_base< elem_type, arma_derived >::get_ref(), and auxlib::lu().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  auxlib::lu(L, U, P, tmp.M);
  }