Armadillo Technical: Fn_sort
Fn_sort
Functions
template<typename T1>
const op_data< T1, op_sort > sort (const arma_base< typename T1::elem_type, T1 > &X, const u32 sort_type=0, const u32 dim=0)
template<typename eT>
const op_data< basic_colvec
< eT >, op_sort > sort (const basic_colvec< eT > &X, const u32 sort_type=0)
template<typename eT>
const op_data< basic_rowvec
< eT >, op_sort > sort (const basic_rowvec< eT > &X, const u32 sort_type=0)
Function Documentation
template<typename T1> const op_data<T1, op_sort> sort (const arma_base< typename T1::elem_type, T1 > & X, const u32 sort_type = 0, const u32 dim = 0) [inline]
Definition at line 23 of file fn_sort.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by op_median::direct_cx_median_index(), op_median::direct_median(), and sort_index_helper().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_sort>(X.get_ref(), sort_type, dim);
  }
template<typename eT> const op_data<basic_colvec<eT>, op_sort> sort (const basic_colvec< eT > & X, const u32 sort_type = 0) [inline]
Definition at line 35 of file fn_sort.hpp.
  {
  arma_extra_debug_sigprint();
  const u32 dim = 0;
  return op_data<basic_colvec<eT>, op_sort>(X, sort_type, dim);
  }
template<typename eT> const op_data<basic_rowvec<eT>, op_sort> sort (const basic_rowvec< eT > & X, const u32 sort_type = 0) [inline]
Definition at line 49 of file fn_sort.hpp.
  {
  arma_extra_debug_sigprint();
  const u32 dim = 1;
  return op_data<basic_rowvec<eT>, op_sort>(X, sort_type, dim);
  }