Armadillo Technical: Op_diagmat
Op_diagmat
Classes
class op_diagmat
convert a mat/rowvec/colvec to a diagonal matrix
class op_diagmat_vec
Functions
template<typename eT>
static void op_diagmat::zero_offdiag (basic_mat< eT > &X)
template<typename T1>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_diagmat > &in)
template<typename T1, typename T2>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< glue_data< T1, T2, glue_div >, op_diagmat > &in)
template<typename T1, typename T2>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< glue_data< T1, T2, glue_minus >, op_diagmat > &in)
template<typename T1, typename T2>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< glue_data< T1, T2, glue_plus >, op_diagmat > &in)
template<typename T1, typename T2>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< glue_data< T1, T2, glue_schur >, op_diagmat > &in)
template<typename T1, typename T2>
static void op_diagmat::apply (basic_mat< typename T1::elem_type > &out, const op_data< glue_data< T1, T2, glue_times >, op_diagmat > &in)
template<typename T1>
static void op_diagmat_vec::apply (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_diagmat_vec > &in)
Function Documentation
template<typename eT> void op_diagmat::zero_offdiag (basic_mat< eT > & X) [inline, static, private, inherited]
Definition at line 24 of file op_diagmat_meat.hpp.
References basic_mat< eT >::colptr(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
Referenced by apply().
  {
  for(u32 col=0; col<X.n_cols; ++col)
    {
    eT* colmem = X.colptr(col);
    // above the diagonal
    for(u32 row=0; row<col; ++row)
      {
      colmem[row] = eT(0);
      }
    // below the diagonal
    for(u32 row=col+1; row<X.n_rows; ++row)
      {
      colmem[row] = eT(0);
      }
    }
  }
template<typename T1> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_diagmat > & in) [inline, static, inherited]
Definition at line 51 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), op_data< T1, op_type >::m, basic_mat< eT >::n_rows, zero_offdiag(), and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.m);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& X = tmp.M;
  arma_debug_check( !X.is_square(), "diagmat(): matrix must be square" );
  if(&out != &X)
    {
    out.zeros(X.n_rows, X.n_rows);
    for(u32 i=0; i<X.n_rows; ++i)
      {
      out.at(i,i) = X.at(i,i);
      }
    }
  else
    {
    op_diagmat::zero_offdiag(out);
    }
  }
template<typename T1, typename T2> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< glue_data< T1, T2, glue_div >, op_diagmat > & in) [inline, static, inherited]
Definition at line 82 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), basic_mat< eT >::n_rows, basic_mat< eT >::set_size(), and zero_offdiag().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (!A.is_square() || !B.is_square()), "diagmat(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix element-wise division");
  // not using out.zeros() as 'out' might be an alias of A and/or B.
  // the off-diagonal elements are zeroed at the end
  out.set_size(A.n_rows, A.n_rows);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = A.at(i,i) / B.at(i,i);
    }
  op_diagmat::zero_offdiag(out);
  }
template<typename T1, typename T2> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< glue_data< T1, T2, glue_minus >, op_diagmat > & in) [inline, static, inherited]
Definition at line 114 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), basic_mat< eT >::n_rows, basic_mat< eT >::set_size(), and zero_offdiag().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (!A.is_square() || !B.is_square()), "diagmat(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix subtraction");
  // not using out.zeros() as 'out' might be an alias of A and/or B.
  // the off-diagonal elements are zeroed at the end
  out.set_size(A.n_rows, A.n_rows);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = A.at(i,i) - B.at(i,i);
    }
  op_diagmat::zero_offdiag(out);
  }
template<typename T1, typename T2> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< glue_data< T1, T2, glue_plus >, op_diagmat > & in) [inline, static, inherited]
Definition at line 146 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), basic_mat< eT >::n_rows, basic_mat< eT >::set_size(), and zero_offdiag().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (!A.is_square() || !B.is_square()), "diagmat(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix addition");
  // not using out.zeros() as 'out' might be an alias of A and/or B.
  // the off-diagonal elements are zeroed at the end
  out.set_size(A.n_rows, A.n_rows);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = A.at(i,i) + B.at(i,i);
    }
  op_diagmat::zero_offdiag(out);
  }
template<typename T1, typename T2> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< glue_data< T1, T2, glue_schur >, op_diagmat > & in) [inline, static, inherited]
Definition at line 178 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::is_square(), basic_mat< eT >::n_rows, basic_mat< eT >::set_size(), and zero_offdiag().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp1(in.m.A);
  const unwrap<T2> tmp2(in.m.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (!A.is_square() || !B.is_square()), "diagmat(): matrices must be square" );
  arma_debug_assert_same_size(A, B, "matrix schur product");
  // not using out.zeros() as 'out' might be an alias of A and/or B.
  // the off-diagonal elements are zeroed at the end
  out.set_size(A.n_rows, A.n_rows);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    out.at(i,i) = A.at(i,i) * B.at(i,i);
    }
  op_diagmat::zero_offdiag(out);
  }
template<typename T1, typename T2> void op_diagmat::apply (basic_mat< typename T1::elem_type > & out, const op_data< glue_data< T1, T2, glue_times >, op_diagmat > & in) [inline, static, inherited]
Definition at line 210 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::colptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  const unwrap_check<T1> tmp1(in.m.A, out);
  const unwrap_check<T2> tmp2(in.m.B, out);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (A.n_rows != B.n_cols), "diagmat(): result of multiplication is not square" );
  arma_debug_assert_mul_size(A, B, "matrix multiplication");
  // out is cleared here, as we've made sure that A and B are not aliases of 'out'
  out.zeros(A.n_rows, A.n_rows);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    const eT* B_colmem = B.colptr(i);
    eT val = eT(0);
    for(u32 j=0; j<A.n_cols; ++j)
      {
      val += A.at(i,j) * B_colmem[j];
      }
    out.at(i,i) = val;
    }
  }
template<typename T1> void op_diagmat_vec::apply (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_diagmat_vec > & in) [inline, static, inherited]
Definition at line 252 of file op_diagmat_meat.hpp.
References basic_mat< eT >::at(), op_data< T1, op_type >::m, basic_mat< eT >::mem, podarray< T1 >::n_elem, basic_mat< eT >::n_elem, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.m);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& X = tmp.M;
  if(&out != &X)
    {
    out.zeros(X.n_elem, X.n_elem);
    const eT* X_mem = X.mem;
    for(u32 i=0; i<X.n_elem; ++i)
      {
      out.at(i,i) = X_mem[i];
      }
    }
  else
    {
    podarray<eT> tmp(X.n_elem);
    for(u32 i=0; i<X.n_elem; ++i)
      {
      tmp[i] = X[i];
      }
    out.zeros(tmp.n_elem, tmp.n_elem);
    for(u32 i=0; i<tmp.n_elem; ++i)
      {
      out.at(i,i) = tmp[i];
      }
    }
  }