Armadillo Technical: Diagview
Diagview
Classes
class diagview< eT >
Class for storing data required to extract and set the diagonals of a matrix.
Functions
diagview::~diagview ()
diagview::diagview (const basic_mat< eT > &in_m, const u32 in_row_offset, const u32 in_col_offset, const u32 len)
diagview::diagview (basic_mat< eT > &in_m, const u32 in_row_offset, const u32 in_col_offset, const u32 len)
template<typename T1>
void diagview::operator= (const arma_base< eT, T1 > &x)
set a diagonal of our matrix using data from a foreign object
void diagview::operator= (const diagview &x)
set a diagonal of our matrix using a diagonal from a foreign matrix
static void diagview::extract (basic_mat< eT > &out, const diagview &in)
extract a diagonal and store it as a column vector
eT & diagview::operator[] (const u32 i)
eT diagview::operator[] (const u32 i) const
eT & diagview::operator() (const u32 i)
eT diagview::operator() (const u32 i) const
void diagview::fill (const eT val)
void diagview::zeros ()
Function Documentation
template<typename eT> diagview< eT >::~diagview () [inline, inherited]
Definition at line 22 of file diagview_meat.hpp.
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> diagview< eT >::diagview (const basic_mat< eT > & in_m, const u32 in_row_offset, const u32 in_col_offset, const u32 len) [inline, protected, inherited]
Definition at line 30 of file diagview_meat.hpp.
  : m(in_m)
  , m_ptr(0)
  , row_offset(in_row_offset)
  , col_offset(in_col_offset)
  , n_elem(in_len)
//   , len
//       (
//       (id == 0)
//         ? (std::min)(m.n_rows, m.n_cols)
//         : (
//           (id > 0)
//             ? (std::min)(m.n_rows,      m.n_cols - id)
//             : (std::min)(m.n_rows + id, m.n_cols)
//)
//)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> diagview< eT >::diagview (basic_mat< eT > & in_m, const u32 in_row_offset, const u32 in_col_offset, const u32 len) [inline, protected, inherited]
Definition at line 54 of file diagview_meat.hpp.
  : m(in_m)
  , m_ptr(&in_m)
  , row_offset(in_row_offset)
  , col_offset(in_col_offset)
  , n_elem(in_len)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> template<typename T1> void diagview< eT >::operator= (const arma_base< eT, T1 > & x) [inline, inherited]
set a diagonal of our matrix using data from a foreign object
Definition at line 71 of file diagview_meat.hpp.
References arma_check(), basic_mat< eT >::at(), diagview< eT >::col_offset, arma_base< elem_type, arma_derived >::get_ref(), diagview< eT >::m_ptr, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_extra_debug_sigprint();
  arma_check( (m_ptr == 0), "diagview::operator=(): matrix is read only");
  const unwrap<T1> tmp(o.get_ref());
  const basic_mat<eT>& x = tmp.M;
  diagview& t = *this;
  arma_debug_check( !x.is_vec(), "diagview::operator=(): need a vector");
  arma_debug_check( (t.n_elem != x.n_elem), "diagview::operator=(): diagonal and given vector have incompatible lengths");
  basic_mat<eT>& t_m = *(t.m_ptr);
  for(u32 i=0; i<n_elem; ++i)
    {
    t_m.at(i+row_offset, i+col_offset) = x.mem[i];
    }
  }
template<typename eT> void diagview< eT >::operator= (const diagview< eT > & x) [inline, inherited]
set a diagonal of our matrix using a diagonal from a foreign matrix
Definition at line 99 of file diagview_meat.hpp.
References arma_check(), basic_mat< eT >::at(), diagview< eT >::col_offset, diagview< eT >::m, diagview< eT >::m_ptr, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_extra_debug_sigprint();
  arma_check( (m_ptr == 0), "diagview::operator=(): matrix is read only");
  diagview<eT>& t = *this;
  arma_debug_check( (t.n_elem != x.n_elem), "diagview::operator=(): diagonals have incompatible lengths");
        basic_mat<eT>& t_m = *(t.m_ptr);
  const basic_mat<eT>& x_m = x.m;
  for(u32 i=0; i<n_elem; ++i)
    {
    t_m.at(i+t.row_offset, i+t.col_offset) = x_m.at(i+x.row_offset, i+x.col_offset);
    }
  }
template<typename eT> void diagview< eT >::extract (basic_mat< eT > & out, const diagview< eT > & in) [inline, static, inherited]
extract a diagonal and store it as a column vector
Definition at line 125 of file diagview_meat.hpp.
References basic_mat< eT >::at(), diagview< eT >::col_offset, diagview< eT >::m, basic_mat< eT >::memptr(), diagview< eT >::n_elem, diagview< eT >::row_offset, and basic_mat< eT >::set_size().
Referenced by basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  const basic_mat<eT>& in_m = in.m;
  const bool alias = (&actual_out == &in_m);
  basic_mat<eT>* tmp = (alias) ? new basic_mat<eT> : 0;
  basic_mat<eT>& out = (alias) ? (*tmp)            : actual_out;
  const u32 in_n_elem     = in.n_elem;
  const u32 in_row_offset = in.row_offset;
  const u32 in_col_offset = in.col_offset;
  out.set_size(in_n_elem,1);
  eT* out_mem = out.memptr();
  for(u32 i=0; i<in_n_elem; ++i)
    {
    out_mem[i] = in_m.at(i+in_row_offset, i+in_col_offset);
    }
  if(alias)
    {
    actual_out = out;
    delete tmp;
    }
  }
template<typename eT> eT & diagview< eT >::operator[] (const u32 i) [inline, inherited]
Definition at line 161 of file diagview_meat.hpp.
References diagview< eT >::col_offset, and diagview< eT >::row_offset.
  {
  return (*m_ptr).at(i+row_offset, i+col_offset);
  }
template<typename eT> eT diagview< eT >::operator[] (const u32 i) const [inline, inherited]
Definition at line 171 of file diagview_meat.hpp.
References diagview< eT >::col_offset, diagview< eT >::m, and diagview< eT >::row_offset.
  {
  return m.at(i+row_offset, i+col_offset);
  }
template<typename eT> eT & diagview< eT >::operator() (const u32 i) [inline, inherited]
Definition at line 181 of file diagview_meat.hpp.
References arma_check(), diagview< eT >::col_offset, diagview< eT >::m_ptr, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_check( (m_ptr == 0), "diagview::operator(): matrix is read only");
  arma_debug_check( (i > n_elem), "diagview::operator(): index out of bounds" );
  return (*m_ptr).at(i+row_offset, i+col_offset);
  }
template<typename eT> eT diagview< eT >::operator() (const u32 i) const [inline, inherited]
Definition at line 194 of file diagview_meat.hpp.
References diagview< eT >::col_offset, diagview< eT >::m, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_debug_check( (i > n_elem), "diagview::operator(): index out of bounds" );
  return m.at(i+row_offset, i+col_offset);
  }
template<typename eT> void diagview< eT >::fill (const eT val) [inline, inherited]
Definition at line 206 of file diagview_meat.hpp.
References arma_check(), basic_mat< eT >::at(), diagview< eT >::col_offset, diagview< eT >::m_ptr, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_extra_debug_sigprint();
  arma_check( (m_ptr == 0), "diagview::operator(): matrix is read only");
  basic_mat<eT>& x = (*m_ptr);
  for(u32 i=0; i<n_elem; ++i)
    {
    x.at(i+row_offset, i+col_offset) = val;
    }
  }
template<typename eT> void diagview< eT >::zeros () [inline, inherited]
Definition at line 224 of file diagview_meat.hpp.
References arma_check(), basic_mat< eT >::at(), diagview< eT >::col_offset, diagview< eT >::m_ptr, diagview< eT >::n_elem, and diagview< eT >::row_offset.
  {
  arma_extra_debug_sigprint();
  arma_check( (m_ptr == 0), "diagview::operator(): matrix is read only");
  basic_mat<eT>& x = (*m_ptr);
  for(u32 i=0; i<n_elem; ++i)
    {
    x.at(i+row_offset, i+col_offset) = eT(0);
    }
  }