Armadillo Technical: Fn_mean
Fn_mean
Functions
template<typename T1>
const op_data< T1, op_mean > mean (const arma_base< typename T1::elem_type, T1 > &X, const u32 dim=0)
template<typename eT>
eT mean (const basic_rowvec< eT > &A)
Immediate 'find the mean value of a row vector' operation.
template<typename eT>
eT mean (const basic_colvec< eT > &A)
Immediate 'find the mean value of a column vector' operation.
template<typename T1>
T1::elem_type mean (const op_data< T1, op_mean > &in)
Immediate 'find mean value' operation, invoked, for example, by: mean(mean(A)).
template<typename T1>
const op_data< op_data< T1,
op_mean >, op_mean > mean (const op_data< T1, op_mean > &in, const u32 dim)
template<typename eT>
eT mean (const subview_row< eT > &A)
template<typename eT>
eT mean (const subview_col< eT > &A)
template<typename eT>
eT mean (const op_data< subview< eT >, op_mean > &in)
template<typename eT>
eT mean (const diagview< eT > &A)
Function Documentation
template<typename T1> const op_data<T1, op_mean> mean (const arma_base< typename T1::elem_type, T1 > & X, const u32 dim = 0) [inline]
Definition at line 24 of file fn_mean.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_mean>(X.get_ref(), dim, 0);
  }
template<typename eT> eT mean (const basic_rowvec< eT > & A) [inline]
Immediate 'find the mean value of a row vector' operation.
Definition at line 37 of file fn_mean.hpp.
References op_mean::direct_mean(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "mean(): given vector has no elements" );
  return op_mean::direct_mean(A.mem, A.n_elem);
  }
template<typename eT> eT mean (const basic_colvec< eT > & A) [inline]
Immediate 'find the mean value of a column vector' operation.
Definition at line 52 of file fn_mean.hpp.
References op_mean::direct_mean(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "mean(): given vector has no elements" );
  return op_mean::direct_mean(A.mem, A.n_elem);
  }
template<typename T1> T1::elem_type mean (const op_data< T1, op_mean > & in) [inline]
Immediate 'find mean value' operation, invoked, for example, by: mean(mean(A)).
Definition at line 69 of file fn_mean.hpp.
References op_mean::direct_mean(), op_data< T1, op_type >::m, basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("mean(): two consecutive mean() calls detected");
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.m);
  const basic_mat<eT>& X = tmp1.M;
  arma_debug_check( (X.n_elem == 0), "mean(): given matrix has no elements" );
  return op_mean::direct_mean(X.mem, X.n_elem);
  }
template<typename T1> const op_data< op_data<T1, op_mean>, op_mean> mean (const op_data< T1, op_mean > & in, const u32 dim) [inline]
Definition at line 89 of file fn_mean.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data< op_data<T1, op_mean>, op_mean>(in, dim, 0);
  }
template<typename eT> eT mean (const subview_row< eT > & A) [inline]
Definition at line 101 of file fn_mean.hpp.
References op_mean::direct_mean(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "mean(): given vector has no elements" );
  return op_mean::direct_mean(A);
  }
template<typename eT> eT mean (const subview_col< eT > & A) [inline]
Definition at line 115 of file fn_mean.hpp.
References op_mean::direct_mean(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "mean(): given vector has no elements" );
  return op_mean::direct_mean(A);
  }
template<typename eT> eT mean (const op_data< subview< eT >, op_mean > & in) [inline]
Definition at line 129 of file fn_mean.hpp.
References op_mean::direct_mean(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("mean(): two consecutive mean() calls detected");
  const subview<eT>& X = in.m;
  arma_debug_check( (X.n_elem == 0), "mean(): given matrix has no elements" );
  return op_mean::direct_mean(X);
  }
template<typename eT> eT mean (const diagview< eT > & A) [inline]
Definition at line 146 of file fn_mean.hpp.
References op_mean::direct_mean(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "mmean(): given vector has no elements" );
  return op_mean::direct_mean(A);
  }