Armadillo Technical: Basic_colvec
Basic_colvec
Classes
class basic_colvec< eT >
Class for column vectors (matrices with only column).
Functions
basic_colvec::basic_colvec ()
construct an empty column vector
basic_colvec::basic_colvec (const u32 n_elem)
construct a column vector with the specified number of n_elem
basic_colvec::basic_colvec (const char *text)
construct a column vector from specified text
const basic_colvec & basic_colvec::operator= (const char *text)
construct a column vector from specified text
basic_colvec::basic_colvec (const basic_colvec &X)
construct a column vector from a given column vector
const basic_colvec & basic_colvec::operator= (const basic_colvec &X)
construct a column vector from a given column vector
basic_colvec::basic_colvec (const basic_mat< eT > &X)
construct a column vector from a given matrix; the matrix must have exactly one column
const basic_colvec & basic_colvec::operator= (const basic_mat< eT > &X)
construct a column vector from a given matrix; the matrix must have exactly one column
const basic_colvec & basic_colvec::operator*= (const basic_mat< eT > &X)
in-place matrix multiplication
basic_colvec::basic_colvec (const eT *aux_mem, const u32 aux_length)
construct a column vector from a given auxillary array of eTs
template<typename T1, typename T2>
basic_colvec::basic_colvec (const arma_base< typename basic_colvec< eT >::pod_type, T1 > &A, const arma_base< typename basic_colvec< eT >::pod_type, T2 > &B)
basic_colvec::basic_colvec (const subview< eT > &X)
construct a column vector from given a submatrix; the submatrix must have exactly one column
const basic_colvec & basic_colvec::operator= (const subview< eT > &X)
construct a column vector from given a submatrix; the submatrix must have exactly one column
const basic_colvec & basic_colvec::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
basic_colvec::basic_colvec (const diagview< eT > &X)
construct a column vector from given a diagview
const basic_colvec & basic_colvec::operator= (const diagview< eT > &X)
construct a column vector from given a diagview
const basic_colvec & basic_colvec::operator*= (const diagview< eT > &X)
template<typename T1, typename op_type>
basic_colvec::basic_colvec (const op_data< T1, op_type > &X)
construct a column vector from op_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1, typename op_type>
const basic_colvec & basic_colvec::operator= (const op_data< T1, op_type > &X)
construct a column vector from op_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1, typename op_type>
const basic_colvec & basic_colvec::operator*= (const op_data< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1, typename T2, typename glue_type>
basic_colvec::basic_colvec (const glue_data< T1, T2, glue_type > &X)
construct a column vector from glue_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1, typename T2, typename glue_type>
const basic_colvec & basic_colvec::operator= (const glue_data< T1, T2, glue_type > &X)
construct a column vector from glue_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
template<typename T1, typename T2, typename glue_type>
const basic_colvec & basic_colvec::operator*= (const glue_data< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
void basic_colvec::set_size (const u32 n_elem)
change the number of n_rows
void basic_colvec::set_size (const u32 n_rows, const u32 n_cols)
change the number of n_rows (this function re-implements mat::set_size() in order to check the number of columns)
void basic_colvec::zeros ()
void basic_colvec::zeros (const u32 n_elem)
void basic_colvec::zeros (const u32 n_rows, const u32 n_cols)
void basic_colvec::load (const std::string name, const file_type type=auto_detect)
load a matrix from a file
Function Documentation
template<typename eT> basic_colvec< eT >::basic_colvec () [inline, inherited]
construct an empty column vector
Definition at line 23 of file basic_colvec_meat.hpp.
  : basic_mat<eT>()
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const u32 n_elem) [inline, explicit, inherited]
construct a column vector with the specified number of n_elem
Definition at line 34 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(in_n_elem,1)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const char * text) [inline, inherited]
construct a column vector from specified text
Definition at line 45 of file basic_colvec_meat.hpp.
References access::rw().
  : basic_mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  std::swap( access::rw(basic_mat<eT>::n_rows), access::rw(basic_mat<eT>::n_cols) );
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator= (const char * text) [inline, inherited]
construct a column vector from specified text
Reimplemented from basic_mat< eT >.
Definition at line 60 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=(), and access::rw().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(text);
  std::swap( access::rw(basic_mat<eT>::n_rows), access::rw(basic_mat<eT>::n_cols) );
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const basic_colvec< eT > & X) [inline, inherited]
construct a column vector from a given column vector
Definition at line 76 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator= (const basic_colvec< eT > & X) [inline, inherited]
construct a column vector from a given column vector
Definition at line 88 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  return *this;
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const basic_mat< eT > & X) [inline, inherited]
construct a column vector from a given matrix; the matrix must have exactly one column
Definition at line 101 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator= (const basic_mat< eT > & X) [inline, inherited]
construct a column vector from a given matrix; the matrix must have exactly one column
Reimplemented from basic_mat< eT >.
Definition at line 115 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator*= (const basic_mat< eT > & m) [inline, inherited]
in-place matrix multiplication
Reimplemented from basic_mat< eT >.
Definition at line 130 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const eT * aux_mem, const u32 aux_length) [inline, inherited]
construct a column vector from a given auxillary array of eTs
Definition at line 145 of file basic_colvec_meat.hpp.
References arma_check(), syslib::copy_elem(), and basic_colvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  set_size(aux_length, 1);
  arma_check( (basic_mat<eT>::n_elem != aux_length), "basic_colvec::basic_colvec(): don't know how to handle the given array" );
  syslib::copy_elem( basic_mat<eT>::memptr(), aux_mem, basic_mat<eT>::n_elem );
  }
template<typename eT> template<typename T1, typename T2> basic_colvec< eT >::basic_colvec (const arma_base< typename basic_colvec< eT >::pod_type, T1 > & A, const arma_base< typename basic_colvec< eT >::pod_type, T2 > & B) [inline, inherited]
Definition at line 162 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(A,B)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const subview< eT > & X) [inline, inherited]
construct a column vector from given a submatrix; the submatrix must have exactly one column
Definition at line 178 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a column vector from given a submatrix; the submatrix must have exactly one column
Reimplemented from basic_mat< eT >.
Definition at line 192 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented from basic_mat< eT >.
Definition at line 207 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_colvec< eT >::basic_colvec (const diagview< eT > & X) [inline, inherited]
construct a column vector from given a diagview
Definition at line 222 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a column vector from given a diagview
Reimplemented from basic_mat< eT >.
Definition at line 236 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_colvec< eT > & basic_colvec< eT >::operator*= (const diagview< eT > & X) [inline, inherited]
Definition at line 250 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> basic_colvec< eT >::basic_colvec (const op_data< T1, op_type > & X) [inline, inherited]
construct a column vector from op_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Definition at line 265 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> template<typename T1, typename op_type> const basic_colvec< eT > & basic_colvec< eT >::operator= (const op_data< T1, op_type > & X) [inline, inherited]
construct a column vector from op_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Reimplemented from basic_mat< eT >.
Definition at line 280 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec::operator=(): given matrix can't be interpreted as a column vector" );
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_colvec< eT > & basic_colvec< eT >::operator*= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented from basic_mat< eT >.
Definition at line 295 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec::operator=(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> basic_colvec< eT >::basic_colvec (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
construct a column vector from glue_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Definition at line 310 of file basic_colvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_colvec< eT > & basic_colvec< eT >::operator= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
construct a column vector from glue_data, i.e. run the previously delayed operations; the result of the operations must have exactly one column
Reimplemented from basic_mat< eT >.
Definition at line 325 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_colvec< eT > & basic_colvec< eT >::operator*= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented from basic_mat< eT >.
Definition at line 341 of file basic_colvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> void basic_colvec< eT >::set_size (const u32 n_elem) [inline, inherited]
change the number of n_rows
Definition at line 357 of file basic_colvec_meat.hpp.
References basic_mat< eT >::set_size().
Referenced by op_randn::apply(), op_rand::apply(), op_ones_full::apply(), basic_colvec< eT >::basic_colvec(), auxlib::eig(), and auxlib::svd().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::set_size(in_n_elem,1);
  }
template<typename eT> void basic_colvec< eT >::set_size (const u32 n_rows, const u32 n_cols) [inline, inherited]
change the number of n_rows (this function re-implements mat::set_size() in order to check the number of columns)
Reimplemented from basic_mat< eT >.
Definition at line 370 of file basic_colvec_meat.hpp.
References min(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::set_size( in_n_rows, (std::min)( u32(1), in_n_cols ) );
  arma_debug_check( (in_n_cols > 1), "basic_colvec::set_size(): incompatible dimensions" );
  }
template<typename eT> void basic_colvec< eT >::zeros () [inline, inherited]
Reimplemented from basic_mat< eT >.
Definition at line 383 of file basic_colvec_meat.hpp.
References basic_mat< eT >::zeros().
Referenced by op_zeros::apply().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros();
  }
template<typename eT> void basic_colvec< eT >::zeros (const u32 n_elem) [inline, inherited]
Definition at line 395 of file basic_colvec_meat.hpp.
References basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros(in_n_elem,1);
  }
template<typename eT> void basic_colvec< eT >::zeros (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from basic_mat< eT >.
Definition at line 407 of file basic_colvec_meat.hpp.
References min(), and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros( in_n_rows, (std::min)( u32(1), in_n_cols ) );
  arma_debug_check( (in_n_cols > 1), "basic_colvec::zeros(): incompatible dimensions" );
  }
template<typename eT> void basic_colvec< eT >::load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file
Reimplemented from basic_mat< eT >.
Definition at line 420 of file basic_colvec_meat.hpp.
References basic_mat< eT >::load().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::load(name,type);
  arma_debug_check( (basic_mat<eT>::n_cols > 1), "basic_colvec(): incompatible dimensions" );
  }