Armadillo Technical: Op_rand
Op_rand
Classes
class op_rand
'generate matrix with random values' operation
Functions
template<typename eT>
static void op_rand::direct_rand (eT *x, const u32 n_elem)
TODO: optionally use the Marsenne-Twister random number generator (see Boost).
template<typename T>
static void op_rand::direct_rand (std::complex< T > *x, const u32 n_elem)
template<typename eT>
static void op_rand::apply (basic_mat< eT > &out, const op_data< basic_mat< eT >, op_rand > &in)
template<typename eT>
static void op_rand::apply (basic_mat< eT > &out, const op_data< basic_colvec< eT >, op_rand > &in)
template<typename eT>
static void op_rand::apply (basic_mat< eT > &out, const op_data< basic_rowvec< eT >, op_rand > &in)
template<typename eT>
static void op_rand::apply (basic_colvec< eT > &out, const op_data< basic_colvec< eT >, op_rand > &in)
template<typename eT>
static void op_rand::apply (basic_rowvec< eT > &out, const op_data< basic_rowvec< eT >, op_rand > &in)
Function Documentation
template<typename eT> void op_rand::direct_rand (eT * x, const u32 n_elem) [inline, static, private, inherited]
TODO: optionally use the Marsenne-Twister random number generator (see Boost).
Definition at line 24 of file op_rand_meat.hpp.
References rand().
Referenced by apply().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    x[i] = eT(std::rand()) / eT(RAND_MAX);
    }
  }
template<typename T> void op_rand::direct_rand (std::complex< T > * x, const u32 n_elem) [inline, static, private, inherited]
Definition at line 41 of file op_rand_meat.hpp.
References rand().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    const T a = T(std::rand()) / T(RAND_MAX);
    const T b = T(std::rand()) / T(RAND_MAX);
    x[i] = std::complex<T>(a,b);
    }
  }
template<typename eT> void op_rand::apply (basic_mat< eT > & out, const op_data< basic_mat< eT >, op_rand > & in) [inline, static, inherited]
Definition at line 61 of file op_rand_meat.hpp.
References direct_rand(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  const u32 n_rows = in.aux_u32_a;
  const u32 n_cols = (in.aux_u32_b > 0) ? in.aux_u32_b : 1;
  out.set_size(n_rows, n_cols);
  op_rand::direct_rand(out.memptr(), out.n_elem);
  }
template<typename eT> void op_rand::apply (basic_mat< eT > & out, const op_data< basic_colvec< eT >, op_rand > & in) [inline, static, inherited]
Definition at line 78 of file op_rand_meat.hpp.
References direct_rand(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a, 1);
  op_rand::direct_rand(out.memptr(), out.n_elem);
  }
template<typename eT> void op_rand::apply (basic_mat< eT > & out, const op_data< basic_rowvec< eT >, op_rand > & in) [inline, static, inherited]
Definition at line 92 of file op_rand_meat.hpp.
References direct_rand(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(1, in.aux_u32_a);
  op_rand::direct_rand(out.memptr(), out.n_elem);
  }
template<typename eT> void op_rand::apply (basic_colvec< eT > & out, const op_data< basic_colvec< eT >, op_rand > & in) [inline, static, inherited]
Definition at line 106 of file op_rand_meat.hpp.
References direct_rand(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_colvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  op_rand::direct_rand(out.memptr(), out.n_elem);
  }
template<typename eT> void op_rand::apply (basic_rowvec< eT > & out, const op_data< basic_rowvec< eT >, op_rand > & in) [inline, static, inherited]
Definition at line 120 of file op_rand_meat.hpp.
References direct_rand(), basic_mat< eT >::memptr(), basic_mat< eT >::n_elem, and basic_rowvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  op_rand::direct_rand(out.memptr(), out.n_elem);
  }