Armadillo Technical: Fn_stddev
Fn_stddev
Functions
template<typename T1>
basic_mat< typename T1::pod_type > stddev (const arma_base< typename T1::elem_type, T1 > &X, const u32 norm_type=0, const u32 dim=0)
template<typename eT>
eT stddev (const basic_rowvec< eT > &A, const u32 norm_type=0)
Immediate 'find the standard deviation of a row vector' operation.
template<typename T>
T stddev (const basic_rowvec< std::complex< T > > &A, const u32 norm_type=0)
Immediate 'find the standard deviation of a row vector' operation (version for complex numbers).
template<typename eT>
eT stddev (const basic_colvec< eT > &A, const u32 norm_type=0)
Immediate 'find the standard deviation of a column vector' operation.
template<typename T>
T stddev (const basic_colvec< std::complex< T > > &A, const u32 norm_type=0)
Immediate 'find the standard deviation of a column vector' operation (version for complex numbers).
template<typename eT>
eT stddev (const subview_row< eT > &A, const u32 norm_type=0)
find the standard deviation of a subview_row
template<typename T>
T stddev (const subview_row< std::complex< T > > &A, const u32 norm_type=0)
find the standard deviation of a subview_row (version for complex numbers)
template<typename eT>
eT stddev (const subview_col< eT > &A, const u32 norm_type=0)
find the standard deviation of a subview_col
template<typename T>
T stddev (const subview_col< std::complex< T > > &A, const u32 norm_type=0)
find the standard deviation of a subview_col (version for complex numbers)
template<typename eT>
eT stddev (const diagview< eT > &A, const u32 norm_type=0)
find the standard deviation of a diagview
template<typename T>
T stddev (const diagview< std::complex< T > > &A, const u32 norm_type=0)
find the standard deviation of a diagview (version for complex numbers)
Function Documentation
template<typename T1> basic_mat<typename T1::pod_type> stddev (const arma_base< typename T1::elem_type, T1 > & X, const u32 norm_type = 0, const u32 dim = 0) [inline]
Definition at line 24 of file fn_stddev.hpp.
References op_stddev::apply(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> A_tmp(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  const basic_mat<in_eT>& A = A_tmp.M;
  basic_mat<out_eT> out;
  op_stddev::apply(out, A, norm_type, dim);
  return out;
  }
template<typename eT> eT stddev (const basic_rowvec< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the standard deviation of a row vector' operation.
Definition at line 52 of file fn_stddev.hpp.
References op_var::direct_var(), basic_mat< eT >::mem, basic_mat< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A.mem, A.n_elem, norm_type) );
  }
template<typename T> T stddev (const basic_rowvec< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Immediate 'find the standard deviation of a row vector' operation (version for complex numbers).
Definition at line 67 of file fn_stddev.hpp.
References op_var::direct_var(), and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A.mem, A.n_elem, norm_type) );
  }
template<typename eT> eT stddev (const basic_colvec< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the standard deviation of a column vector' operation.
Definition at line 82 of file fn_stddev.hpp.
References op_var::direct_var(), basic_mat< eT >::mem, basic_mat< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A.mem, A.n_elem, norm_type) );
  }
template<typename T> T stddev (const basic_colvec< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Immediate 'find the standard deviation of a column vector' operation (version for complex numbers).
Definition at line 97 of file fn_stddev.hpp.
References op_var::direct_var(), and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A.mem, A.n_elem, norm_type) );
  }
template<typename eT> eT stddev (const subview_row< eT > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a subview_row
Definition at line 112 of file fn_stddev.hpp.
References op_var::direct_var(), subview< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }
template<typename T> T stddev (const subview_row< std::complex< T > > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a subview_row (version for complex numbers)
Definition at line 127 of file fn_stddev.hpp.
References op_var::direct_var(), and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }
template<typename eT> eT stddev (const subview_col< eT > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a subview_col
Definition at line 142 of file fn_stddev.hpp.
References op_var::direct_var(), subview< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }
template<typename T> T stddev (const subview_col< std::complex< T > > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a subview_col (version for complex numbers)
Definition at line 157 of file fn_stddev.hpp.
References op_var::direct_var(), and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }
template<typename eT> eT stddev (const diagview< eT > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a diagview
Definition at line 172 of file fn_stddev.hpp.
References op_var::direct_var(), diagview< eT >::n_elem, and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }
template<typename T> T stddev (const diagview< std::complex< T > > & A, const u32 norm_type = 0) [inline]
find the standard deviation of a diagview (version for complex numbers)
Definition at line 187 of file fn_stddev.hpp.
References op_var::direct_var(), and sqrt().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return std::sqrt( op_var::direct_var(A, norm_type) );
  }