Armadillo Technical: Fn_qr
Fn_qr
Functions
template<typename eT, typename T1>
void qr (basic_mat< eT > &Q, basic_mat< eT > &R, const arma_base< eT, T1 > &X)
QR decomposition.
Function Documentation
template<typename eT, typename T1> void qr (basic_mat< eT > & Q, basic_mat< eT > & R, const arma_base< eT, T1 > & X) [inline]
QR decomposition.
Definition at line 24 of file fn_qr.hpp.
References arma_print(), arma_base< elem_type, arma_derived >::get_ref(), and auxlib::qr().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(X.get_ref());
  const bool ok = auxlib::qr(Q, R, tmp.M);
  if(ok == false)
    {
    arma_print("qr(): matrix factorisation failed");
    }
  }