Armadillo Technical: Fn_conv_to
Fn_conv_to
Classes
class conv_to< out_eT >
class conv_to< basic_mat< out_eT > >
class conv_to< basic_rowvec< out_eT > >
class conv_to< basic_colvec< out_eT > >
class conv_to< itpp::Mat< out_eT > >
class conv_to< itpp::Vec< out_eT > >
Functions
template<typename out_eT, typename in_eT>
void copy_complex_elem (out_eT &out, const in_eT &in)
template<typename out_eT, typename in_T>
void copy_complex_elem (out_eT &out, const std::complex< in_T > &in)
template<typename out_T, typename in_T>
void copy_complex_elem (std::complex< out_T > &out, const std::complex< in_T > &in)
static out_eT conv_to::from (const basic_mat< out_eT > &in)
template<typename in_eT>
static out_eT conv_to::from (const basic_mat< in_eT > &in)
template<typename in_eT, typename T1>
static out_eT conv_to::from (const arma_base< in_eT, T1 > &in)
template<typename in_eT>
static basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const basic_mat< in_eT > &in)
template<typename in_T>
static basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const basic_mat< std::complex< in_T > > &in)
template<typename in_eT, typename T1>
static basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const arma_base< in_eT, T1 > &in)
template<typename in_eT>
static basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const itpp::Mat< in_eT > &in)
template<typename in_T>
static basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const itpp::Mat< std::complex< in_T > > &in)
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< out_eT > &in)
template<typename in_eT>
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< in_eT > &in)
template<typename in_T>
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< std::complex< in_T > > &in)
template<typename in_eT, typename T1>
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const arma_base< in_eT, T1 > &in)
template<typename in_eT>
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const itpp::Vec< in_eT > &in)
template<typename in_T>
static basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const itpp::Vec< std::complex< in_T > > &in)
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< out_eT > &in)
template<typename in_eT>
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< in_eT > &in)
template<typename in_T>
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< std::complex< in_T > > &in)
template<typename in_eT, typename T1>
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const arma_base< in_eT, T1 > &in)
template<typename in_eT>
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const itpp::Vec< in_eT > &in)
template<typename in_T>
static basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const itpp::Vec< std::complex< in_T > > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< out_eT > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< out_eT > &in)
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< out_eT > &in)
template<typename in_eT>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< in_eT > &in)
template<typename in_eT>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< in_eT > &in)
template<typename in_eT>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< in_eT > &in)
template<typename in_T>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< std::complex< in_T > > &in)
template<typename in_T>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< std::complex< in_T > > &in)
template<typename in_T>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< std::complex< in_T > > &in)
template<typename in_eT, typename T1>
static itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const arma_base< in_eT, T1 > &in)
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< out_eT > &in)
template<typename in_eT>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< in_eT > &in)
template<typename in_T>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< std::complex< in_T > > &in)
template<typename in_eT>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_colvec< in_eT > &in)
template<typename in_T>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_colvec< std::complex< in_T > > &in)
template<typename in_eT>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_rowvec< in_eT > &in)
template<typename in_T>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_rowvec< std::complex< in_T > > &in)
template<typename in_eT, typename T1>
static itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const arma_base< in_eT, T1 > &in)
Function Documentation
template<typename out_eT, typename in_eT> void copy_complex_elem (out_eT & out, const in_eT & in) [inline]
Definition at line 27 of file fn_conv_to.hpp.
Referenced by conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< basic_colvec< out_eT > >::from(), conv_to< basic_rowvec< out_eT > >::from(), conv_to< basic_mat< out_eT > >::from(), and conv_to< out_eT >::from().
  {
  //arma_extra_debug_sigprint();
  out = out_eT(in);
  }
template<typename out_eT, typename in_T> void copy_complex_elem (out_eT & out, const std::complex< in_T > & in) [inline]
Definition at line 39 of file fn_conv_to.hpp.
  {
  //arma_extra_debug_sigprint();
  out = out_eT( in.real() );
  }
template<typename out_T, typename in_T> void copy_complex_elem (std::complex< out_T > & out, const std::complex< in_T > & in) [inline]
Definition at line 51 of file fn_conv_to.hpp.
  {
  //arma_extra_debug_sigprint();
  typedef std::complex<out_T> out_eT;
  out = out_eT(in);
  }
template<typename out_eT> out_eT conv_to< out_eT >::from (const basic_mat< out_eT > & in) [inline, static, inherited]
Definition at line 84 of file fn_conv_to.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
Referenced by conv_to< itpp::Vec< out_eT > >::from(), conv_to< itpp::Mat< out_eT > >::from(), conv_to< basic_colvec< out_eT > >::from(), conv_to< basic_rowvec< out_eT > >::from(), conv_to< basic_mat< out_eT > >::from(), conv_to< out_eT >::from(), and diskio::save_pgm_binary().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: matrix doesn't have exactly one element" );
  return in.mem[0];
  }
template<typename out_eT> template<typename in_eT> out_eT conv_to< out_eT >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 99 of file fn_conv_to.hpp.
References copy_complex_elem(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  arma_debug_check( (in.n_elem != 1), "conv_to<>: matrix doesn't have exactly one element" );
  out_eT out;
  copy_complex_elem(out, in.mem[0]);
  return out;
  }
template<typename out_eT> template<typename in_eT, typename T1> out_eT conv_to< out_eT >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 119 of file fn_conv_to.hpp.
References conv_to< out_eT >::from(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  arma_type_check< is_supported_elem_type<out_eT>::value == false >::apply();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to<out_eT>::from( tmp.M );
  }
template<typename out_eT> template<typename in_eT> basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 172 of file fn_conv_to.hpp.
References basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  basic_mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const basic_mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 195 of file fn_conv_to.hpp.
References copy_complex_elem(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  basic_mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT, typename T1> basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 220 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< basic_mat<out_eT> >::from( tmp.M );
  }
template<typename out_eT> template<typename in_eT> basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const itpp::Mat< in_eT > & in) [inline, static, inherited]
Definition at line 235 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  basic_mat<out_eT> out(in.rows(), in.cols());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_mat< out_eT > conv_to< basic_mat< out_eT > >::from (const itpp::Mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 258 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  basic_mat<out_eT> out(in.rows(), in.cols());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< out_eT > & in) [inline, static, inherited]
Definition at line 318 of file fn_conv_to.hpp.
References syslib::copy_elem(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  basic_rowvec<out_eT> out(in.n_cols);
  syslib::copy_elem(out.memptr(), in.mem, out.n_elem);
  return out;
  }
template<typename out_eT> template<typename in_eT> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 337 of file fn_conv_to.hpp.
References basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  basic_rowvec<out_eT> out(in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const basic_mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 361 of file fn_conv_to.hpp.
References copy_complex_elem(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( (in.n_rows > 1), "conv_to<>: given matrix has more than one row");
  basic_rowvec<out_eT> out(in.n_cols);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT, typename T1> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 387 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< basic_rowvec<out_eT> >::from( tmp.M );
  }
template<typename out_eT> template<typename in_eT> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const itpp::Vec< in_eT > & in) [inline, static, inherited]
Definition at line 402 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  basic_rowvec<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_rowvec< out_eT > conv_to< basic_rowvec< out_eT > >::from (const itpp::Vec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 425 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  basic_rowvec<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< out_eT > & in) [inline, static, inherited]
Definition at line 545 of file fn_conv_to.hpp.
References syslib::copy_elem(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  basic_colvec<out_eT> out(in.n_rows);
  syslib::copy_elem(out.memptr(), in.mem, out.n_elem);
  return out;
  }
template<typename out_eT> template<typename in_eT> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 563 of file fn_conv_to.hpp.
References basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  basic_colvec<out_eT> out(in.n_rows);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const basic_mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 587 of file fn_conv_to.hpp.
References copy_complex_elem(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( (in.n_cols > 1), "conv_to<>: given matrix has more than one column");
  basic_colvec<out_eT> out(in.n_rows);
  const in_eT*  in_mem = in.mem;
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT, typename T1> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 613 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< basic_colvec<out_eT> >::from( tmp.M );
  }
template<typename out_eT> template<typename in_eT> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const itpp::Vec< in_eT > & in) [inline, static, inherited]
Definition at line 628 of file fn_conv_to.hpp.
  {
  arma_extra_debug_sigprint();
  basic_colvec<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> basic_colvec< out_eT > conv_to< basic_colvec< out_eT > >::from (const itpp::Vec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 651 of file fn_conv_to.hpp.
References copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  basic_colvec<out_eT> out(in.length());
  const in_eT*  in_mem = in._data();
  out_eT*      out_mem = out.memptr();
  for(u32 i=0; i<out.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< out_eT > & in) [inline, static, inherited]
Definition at line 779 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and syslib::copy_elem().
  {
  arma_extra_debug_sigprint();
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  syslib::copy_elem(out._data(), in.mem, in.n_elem);
  return out;
  }
template<typename out_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< out_eT > & in) [inline, static, inherited]
Definition at line 795 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat<out_eT>& >(in) );
  }
template<typename out_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< out_eT > & in) [inline, static, inherited]
Definition at line 807 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat<out_eT>& >(in) );
  }
template<typename out_eT> template<typename in_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 820 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT* in_mem = in.memptr();
  out_eT*     out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< in_eT > & in) [inline, static, inherited]
Definition at line 843 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat<in_eT>& >(in) );
  }
template<typename out_eT> template<typename in_eT> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< in_eT > & in) [inline, static, inherited]
Definition at line 856 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat<in_eT>& >(in) );
  }
template<typename out_eT> template<typename in_T> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 869 of file fn_conv_to.hpp.
References itpp::Mat< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Mat<out_eT> out(in.n_rows, in.n_cols);
  const in_eT* in_mem = in.memptr();
  out_eT*     out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_T> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_colvec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 894 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat< std::complex<in_T> >& >(in) );
  }
template<typename out_eT> template<typename in_T> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const basic_rowvec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 907 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  return conv_to< itpp::Mat<out_eT> >::from( reinterpret_cast<const basic_mat< std::complex<in_T> >& >(in) );
  }
template<typename out_eT> template<typename in_eT, typename T1> itpp::Mat< out_eT > conv_to< itpp::Mat< out_eT > >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 920 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< itpp::Mat<out_eT> >::from( tmp.M );
  }
template<typename out_eT> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< out_eT > & in) [inline, static, inherited]
Definition at line 975 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and syslib::copy_elem().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  syslib::copy_elem(out._data(), in.mem, in.n_elem);
  return out;
  }
template<typename out_eT> template<typename in_eT> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< in_eT > & in) [inline, static, inherited]
Definition at line 994 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_mat< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1018 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  arma_debug_check( ( (in.n_cols != 1) && (in.n_rows != 1) ), "conv_to<>: given matrix can't be interpreted as a vector");
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_colvec< in_eT > & in) [inline, static, inherited]
Definition at line 1045 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_colvec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1068 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_rowvec< in_eT > & in) [inline, static, inherited]
Definition at line 1093 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data().
  {
  arma_extra_debug_sigprint();
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    out_mem[i] = out_eT( in_mem[i] );
    }
  return out;
  }
template<typename out_eT> template<typename in_T> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const basic_rowvec< std::complex< in_T > > & in) [inline, static, inherited]
Definition at line 1116 of file fn_conv_to.hpp.
References itpp::Vec< eT >::_data(), and copy_complex_elem().
  {
  arma_extra_debug_sigprint();
  typedef std::complex<in_T> in_eT;
  itpp::Vec<out_eT> out(in.n_elem);
  const in_eT*  in_mem = in.memptr();
  out_eT*      out_mem = out._data();
  for(u32 i=0; i<in.n_elem; ++i)
    {
    copy_complex_elem(out_mem[i], in_mem[i]);
    }
  return out;
  }
template<typename out_eT> template<typename in_eT, typename T1> itpp::Vec< out_eT > conv_to< itpp::Vec< out_eT > >::from (const arma_base< in_eT, T1 > & in) [inline, static, inherited]
Definition at line 1141 of file fn_conv_to.hpp.
References conv_to< out_eT >::from().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(in.get_ref());
  return conv_to< itpp::Vec<out_eT> >::from( tmp.M );
  }