Armadillo Technical: Operator_times
Operator_times
Functions
template<typename T1>
const op_data< T1,
op_scalar_times > operator* (const arma_base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
arma_base * scalar
template<typename T1>
const op_data< T1,
op_scalar_times > operator* (const op_data< T1, op_scalar_times > &X, const typename T1::elem_type k)
op * scalar, level 2
template<typename eT>
basic_mat< eT > operator* (const op_data< basic_mat< eT >, op_ones_full > &X, const eT k)
op_data<mat,op_ones_full> * scalar
template<typename eT>
basic_mat< eT > operator* (const op_data< basic_mat< eT >, op_ones_diag > &X, const eT k)
op_data<mat,op_ones_diag> * scalar
template<typename T1>
const op_data< T1,
op_scalar_times > operator* (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > &X)
scalar * arma_base
template<typename eT>
basic_mat< eT > operator* (const eT k, const op_data< basic_mat< eT >, op_ones_full > &X)
scalar * op_data<mat,op_ones_full>
template<typename eT>
basic_mat< eT > operator* (const eT k, const op_data< basic_mat< eT >, op_ones_diag > &X)
scalar * op_data<mat,op_ones_diag>
template<typename T1, typename T2>
const glue_data< T1, op_data
< T2, op_diagmat >
, glue_times_diag > operator* (const arma_base< typename T2::elem_type, T1 > &X, const op_data< T2, op_diagmat > &Y)
arma_base * diagmat
template<typename T1, typename T2>
const glue_data< op_data< T1,
op_diagmat >, T2,
glue_times_diag > operator* (const op_data< T1, op_diagmat > &X, const arma_base< typename T1::elem_type, T2 > &Y)
diagmat * arma_base
template<typename eT>
const glue_data< basic_colvec
< eT >, basic_rowvec< eT >
, glue_times_vec > operator* (const basic_colvec< eT > &X, const basic_rowvec< eT > &Y)
colvec * rowvec
template<typename T1>
const glue_data< T1,
basic_colvec< typename
T1::elem_type >
, glue_times_vec > operator* (const arma_base< typename T1::elem_type, T1 > &X, const basic_colvec< typename T1::elem_type > &Y)
arma_base * colvec
template<typename T1>
const glue_data< T1,
basic_rowvec< typename
T1::elem_type >
, glue_times_vec > operator* (const arma_base< typename T1::elem_type, T1 > &X, const basic_rowvec< typename T1::elem_type > &Y)
arma_base * rowvec
template<typename T1>
const glue_data< basic_colvec
< typename T1::elem_type >, T1,
glue_times_vec > operator* (const basic_colvec< typename T1::elem_type > &X, const arma_base< typename T1::elem_type, T1 > &Y)
colvec * arma_base
template<typename T1>
const glue_data< basic_rowvec
< typename T1::elem_type >, T1,
glue_times_vec > operator* (const basic_rowvec< typename T1::elem_type > &X, const arma_base< typename T1::elem_type, T1 > &Y)
rowvec * arma_base
template<typename T1>
const glue_data< op_data< T1,
op_diagmat >, basic_colvec
< typename T1::elem_type >
, glue_times_diag > operator* (const op_data< T1, op_diagmat > &X, const basic_colvec< typename T1::elem_type > &Y)
diagmat * colvec
template<typename T1>
const glue_data< op_data< T1,
op_diagmat >, basic_rowvec
< typename T1::elem_type >
, glue_times_diag > operator* (const op_data< T1, op_diagmat > &X, const basic_rowvec< typename T1::elem_type > &Y)
diagmat * rowvec
template<typename T1>
const glue_data< basic_colvec
< typename T1::elem_type >
, op_data< T1, op_diagmat >
, glue_times_diag > operator* (const basic_colvec< typename T1::elem_type > &X, const op_data< T1, op_diagmat > &Y)
colvec * diagmat
template<typename T1>
const glue_data< basic_rowvec
< typename T1::elem_type >
, op_data< T1, op_diagmat >
, glue_times_diag > operator* (const basic_rowvec< typename T1::elem_type > &X, const op_data< T1, op_diagmat > &Y)
rowvec * diagmat
template<typename eT1, typename T1, typename eT2, typename T2>
basic_mat< typename
promote_type< eT1, eT2 >
::result > operator* (const arma_base< eT1, T1 > &X, const arma_base< eT2, T2 > &Y)
arma_base * arma_base
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< std::complex< double >, T1 > &X, const arma_base< std::complex< double >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< std::complex< float >, T1 > &X, const arma_base< std::complex< float >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< double, T1 > &X, const arma_base< double, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< float, T1 > &X, const arma_base< float, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< s32, T1 > &X, const arma_base< s32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< u32, T1 > &X, const arma_base< u32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< s16, T1 > &X, const arma_base< s16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< u16, T1 > &X, const arma_base< u16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< s8, T1 > &X, const arma_base< s8, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2,
glue_times > operator* (const arma_base< u8, T1 > &X, const arma_base< u8, T2 > &Y)
Function Documentation
template<typename T1> const op_data<T1, op_scalar_times> operator* (const arma_base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
arma_base * scalar
Definition at line 32 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_times>(X.get_ref(),k);
  }
template<typename T1> const op_data<T1,op_scalar_times> operator* (const op_data< T1, op_scalar_times > & X, const typename T1::elem_type k) [inline]
op * scalar, level 2
Definition at line 46 of file operator_times.hpp.
References op_data< T1, op_type >::aux, and op_data< T1, op_type >::m.
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_times>(X.m, X.aux * k);
  }
template<typename eT> basic_mat<eT> operator* (const op_data< basic_mat< eT >, op_ones_full > & X, const eT k) [inline]
op_data<mat,op_ones_full> * scalar
Definition at line 60 of file operator_times.hpp.
References op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, and basic_mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill(k);
  return tmp;
  }
template<typename eT> basic_mat<eT> operator* (const op_data< basic_mat< eT >, op_ones_diag > & X, const eT k) [inline]
op_data<mat,op_ones_diag> * scalar
Definition at line 77 of file operator_times.hpp.
References basic_mat< eT >::at(), op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  for(u32 i=0; i<out.n_rows; ++i)
    {
    out.at(i,i) = k;
    }
  return out;
  }
template<typename T1> const op_data<T1, op_scalar_times> operator* (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > & X) [inline]
scalar * arma_base
Definition at line 99 of file operator_times.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_times>(X.get_ref(),k);  // NOTE: order is swapped
  }
template<typename eT> basic_mat<eT> operator* (const eT k, const op_data< basic_mat< eT >, op_ones_full > & X) [inline]
scalar * op_data<mat,op_ones_full>
Definition at line 113 of file operator_times.hpp.
References op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, and basic_mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill(k);
  return tmp;
  }
template<typename eT> basic_mat<eT> operator* (const eT k, const op_data< basic_mat< eT >, op_ones_diag > & X) [inline]
scalar * op_data<mat,op_ones_diag>
Definition at line 130 of file operator_times.hpp.
References basic_mat< eT >::at(), op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  for(u32 i=0; i<out.n_rows; ++i)
    out.at(i,i) = k;
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, op_data<T2,op_diagmat>, glue_times_diag> operator* (const arma_base< typename T2::elem_type, T1 > & X, const op_data< T2, op_diagmat > & Y) [inline]
arma_base * diagmat
Definition at line 150 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, op_data<T2,op_diagmat>, glue_times_diag>(X.get_ref(), Y);
  }
template<typename T1, typename T2> const glue_data<op_data<T1,op_diagmat>, T2, glue_times_diag> operator* (const op_data< T1, op_diagmat > & X, const arma_base< typename T1::elem_type, T2 > & Y) [inline]
diagmat * arma_base
Definition at line 164 of file operator_times.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<op_data<T1,op_diagmat>, T2, glue_times_diag>(X, Y.get_ref());
  }
template<typename eT> const glue_data<basic_colvec<eT>, basic_rowvec<eT>, glue_times_vec> operator* (const basic_colvec< eT > & X, const basic_rowvec< eT > & Y) [inline]
colvec * rowvec
Definition at line 178 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return glue_data<basic_colvec<eT>, basic_rowvec<eT>, glue_times_vec>(X, Y);
  }
template<typename T1> const glue_data<T1, basic_colvec<typename T1::elem_type>, glue_times_vec> operator* (const arma_base< typename T1::elem_type, T1 > & X, const basic_colvec< typename T1::elem_type > & Y) [inline]
arma_base * colvec
Definition at line 192 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, basic_colvec<typename T1::elem_type>, glue_times_vec>(X.get_ref(), Y);
  }
template<typename T1> const glue_data<T1, basic_rowvec<typename T1::elem_type>, glue_times_vec> operator* (const arma_base< typename T1::elem_type, T1 > & X, const basic_rowvec< typename T1::elem_type > & Y) [inline]
arma_base * rowvec
Definition at line 206 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, basic_rowvec<typename T1::elem_type>, glue_times_vec>(X.get_ref(), Y);
  }
template<typename T1> const glue_data<basic_colvec<typename T1::elem_type>, T1, glue_times_vec> operator* (const basic_colvec< typename T1::elem_type > & X, const arma_base< typename T1::elem_type, T1 > & Y) [inline]
colvec * arma_base
Definition at line 220 of file operator_times.hpp.
References arma_base< eT, basic_mat< eT > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<basic_colvec<typename T1::elem_type>, T1, glue_times_vec>(X, Y.get_ref());
  }
template<typename T1> const glue_data<basic_rowvec<typename T1::elem_type>, T1, glue_times_vec> operator* (const basic_rowvec< typename T1::elem_type > & X, const arma_base< typename T1::elem_type, T1 > & Y) [inline]
rowvec * arma_base
Definition at line 234 of file operator_times.hpp.
References arma_base< eT, basic_mat< eT > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<basic_rowvec<typename T1::elem_type>, T1, glue_times_vec>(X, Y.get_ref());
  }
template<typename T1> const glue_data<op_data<T1, op_diagmat>, basic_colvec<typename T1::elem_type>, glue_times_diag> operator* (const op_data< T1, op_diagmat > & X, const basic_colvec< typename T1::elem_type > & Y) [inline]
diagmat * colvec
Definition at line 248 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return glue_data<op_data<T1, op_diagmat>, basic_colvec<typename T1::elem_type>, glue_times_diag>(X, Y);
  }
template<typename T1> const glue_data<op_data<T1, op_diagmat>, basic_rowvec<typename T1::elem_type>, glue_times_diag> operator* (const op_data< T1, op_diagmat > & X, const basic_rowvec< typename T1::elem_type > & Y) [inline]
diagmat * rowvec
Definition at line 262 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return glue_data<op_data<T1, op_diagmat>, basic_rowvec<typename T1::elem_type>, glue_times_diag>(X, Y);
  }
template<typename T1> const glue_data<basic_colvec<typename T1::elem_type>, op_data<T1, op_diagmat>, glue_times_diag> operator* (const basic_colvec< typename T1::elem_type > & X, const op_data< T1, op_diagmat > & Y) [inline]
colvec * diagmat
Definition at line 276 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return glue_data<basic_colvec<typename T1::elem_type>, op_data<T1, op_diagmat>, glue_times_diag>(X, Y);
  }
template<typename T1> const glue_data<basic_rowvec<typename T1::elem_type>, op_data<T1, op_diagmat>, glue_times_diag> operator* (const basic_rowvec< typename T1::elem_type > & X, const op_data< T1, op_diagmat > & Y) [inline]
rowvec * diagmat
Definition at line 290 of file operator_times.hpp.
  {
  arma_extra_debug_sigprint();
  return glue_data<basic_rowvec<typename T1::elem_type>, op_data<T1, op_diagmat>, glue_times_diag>(X, Y);
  }
template<typename eT1, typename T1, typename eT2, typename T2> basic_mat<typename promote_type<eT1,eT2>::result> operator* (const arma_base< eT1, T1 > & X, const arma_base< eT2, T2 > & Y) [inline]
arma_base * arma_base
Definition at line 310 of file operator_times.hpp.
References glue_times::apply_mixed(), promote_type< T1, T2 >::check(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const basic_mat< eT1 >& A = tmp1.M;
  const basic_mat< eT2 >& B = tmp2.M;
  basic_mat< typename promote_type<eT1,eT2>::result > out;
  glue_times::apply_mixed(out, A, B);
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< std::complex< double >, T1 > & X, const arma_base< std::complex< double >, T2 > & Y) [inline]
Definition at line 341 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< std::complex< float >, T1 > & X, const arma_base< std::complex< float >, T2 > & Y) [inline]
Definition at line 354 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< double, T1 > & X, const arma_base< double, T2 > & Y) [inline]
Definition at line 367 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< float, T1 > & X, const arma_base< float, T2 > & Y) [inline]
Definition at line 380 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< s32, T1 > & X, const arma_base< s32, T2 > & Y) [inline]
Definition at line 393 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< u32, T1 > & X, const arma_base< u32, T2 > & Y) [inline]
Definition at line 406 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< s16, T1 > & X, const arma_base< s16, T2 > & Y) [inline]
Definition at line 419 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< u16, T1 > & X, const arma_base< u16, T2 > & Y) [inline]
Definition at line 432 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< s8, T1 > & X, const arma_base< s8, T2 > & Y) [inline]
Definition at line 445 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_times> operator* (const arma_base< u8, T1 > & X, const arma_base< u8, T2 > & Y) [inline]
Definition at line 458 of file operator_times.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_times>(X.get_ref(), Y.get_ref());
  }