Armadillo Technical: Op_ones
Op_ones
Classes
class op_ones_full
Class for creation of a dense matrix/vector with all elements set to one.
class op_ones_diag
Functions
template<typename eT>
static void op_ones_full::apply (basic_mat< eT > &out, const op_data< basic_mat< eT >, op_ones_full > &in)
template<typename eT>
static void op_ones_full::apply (basic_mat< eT > &out, const op_data< basic_colvec< eT >, op_ones_full > &in)
template<typename eT>
static void op_ones_full::apply (basic_mat< eT > &out, const op_data< basic_rowvec< eT >, op_ones_full > &in)
template<typename eT>
static void op_ones_full::apply (basic_colvec< eT > &out, const op_data< basic_colvec< eT >, op_ones_full > &in)
template<typename eT>
static void op_ones_full::apply (basic_rowvec< eT > &out, const op_data< basic_rowvec< eT >, op_ones_full > &in)
template<typename eT>
static void op_ones_diag::apply (basic_mat< eT > &out, const op_data< basic_mat< eT >, op_ones_diag > &in)
Function Documentation
template<typename eT> void op_ones_full::apply (basic_mat< eT > & out, const op_data< basic_mat< eT >, op_ones_full > & in) [inline, static, inherited]
Definition at line 22 of file op_ones_meat.hpp.
References basic_mat< eT >::fill(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a, in.aux_u32_b);
  out.fill(eT(1));
  }
template<typename eT> void op_ones_full::apply (basic_mat< eT > & out, const op_data< basic_colvec< eT >, op_ones_full > & in) [inline, static, inherited]
Definition at line 35 of file op_ones_meat.hpp.
References basic_mat< eT >::fill(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a, 1);
  out.fill(eT(1));
  }
template<typename eT> void op_ones_full::apply (basic_mat< eT > & out, const op_data< basic_rowvec< eT >, op_ones_full > & in) [inline, static, inherited]
Definition at line 48 of file op_ones_meat.hpp.
References basic_mat< eT >::fill(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(1, in.aux_u32_a);
  out.fill(eT(1));
  }
template<typename eT> void op_ones_full::apply (basic_colvec< eT > & out, const op_data< basic_colvec< eT >, op_ones_full > & in) [inline, static, inherited]
Definition at line 61 of file op_ones_meat.hpp.
References basic_mat< eT >::fill(), and basic_colvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  out.fill(eT(1));
  }
template<typename eT> void op_ones_full::apply (basic_rowvec< eT > & out, const op_data< basic_rowvec< eT >, op_ones_full > & in) [inline, static, inherited]
Definition at line 74 of file op_ones_meat.hpp.
References basic_mat< eT >::fill(), and basic_rowvec< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  out.set_size(in.aux_u32_a);
  out.fill(eT(1));
  }
template<typename eT> void op_ones_diag::apply (basic_mat< eT > & out, const op_data< basic_mat< eT >, op_ones_diag > & in) [inline, static, inherited]
Definition at line 87 of file op_ones_meat.hpp.
References basic_mat< eT >::at(), basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  out.zeros(in.aux_u32_a, in.aux_u32_b);
  for(u32 i=0; i<out.n_rows; ++i)
    {
    out.at(i,i) = eT(1);
    }
  }