Armadillo Technical: Debug
Debug
Namespaces
namespace junk
Functions
void arma_print ()
template<typename T1>
void arma_print (const T1 &x)
template<typename T1, typename T2>
void arma_print (const T1 &x, const T2 &y)
template<typename T1>
void arma_print (const arma_boost::basic_format< T1 > &x)
template<typename T1, typename T2>
void arma_print (const arma_boost::basic_format< T1, T2 > &x)
void arma_sigprint (const char *x)
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
void arma_bktprint ()
template<typename T1>
void arma_bktprint (const T1 &x)
template<typename T1, typename T2>
void arma_bktprint (const T1 &x, const T2 &y)
template<typename T1>
void arma_bktprint (const arma_boost::basic_format< T1 > &x)
template<typename T1, typename T2>
void arma_bktprint (const arma_boost::basic_format< T1, T2 > &x)
void arma_thisprint (void *this_ptr)
template<typename T1>
void arma_warn (const bool state, const T1 &x)
if state is true, print a message on cout
template<typename T1, typename T2>
void arma_warn (const bool state, const T1 &x, const T2 &y)
template<typename T1>
void arma_warn (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1, typename T2>
void arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > &x)
template<typename T1>
void arma_check (const bool state, const T1 &x)
if state is true, throw a run-time error exception
template<typename T1, typename T2>
void arma_check (const bool state, const T1 &x, const T2 &y)
template<typename T1>
void arma_check (const bool state, const arma_boost::basic_format< T1 > &x)
template<typename T1, typename T2>
void arma_check (const bool state, const arma_boost::basic_format< T1, T2 > &x)
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
void arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1, typename eT2>
void arma_assert_same_size (const basic_mat< eT1 > &A, const basic_mat< eT2 > &B, const char *x)
if given matrices have different sizes, throw a run-time error exception
template<typename eT1, typename eT2>
void arma_assert_same_size (const basic_mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1, typename eT2>
void arma_assert_same_size (const subview< eT1 > &A, const basic_mat< eT2 > &B, const char *x)
template<typename eT1, typename eT2>
void arma_assert_same_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
void arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char *x)
template<typename eT1, typename eT2>
void arma_assert_mul_size (const basic_mat< eT1 > &A, const basic_mat< eT2 > &B, const char *x)
if given matrices are incompatible for multiplication, throw a run-time error exception
template<typename eT1, typename eT2>
void arma_assert_mul_size (const basic_mat< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename eT1, typename eT2>
void arma_assert_mul_size (const subview< eT1 > &A, const basic_mat< eT2 > &B, const char *x)
template<typename eT1, typename eT2>
void arma_assert_mul_size (const subview< eT1 > &A, const subview< eT2 > &B, const char *x)
template<typename T1>
void arma_stop (const T1 &x)
throw a run-time error exception
Function Documentation
void arma_print () [inline]
Definition at line 26 of file debug.hpp.
Referenced by arma_warn(), chol(), diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_field(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), qr(), diskio::save_arma_binary(), diskio::save_field(), diskio::save_pgm_binary(), diskio::save_raw_ascii(), solve(), and svd().
  {
  std::cout << std::endl;
  }
template<typename T1> void arma_print (const T1 & x) [inline]
Definition at line 35 of file debug.hpp.
  {
  std::cout << x << std::endl;
  }
template<typename T1, typename T2> void arma_print (const T1 & x, const T2 & y) [inline]
Definition at line 45 of file debug.hpp.
  {
  std::cout << x << y << std::endl;
  }
template<typename T1> void arma_print (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 56 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
template<typename T1, typename T2> void arma_print (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 64 of file debug.hpp.
    {
    std::cout << x << std::endl;
    }
void arma_sigprint (const char * x) [inline]
print a message on cout, with a preceding @ character. used for printing the signature of a function (see the arma_extra_debug_sigprint macro)
Definition at line 80 of file debug.hpp.
  {
  std::cout << "@ " << x;
  }
void arma_bktprint () [inline]
Definition at line 93 of file debug.hpp.
  {
  std::cout << std::endl;
  }
template<typename T1> void arma_bktprint (const T1 & x) [inline]
Definition at line 102 of file debug.hpp.
  {
  std::cout << " [" << x << "]" << std::endl;
  }
template<typename T1, typename T2> void arma_bktprint (const T1 & x, const T2 & y) [inline]
Definition at line 112 of file debug.hpp.
  {
  std::cout << " [" << x << y << "]" << std::endl;
  }
template<typename T1> void arma_bktprint (const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 123 of file debug.hpp.
    {
    std::cout << " [" << x << "]" << std::endl;
    }
template<typename T1, typename T2> void arma_bktprint (const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 131 of file debug.hpp.
    {
    std::cout << " [" << x << "]" << std::endl;
    }
void arma_thisprint (void * this_ptr) [inline]
Definition at line 145 of file debug.hpp.
  {
  std::cout << " [this = " << this_ptr << "]" << std::endl;
  }
template<typename T1> void arma_warn (const bool state, const T1 & x) [inline]
if state is true, print a message on cout
Definition at line 159 of file debug.hpp.
References arma_print().
Referenced by diskio::safe_rename(), diskio::save_arma_ascii(), diskio::save_arma_binary(), diskio::save_field(), diskio::save_pgm_binary(), and diskio::save_raw_ascii().
  {
  if(state==true)
    {
    arma_print(x);
    }
  }
template<typename T1, typename T2> void arma_warn (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 171 of file debug.hpp.
References arma_print().
  {
  if(state==true)
    {
    arma_print(x,y);
    }
  }
template<typename T1> void arma_warn (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 184 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1, typename T2> void arma_warn (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 193 of file debug.hpp.
References arma_print().
    {
    if(state==true)
      arma_print(x);
    }
template<typename T1> void arma_check (const bool state, const T1 & x) [inline]
if state is true, throw a run-time error exception
Definition at line 209 of file debug.hpp.
Referenced by arma_stop(), subview< eT >::at(), subview_field< oT >::at(), basic_colvec< eT >::basic_colvec(), basic_rowvec< eT >::basic_rowvec(), subview< eT >::colptr(), diagview< eT >::fill(), field< oT >::init(), basic_mat< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), subview< eT >::operator()(), subview_field< oT >::operator()(), diagview< eT >::operator()(), diagview< eT >::operator=(), subview< eT >::operator[](), subview_field< oT >::operator[](), and diagview< eT >::zeros().
  {
  if(state==true)
    {
    throw std::runtime_error(x);
    }
  }
template<typename T1, typename T2> void arma_check (const bool state, const T1 & x, const T2 & y) [inline]
Definition at line 221 of file debug.hpp.
  {
  if(state==true)
    {
    throw std::runtime_error( std::string(x) + std::string(y) );
    }
  }
template<typename T1> void arma_check (const bool state, const arma_boost::basic_format< T1 > & x) [inline]
Definition at line 234 of file debug.hpp.
References arma_boost::str().
    {
    if(state==true)
      {
      throw std::runtime_error(str(x));
      }
    }
template<typename T1, typename T2> void arma_check (const bool state, const arma_boost::basic_format< T1, T2 > & x) [inline]
Definition at line 245 of file debug.hpp.
References arma_boost::str().
    {
    if(state==true)
      {
      throw std::runtime_error(str(x));
      }
    }
std::string arma_incompat_size_string (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 258 of file debug.hpp.
Referenced by arma_assert_mul_size(), and arma_assert_same_size().
  {
  std::stringstream tmp;
  tmp << x << ": incompatible matrix dimensions: (" << A_n_rows << "," << A_n_cols << ") and (" << B_n_rows << "," << B_n_cols << ")";
  return tmp.str();
  }
void arma_assert_same_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 271 of file debug.hpp.
References arma_incompat_size_string().
Referenced by basic_mat< eT >::basic_mat().
  {
  if( (A_n_rows != B_n_rows) || (A_n_cols != B_n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_same_size (const basic_mat< eT1 > & A, const basic_mat< eT2 > & B, const char * x) [inline]
if given matrices have different sizes, throw a run-time error exception
Definition at line 288 of file debug.hpp.
References arma_incompat_size_string(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_same_size (const basic_mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 304 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, basic_mat< eT >::n_cols, subview< eT >::n_rows, and basic_mat< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_same_size (const subview< eT1 > & A, const basic_mat< eT2 > & B, const char * x) [inline]
Definition at line 320 of file debug.hpp.
References arma_incompat_size_string(), basic_mat< eT >::n_cols, subview< eT >::n_cols, basic_mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_same_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 336 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols) )
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
void arma_assert_mul_size (const u32 A_n_rows, const u32 A_n_cols, const u32 B_n_rows, const u32 B_n_cols, const char * x) [inline]
Definition at line 351 of file debug.hpp.
References arma_incompat_size_string().
  {
  if(A_n_cols != B_n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A_n_rows, A_n_cols, B_n_rows, B_n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_mul_size (const basic_mat< eT1 > & A, const basic_mat< eT2 > & B, const char * x) [inline]
if given matrices are incompatible for multiplication, throw a run-time error exception
Definition at line 368 of file debug.hpp.
References arma_incompat_size_string(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_mul_size (const basic_mat< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 384 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_mul_size (const subview< eT1 > & A, const basic_mat< eT2 > & B, const char * x) [inline]
Definition at line 400 of file debug.hpp.
References arma_incompat_size_string(), basic_mat< eT >::n_cols, subview< eT >::n_cols, subview< eT >::n_rows, and basic_mat< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename eT1, typename eT2> void arma_assert_mul_size (const subview< eT1 > & A, const subview< eT2 > & B, const char * x) [inline]
Definition at line 416 of file debug.hpp.
References arma_incompat_size_string(), subview< eT >::n_cols, and subview< eT >::n_rows.
  {
  if(A.n_cols != B.n_rows)
    {
    throw std::runtime_error
      (
      arma_incompat_size_string(A.n_rows, A.n_cols, B.n_rows, B.n_cols, x)
      );
    }
  }
template<typename T1> void arma_stop (const T1 & x) [inline]
throw a run-time error exception
Definition at line 436 of file debug.hpp.
References arma_check().
Referenced by op_atanh::apply(), op_atan::apply(), op_asinh::apply(), op_asin::apply(), op_acosh::apply(), op_acos::apply(), auxlib::chol(), auxlib::det(), auxlib::eig(), auxlib::inv_inplace(), auxlib::inv_noalias(), basic_mat< eT >::load(), auxlib::lu(), auxlib::qr(), basic_mat< eT >::save(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), and auxlib::svd().
  {
  arma_check(true, x);
  }