Armadillo Technical: Operator_div
Operator_div
Functions
template<typename T1>
const op_data< T1,
op_scalar_div_post > operator/ (const arma_base< typename T1::elem_type, T1 > &X, const typename T1::elem_type k)
arma_base / scalar
template<typename eT>
basic_mat< eT > operator/ (const op_data< basic_mat< eT >, op_ones_full > &X, const eT k)
op_data<mat,op_ones_full> / scalar
template<typename eT>
basic_mat< eT > operator/ (const op_data< basic_mat< eT >, op_ones_diag > &X, const eT k)
op_data<mat,op_ones_diag> / scalar
template<typename T1>
const op_data< T1,
op_scalar_div_pre > operator/ (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > &X)
scalar / arma_base
template<typename eT1, typename T1, typename eT2, typename T2>
basic_mat< typename
promote_type< eT1, eT2 >
::result > operator/ (const arma_base< eT1, T1 > &X, const arma_base< eT2, T2 > &Y)
arma_base / arma_base
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< std::complex< double >, T1 > &X, const arma_base< std::complex< double >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< std::complex< float >, T1 > &X, const arma_base< std::complex< float >, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< double, T1 > &X, const arma_base< double, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< float, T1 > &X, const arma_base< float, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< s32, T1 > &X, const arma_base< s32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< u32, T1 > &X, const arma_base< u32, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< s16, T1 > &X, const arma_base< s16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< u16, T1 > &X, const arma_base< u16, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< s8, T1 > &X, const arma_base< s8, T2 > &Y)
template<typename T1, typename T2>
const glue_data< T1, T2, glue_div > operator/ (const arma_base< u8, T1 > &X, const arma_base< u8, T2 > &Y)
Function Documentation
template<typename T1> const op_data<T1, op_scalar_div_post> operator/ (const arma_base< typename T1::elem_type, T1 > & X, const typename T1::elem_type k) [inline]
arma_base / scalar
Definition at line 26 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_div_post>(X.get_ref(), k);
  }
template<typename eT> basic_mat<eT> operator/ (const op_data< basic_mat< eT >, op_ones_full > & X, const eT k) [inline]
op_data<mat,op_ones_full> / scalar
Definition at line 40 of file operator_div.hpp.
References op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, and basic_mat< eT >::fill().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> tmp(X.aux_u32_a, X.aux_u32_b);
  tmp.fill( eT(1)/k );
  return tmp;
  }
template<typename eT> basic_mat<eT> operator/ (const op_data< basic_mat< eT >, op_ones_diag > & X, const eT k) [inline]
op_data<mat,op_ones_diag> / scalar
Definition at line 57 of file operator_div.hpp.
References basic_mat< eT >::at(), op_data< T1, op_type >::aux_u32_a, op_data< T1, op_type >::aux_u32_b, basic_mat< eT >::n_rows, and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT> out;
  out.zeros(X.aux_u32_a, X.aux_u32_b);
  const eT inv_k = eT(1)/k;
  for(u32 i=0; i<out.n_rows; ++i)
    {
    out.at(i,i) = inv_k;
    }
  return out;
  }
template<typename T1> const op_data<T1, op_scalar_div_pre> operator/ (const typename T1::elem_type k, const arma_base< typename T1::elem_type, T1 > & X) [inline]
scalar / arma_base
Definition at line 81 of file operator_div.hpp.
References arma_base< T1::elem_type, op_data< T1, op_type > >::get_ref().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_scalar_div_pre>(X.get_ref(), k);
  }
template<typename eT1, typename T1, typename eT2, typename T2> basic_mat<typename promote_type<eT1,eT2>::result> operator/ (const arma_base< eT1, T1 > & X, const arma_base< eT2, T2 > & Y) [inline]
arma_base / arma_base
Definition at line 101 of file operator_div.hpp.
References glue_div::apply_mixed(), promote_type< T1, T2 >::check(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  promote_type<eT1,eT2>::check();
  const unwrap<T1> tmp1(X.get_ref());
  const unwrap<T2> tmp2(Y.get_ref());
  const basic_mat<eT1>& A = tmp1.M;
  const basic_mat<eT2>& B = tmp2.M;
  basic_mat< typename promote_type<eT1,eT2>::result > out;
  glue_div::apply_mixed(out, A, B);
  return out;
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< std::complex< double >, T1 > & X, const arma_base< std::complex< double >, T2 > & Y) [inline]
Definition at line 131 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< std::complex< float >, T1 > & X, const arma_base< std::complex< float >, T2 > & Y) [inline]
Definition at line 144 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< double, T1 > & X, const arma_base< double, T2 > & Y) [inline]
Definition at line 157 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< float, T1 > & X, const arma_base< float, T2 > & Y) [inline]
Definition at line 170 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< s32, T1 > & X, const arma_base< s32, T2 > & Y) [inline]
Definition at line 183 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< u32, T1 > & X, const arma_base< u32, T2 > & Y) [inline]
Definition at line 196 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< s16, T1 > & X, const arma_base< s16, T2 > & Y) [inline]
Definition at line 209 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< u16, T1 > & X, const arma_base< u16, T2 > & Y) [inline]
Definition at line 222 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< s8, T1 > & X, const arma_base< s8, T2 > & Y) [inline]
Definition at line 235 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }
template<typename T1, typename T2> const glue_data<T1, T2, glue_div> operator/ (const arma_base< u8, T1 > & X, const arma_base< u8, T2 > & Y) [inline]
Definition at line 248 of file operator_div.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  return glue_data<T1, T2, glue_div>(X.get_ref(), Y.get_ref());
  }