Armadillo Technical: Glue_div
Glue_div
Classes
class glue_div
Class which implements the immediate element-wise division of two or more matrices.
Functions
template<typename eT>
static void glue_div::apply (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B)
template<typename eT>
static void glue_div::apply (basic_mat< eT > &out, const basic_mat< eT > &A, const basic_mat< eT > &B, const basic_mat< eT > &C)
template<typename eT>
static void glue_div::apply (basic_mat< eT > &out, const glue_data< basic_mat< eT >, basic_mat< eT >, glue_div > &X)
template<typename eT>
static void glue_div::apply (basic_mat< eT > &out, const glue_data< glue_data< basic_mat< eT >, basic_mat< eT >, glue_div >, basic_mat< eT >, glue_div > &X)
template<typename T1, typename T2>
static void glue_div::apply (basic_mat< typename T1::elem_type > &out, const glue_data< T1, T2, glue_div > &X)
template<typename eT>
static void glue_div::apply_inplace (basic_mat< eT > &out, const basic_mat< eT > &B)
template<typename T1, typename op_type>
static void glue_div::apply_inplace (basic_mat< typename T1::elem_type > &out, const op_data< T1, op_type > &X)
template<typename T1, typename T2, typename glue_type>
static void glue_div::apply_inplace (basic_mat< typename T1::elem_type > &out, const glue_data< T1, T2, glue_type > &X)
template<typename eT1, typename eT2>
static void glue_div::apply_mixed (basic_mat< typename promote_type< eT1, eT2 >::result > &out, const basic_mat< eT1 > &X, const basic_mat< eT2 > &Y)
Function Documentation
template<typename eT> void glue_div::apply (basic_mat< eT > & out, const basic_mat< eT > & A, const basic_mat< eT > & B) [inline, static, inherited]
Definition at line 23 of file glue_div_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
Referenced by apply(), and apply_inplace().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "element-wise matrix division");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
  const u32 n_elem = A.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out[i] = A.mem[i] / B.mem[i];
    }
  }
template<typename eT> void glue_div::apply (basic_mat< eT > & out, const basic_mat< eT > & A, const basic_mat< eT > & B, const basic_mat< eT > & C) [inline, static, inherited]
Definition at line 46 of file glue_div_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(A, B, "element-wise matrix division");
  arma_debug_assert_same_size(A, C, "element-wise matrix division");
  // no aliasing problem
  out.set_size(A.n_rows, A.n_cols);
  const u32 n_elem = A.n_elem;
  for(u32 i=0; i != n_elem; ++i)
    {
    out[i] = A.mem[i] / B.mem[i] / C.mem[i];
    }
  }
template<typename eT> void glue_div::apply (basic_mat< eT > & out, const glue_data< basic_mat< eT >, basic_mat< eT >, glue_div > & X) [inline, static, inherited]
Definition at line 69 of file glue_div_meat.hpp.
References apply().
  {
  glue_div::apply(out, X.A, X.B);
  }
template<typename eT> void glue_div::apply (basic_mat< eT > & out, const glue_data< glue_data< basic_mat< eT >, basic_mat< eT >, glue_div >, basic_mat< eT >, glue_div > & X) [inline, static, inherited]
Definition at line 79 of file glue_div_meat.hpp.
References apply().
  {
  glue_div::apply(out, X.A.A, X.A.B, X.B);
  }
template<typename T1, typename T2> void glue_div::apply (basic_mat< typename T1::elem_type > & out, const glue_data< T1, T2, glue_div > & X) [inline, static, inherited]
Definition at line 88 of file glue_div_meat.hpp.
References glue_data< T1, T2, glue_type >::A, apply(), glue_data< T1, T2, glue_type >::B, and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const u32 N_mat = 1 + depth_lhs< glue_div, glue_data<T1,T2,glue_div> >::num;
  arma_extra_debug_print( arma_boost::format("N_mat = %d") % N_mat );
  if(N_mat == 2)
    {
    unwrap<T1> tmp1(X.A);
    unwrap<T2> tmp2(X.B);
    glue_div::apply(out, tmp1.M, tmp2.M);
    }
  else
    {
    const basic_mat<eT>* ptrs[N_mat];
    bool                  del[N_mat];
    mat_ptrs<glue_div, glue_data<T1,T2,glue_div> >::get_ptrs(ptrs, del, X);
    //mat_ptrs_outcheck<glue_div, glue_data<T1,T2,glue_div> >::get_ptrs(ptrs, del, X, &out);
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format("ptrs[%d] = %x") % i % ptrs[i] );
    for(u32 i=0; i<N_mat; ++i)  arma_extra_debug_print( arma_boost::format(" del[%d] = %d") % i %  del[i] );
    const basic_mat<eT>& tmp_mat = *(ptrs[0]);
    for(u32 i=1; i<N_mat; ++i)
      {
      arma_debug_assert_same_size(tmp_mat, *(ptrs[i]), "element-wise matrix division");
      }
    const u32 n_rows = ptrs[0]->n_rows;
    const u32 n_cols = ptrs[0]->n_cols;
    // no aliasing problem
    out.set_size(n_rows,n_cols);
    const u32 n_elem = ptrs[0]->n_elem;
    for(u32 j=0; j<n_elem; ++j)
      {
      eT acc = ptrs[0]->mem[j];
      for(u32 i=1; i<N_mat; ++i)
        {
        acc /= ptrs[i]->mem[j];
        }
      out[j] = acc;
      }
    for(u32 i=0; i<N_mat; ++i)
      {
      if(del[i] == true)
        {
        arma_extra_debug_print( arma_boost::format("delete ptrs[%d]") % i );
        delete ptrs[i];
        }
      }
    }
  }
template<typename eT> void glue_div::apply_inplace (basic_mat< eT > & out, const basic_mat< eT > & B) [inline, static, inherited]
Definition at line 161 of file glue_div_meat.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
Referenced by basic_mat< eT >::operator/=().
  {
  arma_extra_debug_sigprint();
  arma_debug_assert_same_size(out, B, "element-wise matrix division");
  const u32 n_elem = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out[i] /= B.mem[i];
    }
  }
template<typename T1, typename op_type> void glue_div::apply_inplace (basic_mat< typename T1::elem_type > & out, const op_data< T1, op_type > & X) [inline, static, inherited]
Definition at line 181 of file glue_div_meat.hpp.
References apply().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const basic_mat<eT> tmp(X);
  glue_div::apply(out, out, tmp);
  }
template<typename T1, typename T2, typename glue_type> void glue_div::apply_inplace (basic_mat< typename T1::elem_type > & out, const glue_data< T1, T2, glue_type > & X) [inline, static, inherited]
Definition at line 196 of file glue_div_meat.hpp.
References apply().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const basic_mat<eT> tmp(X);
  glue_div::apply(out, X, out);
  }
template<typename eT1, typename eT2> void glue_div::apply_mixed (basic_mat< typename promote_type< eT1, eT2 >::result > & out, const basic_mat< eT1 > & X, const basic_mat< eT2 > & Y) [inline, static, inherited]
Definition at line 214 of file glue_div_meat.hpp.
References upgrade_val< T1, T2 >::apply(), basic_mat< eT >::mem, basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
Referenced by operator/().
  {
  arma_extra_debug_sigprint();
  typedef typename promote_type<eT1,eT2>::result out_eT;
  arma_debug_assert_same_size(X,Y, "element-wise matrix division");
  out.set_size(X.n_rows, X.n_cols);
        out_eT* out_mem = out.memptr();
  const eT1*    X_mem   = X.mem;
  const eT2*    Y_mem   = Y.mem;
  const u32 n_elem = out.n_elem;
  for(u32 i=0; i<n_elem; ++i)
    {
    out_mem[i] = upgrade_val<eT1,eT2>::apply(X_mem[i]) / upgrade_val<eT1,eT2>::apply(Y_mem[i]);
    }
  }