Armadillo Technical: Basic_rowvec
Basic_rowvec
Classes
class basic_rowvec< eT >
Class for row vectors (matrices with only one row).
Functions
basic_rowvec::basic_rowvec ()
basic_rowvec::basic_rowvec (const u32 N)
basic_rowvec::basic_rowvec (const char *text)
const basic_rowvec & basic_rowvec::operator= (const char *text)
create the matrix from a textual description
basic_rowvec::basic_rowvec (const basic_rowvec &X)
const basic_rowvec & basic_rowvec::operator= (const basic_rowvec &X)
basic_rowvec::basic_rowvec (const basic_mat< eT > &X)
const basic_rowvec & basic_rowvec::operator= (const basic_mat< eT > &X)
construct a matrix from a given matrix
const basic_rowvec & basic_rowvec::operator*= (const basic_mat< eT > &X)
in-place matrix multiplication
basic_rowvec::basic_rowvec (const eT *aux_mem, const u32 aux_length)
construct a row vector from a given auxillary array
template<typename T1, typename T2>
basic_rowvec::basic_rowvec (const arma_base< typename basic_rowvec< eT >::pod_type, T1 > &A, const arma_base< typename basic_rowvec< eT >::pod_type, T2 > &B)
basic_rowvec::basic_rowvec (const subview< eT > &X)
const basic_rowvec & basic_rowvec::operator= (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const basic_rowvec & basic_rowvec::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
basic_rowvec::basic_rowvec (const diagview< eT > &X)
construct a row vector from given a diagview
const basic_rowvec & basic_rowvec::operator= (const diagview< eT > &X)
construct a row vector from given a diagview
const basic_rowvec & basic_rowvec::operator*= (const diagview< eT > &X)
template<typename T1, typename op_type>
basic_rowvec::basic_rowvec (const op_data< T1, op_type > &X)
template<typename T1, typename op_type>
const basic_rowvec & basic_rowvec::operator= (const op_data< T1, op_type > &X)
create a matrix from op_data, i.e. run the previously delayed unary operations
template<typename T1, typename op_type>
const basic_rowvec & basic_rowvec::operator*= (const op_data< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1, typename T2, typename glue_type>
basic_rowvec::basic_rowvec (const glue_data< T1, T2, glue_type > &X)
template<typename T1, typename T2, typename glue_type>
const basic_rowvec & basic_rowvec::operator= (const glue_data< T1, T2, glue_type > &X)
create a matrix from glue_data, i.e. run the previously delayed binary operations
template<typename T1, typename T2, typename glue_type>
const basic_rowvec & basic_rowvec::operator*= (const glue_data< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
void basic_rowvec::set_size (const u32 N)
void basic_rowvec::set_size (const u32 n_rows, const u32 n_cols)
change the matrix to have user specified dimensions (data is not preserved)
void basic_rowvec::zeros ()
void basic_rowvec::zeros (const u32 N)
void basic_rowvec::zeros (const u32 n_rows, const u32 n_cols)
void basic_rowvec::load (const std::string name, const file_type type=auto_detect)
load a matrix from a file
Function Documentation
template<typename eT> basic_rowvec< eT >::basic_rowvec () [inline, inherited]
Definition at line 21 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>()
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const u32 N) [inline, explicit, inherited]
Definition at line 31 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(1,in_n_elem)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const char * text) [inline, inherited]
Definition at line 41 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(text)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const char * text) [inline, inherited]
create the matrix from a textual description
Reimplemented from basic_mat< eT >.
Definition at line 54 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(text);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const basic_rowvec< eT > & X) [inline, inherited]
Definition at line 67 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const basic_rowvec< eT > & X) [inline, inherited]
Definition at line 78 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  return *this;
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const basic_mat< eT > & X) [inline, inherited]
Definition at line 89 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const basic_mat< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Reimplemented from basic_mat< eT >.
Definition at line 102 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator*= (const basic_mat< eT > & m) [inline, inherited]
in-place matrix multiplication
Reimplemented from basic_mat< eT >.
Definition at line 116 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const eT * aux_mem, const u32 aux_length) [inline, inherited]
construct a row vector from a given auxillary array
Definition at line 130 of file basic_rowvec_meat.hpp.
References arma_check(), syslib::copy_elem(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::set_size(1, aux_length);
  arma_check( (basic_mat<eT>::n_elem != aux_length), "basic_rowvec(): don't know how to handle the given array" );
  syslib::copy_elem( basic_mat<eT>::memptr(), aux_mem, basic_mat<eT>::n_elem );
  }
template<typename eT> template<typename T1, typename T2> basic_rowvec< eT >::basic_rowvec (const arma_base< typename basic_rowvec< eT >::pod_type, T1 > & A, const arma_base< typename basic_rowvec< eT >::pod_type, T2 > & B) [inline, inherited]
Definition at line 146 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(A,B)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_colvec(): incompatible dimensions" );
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const subview< eT > & X) [inline, inherited]
Definition at line 161 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Reimplemented from basic_mat< eT >.
Definition at line 174 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented from basic_mat< eT >.
Definition at line 188 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> basic_rowvec< eT >::basic_rowvec (const diagview< eT > & X) [inline, explicit, inherited]
construct a row vector from given a diagview
Definition at line 201 of file basic_rowvec_meat.hpp.
References access::rw().
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  std::swap( access::rw(basic_mat<eT>::n_rows), access::rw(basic_mat<eT>::n_cols) );
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a row vector from given a diagview
Reimplemented from basic_mat< eT >.
Definition at line 216 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  //std::swap( access::rw(basic_mat<eT>::n_rows), access::rw(basic_mat<eT>::n_cols) );
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> const basic_rowvec< eT > & basic_rowvec< eT >::operator*= (const diagview< eT > & X) [inline, inherited]
Definition at line 233 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> basic_rowvec< eT >::basic_rowvec (const op_data< T1, op_type > & X) [inline, inherited]
Definition at line 249 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> template<typename T1, typename op_type> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const op_data< T1, op_type > & X) [inline, inherited]
create a matrix from op_data, i.e. run the previously delayed unary operations
Reimplemented from basic_mat< eT >.
Definition at line 263 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_rowvec< eT > & basic_rowvec< eT >::operator*= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented from basic_mat< eT >.
Definition at line 278 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> basic_rowvec< eT >::basic_rowvec (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
Definition at line 292 of file basic_rowvec_meat.hpp.
  : basic_mat<eT>(X)
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_rowvec< eT > & basic_rowvec< eT >::operator= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from glue_data, i.e. run the previously delayed binary operations
Reimplemented from basic_mat< eT >.
Definition at line 306 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_rowvec< eT > & basic_rowvec< eT >::operator*= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented from basic_mat< eT >.
Definition at line 321 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::operator*=(X);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  return *this;
  }
template<typename eT> void basic_rowvec< eT >::set_size (const u32 N) [inline, inherited]
Definition at line 335 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::set_size().
Referenced by op_randn::apply(), op_rand::apply(), and op_ones_full::apply().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::set_size(1,in_n_elem);
  }
template<typename eT> void basic_rowvec< eT >::set_size (const u32 in_rows, const u32 in_cols) [inline, inherited]
change the matrix to have user specified dimensions (data is not preserved)
Reimplemented from basic_mat< eT >.
Definition at line 347 of file basic_rowvec_meat.hpp.
References min(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::set_size( (std::min)( u32(1), in_n_rows), in_n_cols );
  arma_debug_check( (in_n_rows > 1), "basic_rowvec::set_size(): incompatible dimensions" );
  }
template<typename eT> void basic_rowvec< eT >::zeros () [inline, inherited]
Reimplemented from basic_mat< eT >.
Definition at line 361 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::zeros().
Referenced by op_zeros::apply().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros();
  }
template<typename eT> void basic_rowvec< eT >::zeros (const u32 N) [inline, inherited]
Definition at line 373 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros(1,in_n_elem);
  }
template<typename eT> void basic_rowvec< eT >::zeros (const u32 n_rows, const u32 n_cols) [inline, inherited]
Reimplemented from basic_mat< eT >.
Definition at line 385 of file basic_rowvec_meat.hpp.
References min(), and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::zeros( (std::min)( u32(1), in_n_rows), in_n_cols );
  arma_debug_check( (in_n_rows > 1), "basic_rowvec<eT>::zeros(): incompatible dimensions" );
  }
template<typename eT> void basic_rowvec< eT >::load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file
Reimplemented from basic_mat< eT >.
Definition at line 398 of file basic_rowvec_meat.hpp.
References basic_mat< eT >::load().
  {
  arma_extra_debug_sigprint();
  basic_mat<eT>::load(name,type);
  arma_debug_check( (basic_mat<eT>::n_rows > 1), "basic_rowvec(): incompatible dimensions" );
  }