Armadillo Technical: Basic_mat
Basic_mat
Classes
class basic_mat< eT >
Dense matrix class.
Functions
basic_mat::~basic_mat ()
basic_mat::basic_mat ()
basic_mat::basic_mat (const u32 in_rows, const u32 in_cols)
construct the matrix to have user specified dimensions
void basic_mat::set_size (const u32 in_rows, const u32 in_cols)
change the matrix to have user specified dimensions (data is not preserved)
void basic_mat::init (const u32 in_rows, const u32 in_cols)
internal matrix construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
basic_mat::basic_mat (const char *text)
create the matrix from a textual description
const basic_mat & basic_mat::operator= (const char *text)
create the matrix from a textual description
basic_mat::basic_mat (const std::string &text)
create the matrix from a textual description
const basic_mat & basic_mat::operator= (const std::string &text)
create the matrix from a textual description
void basic_mat::init (const std::string &text)
internal function to create the matrix from a textual description
const basic_mat & basic_mat::operator= (const eT val)
Set the matrix to be equal to the specified scalar. NOTE: the size of the matrix will be 1x1, as a scalar is a 1x1 matrix.
const basic_mat & basic_mat::operator+= (const eT val)
In-place addition of a scalar to all elements of the matrix.
const basic_mat & basic_mat::operator-= (const eT val)
In-place subtraction of a scalar from all elements of the matrix.
const basic_mat & basic_mat::operator*= (const eT val)
In-place multiplication of all elements of the matrix with a scalar.
const basic_mat & basic_mat::operator/= (const eT val)
In-place division of all elements of the matrix with a scalar.
basic_mat::basic_mat (const basic_mat &m)
construct a matrix from a given matrix
const basic_mat & basic_mat::operator= (const basic_mat &m)
construct a matrix from a given matrix
void basic_mat::init (const basic_mat &x)
construct a matrix from a given matrix
basic_mat::basic_mat (const eT *aux_mem, const u32 aux_n_rows, const u32 aux_n_cols)
construct a matrix from a given auxillary array of eTs
const basic_mat & basic_mat::operator+= (const basic_mat &m)
in-place matrix addition
const basic_mat & basic_mat::operator-= (const basic_mat &m)
in-place matrix subtraction
const basic_mat & basic_mat::operator*= (const basic_mat &m)
in-place matrix multiplication
const basic_mat & basic_mat::operator%= (const basic_mat &m)
in-place element-wise matrix multiplication
const basic_mat & basic_mat::operator/= (const basic_mat &m)
in-place element-wise matrix division
template<typename T1, typename T2>
basic_mat::basic_mat (const arma_base< typename basic_mat< eT >::pod_type, T1 > &A, const arma_base< typename basic_mat< eT >::pod_type, T2 > &B)
for constructing a complex matrix out of two non-complex matrices
basic_mat::basic_mat (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const basic_mat & basic_mat::operator= (const subview< eT > &X)
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
const basic_mat & basic_mat::operator+= (const subview< eT > &X)
in-place matrix addition (using a submatrix on the right-hand-side)
const basic_mat & basic_mat::operator-= (const subview< eT > &X)
in-place matrix subtraction (using a submatrix on the right-hand-side)
const basic_mat & basic_mat::operator*= (const subview< eT > &X)
in-place matrix mutiplication (using a submatrix on the right-hand-side)
const basic_mat & basic_mat::operator%= (const subview< eT > &X)
in-place element-wise matrix mutiplication (using a submatrix on the right-hand-side)
const basic_mat & basic_mat::operator/= (const subview< eT > &X)
in-place element-wise matrix division (using a submatrix on the right-hand-side)
basic_mat::basic_mat (const diagview< eT > &X)
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
const basic_mat & basic_mat::operator= (const diagview< eT > &X)
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
subview_row< eT > basic_mat::row (const u32 row_num)
creation of subview (row vector)
const subview_row< eT > basic_mat::row (const u32 row_num) const
creation of subview (row vector)
subview_col< eT > basic_mat::col (const u32 col_num)
creation of subview (column vector)
const subview_col< eT > basic_mat::col (const u32 col_num) const
creation of subview (column vector)
subview< eT > basic_mat::rows (const u32 in_row1, const u32 in_row2)
creation of subview (submatrix comprised of specified row vectors)
const subview< eT > basic_mat::rows (const u32 in_row1, const u32 in_row2) const
creation of subview (submatrix comprised of specified row vectors)
subview< eT > basic_mat::cols (const u32 in_col1, const u32 in_col2)
creation of subview (submatrix comprised of specified column vectors)
const subview< eT > basic_mat::cols (const u32 in_col1, const u32 in_col2) const
creation of subview (submatrix comprised of specified column vectors)
subview< eT > basic_mat::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2)
creation of subview (submatrix)
const subview< eT > basic_mat::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const
creation of subview (generic submatrix)
diagview< eT > basic_mat::diag (const s32 in_id=0)
creation of diagview (diagonal)
const diagview< eT > basic_mat::diag (const s32 in_id=0) const
creation of diagview (diagonal)
void basic_mat::swap_rows (const u32 in_row1, const u32 in_row2)
void basic_mat::swap_cols (const u32 in_col1, const u32 in_col2)
template<typename T1, typename op_type>
basic_mat::basic_mat (const op_data< T1, op_type > &X)
create a matrix from op_data, i.e. run the previously delayed unary operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator= (const op_data< T1, op_type > &X)
create a matrix from op_data, i.e. run the previously delayed unary operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator+= (const op_data< T1, op_type > &X)
in-place matrix addition, with the right-hand-side operand having delayed operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator-= (const op_data< T1, op_type > &X)
in-place matrix subtraction, with the right-hand-side operand having delayed operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator*= (const op_data< T1, op_type > &X)
in-place matrix multiplication, with the right-hand-side operand having delayed operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator%= (const op_data< T1, op_type > &X)
in-place matrix element-wise multiplication, with the right-hand-side operand having delayed operations
template<typename T1, typename op_type>
const basic_mat & basic_mat::operator/= (const op_data< T1, op_type > &X)
in-place matrix element-wise division, with the right-hand-side operand having delayed operations
template<typename T1, typename T2, typename glue_type>
basic_mat::basic_mat (const glue_data< T1, T2, glue_type > &X)
create a matrix from glue_data, i.e. run the previously delayed binary operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator= (const glue_data< T1, T2, glue_type > &X)
create a matrix from glue_data, i.e. run the previously delayed binary operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator+= (const glue_data< T1, T2, glue_type > &X)
in-place matrix addition, with the right-hand-side operands having delayed operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator-= (const glue_data< T1, T2, glue_type > &X)
in-place matrix subtraction, with the right-hand-side operands having delayed operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator*= (const glue_data< T1, T2, glue_type > &X)
in-place matrix multiplications, with the right-hand-side operands having delayed operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator%= (const glue_data< T1, T2, glue_type > &X)
in-place matrix element-wise multiplication, with the right-hand-side operands having delayed operations
template<typename T1, typename T2, typename glue_type>
const basic_mat & basic_mat::operator/= (const glue_data< T1, T2, glue_type > &X)
in-place matrix element-wise division, with the right-hand-side operands having delayed operations
eT & basic_mat::operator() (const u32 i)
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
eT basic_mat::operator() (const u32 i) const
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
eT & basic_mat::operator[] (const u32 i)
linear element accessor (treats the matrix as a vector); no bounds check.
eT basic_mat::operator[] (const u32 i) const
linear element accessor (treats the matrix as a vector); no bounds check
eT & basic_mat::operator() (const u32 in_row, const u32 in_col)
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
eT basic_mat::operator() (const u32 in_row, const u32 in_col) const
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
eT & basic_mat::at (const u32 in_row, const u32 in_col)
element accessor; no bounds check
eT basic_mat::at (const u32 in_row, const u32 in_col) const
element accessor; no bounds check
bool basic_mat::is_vec () const
returns true if the object can be interpreted as a column or row vector
bool basic_mat::is_square () const
returns true if the object has the same number of non-zero rows and columnns
eT * basic_mat::colptr (const u32 in_col)
returns a pointer to array of eTs for a specified column; no bounds check
const eT * basic_mat::colptr (const u32 in_col) const
returns a pointer to array of eTs for a specified column; no bounds check
eT * basic_mat::memptr ()
returns a pointer to array of eTs used by the matrix
const eT * basic_mat::memptr () const
returns a pointer to array of eTs used by the matrix
void basic_mat::print (const std::string extra_text="") const
print contents of the matrix, optionally preceding with a user specified line of text
void basic_mat::fill (const eT val)
fill the matrix with the specified value
void basic_mat::zeros ()
void basic_mat::zeros (const u32 in_rows, const u32 in_cols)
void basic_mat::reset ()
void basic_mat::save (const std::string name, const file_type type=arma_binary) const
save the matrix to a file
void basic_mat::load (const std::string name, const file_type type=auto_detect)
load a matrix from a file
Function Documentation
template<typename eT> basic_mat< eT >::~basic_mat () [inline, inherited]
Definition at line 22 of file basic_mat_meat.hpp.
References isnt_supported_elem_type< T1 >::check(), arma_config::debug, basic_mat< eT >::mem, basic_mat< eT >::mem_local, basic_mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint_this(this);
  if(n_elem > sizeof(mem_local)/sizeof(eT) )
    {
    delete [] mem;
    }
  if(arma_config::debug == true)
    {
    access::rw(mem) = 0;  // try to expose buggy code that still accesses a deleted 'mat'
    }
  isnt_supported_elem_type<eT>::check();
  }
template<typename eT> basic_mat< eT >::basic_mat () [inline, inherited]
Definition at line 43 of file basic_mat_meat.hpp.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  }
template<typename eT> basic_mat< eT >::basic_mat (const u32 in_rows, const u32 in_cols) [inline, inherited]
construct the matrix to have user specified dimensions
Definition at line 57 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(in_n_rows, in_n_cols);
  }
template<typename eT> void basic_mat< eT >::set_size (const u32 in_rows, const u32 in_cols) [inline, inherited]
change the matrix to have user specified dimensions (data is not preserved)
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 75 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
Referenced by op_var::apply(), op_atanh::apply(), op_tanh::apply(), op_atan::apply(), op_tan::apply(), op_asinh::apply(), op_sinh::apply(), op_asin::apply(), op_sin::apply(), op_acosh::apply(), op_cosh::apply(), op_acos::apply(), op_cos::apply(), op_trans::apply(), op_sum::apply(), op_stddev::apply(), op_sort::apply(), op_scalar_div_post::apply(), op_scalar_div_pre::apply(), op_scalar_times::apply(), op_scalar_minus_post::apply(), op_scalar_minus_pre::apply(), op_scalar_plus::apply(), op_randn::apply(), op_rand::apply(), op_ones_full::apply(), op_neg::apply(), op_conj::apply(), op_pow_s32::apply(), op_pow::apply(), op_square::apply(), op_sqrt::apply(), op_trunc_exp::apply(), op_exp::apply(), op_log10::apply(), op_trunc_log::apply(), op_log::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_diagmat::apply(), glue_times_vec::apply(), glue_times_diag::apply(), glue_times::apply(), glue_schur::apply(), glue_plus_diag::apply(), glue_plus::apply(), glue_minus_diag::apply(), glue_minus::apply(), glue_div::apply(), glue_plus::apply_mixed(), op_trans::apply_noalias(), glue_times::apply_noalias(), basic_rowvec< eT >::basic_rowvec(), subview< eT >::extract(), diagview< eT >::extract(), basic_mat< eT >::init(), auxlib::inv_noalias(), linspace(), diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), auxlib::lu(), auxlib::qr(), reshape(), basic_rowvec< eT >::set_size(), basic_colvec< eT >::set_size(), auxlib::solve_od(), auxlib::solve_ud(), auxlib::svd(), and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint(arma_boost::format("in_n_rows = %d, in_n_cols = %d") % in_n_rows % in_n_cols);
  init(in_n_rows,in_n_cols);
  }
template<typename eT> void basic_mat< eT >::init (const u32 in_rows, const u32 in_cols) [inline, protected, inherited]
internal matrix construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
Definition at line 87 of file basic_mat_meat.hpp.
References arma_check(), basic_mat< eT >::mem, basic_mat< eT >::mem_local, basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, basic_mat< eT >::n_rows, and access::rw().
Referenced by basic_mat< eT >::basic_mat(), basic_mat< eT >::init(), basic_mat< eT >::operator=(), basic_mat< eT >::reset(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint( arma_boost::format("in_n_rows = %d, in_n_cols = %d") % in_n_rows % in_n_cols );
  const u32 new_n_elem = in_n_rows * in_n_cols;
  if(n_elem == new_n_elem)
    {
    access::rw(n_rows) = in_n_rows;
    access::rw(n_cols) = in_n_cols;
    }
  else
    {
    if(n_elem > sizeof(mem_local)/sizeof(eT) )
      {
      delete [] mem;
      }
    if(new_n_elem <= sizeof(mem_local)/sizeof(eT) )
      {
      access::rw(mem) = mem_local;
      }
    else
      {
      access::rw(mem) = new(std::nothrow) eT[new_n_elem];
      arma_check( (mem == 0), "basic_mat::init(): out of memory" );
      }
    access::rw(n_elem) = new_n_elem;
    if(new_n_elem == 0)
      {
      access::rw(n_rows) = 0;
      access::rw(n_cols) = 0;
      }
    else
      {
      access::rw(n_rows) = in_n_rows;
      access::rw(n_cols) = in_n_cols;
      }
    }
  }
template<typename eT> basic_mat< eT >::basic_mat (const char * text) [inline, inherited]
create the matrix from a textual description
Definition at line 138 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init( std::string(text) );
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const char * text) [inline, inherited]
create the matrix from a textual description
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 156 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
Referenced by basic_mat< eT >::basic_mat(), basic_rowvec< eT >::operator=(), and basic_colvec< eT >::operator=().
  {
  arma_extra_debug_sigprint();
  init( std::string(text) );
  return *this;
  }
template<typename eT> basic_mat< eT >::basic_mat (const std::string & text) [inline, inherited]
create the matrix from a textual description
Definition at line 169 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(text);
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const std::string & text) [inline, inherited]
create the matrix from a textual description
Definition at line 187 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  {
  arma_extra_debug_sigprint();
  init(text);
  return *this;
  }
template<typename eT> void basic_mat< eT >::init (const std::string & text) [inline, protected, inherited]
internal function to create the matrix from a textual description
Definition at line 201 of file basic_mat_meat.hpp.
References arma_check(), basic_mat< eT >::at(), basic_mat< eT >::col(), basic_mat< eT >::row(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint();
  //
  // work out the size
  u32 t_n_rows = 0;
  u32 t_n_cols = 0;
  bool t_n_cols_found = false;
  std::string token;
  std::string::size_type line_start = 0;
  std::string::size_type   line_end = 0;
  while( line_start < text.length() )
    {
    line_end = text.find(';', line_start);
    if(line_end == std::string::npos)
      line_end = text.length()-1;
    std::string::size_type line_len = line_end - line_start + 1;
    std::stringstream line_stream( text.substr(line_start,line_len) );
    u32 line_n_cols = 0;
    while(line_stream >> token)
      {
      ++line_n_cols;
      }
    if(line_n_cols > 0)
      {
      if(t_n_cols_found == false)
        {
        t_n_cols = line_n_cols;
        t_n_cols_found = true;
        }
      else
        arma_check( (line_n_cols != t_n_cols), "basic_mat::init(): inconsistent number of columns in given string");
      ++t_n_rows;
      }
    line_start = line_end+1;
    }
  basic_mat<eT> &x = *this;
  x.set_size(t_n_rows, t_n_cols);
  line_start = 0;
  line_end = 0;
  u32 row = 0;
  while( line_start < text.length() )
    {
    line_end = text.find(';', line_start);
    if(line_end == std::string::npos)
      line_end = text.length()-1;
    std::string::size_type line_len = line_end - line_start + 1;
    std::stringstream line_stream( text.substr(line_start,line_len) );
//     u32 col = 0;
//     while(line_stream >> token)
//       {
//       x.at(row,col) = strtod(token.c_str(), 0);
//       ++col;
//       }
    u32 col = 0;
    eT val;
    while(line_stream >> val)
      {
      x.at(row,col) = val;
      ++col;
      }
    ++row;
    line_start = line_end+1;
    }
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const eT val) [inline, inherited]
Set the matrix to be equal to the specified scalar. NOTE: the size of the matrix will be 1x1, as a scalar is a 1x1 matrix.
Definition at line 299 of file basic_mat_meat.hpp.
References basic_mat< eT >::init(), basic_mat< eT >::mem, and access::rw().
  {
  arma_extra_debug_sigprint();
  init(1,1);
  access::rw(mem[0]) = val;
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator+= (const eT val) [inline, inherited]
In-place addition of a scalar to all elements of the matrix.
Definition at line 314 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) += val;
    }
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator-= (const eT val) [inline, inherited]
In-place subtraction of a scalar from all elements of the matrix.
Definition at line 332 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) -= val;
    }
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator*= (const eT val) [inline, inherited]
In-place multiplication of all elements of the matrix with a scalar.
Definition at line 350 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
Referenced by basic_rowvec< eT >::operator*=(), and basic_colvec< eT >::operator*=().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) *= val;
    }
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator/= (const eT val) [inline, inherited]
In-place division of all elements of the matrix with a scalar.
Definition at line 368 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) /= val;
    }
  return *this;
  }
template<typename eT> basic_mat< eT >::basic_mat (const basic_mat< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Definition at line 385 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x   in_mat = %x") % this % &in_mat);
  init(in_mat);
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const basic_mat< eT > & m) [inline, inherited]
construct a matrix from a given matrix
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 403 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
  {
  arma_extra_debug_sigprint();
  init(x);
  return *this;
  }
template<typename eT> void basic_mat< eT >::init (const basic_mat< eT > & x) [inline, protected, inherited]
construct a matrix from a given matrix
Definition at line 417 of file basic_mat_meat.hpp.
References syslib::copy_elem(), basic_mat< eT >::init(), basic_mat< eT >::mem, basic_mat< eT >::memptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  if(this != &x)
    {
    init(x.n_rows, x.n_cols);
    syslib::copy_elem( memptr(), x.mem, n_elem );
    }
  }
template<typename eT> basic_mat< eT >::basic_mat (const eT * aux_mem, const u32 aux_n_rows, const u32 aux_n_cols) [inline, inherited]
construct a matrix from a given auxillary array of eTs
Definition at line 433 of file basic_mat_meat.hpp.
References syslib::copy_elem(), basic_mat< eT >::init(), basic_mat< eT >::memptr(), and basic_mat< eT >::n_elem.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  init(aux_n_rows, aux_n_cols);
  syslib::copy_elem( memptr(), aux_mem, n_elem );
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator+= (const basic_mat< eT > & m) [inline, inherited]
in-place matrix addition
Definition at line 452 of file basic_mat_meat.hpp.
References glue_plus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_plus::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator-= (const basic_mat< eT > & m) [inline, inherited]
in-place matrix subtraction
Definition at line 466 of file basic_mat_meat.hpp.
References glue_minus::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_minus::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator*= (const basic_mat< eT > & m) [inline, inherited]
in-place matrix multiplication
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 480 of file basic_mat_meat.hpp.
References glue_times::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_times::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator%= (const basic_mat< eT > & m) [inline, inherited]
in-place element-wise matrix multiplication
Definition at line 494 of file basic_mat_meat.hpp.
References glue_schur::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_schur::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator/= (const basic_mat< eT > & m) [inline, inherited]
in-place element-wise matrix division
Definition at line 508 of file basic_mat_meat.hpp.
References glue_div::apply_inplace().
  {
  arma_extra_debug_sigprint();
  glue_div::apply_inplace(*this, m);
  return *this;
  }
template<typename eT> template<typename T1, typename T2> basic_mat< eT >::basic_mat (const arma_base< typename basic_mat< eT >::pod_type, T1 > & A, const arma_base< typename basic_mat< eT >::pod_type, T2 > & B) [inline, inherited]
for constructing a complex matrix out of two non-complex matrices
< compile-time abort if eT isn't std::complex
< compile-time abort if T is std::complex
< compile-time abort if types are not compatible
Definition at line 523 of file basic_mat_meat.hpp.
References arma_assert_same_size(), basic_mat< eT >::init(), basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, and access::rw().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  arma_type_check< is_complex<eT>::value == false >::apply();   //!< compile-time abort if eT isn't std::complex
  typedef typename T1::elem_type T;
  arma_type_check< is_complex<T>::value == true >::apply();   //!< compile-time abort if T is std::complex
  isnt_same_type<std::complex<T>, eT>::check();   //!< compile-time abort if types are not compatible
  const unwrap<T1> tmp_A(A.get_ref());
  const unwrap<T2> tmp_B(B.get_ref());
  const basic_mat<T>& X = tmp_A.M;
  const basic_mat<T>& Y = tmp_B.M;
  arma_assert_same_size(X, Y, "basic_mat()");
  init(X.n_rows, Y.n_cols);
  const T* X_mem = X.mem;
  const T* Y_mem = Y.mem;
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) = std::complex<T>(X_mem[i], Y_mem[i]);
    }
  }
template<typename eT> basic_mat< eT >::basic_mat (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Definition at line 566 of file basic_mat_meat.hpp.
References basic_mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const subview< eT > & X) [inline, inherited]
construct a matrix from subview (e.g. construct a matrix from a delayed submatrix operation)
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 584 of file basic_mat_meat.hpp.
References subview< eT >::extract().
  {
  arma_extra_debug_sigprint();
  subview<eT>::extract(*this, X);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator+= (const subview< eT > & X) [inline, inherited]
in-place matrix addition (using a submatrix on the right-hand-side)
Definition at line 597 of file basic_mat_meat.hpp.
References subview< eT >::plus_inplace().
  {
  arma_extra_debug_sigprint();
  subview<eT>::plus_inplace(*this, X);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator-= (const subview< eT > & X) [inline, inherited]
in-place matrix subtraction (using a submatrix on the right-hand-side)
Definition at line 610 of file basic_mat_meat.hpp.
References subview< eT >::minus_inplace().
  {
  arma_extra_debug_sigprint();
  subview<eT>::minus_inplace(*this, X);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator*= (const subview< eT > & X) [inline, inherited]
in-place matrix mutiplication (using a submatrix on the right-hand-side)
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 624 of file basic_mat_meat.hpp.
References subview< eT >::times_inplace().
  {
  arma_extra_debug_sigprint();
  subview<eT>::times_inplace(*this, X);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator%= (const subview< eT > & X) [inline, inherited]
in-place element-wise matrix mutiplication (using a submatrix on the right-hand-side)
Definition at line 638 of file basic_mat_meat.hpp.
References subview< eT >::schur_inplace().
  {
  arma_extra_debug_sigprint();
  subview<eT>::schur_inplace(*this, X);
  return *this;
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator/= (const subview< eT > & X) [inline, inherited]
in-place element-wise matrix division (using a submatrix on the right-hand-side)
Definition at line 652 of file basic_mat_meat.hpp.
References subview< eT >::div_inplace().
  {
  arma_extra_debug_sigprint();
  subview<eT>::div_inplace(*this, X);
  return *this;
  }
template<typename eT> basic_mat< eT >::basic_mat (const diagview< eT > & X) [inline, inherited]
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
Definition at line 665 of file basic_mat_meat.hpp.
References basic_mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT> const basic_mat< eT > & basic_mat< eT >::operator= (const diagview< eT > & X) [inline, inherited]
construct a matrix from diagview (e.g. construct a matrix from a delayed diag operation)
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 683 of file basic_mat_meat.hpp.
References diagview< eT >::extract().
  {
  arma_extra_debug_sigprint();
  diagview<eT>::extract(*this, X);
  return *this;
  }
template<typename eT> subview_row< eT > basic_mat< eT >::row (const u32 row_num) [inline, inherited]
creation of subview (row vector)
Definition at line 697 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_rows.
Referenced by basic_mat< eT >::init(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), diskio::save_arma_ascii(), diskio::save_pgm_binary(), diskio::save_raw_ascii(), and basic_mat< eT >::swap_cols().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( row_num >= n_rows, "basic_mat::row(): row out of bounds" );
  return subview_row<eT>(*this, row_num);
  }
template<typename eT> const subview_row< eT > basic_mat< eT >::row (const u32 row_num) const [inline, inherited]
creation of subview (row vector)
Definition at line 712 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( row_num >= n_rows, "basic_mat::row(): row out of bounds" );
  return subview_row<eT>(*this, row_num);
  }
template<typename eT> subview_col< eT > basic_mat< eT >::col (const u32 col_num) [inline, inherited]
creation of subview (column vector)
Definition at line 727 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols.
Referenced by basic_mat< eT >::init(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), diskio::save_arma_ascii(), diskio::save_pgm_binary(), diskio::save_raw_ascii(), and basic_mat< eT >::swap_rows().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( col_num >= n_cols, "basic_mat::col(): out of bounds");
  return subview_col<eT>(*this, col_num);
  }
template<typename eT> const subview_col< eT > basic_mat< eT >::col (const u32 col_num) const [inline, inherited]
creation of subview (column vector)
Definition at line 742 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( col_num >= n_cols, "basic_mat::col(): out of bounds");
  return subview_col<eT>(*this, col_num);
  }
template<typename eT> subview< eT > basic_mat< eT >::rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Definition at line 757 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_row2 >= n_rows),
    "basic_mat::rows(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, 0, in_row2, n_cols-1);
  }
template<typename eT> const subview< eT > basic_mat< eT >::rows (const u32 in_row1, const u32 in_row2) const [inline, inherited]
creation of subview (submatrix comprised of specified row vectors)
Definition at line 776 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_row2 >= n_rows),
    "basic_mat::rows(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, 0, in_row2, n_cols-1);
  }
template<typename eT> subview< eT > basic_mat< eT >::cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Definition at line 795 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 > in_col2) || (in_col2 >= n_cols),
    "basic_mat::cols(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, 0, in_col1, n_rows-1, in_col2);
  }
template<typename eT> const subview< eT > basic_mat< eT >::cols (const u32 in_col1, const u32 in_col2) const [inline, inherited]
creation of subview (submatrix comprised of specified column vectors)
Definition at line 814 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 > in_col2) || (in_col2 >= n_cols),
    "basic_mat::cols(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, 0, in_col1, n_rows-1, in_col2);
  }
template<typename eT> subview< eT > basic_mat< eT >::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) [inline, inherited]
creation of subview (submatrix)
Definition at line 833 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_col1 >  in_col2) || (in_row2 >= n_rows) || (in_col2 >= n_cols),
    "basic_mat::submat(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename eT> const subview< eT > basic_mat< eT >::submat (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const [inline, inherited]
creation of subview (generic submatrix)
Definition at line 852 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 > in_row2) || (in_col1 >  in_col2) || (in_row2 >= n_rows) || (in_col2 >= n_cols),
    "basic_mat::submat(): indices out of bounds or incorrectly used"
    );
  return subview<eT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename eT> diagview< eT > basic_mat< eT >::diag (const s32 in_id = 0) [inline, inherited]
creation of diagview (diagonal)
Definition at line 871 of file basic_mat_meat.hpp.
References min(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  const u32 row_offset = (in_id < 0) ? -in_id : 0;
  const u32 col_offset = (in_id > 0) ?  in_id : 0;
  arma_debug_check
    (
    (row_offset >= n_rows) || (col_offset >= n_cols),
    "basic_mat::diag(): out of bounds"
    );
  const u32 len = (std::min)(n_rows - row_offset, n_cols - col_offset);
  return diagview<eT>(*this, row_offset, col_offset, len);
  }
template<typename eT> const diagview< eT > basic_mat< eT >::diag (const s32 in_id = 0) const [inline, inherited]
creation of diagview (diagonal)
Definition at line 895 of file basic_mat_meat.hpp.
References min(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  const u32 row_offset = (in_id < 0) ? -in_id : 0;
  const u32 col_offset = (in_id > 0) ?  in_id : 0;
  arma_debug_check
    (
    (row_offset >= n_rows) || (col_offset >= n_cols),
    "basic_mat::diag(): out of bounds"
    );
  const u32 len = (std::min)(n_rows - row_offset, n_cols - col_offset);
  return diagview<eT>(*this, row_offset, col_offset, len);
  }
template<typename eT> void basic_mat< eT >::swap_rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
Definition at line 919 of file basic_mat_meat.hpp.
References basic_mat< eT >::col(), basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and access::rw().
Referenced by auxlib::lu().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 >= n_rows) || (in_row2 >= n_rows),
    "basic_mat::swap_rows(): out of bounds"
    );
  for(u32 col=0; col<n_cols; ++col)
    {
    const u32 offset = col*n_rows;
    const u32 pos1   = in_row1 + offset;
    const u32 pos2   = in_row2 + offset;
    const eT tmp          = mem[pos1];
    access::rw(mem[pos1]) = mem[pos2];
    access::rw(mem[pos2]) = tmp;
    }
  }
template<typename eT> void basic_mat< eT >::swap_cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
Definition at line 947 of file basic_mat_meat.hpp.
References basic_mat< eT >::colptr(), basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and basic_mat< eT >::row().
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_col1 >= n_cols) || (in_col2 >= n_cols),
    "basic_mat::swap_cols(): out of bounds"
    );
  eT* ptr1 = colptr(in_col1);
  eT* ptr2 = colptr(in_col2);
  for(u32 row=0; row<n_rows; ++row)
    {
    const eT tmp = ptr1[row];
    ptr1[row]    = ptr2[row];
    ptr2[row]    = tmp;
    }
  }
template<typename eT> template<typename T1, typename op_type> basic_mat< eT >::basic_mat (const op_data< T1, op_type > & X) [inline, inherited]
create a matrix from op_data, i.e. run the previously delayed unary operations
Definition at line 975 of file basic_mat_meat.hpp.
References isnt_same_type< T1, T2 >::check().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  isnt_same_type<eT, typename T1::elem_type>::check();
  op_type::apply(*this, X);
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator= (const op_data< T1, op_type > & X) [inline, inherited]
create a matrix from op_data, i.e. run the previously delayed unary operations
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 996 of file basic_mat_meat.hpp.
References isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  op_type::apply(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator+= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix addition, with the right-hand-side operand having delayed operations
Definition at line 1014 of file basic_mat_meat.hpp.
References glue_plus::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_plus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator-= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix subtraction, with the right-hand-side operand having delayed operations
Definition at line 1032 of file basic_mat_meat.hpp.
References glue_minus::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_minus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator*= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix multiplication, with the right-hand-side operand having delayed operations
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1050 of file basic_mat_meat.hpp.
References glue_times::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_times::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator%= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix element-wise multiplication, with the right-hand-side operand having delayed operations
Definition at line 1068 of file basic_mat_meat.hpp.
References glue_schur::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_schur::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename op_type> const basic_mat< eT > & basic_mat< eT >::operator/= (const op_data< T1, op_type > & X) [inline, inherited]
in-place matrix element-wise division, with the right-hand-side operand having delayed operations
Definition at line 1085 of file basic_mat_meat.hpp.
References glue_div::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  glue_div::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> basic_mat< eT >::basic_mat (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from glue_data, i.e. run the previously delayed binary operations
Definition at line 1101 of file basic_mat_meat.hpp.
References basic_mat< eT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  //, mem(0)
  , mem(mem)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
create a matrix from glue_data, i.e. run the previously delayed binary operations
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1119 of file basic_mat_meat.hpp.
References isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  // TODO:
  // it may be simpler to pass the two objects (currently wrapped in X)
  // directly to the apply function.
  // (many adjustments throughout the source code will be required)
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_type::apply(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator+= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix addition, with the right-hand-side operands having delayed operations
Definition at line 1142 of file basic_mat_meat.hpp.
References glue_plus::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_plus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator-= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix subtraction, with the right-hand-side operands having delayed operations
Definition at line 1161 of file basic_mat_meat.hpp.
References glue_minus::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_minus::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator*= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix multiplications, with the right-hand-side operands having delayed operations
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1180 of file basic_mat_meat.hpp.
References glue_times::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_times::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator%= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix element-wise multiplication, with the right-hand-side operands having delayed operations
Definition at line 1198 of file basic_mat_meat.hpp.
References glue_schur::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_schur::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> template<typename T1, typename T2, typename glue_type> const basic_mat< eT > & basic_mat< eT >::operator/= (const glue_data< T1, T2, glue_type > & X) [inline, inherited]
in-place matrix element-wise division, with the right-hand-side operands having delayed operations
Definition at line 1216 of file basic_mat_meat.hpp.
References glue_div::apply_inplace(), and isnt_same_type< T1, T2 >::check().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<eT, typename T1::elem_type>::check();
  isnt_same_type<eT, typename T2::elem_type>::check();
  glue_div::apply_inplace(*this, X);
  return *this;
  }
template<typename eT> eT & basic_mat< eT >::operator() (const u32 i) [inline, inherited]
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1233 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
  {
  arma_debug_check( (i >= n_elem), "basic_mat::operator(): index out of bounds");
  return access::rw(mem[i]);
  }
template<typename eT> eT basic_mat< eT >::operator() (const u32 i) const [inline, inherited]
linear element accessor (treats the matrix as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1245 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_debug_check( (i >= n_elem), "basic_mat::operator(): index out of bounds");
  return mem[i];
  }
template<typename eT> eT & basic_mat< eT >::operator[] (const u32 i) [inline, inherited]
linear element accessor (treats the matrix as a vector); no bounds check.
Definition at line 1256 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, and access::rw().
  {
  return access::rw(mem[i]);
  }
template<typename eT> eT basic_mat< eT >::operator[] (const u32 i) const [inline, inherited]
linear element accessor (treats the matrix as a vector); no bounds check
Definition at line 1267 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem.
  {
  return mem[i];
  }
template<typename eT> eT & basic_mat< eT >::operator() (const u32 in_row, const u32 in_col) [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1278 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and access::rw().
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "basic_mat::operator(): index out of bounds");
  return access::rw(mem[in_row + in_col*n_rows]);
  }
template<typename eT> eT basic_mat< eT >::operator() (const u32 in_row, const u32 in_col) const [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 1290 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "basic_mat::operator(): index out of bounds");
  return mem[in_row + in_col*n_rows];
  }
template<typename eT> eT & basic_mat< eT >::at (const u32 in_row, const u32 in_col) [inline, inherited]
element accessor; no bounds check
Definition at line 1302 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_rows, and access::rw().
Referenced by accu(), op_var::apply(), op_trans::apply(), op_sum::apply(), op_stddev::apply(), op_sort::apply(), op_ones_diag::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_inv::apply(), op_diagmat_vec::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_times::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_plus::apply(), glue_minus_diag::apply(), gemv_arma< do_trans_A, use_alpha, use_beta >::apply(), gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), op_inv::apply_diagvec(), glue_times::apply_inplace(), op_trans::apply_noalias(), det(), auxlib::det(), diagmat(), glue_times::direct_rowvec_diagmat_colvec(), glue_times::direct_rowvec_invdiagmat_colvec(), glue_times::direct_rowvec_mat_colvec(), diagview< eT >::extract(), diagview< eT >::fill(), basic_mat< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), diskio::load_arma_ascii(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), auxlib::lu(), operator*(), operator/(), operator<<(), diagview< eT >::operator=(), auxlib::qr(), diskio::save_arma_ascii(), diskio::save_raw_ascii(), trace(), and diagview< eT >::zeros().
  {
  return access::rw( mem[in_row + in_col*n_rows] );
  }
template<typename eT> eT basic_mat< eT >::at (const u32 in_row, const u32 in_col) const [inline, inherited]
element accessor; no bounds check
Definition at line 1313 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_rows.
  {
  return mem[in_row + in_col*n_rows];
  }
template<typename eT> bool basic_mat< eT >::is_vec () const [inline, inherited]
returns true if the object can be interpreted as a column or row vector
Definition at line 1324 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
Referenced by accu(), op_inv::apply_diagvec(), det(), operator<<(), and trace().
  {
  return ( (n_rows == 1) || (n_cols == 1) );
  }
template<typename eT> bool basic_mat< eT >::is_square () const [inline, inherited]
returns true if the object has the same number of non-zero rows and columnns
Definition at line 1335 of file basic_mat_meat.hpp.
References basic_mat< eT >::n_cols, basic_mat< eT >::n_elem, and basic_mat< eT >::n_rows.
Referenced by accu(), op_inv::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_minus_diag::apply(), det(), operator<<(), and trace().
  {
  return ( (n_rows == n_cols) && (n_elem > 0) );
  }
template<typename eT> eT * basic_mat< eT >::colptr (const u32 in_col) [inline, inherited]
returns a pointer to array of eTs for a specified column; no bounds check
Definition at line 1346 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_rows, and access::rw().
Referenced by op_var::apply(), op_trans::apply(), op_stddev::apply(), op_sort::apply(), op_min::apply(), op_median::apply(), op_mean::apply(), op_max::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_times::apply(), gemv_arma< do_trans_A, use_alpha, use_beta >::apply(), gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_emul_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), glue_times::apply_inplace(), auxlib::chol(), auxlib::det(), glue_times::direct_rowvec_mat_colvec(), subview< eT >::div_inplace(), subview< eT >::extract(), auxlib::inv_inplace(), auxlib::inv_noalias(), subview< eT >::minus_inplace(), glue_times_vec::mul_col_row(), subview< eT >::plus_inplace(), subview< eT >::schur_inplace(), auxlib::solve_od(), auxlib::solve_ud(), basic_mat< eT >::swap_cols(), and op_diagmat::zero_offdiag().
  {
  return & access::rw(mem[in_col*n_rows]);
  }
template<typename eT> const eT * basic_mat< eT >::colptr (const u32 in_col) const [inline, inherited]
returns a pointer to array of eTs for a specified column; no bounds check
Definition at line 1357 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, and basic_mat< eT >::n_rows.
  {
  return & mem[in_col*n_rows];
  }
template<typename eT> eT * basic_mat< eT >::memptr () [inline, inherited]
returns a pointer to array of eTs used by the matrix
Definition at line 1368 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem.
Referenced by abs(), op_atanh::apply(), op_tanh::apply(), op_atan::apply(), op_tan::apply(), op_asinh::apply(), op_sinh::apply(), op_asin::apply(), op_sin::apply(), op_acosh::apply(), op_cosh::apply(), op_acos::apply(), op_cos::apply(), op_sort::apply(), op_scalar_div_post::apply(), op_scalar_div_pre::apply(), op_scalar_times::apply(), op_scalar_minus_post::apply(), op_scalar_minus_pre::apply(), op_scalar_plus::apply(), op_randn::apply(), op_rand::apply(), op_neg::apply(), op_conj::apply(), op_pow_s32::apply(), op_pow::apply(), op_square::apply(), op_sqrt::apply(), op_trunc_exp::apply(), op_exp::apply(), op_log10::apply(), op_trunc_log::apply(), op_log::apply(), glue_times_vec::apply(), glue_schur::apply(), glue_plus::apply(), glue_minus::apply(), gemm< do_trans_A, do_trans_B, use_alpha, use_beta >::apply_blas_type(), glue_plus::apply_inplace(), glue_minus::apply_inplace(), glue_plus::apply_mixed(), op_trans::apply_noalias(), basic_mat< eT >::basic_mat(), auxlib::chol(), auxlib::det(), subview< eT >::div_inplace(), auxlib::eig(), diagview< eT >::extract(), conv_to< basic_colvec< out_eT > >::from(), conv_to< basic_rowvec< out_eT > >::from(), conv_to< basic_mat< out_eT > >::from(), imag(), basic_mat< eT >::init(), auxlib::inv_inplace(), auxlib::inv_noalias(), diskio::load_arma_binary(), auxlib::lu(), operator!=(), operator<(), operator<=(), operator==(), operator>(), operator>=(), subview< eT >::plus_inplace(), auxlib::qr(), real(), reshape(), subview< eT >::schur_inplace(), auxlib::solve(), auxlib::solve_od(), auxlib::solve_ud(), and auxlib::svd().
  {
  return const_cast<eT*>(mem);
  }
template<typename eT> const eT * basic_mat< eT >::memptr () const [inline, inherited]
returns a pointer to array of eTs used by the matrix
Definition at line 1379 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem.
  {
  return mem;
  }
template<typename eT> void basic_mat< eT >::print (const std::string extra_text = "") const [inline, inherited]
print contents of the matrix, optionally preceding with a user specified line of text
Definition at line 1390 of file basic_mat_meat.hpp.
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    cout << extra_text << '\n';
    }
  cout << *this << '\n';
  }
template<typename eT> void basic_mat< eT >::fill (const eT val) [inline, inherited]
fill the matrix with the specified value
Definition at line 1408 of file basic_mat_meat.hpp.
References basic_mat< eT >::mem, basic_mat< eT >::n_elem, and access::rw().
Referenced by op_ones_full::apply(), operator*(), operator/(), and basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<n_elem; ++i)
    {
    access::rw(mem[i]) = val;
    }
  }
template<typename eT> void basic_mat< eT >::zeros () [inline, inherited]
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1423 of file basic_mat_meat.hpp.
References basic_mat< eT >::fill().
Referenced by op_zeros::apply(), op_ones_diag::apply(), op_inv::apply(), op_diagmat_vec::apply(), op_diagmat::apply(), glue_times_diag::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_minus_diag::apply(), op_inv::apply_diagvec(), diagmat(), subview< eT >::minus_inplace(), operator*(), operator/(), basic_rowvec< eT >::zeros(), and basic_colvec< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  fill(eT(0));
  }
template<typename eT> void basic_mat< eT >::zeros (const u32 in_rows, const u32 in_cols) [inline, inherited]
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1435 of file basic_mat_meat.hpp.
References basic_mat< eT >::fill(), and basic_mat< eT >::set_size().
  {
  arma_extra_debug_sigprint( arma_boost::format("in_rows = %d, in_cols = %d") % in_rows % in_cols );
  set_size(in_rows, in_cols);
  fill(eT(0));
  }
template<typename eT> void basic_mat< eT >::reset () [inline, inherited]
Definition at line 1448 of file basic_mat_meat.hpp.
References basic_mat< eT >::init().
Referenced by diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), and diskio::load_raw_ascii().
  {
  arma_extra_debug_sigprint();
  init(0,0);
  }
template<typename eT> void basic_mat< eT >::save (const std::string name, const file_type type = arma_binary) const [inline, inherited]
save the matrix to a file
Definition at line 1461 of file basic_mat_meat.hpp.
References arma_ascii, arma_binary, arma_stop(), pgm_binary, raw_ascii, diskio::save_arma_ascii(), diskio::save_arma_binary(), diskio::save_pgm_binary(), and diskio::save_raw_ascii().
  {
  arma_extra_debug_sigprint();
  switch(type)
    {
    case raw_ascii:
      diskio::save_raw_ascii(*this, name);
      break;
    case arma_ascii:
      diskio::save_arma_ascii(*this, name);
      break;
    case arma_binary:
      diskio::save_arma_binary(*this, name);
      break;
    case pgm_binary:
      diskio::save_pgm_binary(*this, name);
      break;
    default:
      arma_stop("basic_mat::save(): unknown type");
    }
  }
template<typename eT> void basic_mat< eT >::load (const std::string name, const file_type type = auto_detect) [inline, inherited]
load a matrix from a file
Reimplemented in basic_colvec< eT >, and basic_rowvec< eT >.
Definition at line 1495 of file basic_mat_meat.hpp.
References arma_ascii, arma_binary, arma_stop(), auto_detect, diskio::load_arma_ascii(), diskio::load_arma_binary(), diskio::load_auto_detect(), diskio::load_pgm_binary(), diskio::load_raw_ascii(), pgm_binary, and raw_ascii.
Referenced by basic_rowvec< eT >::load(), basic_colvec< eT >::load(), and diskio::load_pgm_binary().
  {
  arma_extra_debug_sigprint();
  switch(type)
    {
    case auto_detect:
      diskio::load_auto_detect(*this, name);
      break;
    case raw_ascii:
      diskio::load_raw_ascii(*this, name);
      break;
    case arma_ascii:
      diskio::load_arma_ascii(*this, name);
      break;
    case arma_binary:
      diskio::load_arma_binary(*this, name);
      break;
    case pgm_binary:
      diskio::load_pgm_binary(*this, name);
      break;
    default:
      arma_stop("basic_mat:load(): unknown type");
    }
  }