Armadillo Technical: Fn_min
Fn_min
Functions
template<typename T1>
const op_data< T1, op_min > min (const arma_base< typename T1::elem_type, T1 > &X, const u32 dim=0)
Delayed 'minimum values' operation. The dimension, along which the minima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
template<typename eT>
eT min (const basic_rowvec< eT > &A)
Immediate 'find the minimum value in a row vector' operation.
template<typename eT>
eT min (const basic_colvec< eT > &A)
Immediate 'find the minimum value in a column vector'.
template<typename T1>
T1::elem_type min (const op_data< T1, op_min > &in)
Immediate 'find minimum value' operation, invoked, for example, by: min(min(A)).
template<typename T1>
const op_data< op_data< T1,
op_min >, op_min > min (const op_data< T1, op_min > &in, const u32 dim)
template<typename eT>
eT min (const subview_row< eT > &A)
template<typename eT>
eT min (const subview_col< eT > &A)
template<typename eT>
eT min (const diagview< eT > &A)
template<typename eT>
eT min (const op_data< subview< eT >, op_min > &in)
Function Documentation
template<typename T1> const op_data<T1, op_min> min (const arma_base< typename T1::elem_type, T1 > & X, const u32 dim = 0) [inline]
Delayed 'minimum values' operation. The dimension, along which the minima are found, is set via 'dim'. For dim = 0, the maximum value of each column is found. For dim = 1, the maximum value of each row is found. The default is dim = 0. NOTE: This function works differently than in Matlab/Octave.
Definition at line 30 of file fn_min.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by basic_mat< eT >::diag(), basic_math< eT >::log_min(), auxlib::qr(), basic_rowvec< eT >::set_size(), basic_colvec< eT >::set_size(), auxlib::svd(), basic_rowvec< eT >::zeros(), and basic_colvec< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  return op_data<T1, op_min>(X.get_ref(), dim, 0);
  }
template<typename eT> eT min (const basic_rowvec< eT > & A) [inline]
Immediate 'find the minimum value in a row vector' operation.
Definition at line 42 of file fn_min.hpp.
References op_min::direct_min(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "min(): given vector has no elements" );
  return op_min::direct_min(A.mem, A.n_elem);
  }
template<typename eT> eT min (const basic_colvec< eT > & A) [inline]
Immediate 'find the minimum value in a column vector'.
Definition at line 57 of file fn_min.hpp.
References op_min::direct_min(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "min(): given vector has no elements" );
  return op_min::direct_min(A.mem, A.n_elem);
  }
template<typename T1> T1::elem_type min (const op_data< T1, op_min > & in) [inline]
Immediate 'find minimum value' operation, invoked, for example, by: min(min(A)).
Definition at line 74 of file fn_min.hpp.
References op_min::direct_min(), op_data< T1, op_type >::m, basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("min(): two consecutive min() calls detected");
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp1(in.m);
  const basic_mat<eT>& X = tmp1.M;
  arma_debug_check( (X.n_elem == 0), "min(): given matrix has no elements" );
  return op_min::direct_min(X.mem, X.n_elem);
  }
template<typename T1> const op_data< op_data<T1, op_min>, op_min> min (const op_data< T1, op_min > & in, const u32 dim) [inline]
Definition at line 94 of file fn_min.hpp.
  {
  arma_extra_debug_sigprint();
  return op_data< op_data<T1, op_min>, op_min>(in, dim, 0);
  }
template<typename eT> eT min (const subview_row< eT > & A) [inline]
Definition at line 106 of file fn_min.hpp.
References op_min::direct_min(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "min(): given vector has no elements" );
  return op_min::direct_min(A);
  }
template<typename eT> eT min (const subview_col< eT > & A) [inline]
Definition at line 120 of file fn_min.hpp.
References op_min::direct_min(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "min(): given vector has no elements" );
  return op_min::direct_min(A);
  }
template<typename eT> eT min (const diagview< eT > & A) [inline]
Definition at line 134 of file fn_min.hpp.
References op_min::direct_min(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "min(): given vector has no elements" );
  return op_min::direct_min(A);
  }
template<typename eT> eT min (const op_data< subview< eT >, op_min > & in) [inline]
Definition at line 148 of file fn_min.hpp.
References op_min::direct_min(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_extra_debug_print("max(): two consecutive max() calls detected");
  const subview<eT>& X = in.m;
  arma_debug_check( (X.n_elem == 0), "max(): given matrix has no elements" );
  return op_min::direct_min(X);
  }