Armadillo Technical: Fn_eig
Fn_eig
Functions
template<typename eT, typename T1>
void eig (basic_colvec< eT > &eigval, const arma_base< eT, T1 > &A)
template<typename eT, typename T1>
void eig (basic_colvec< eT > &eigval, basic_mat< eT > &eigvec, const arma_base< eT, T1 > &A)
Function Documentation
template<typename eT, typename T1> void eig (basic_colvec< eT > & eigval, const arma_base< eT, T1 > & A) [inline]
Definition at line 23 of file fn_eig.hpp.
References auxlib::eig(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(A.get_ref());
  auxlib::eig(eigval, tmp.M);
  }
template<typename eT, typename T1> void eig (basic_colvec< eT > & eigval, basic_mat< eT > & eigvec, const arma_base< eT, T1 > & A) [inline]
Definition at line 37 of file fn_eig.hpp.
References auxlib::eig(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> tmp(A.get_ref());
  auxlib::eig(eigval, eigvec, tmp.M);
  }