Armadillo Technical: Field
Field
Classes
class field< oT >
A lightweight 2D container for abitrary objects (the objects must have a copy constructor).
class field_aux
Functions
field::~field ()
field::field ()
field::field (const field &x)
construct a field from a given field
const field & field::operator= (const field &x)
construct a field from a given field
field::field (const subview_field< oT > &x)
construct a field from subview_field (e.g. construct a field from a delayed subfield operation)
const field & field::operator= (const subview_field< oT > &x)
construct a field from subview_field (e.g. construct a field from a delayed subfield operation)
field::field (const u32 n_elem_in)
construct the field to have a user specified number of elements, assuming a column-major layout
field::field (const u32 n_rows_in, const u32 n_cols_in)
construct the field to have user specified dimensions
void field::set_size (const u32 n_obj_in)
change the field to have a user specified number of elements, assuming a column-major layout (data is not preserved)
void field::set_size (const u32 n_rows_in, const u32 n_cols_in)
change the field to have user specified dimensions (data is not preserved)
oT & field::operator[] (const u32 i)
linear element accessor (treats the field as a vector); no bounds check
const oT & field::operator[] (const u32 i) const
linear element accessor (treats the field as a vector); no bounds check
oT & field::operator() (const u32 i)
linear element accessor (treats the field as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
const oT & field::operator() (const u32 i) const
linear element accessor (treats the field as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
oT & field::operator() (const u32 row, const u32 col)
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
const oT & field::operator() (const u32 row, const u32 col) const
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
oT & field::at (const u32 row, const u32 col)
element accessor; no bounds check
const oT & field::at (const u32 row, const u32 col) const
element accessor; no bounds check
subview_field< oT > field::row (const u32 row_num)
creation of subview_field (row of a field)
const subview_field< oT > field::row (const u32 row_num) const
creation of subview_field (row of a field)
subview_field< oT > field::col (const u32 col_num)
creation of subview_field (column of a field)
const subview_field< oT > field::col (const u32 col_num) const
creation of subview_field (column of a field)
subview_field< oT > field::rows (const u32 in_row1, const u32 in_row2)
creation of subview_field (subfield comprised of specified rows)
const subview_field< oT > field::rows (const u32 in_row1, const u32 in_row2) const
creation of subview_field (subfield comprised of specified rows)
subview_field< oT > field::cols (const u32 in_col1, const u32 in_col2)
creation of subview_field (subfield comprised of specified columns)
const subview_field< oT > field::cols (const u32 in_col1, const u32 in_col2) const
creation of subview_field (subfield comprised of specified columns)
subview_field< oT > field::subfield (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2)
creation of subview_field (subfield)
const subview_field< oT > field::subfield (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const
creation of subview_field (generic submatrix)
void field::print (const std::string extra_text="") const
print contents of the field, optionally preceding with a user specified line of text
void field::fill (const oT &x)
fill the field with an object
void field::reset ()
void field::reset_objects ()
void field::save (const std::string name) const
void field::load (const std::string name)
void field::init (const field< oT > &x)
construct a field from a given field
void field::init (const u32 n_rows_in, const u32 n_cols_in)
internal field construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
void field::delete_objects ()
void field::create_objects ()
template<typename oT>
static void field_aux::reset_objects (field< oT > &x)
template<typename eT>
static void field_aux::reset_objects (field< basic_mat< eT > > &x)
template<typename eT>
static void field_aux::reset_objects (field< basic_colvec< eT > > &x)
template<typename eT>
static void field_aux::reset_objects (field< basic_rowvec< eT > > &x)
Function Documentation
template<typename oT> field< oT >::~field () [inline, inherited]
Definition at line 22 of file field_meat.hpp.
References arma_config::debug, field< oT >::delete_objects(), field< oT >::mem, field< oT >::mem_local, and field< oT >::n_elem.
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x") % this);
  delete_objects();
  if(n_elem > sizeof(mem_local)/sizeof(oT*) )
    {
    delete [] mem;
    }
  if(arma_config::debug == true)
    {
    mem = 0;  // try to expose buggy code that still accesses a deleted 'field'
    }
  }
template<typename oT> field< oT >::field () [inline, inherited]
Definition at line 43 of file field_meat.hpp.
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x") % this);
  }
template<typename oT> field< oT >::field (const field< oT > & x) [inline, inherited]
construct a field from a given field
Definition at line 57 of file field_meat.hpp.
References field< oT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x   x = %x") % this % &x);
  init(x);
  }
template<typename oT> const field< oT > & field< oT >::operator= (const field< oT > & x) [inline, inherited]
construct a field from a given field
Definition at line 74 of file field_meat.hpp.
References field< oT >::init().
Referenced by field< oT >::field().
  {
  arma_extra_debug_sigprint();
  init(x);
  return *this;
  }
template<typename oT> field< oT >::field (const subview_field< oT > & x) [inline, inherited]
construct a field from subview_field (e.g. construct a field from a delayed subfield operation)
Definition at line 87 of file field_meat.hpp.
References field< oT >::operator=().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint_this(this);
  this->operator=(X);
  }
template<typename oT> const field< oT > & field< oT >::operator= (const subview_field< oT > & x) [inline, inherited]
construct a field from subview_field (e.g. construct a field from a delayed subfield operation)
Definition at line 104 of file field_meat.hpp.
References subview_field< oT >::extract().
  {
  arma_extra_debug_sigprint();
  subview_field<oT>::extract(*this, X);
  return *this;
  }
template<typename oT> field< oT >::field (const u32 n_elem_in) [inline, explicit, inherited]
construct the field to have a user specified number of elements, assuming a column-major layout
Definition at line 117 of file field_meat.hpp.
References field< oT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x") % this);
  init(n_elem_in, 1);
  }
template<typename oT> field< oT >::field (const u32 n_rows_in, const u32 n_cols_in) [inline, inherited]
construct the field to have user specified dimensions
Definition at line 133 of file field_meat.hpp.
References field< oT >::init().
  : n_rows(0)
  , n_cols(0)
  , n_elem(0)
  , mem(0)
  {
  arma_extra_debug_sigprint(arma_boost::format("this = %x") % this);
  init(n_rows_in, n_cols_in);
  }
template<typename oT> void field< oT >::set_size (const u32 n_obj_in) [inline, inherited]
change the field to have a user specified number of elements, assuming a column-major layout (data is not preserved)
Definition at line 150 of file field_meat.hpp.
References field< oT >::init().
Referenced by subview_field< oT >::extract(), and diskio::load_field().
  {
  arma_extra_debug_sigprint(arma_boost::format("n_elem_in = %d") % n_elem_in);
  init(n_elem_in, 1);
  }
template<typename oT> void field< oT >::set_size (const u32 n_rows_in, const u32 n_cols_in) [inline, inherited]
change the field to have user specified dimensions (data is not preserved)
Definition at line 163 of file field_meat.hpp.
References field< oT >::init().
  {
  arma_extra_debug_sigprint(arma_boost::format("n_rows_in = %d, n_cols_in = %d") % n_rows_in % n_cols_in);
  init(n_rows_in, n_cols_in);
  }
template<typename oT> oT & field< oT >::operator[] (const u32 i) [inline, inherited]
linear element accessor (treats the field as a vector); no bounds check
Definition at line 176 of file field_meat.hpp.
References field< oT >::mem.
  {
  return (*mem[i]);
  }
template<typename oT> const oT & field< oT >::operator[] (const u32 i) const [inline, inherited]
linear element accessor (treats the field as a vector); no bounds check
Definition at line 187 of file field_meat.hpp.
References field< oT >::mem.
  {
  return (*mem[i]);
  }
template<typename oT> oT & field< oT >::operator() (const u32 i) [inline, inherited]
linear element accessor (treats the field as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 197 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_elem.
  {
  arma_debug_check( (i >= n_elem), "field::operator(): index out of bounds");
  return (*mem[i]);
  }
template<typename oT> const oT & field< oT >::operator() (const u32 i) const [inline, inherited]
linear element accessor (treats the field as a vector); bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 209 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_elem.
  {
  arma_debug_check( (i >= n_elem), "field::operator(): index out of bounds");
  return (*mem[i]);
  }
template<typename oT> oT & field< oT >::operator() (const u32 row, const u32 col) [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 221 of file field_meat.hpp.
References field< oT >::mem, field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "field::operator(): index out of bounds");
  return (*mem[in_row + in_col*n_rows]);
  }
template<typename oT> const oT & field< oT >::operator() (const u32 row, const u32 col) const [inline, inherited]
element accessor; bounds checking not done when ARMA_NO_DEBUG is defined
Definition at line 233 of file field_meat.hpp.
References field< oT >::mem, field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_debug_check( ((in_row >= n_rows) || (in_col >= n_cols)), "field::operator(): index out of bounds");
  return (*mem[in_row + in_col*n_rows]);
  }
template<typename oT> oT & field< oT >::at (const u32 row, const u32 col) [inline, inherited]
element accessor; no bounds check
Definition at line 245 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_rows.
Referenced by subview_field< oT >::extract(), field< oT >::init(), and subview_field< oT >::operator=().
  {
  return (*mem[in_row + in_col*n_rows]);
  }
template<typename oT> const oT & field< oT >::at (const u32 row, const u32 col) const [inline, inherited]
element accessor; no bounds check
Definition at line 256 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_rows.
  {
  return (*mem[in_row + in_col*n_rows]);
  }
template<typename oT> subview_field< oT > field< oT >::row (const u32 row_num) [inline, inherited]
creation of subview_field (row of a field)
Definition at line 267 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
Referenced by subview< eT >::div_inplace(), subview< eT >::extract(), subview< eT >::fill(), field< oT >::init(), subview< eT >::minus_inplace(), subview< eT >::operator%=(), subview< eT >::operator*=(), subview< eT >::operator+=(), subview< eT >::operator-=(), subview< eT >::operator/=(), subview< eT >::operator=(), subview< eT >::plus_inplace(), subview< eT >::schur_inplace(), and subview< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= n_rows), "field::row(): row out of bounds" );
  return subview_field<oT>(*this, row_num, 0, row_num, n_cols-1);
  }
template<typename oT> const subview_field< oT > field< oT >::row (const u32 row_num) const [inline, inherited]
creation of subview_field (row of a field)
Definition at line 281 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (row_num >= n_rows), "field::row(): row out of bounds" );
  return subview_field<oT>(*this, row_num, 0, row_num, n_cols-1);
  }
template<typename oT> subview_field< oT > field< oT >::col (const u32 col_num) [inline, inherited]
creation of subview_field (column of a field)
Definition at line 295 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
Referenced by subview< eT >::div_inplace(), subview< eT >::extract(), subview< eT >::fill(), field< oT >::init(), subview< eT >::minus_inplace(), subview< eT >::operator%=(), subview< eT >::operator*=(), subview< eT >::operator+=(), subview< eT >::operator-=(), subview< eT >::operator/=(), subview< eT >::operator=(), subview< eT >::plus_inplace(), subview< eT >::schur_inplace(), and subview< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (col_num >= n_cols), "field::col(): out of bounds");
  return subview_field<oT>(*this, 0, col_num, n_rows-1, col_num);
  }
template<typename oT> const subview_field< oT > field< oT >::col (const u32 col_num) const [inline, inherited]
creation of subview_field (column of a field)
Definition at line 309 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (col_num >= n_cols), "field::col(): out of bounds");
  return subview_field<oT>(*this, 0, col_num, n_rows-1, col_num);
  }
template<typename oT> subview_field< oT > field< oT >::rows (const u32 in_row1, const u32 in_row2) [inline, inherited]
creation of subview_field (subfield comprised of specified rows)
Definition at line 323 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ((in_row1 >= n_rows) || (in_row2 >= n_rows) ), "field::rows(): out of bounds" );
  arma_debug_check( (in_row1 >  in_row2), "field::rows(): incorrect usage" );
  return subview_field<oT>(*this, in_row1, 0, in_row2, n_cols-1);
  }
template<typename oT> const subview_field< oT > field< oT >::rows (const u32 in_row1, const u32 in_row2) const [inline, inherited]
creation of subview_field (subfield comprised of specified rows)
Definition at line 339 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ((in_row1 >= n_rows) || (in_row2 >= n_rows) ), "field::rows(): out of bounds" );
  arma_debug_check( (in_row1 >  in_row2), "field::rows(): incorrect usage" );
  return subview_field<oT>(*this, in_row1, 0, in_row2, n_cols-1);
  }
template<typename oT> subview_field< oT > field< oT >::cols (const u32 in_col1, const u32 in_col2) [inline, inherited]
creation of subview_field (subfield comprised of specified columns)
Definition at line 355 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ((in_col1 >= n_cols) || (in_col2 >= n_cols) ), "field::cols(): out of bounds" );
  arma_debug_check( (in_col1 >  in_col2), "field::cols(): incorrect usage" );
  return subview_field<oT>(*this, 0, in_col1, n_rows-1, in_col2);
  }
template<typename oT> const subview_field< oT > field< oT >::cols (const u32 in_col1, const u32 in_col2) const [inline, inherited]
creation of subview_field (subfield comprised of specified columns)
Definition at line 371 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( ((in_col1 >= n_cols) || (in_col2 >= n_cols) ), "field::cols(): out of bounds" );
  arma_debug_check( (in_col1 >  in_col2), "field::cols(): incorrect usage" );
  return subview_field<oT>(*this, 0, in_col1, n_rows-1, in_col2);
  }
template<typename oT> subview_field< oT > field< oT >::subfield (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) [inline, inherited]
creation of subview_field (subfield)
Definition at line 387 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 >= n_rows)
    ||
    (in_col1 >= n_cols)
    ||
    (in_row2 >= n_rows)
    ||
    (in_col2 >= n_cols)
    ,
    "field::subfield(): out of bounds"
    );
  arma_debug_check
    (
    (in_row1 >  in_row2)
    ||
    (in_col1 >  in_col2)
    ,
    "field::subfield(): incorrect usage"
    );
  return subview_field<oT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename oT> const subview_field< oT > field< oT >::subfield (const u32 in_row1, const u32 in_col1, const u32 in_row2, const u32 in_col2) const [inline, inherited]
creation of subview_field (generic submatrix)
Definition at line 422 of file field_meat.hpp.
References field< oT >::n_cols, and field< oT >::n_rows.
  {
  arma_extra_debug_sigprint();
  arma_debug_check
    (
    (in_row1 >= n_rows)
    ||
    (in_col1 >= n_cols)
    ||
    (in_row2 >= n_rows)
    ||
    (in_col2 >= n_cols)
    ,
    "field::subfield(): out of bounds"
    );
  arma_debug_check
    (
    (in_row1 >  in_row2)
    ||
    (in_col1 >  in_col2)
    ,
    "field::subfield(): incorrect usage"
    );
  return subview_field<oT>(*this, in_row1, in_col1, in_row2, in_col2);
  }
template<typename oT> void field< oT >::print (const std::string extra_text = "") const [inline, inherited]
print contents of the field, optionally preceding with a user specified line of text
Definition at line 457 of file field_meat.hpp.
  {
  arma_extra_debug_sigprint();
  if(extra_text.length() != 0)
    {
    cout << extra_text << '\n';
    }
  cout << *this << '\n';
  }
template<typename oT> void field< oT >::fill (const oT & x) [inline, inherited]
fill the field with an object
Definition at line 475 of file field_meat.hpp.
References field< oT >::n_elem.
  {
  arma_extra_debug_sigprint();
  field<oT>& t = *this;
  for(u32 i=0; i<n_elem; ++i)
    {
    t[i] = x;
    }
  }
template<typename oT> void field< oT >::reset () [inline, inherited]
Definition at line 492 of file field_meat.hpp.
References field< oT >::init().
Referenced by diskio::load_field().
  {
  arma_extra_debug_sigprint();
  init(0,0);
  }
template<typename oT> void field< oT >::reset_objects () [inline, inherited]
Definition at line 504 of file field_meat.hpp.
References field_aux::reset_objects().
  {
  arma_extra_debug_sigprint();
  field_aux::reset_objects(*this);
  }
template<typename oT> void field< oT >::save (const std::string name) const [inline, inherited]
Definition at line 516 of file field_meat.hpp.
References diskio::save_field().
  {
  arma_extra_debug_sigprint();
  diskio::save_field(*this, name);
  }
template<typename oT> void field< oT >::load (const std::string name) [inline, inherited]
Definition at line 528 of file field_meat.hpp.
References diskio::load_field().
  {
  arma_extra_debug_sigprint();
  diskio::load_field(*this, name);
  }
template<typename oT> void field< oT >::init (const field< oT > & x) [inline, private, inherited]
construct a field from a given field
Definition at line 541 of file field_meat.hpp.
References field< oT >::at(), field< oT >::col(), field< oT >::n_cols, field< oT >::n_rows, and field< oT >::row().
Referenced by field< oT >::field(), field< oT >::operator=(), field< oT >::reset(), and field< oT >::set_size().
  {
  arma_extra_debug_sigprint();
  if(this != &x)
    {
    init(x.n_rows, x.n_cols);
    field& t = *this;
    for(u32 col=0; col<x.n_cols; ++col)
    for(u32 row=0; row<x.n_rows; ++row)
      {
      t.at(row,col) = x.at(row,col);
      }
    }
  }
template<typename oT> void field< oT >::init (const u32 n_rows_in, const u32 n_cols_in) [inline, private, inherited]
internal field construction; if the requested size is small enough, memory from the stack is used. otherwise memory is allocated via 'new'
Definition at line 566 of file field_meat.hpp.
References arma_check(), field< oT >::create_objects(), field< oT >::delete_objects(), field< oT >::mem, field< oT >::mem_local, field< oT >::n_cols, field< oT >::n_elem, field< oT >::n_rows, and access::rw().
  {
  arma_extra_debug_sigprint( arma_boost::format("n_rows_in = %d, n_cols_in = %d") % n_rows_in % n_cols_in );
  const u32 n_elem_new = n_rows_in * n_cols_in;
  if(n_elem == n_elem_new)
    {
    // delete_objects();
    // create_objects();
    access::rw(n_rows) = n_rows_in;
    access::rw(n_cols) = n_cols_in;
    }
  else
    {
    delete_objects();
    if(n_elem > sizeof(mem_local)/sizeof(oT*) )
      {
      delete [] mem;
      }
    if(n_elem_new <= sizeof(mem_local)/sizeof(oT*) )
      {
      mem = mem_local;
      }
    else
      {
      mem = new(std::nothrow) oT* [n_elem_new];
      arma_check( (mem == 0), "field::init(): out of memory" );
      }
    access::rw(n_elem) = n_elem_new;
    if(n_elem_new == 0)
      {
      access::rw(n_rows) = 0;
      access::rw(n_cols) = 0;
      }
    else
      {
      access::rw(n_rows) = n_rows_in;
      access::rw(n_cols) = n_cols_in;
      }
    create_objects();
    }
  }
template<typename oT> void field< oT >::delete_objects () [inline, private, inherited]
Definition at line 622 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_elem.
Referenced by field< oT >::init(), field_aux::reset_objects(), and field< oT >::~field().
  {
  arma_extra_debug_sigprint( arma_boost::format("n_elem = %d") % n_elem );
  for(u32 i=0; i<n_elem; ++i)
    {
    if(mem[i] != 0)
      {
      delete mem[i];
      mem[i] = 0;
      }
    }
  }
template<typename oT> void field< oT >::create_objects () [inline, private, inherited]
Definition at line 642 of file field_meat.hpp.
References field< oT >::mem, and field< oT >::n_elem.
Referenced by field< oT >::init(), and field_aux::reset_objects().
  {
  arma_extra_debug_sigprint( arma_boost::format("n_elem = %d") % n_elem );
  for(u32 i=0; i<n_elem; ++i)
    {
    mem[i] = new oT;
    }
  }
template<typename oT> void field_aux::reset_objects (field< oT > & x) [inline, static, inherited]
Definition at line 664 of file field_meat.hpp.
References field< oT >::create_objects(), and field< oT >::delete_objects().
Referenced by field< oT >::reset_objects().
  {
  arma_extra_debug_sigprint();
  x.delete_objects();
  x.create_objects();
  }
template<typename eT> void field_aux::reset_objects (field< basic_mat< eT > > & x) [inline, static, inherited]
Definition at line 677 of file field_meat.hpp.
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<x.n_elem; ++i)
    {
    (*(x.mem[i])).reset();
    }
  }
template<typename eT> void field_aux::reset_objects (field< basic_colvec< eT > > & x) [inline, static, inherited]
Definition at line 692 of file field_meat.hpp.
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<x.n_elem; ++i)
    {
    (*(x.mem[i])).reset();
    }
  }
template<typename eT> void field_aux::reset_objects (field< basic_rowvec< eT > > & x) [inline, static, inherited]
Definition at line 707 of file field_meat.hpp.
  {
  arma_extra_debug_sigprint();
  for(u32 i=0; i<x.n_elem; ++i)
    {
    (*(x.mem[i])).reset();
    }
  }