Armadillo Technical: Op_zeros
Op_zeros
Classes
class op_zeros
generate matrix/vector with all elements set to zero
Functions
template<typename eT>
static void op_zeros::apply (basic_mat< eT > &out, const op_data< basic_mat< eT >, op_zeros > &in)
template<typename eT>
static void op_zeros::apply (basic_mat< eT > &out, const op_data< basic_colvec< eT >, op_zeros > &in)
template<typename eT>
static void op_zeros::apply (basic_mat< eT > &out, const op_data< basic_rowvec< eT >, op_zeros > &in)
template<typename eT>
static void op_zeros::apply (basic_colvec< eT > &out, const op_data< basic_colvec< eT >, op_zeros > &in)
template<typename eT>
static void op_zeros::apply (basic_rowvec< eT > &out, const op_data< basic_rowvec< eT >, op_zeros > &in)
Function Documentation
template<typename eT> void op_zeros::apply (basic_mat< eT > & out, const op_data< basic_mat< eT >, op_zeros > & in) [inline, static, inherited]
Definition at line 23 of file op_zeros_meat.hpp.
References basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  const u32 n_rows = in.aux_u32_a;
  const u32 n_cols = (in.aux_u32_b > 0) ? in.aux_u32_b : 1;
  out.zeros(n_rows, n_cols);
  }
template<typename eT> void op_zeros::apply (basic_mat< eT > & out, const op_data< basic_colvec< eT >, op_zeros > & in) [inline, static, inherited]
Definition at line 38 of file op_zeros_meat.hpp.
References basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  out.zeros(in.aux_u32_a, 1);
  }
template<typename eT> void op_zeros::apply (basic_mat< eT > & out, const op_data< basic_rowvec< eT >, op_zeros > & in) [inline, static, inherited]
Definition at line 50 of file op_zeros_meat.hpp.
References basic_mat< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  out.zeros(1, in.aux_u32_a);
  }
template<typename eT> void op_zeros::apply (basic_colvec< eT > & out, const op_data< basic_colvec< eT >, op_zeros > & in) [inline, static, inherited]
Definition at line 62 of file op_zeros_meat.hpp.
References basic_colvec< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  out.zeros(in.aux_u32_a);
  }
template<typename eT> void op_zeros::apply (basic_rowvec< eT > & out, const op_data< basic_rowvec< eT >, op_zeros > & in) [inline, static, inherited]
Definition at line 74 of file op_zeros_meat.hpp.
References basic_rowvec< eT >::zeros().
  {
  arma_extra_debug_sigprint();
  out.zeros(in.aux_u32_a);
  }