Armadillo Technical: Fn_var
Fn_var
Functions
template<typename T1>
basic_mat< typename T1::pod_type > var (const arma_base< typename T1::elem_type, T1 > &X, const u32 norm_type=0, const u32 dim=0)
template<typename eT>
eT var (const basic_rowvec< eT > &A, const u32 norm_type=0)
Immediate 'find the variance of a row vector' operation.
template<typename T>
T var (const basic_rowvec< std::complex< T > > &A, const u32 norm_type=0)
Immediate 'find the variance of a row vector' operation (version for complex numbers).
template<typename eT>
eT var (const basic_colvec< eT > &A, const u32 norm_type=0)
Immediate 'find the variance of a column vector' operation.
template<typename T>
T var (const basic_colvec< std::complex< T > > &A, const u32 norm_type=0)
Immediate 'find the variance of a column vector' operation (version for complex numbers).
template<typename eT>
eT var (const subview_row< eT > &A, const u32 norm_type=0)
template<typename T>
T var (const subview_row< std::complex< T > > &A, const u32 norm_type=0)
template<typename eT>
eT var (const subview_col< eT > &A, const u32 norm_type=0)
template<typename T>
T var (const subview_col< std::complex< T > > &A, const u32 norm_type=0)
template<typename eT>
eT var (const diagview< eT > &A, const u32 norm_type=0)
template<typename T>
T var (const diagview< std::complex< T > > &A, const u32 norm_type=0)
Function Documentation
template<typename T1> basic_mat<typename T1::pod_type> var (const arma_base< typename T1::elem_type, T1 > & X, const u32 norm_type = 0, const u32 dim = 0) [inline]
Definition at line 24 of file fn_var.hpp.
References op_var::apply(), and arma_base< elem_type, arma_derived >::get_ref().
  {
  arma_extra_debug_sigprint();
  const unwrap<T1> A_tmp(X.get_ref());
  // if T1 is a complex matrix,
  // pod_type is the underlying type used by std::complex;
  // otherwise pod_type is the same as elem_type
  typedef typename T1::elem_type  in_eT;
  typedef typename T1::pod_type  out_eT;
  const basic_mat<in_eT>& A = A_tmp.M;
  basic_mat<out_eT> out;
  op_var::apply(out, A, norm_type, dim);
  return out;
  }
template<typename eT> eT var (const basic_rowvec< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a row vector' operation.
Definition at line 52 of file fn_var.hpp.
References op_var::direct_var(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename T> T var (const basic_rowvec< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a row vector' operation (version for complex numbers).
Definition at line 67 of file fn_var.hpp.
References op_var::direct_var().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename eT> eT var (const basic_colvec< eT > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a column vector' operation.
Definition at line 82 of file fn_var.hpp.
References op_var::direct_var(), basic_mat< eT >::mem, and basic_mat< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename T> T var (const basic_colvec< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Immediate 'find the variance of a column vector' operation (version for complex numbers).
Definition at line 97 of file fn_var.hpp.
References op_var::direct_var().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A.mem, A.n_elem, norm_type);
  }
template<typename eT> eT var (const subview_row< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 111 of file fn_var.hpp.
References op_var::direct_var(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename T> T var (const subview_row< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Definition at line 125 of file fn_var.hpp.
References op_var::direct_var().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename eT> eT var (const subview_col< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 139 of file fn_var.hpp.
References op_var::direct_var(), and subview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename T> T var (const subview_col< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Definition at line 153 of file fn_var.hpp.
References op_var::direct_var().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename eT> eT var (const diagview< eT > & A, const u32 norm_type = 0) [inline]
Definition at line 167 of file fn_var.hpp.
References op_var::direct_var(), and diagview< eT >::n_elem.
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }
template<typename T> T var (const diagview< std::complex< T > > & A, const u32 norm_type = 0) [inline]
Definition at line 181 of file fn_var.hpp.
References op_var::direct_var().
  {
  arma_extra_debug_sigprint();
  arma_debug_check( (A.n_elem == 0), "var(): given vector has no elements" );
  return op_var::direct_var(A, norm_type);
  }