Armadillo Technical: Fn_trace
Fn_trace
Functions
template<typename T1>
T1::elem_type trace (const arma_base< typename T1::elem_type, T1 > &X)
Immediate trace (sum of diagonal elements) of a square dense matrix.
template<typename T1, typename T2>
T1::elem_type trace (const glue_data< T1, T2, glue_plus > &X)
Immediate trace (sum of diagonal elements) of A + B. A and B must be square and have the same dimensions.
template<typename T1, typename T2>
T1::elem_type trace (const glue_data< T1, T2, glue_minus > &X)
Immediate trace (sum of diagonal elements) of A - B. A and B must be square and have the same dimensions.
template<typename T1, typename T2>
T1::elem_type trace (const glue_data< T1, T2, glue_schur > &X)
Immediate trace (sum of diagonal elements) of A % B (where % is the element-wise multiplication operator). A and B must be square and have the same dimensions.
template<typename T1>
T1::elem_type trace (const op_data< T1, op_scalar_times > &in)
trace (sum of diagonal elements) of k * T1, where k is a scalar and T1 is converted to a dense matrix.
template<typename eT>
eT trace (const op_data< basic_mat< eT >, op_diagmat > &X)
trace (sum of diagonal elements) of a diagonal matrix
template<typename eT>
eT trace (const op_data< basic_mat< eT >, op_diagmat_vec > &X)
Function Documentation
template<typename T1> T1::elem_type trace (const arma_base< typename T1::elem_type, T1 > & X) [inline]
Immediate trace (sum of diagonal elements) of a square dense matrix.
Definition at line 24 of file fn_trace.hpp.
References arma_base< elem_type, arma_derived >::get_ref().
Referenced by trace().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> A_tmp(X.get_ref());
  const basic_mat<eT>& A = A_tmp.M;
  arma_debug_check( !A.is_square(), "trace(): matrix must be square" );
  eT val = eT(0);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    val += A.at(i,i);
    }
  return val;
  }
template<typename T1, typename T2> T1::elem_type trace (const glue_data< T1, T2, glue_plus > & X) [inline]
Immediate trace (sum of diagonal elements) of A + B. A and B must be square and have the same dimensions.
Definition at line 53 of file fn_trace.hpp.
References glue_data< T1, T2, glue_type >::A, glue_data< T1, T2, glue_type >::B, isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and trace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(X.A);
  const unwrap<T2> tmp2(X.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols), "trace(): incompatible matrix dimensions");
  arma_debug_check( !A.is_square(), "trace(): matrices must be square");
  return trace(A) + trace(B);
  }
template<typename T1, typename T2> T1::elem_type trace (const glue_data< T1, T2, glue_minus > & X) [inline]
Immediate trace (sum of diagonal elements) of A - B. A and B must be square and have the same dimensions.
Definition at line 81 of file fn_trace.hpp.
References glue_data< T1, T2, glue_type >::A, glue_data< T1, T2, glue_type >::B, isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), basic_mat< eT >::n_cols, basic_mat< eT >::n_rows, and trace().
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(X.A);
  const unwrap<T2> tmp2(X.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols), "trace(): incompatible matrix dimensions");
  arma_debug_check( !A.is_square(), "trace(): matrices must be square");
  return trace(A) - trace(B);
  }
template<typename T1, typename T2> T1::elem_type trace (const glue_data< T1, T2, glue_schur > & X) [inline]
Immediate trace (sum of diagonal elements) of A % B (where % is the element-wise multiplication operator). A and B must be square and have the same dimensions.
Definition at line 109 of file fn_trace.hpp.
References glue_data< T1, T2, glue_type >::A, basic_mat< eT >::at(), glue_data< T1, T2, glue_type >::B, isnt_same_type< T1, T2 >::check(), basic_mat< eT >::is_square(), basic_mat< eT >::n_cols, and basic_mat< eT >::n_rows.
  {
  arma_extra_debug_sigprint();
  isnt_same_type<typename T1::elem_type, typename T2::elem_type>::check();
  const unwrap<T1> tmp1(X.A);
  const unwrap<T2> tmp2(X.B);
  typedef typename T1::elem_type eT;
  const basic_mat<eT>& A = tmp1.M;
  const basic_mat<eT>& B = tmp2.M;
  arma_debug_check( (A.n_rows != B.n_rows) || (A.n_cols != B.n_cols), "trace(): incompatible matrix dimensions" );
  arma_debug_check( !A.is_square(), "trace(): matrices must be square" );
  eT val = eT(0);
  for(u32 i=0; i<A.n_rows; ++i)
    {
    val += A.at(i,i) * B.at(i,i);
    }
  return val;
  }
template<typename T1> T1::elem_type trace (const op_data< T1, op_scalar_times > & in) [inline]
trace (sum of diagonal elements) of k * T1, where k is a scalar and T1 is converted to a dense matrix.
Definition at line 143 of file fn_trace.hpp.
References op_data< T1, op_type >::aux, op_data< T1, op_type >::m, and trace().
  {
  arma_extra_debug_sigprint();
  typedef typename T1::elem_type eT;
  const unwrap<T1> tmp(in.m);
  const basic_mat<eT>& X = tmp.M;
  return trace(X) * in.aux;
  }
template<typename eT> eT trace (const op_data< basic_mat< eT >, op_diagmat > & X) [inline]
trace (sum of diagonal elements) of a diagonal matrix
Definition at line 161 of file fn_trace.hpp.
References trace().
  {
  arma_extra_debug_sigprint();
  return trace(X.m);
  }
template<typename eT> eT trace (const op_data< basic_mat< eT >, op_diagmat_vec > & X) [inline]
Definition at line 173 of file fn_trace.hpp.
References accu(), and basic_mat< eT >::is_vec().
  {
  arma_extra_debug_sigprint();
  const basic_mat<eT>& A = X.m;
  arma_debug_check( !A.is_vec(), "trace(): internal error: can't interpret as a vector" );
  return accu(X.m);
  }