Armadillo Technical: arma_boost Namespace Reference
arma_boost Namespace Reference
[Format_wrap]
Detailed Description
namespace for functions and classes which partially emulate Boost functionality
Classes
class format
class basic_format
struct format_metaprog
struct format_metaprog< basic_format< T1, T2 > >
Functions
template<typename T2>
basic_format< format, T2 > operator% (const format &X, const T2 &arg)
template<typename T1, typename T2, typename T3>
basic_format< basic_format< T1,
T2 >, T3 > operator% (const basic_format< T1, T2 > &X, const T3 &arg)
template<typename T2>
std::string str (const basic_format< format, T2 > &X)
template<typename T2, typename T3>
std::string str (const basic_format< basic_format< format, T2 >, T3 > &X)
template<typename T2, typename T3, typename T4>
std::string str (const basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 > &X)
template<typename T2, typename T3, typename T4, typename T5>
std::string str (const basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 > &X)
template<typename T2, typename T3, typename T4, typename T5, typename T6>
std::string str (const basic_format< basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 >, T6 > &X)
template<typename T2, typename T3, typename T4, typename T5, typename T6, typename T7>
std::string str (const basic_format< basic_format< basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 >, T6 >, T7 > &X)
template<typename T1, typename T2>
std::string str (const basic_format< T1, T2 > &X)
template<typename T1, typename T2>
std::ostream & operator<< (std::ostream &o, const basic_format< T1, T2 > &X)
Function Documentation
template<typename T2> basic_format< format, T2 > arma_boost::operator% (const format & X, const T2 & arg) [inline]
Definition at line 79 of file format_wrap.hpp.
      {
      return basic_format< format, T2 >(X, arg);
      }
template<typename T1, typename T2, typename T3> basic_format< basic_format<T1,T2>, T3 > arma_boost::operator% (const basic_format< T1, T2 > & X, const T3 & arg) [inline]
Definition at line 89 of file format_wrap.hpp.
      {
      return basic_format< basic_format<T1,T2>, T3 >(X, arg);
      }
template<typename T2> std::string arma_boost::str (const basic_format< format, T2 > & X) [inline]
Definition at line 99 of file format_wrap.hpp.
References arma_boost::format::A, arma_boost::basic_format< T1, T2 >::A, and arma_boost::basic_format< T1, T2 >::B.
Referenced by operator<<().
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.c_str(), X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T2, typename T3> std::string arma_boost::str (const basic_format< basic_format< format, T2 >, T3 > & X) [inline]
Definition at line 131 of file format_wrap.hpp.
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.A.c_str(), X.A.B, X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T2, typename T3, typename T4> std::string arma_boost::str (const basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 > & X) [inline]
Definition at line 163 of file format_wrap.hpp.
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.A.A.c_str(), X.A.A.B, X.A.B, X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T2, typename T3, typename T4, typename T5> std::string arma_boost::str (const basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 > & X) [inline]
Definition at line 195 of file format_wrap.hpp.
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.A.A.A.c_str(), X.A.A.A.B, X.A.A.B, X.A.B, X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T2, typename T3, typename T4, typename T5, typename T6> std::string arma_boost::str (const basic_format< basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 >, T6 > & X) [inline]
Definition at line 227 of file format_wrap.hpp.
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.A.A.A.A.c_str(), X.A.A.A.A.B, X.A.A.A.B, X.A.A.B, X.A.B, X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T2, typename T3, typename T4, typename T5, typename T6, typename T7> std::string arma_boost::str (const basic_format< basic_format< basic_format< basic_format< basic_format< basic_format< format, T2 >, T3 >, T4 >, T5 >, T6 >, T7 > & X) [inline]
Definition at line 259 of file format_wrap.hpp.
      {
      int data_size = 1024;
      int reqd_size = data_size;
      std::string out;
      do
        {
        char* data = new char[data_size];
        reqd_size = snprintf(data, data_size, X.A.A.A.A.A.A.A.c_str(), X.A.A.A.A.A.B, X.A.A.A.A.B, X.A.A.A.B, X.A.A.B, X.A.B, X.B);
        if(reqd_size < 0)
          break;
        if(reqd_size < data_size)
          out = data;
        else
          data_size *= 2;
        delete[] data;
        } while(reqd_size >= data_size);
      return out;
      }
template<typename T1, typename T2> std::string arma_boost::str (const basic_format< T1, T2 > & X) [inline]
Definition at line 325 of file format_wrap.hpp.
References arma_boost::basic_format< T1, T2 >::A.
Referenced by arma_check().
      {
      return format_metaprog< basic_format<T1,T2> >::get_fmt(X.A);
      }
template<typename T1, typename T2> std::ostream& arma_boost::operator<< (std::ostream & o, const basic_format< T1, T2 > & X) [inline]
Definition at line 335 of file format_wrap.hpp.
References str().
      {
      o << str(X);
      return o;
      }