Armadillo Technical: arma_base< elem_type, arma_derived > Struct Template Reference
arma_base< elem_type, arma_derived > Struct Template Reference
[Arma_base]
#include <arma_base.hpp>
Detailed Description
template<typename elem_type, typename arma_derived>
struct arma_base< elem_type, arma_derived >
Class for static polymorphism, modelled after the "Curiously Recurring Template Pattern" (CRTP). Used for type-safe downcasting in functions that restrict their input(s) to be classes that are derived from arma_base (e.g. basic_mat, op_data, glue_data, diagview, subview). An arma_base object can be converted to a basic_mat object by the unwrap class.
Definition at line 26 of file arma_base.hpp.
Public Member Functions
const arma_derived & get_ref () const
Member Function Documentation
template<typename elem_type, typename arma_derived> const arma_derived& arma_base< elem_type, arma_derived >::get_ref () const [inline]
Definition at line 31 of file arma_base.hpp.
Referenced by abs(), accu(), acos(), acosh(), op_norm_dot::apply(), op_dot::apply(), asin(), asinh(), atan(), atanh(), chol(), cos(), cosh(), det(), diagmat(), eig(), exp(), conv_to< out_eT >::from(), inv(), log(), log10(), lu(), max(), mean(), median(), min(), norm(), operator!=(), operator%(), subview< eT >::operator%=(), operator*(), operator+(), subview< eT >::operator+=(), operator-(), subview< eT >::operator-=(), operator/(), subview< eT >::operator/=(), operator<(), operator<=(), subview< eT >::operator=(), diagview< eT >::operator=(), operator==(), operator>(), operator>=(), pow(), qr(), reshape(), sin(), sinh(), solve(), sort(), sqrt(), square(), stddev(), sum(), svd(), tan(), tanh(), trace(), trans(), trunc_exp(), trunc_log(), and var().
    {
    return static_cast<const arma_derived&>(*this);
    }