Armadillo Technical: isnt_same_type< T1, T2 > Struct Template Reference
isnt_same_type< T1, T2 > Struct Template Reference
[Traits]
#include <traits.hpp>
Detailed Description
template<typename T1, typename T2>
struct isnt_same_type< T1, T2 >
Definition at line 168 of file traits.hpp.
Static Public Member Functions
static void check ()
Static Public Attributes
static const bool value = true
Member Function Documentation
template<typename T1, typename T2> static void isnt_same_type< T1, T2 >::check () [inline, static]
Definition at line 172 of file traits.hpp.
Referenced by accu(), op_atan::apply(), op_asin::apply(), op_acos::apply(), op_trans::apply(), op_pow::apply(), op_min::apply(), op_median::apply(), op_max::apply(), op_htrans::apply(), glue_times_diag::apply(), glue_schur_diag::apply(), glue_plus_diag::apply(), glue_minus_diag::apply(), basic_mat< eT >::basic_mat(), mat_ptrs_outcheck< glue_type, glue_data< T1, T2, glue_type > >::get_ptrs(), mat_ptrs< glue_type, glue_data< T1, T2, glue_type > >::get_ptrs(), glue_data< T1, T2, glue_type >::glue_data(), norm(), basic_mat< eT >::operator%=(), basic_mat< eT >::operator*=(), basic_mat< eT >::operator+=(), basic_mat< eT >::operator-=(), basic_mat< eT >::operator/=(), basic_mat< eT >::operator=(), and trace().
    {
    arma_static_assert<false> ERROR___TYPE_MISMATCH;
    ERROR___TYPE_MISMATCH = ERROR___TYPE_MISMATCH;
    }
Member Data Documentation
template<typename T1, typename T2> const bool isnt_same_type< T1, T2 >::value = true [static]
Definition at line 170 of file traits.hpp.