Armadillo Technical: upgrade_val< T1, T2 > Struct Template Reference
upgrade_val< T1, T2 > Struct Template Reference
[Traits]
#include <traits.hpp>
Detailed Description
template<typename T1, typename T2>
struct upgrade_val< T1, T2 >
upgrade_val is used to ensure an operation such as multiplication is possible between two types. values are upgraded only where necessary. used by: glue_div::apply_mixed(), glue_minus::apply_mixed(), glue_plus::apply_mixed(), glue_schur::apply_mixed() and glue_times::apply_mixed() via gemm_mixed().
Definition at line 627 of file traits.hpp.
Public Types
typedef promote_type< T1, T2 >
::result T1_result
typedef promote_type< T1, T2 >
::result T2_result
Static Public Member Functions
static const promote_type< T1,
T2 >::result apply (const T1 x)
static const promote_type< T1,
T2 >::result apply (const T2 x)
Member Typedef Documentation
template<typename T1, typename T2> typedef promote_type<T1,T2>::result upgrade_val< T1, T2 >::T1_result
Definition at line 629 of file traits.hpp.
template<typename T1, typename T2> typedef promote_type<T1,T2>::result upgrade_val< T1, T2 >::T2_result
Definition at line 630 of file traits.hpp.
Member Function Documentation
template<typename T1, typename T2> static const promote_type<T1,T2>::result upgrade_val< T1, T2 >::apply (const T1 x) [inline, static]
Definition at line 635 of file traits.hpp.
Referenced by gemm_mixed_simple< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), gemm_mixed_cache< do_trans_A, do_trans_B, use_alpha, use_beta >::apply(), glue_schur::apply_mixed(), glue_plus::apply_mixed(), glue_minus::apply_mixed(), and glue_div::apply_mixed().
    {
    typedef typename promote_type<T1,T2>::result out_type;
    return out_type(x);
    }
template<typename T1, typename T2> static const promote_type<T1,T2>::result upgrade_val< T1, T2 >::apply (const T2 x) [inline, static]
Definition at line 644 of file traits.hpp.
    {
    typedef typename promote_type<T1,T2>::result out_type;
    return out_type(x);
    }