Armadillo Technical: promote_type< T1, T2 > Struct Template Reference
promote_type< T1, T2 > Struct Template Reference
[Traits]
#include <traits.hpp>
Detailed Description
template<typename T1, typename T2>
struct promote_type< T1, T2 >
Definition at line 456 of file traits.hpp.
Public Types
typedef T1 result
Static Public Member Functions
static void check ()
Member Typedef Documentation
template<typename T1, typename T2> typedef T1 promote_type< T1, T2 >::result
Definition at line 464 of file traits.hpp.
Member Function Documentation
template<typename T1, typename T2> static void promote_type< T1, T2 >::check () [inline, static]
Definition at line 458 of file traits.hpp.
Referenced by operator%(), operator*(), operator+(), operator-(), and operator/().
    {
    arma_static_assert<false> ERROR___UNSUPPORTED_MIXTURE_OF_TYPES;
    ERROR___UNSUPPORTED_MIXTURE_OF_TYPES = ERROR___UNSUPPORTED_MIXTURE_OF_TYPES;
    }